### ISSUE TITLE
Dude, where do I send you money! You rock!!

### ISSUE THREAD

**Issue by renich** [andyholmes/gnome-shell-extension-gsconnect#1001]
I need to donate to your cause. Your GNOME extension is the most useful thing I've installed in a while! Thank you!!

Please, add some donate button somewhere!

**Comment by andyholmes** [comment]
Thanks! I don't collect donations for this project, but you can always [donate to GNOME](https://www.gnome.org/support-gnome/donate/).

I'm currently in the process of looking for a [new full-time maintainer](https://github.com/andyholmes/gnome-shell-extension-gsconnect/issues/989), so whoever that may be might decide to collect donations. Maybe you want to wait for them :slightly_smiling_face:

**Comment by renich** [comment]
Or, maybe, I'll donate twice ;D. Keep up the good work, man. It's awesome.
