### ISSUE TITLE
GSConnect: TypeError in Ubuntu 20.10

### ISSUE THREAD

**Issue by habibseifzadeh** [andyholmes/gnome-shell-extension-gsconnect#1002]
Hey,

I face the following error in the newly installed Ubuntu 20.10 although the OS has connected to the device:

setting getter-only property "conversations" 
_init@/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/sms.js:218:9
loadPlugin@/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/device.js:786:26
loadPlugins@/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/device.js:808:24
async*vfunc_dbus_register@/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:669:20
@/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:753:17

**Comment by habibseifzadeh** [comment]
In the extensions app, it also complains that "No JS module 'tweener' found in search path".

**Comment by andyholmes** [comment]
setting getter-only property "conversations"
    _init@/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/sms.js:218:9
    loadPlugin@/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/device.js:786:26
    loadPlugins@/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/device.js:808:24
    async*vfunc_dbus_register@/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:669:20
    @/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:753:17

This was fixed by PR #1000, you can get a ZIP from the [job artifacts](https://github.com/andyholmes/gnome-shell-extension-gsconnect/actions/runs/325037636) or wait until the next release.

> In the extensions app, it also complains that "No JS module 'tweener' found in search path".

Some deprecated Tweener usage was removed in v40, but you haven't provided any version information about GSConnect so I'm not sure what could be causing that.

**Comment by habibseifzadeh** [comment]
You're right. The version was 20, and it resolved when I upgraded it to 44. Thanks for your help

**Comment by sergioad** [comment]
In my pi 4 I am having the same issue
