### ISSUE TITLE
Not all plugins buttons visible in status menu

### ISSUE THREAD

**Issue by AdamKane41** [andyholmes/gnome-shell-extension-gsconnect#101]
_sorry if duplicate or obsolete issue..._

Using Ubuntu 18.04/Bionic Beaver/Cosmic Cuttlefish

When I enable "too many" plugins, not all buttons are visible in the status/system drop down menu...
For example if I enable "Locate device", "Browse files" and "Url sharing", all buttons are visible;
![screenshot from 2018-05-14 02-40-40](https://user-images.githubusercontent.com/30092603/39982514-9faedd5c-5722-11e8-91e8-5b793f06a74b.png)

But if I enable all of the above plus "Send SMS", some buttons are no longer visible (seem to be "pushed" to the right beyond the drop down menu's frame area);
![screenshot from 2018-05-14 02-41-33](https://user-images.githubusercontent.com/30092603/39982671-197e49a6-5723-11e8-9548-02ba807ffb22.png)

Peace!

**Comment by andyholmes** [comment]
Yep, this was an issue introduced in Gnome Shell 3.28 that has been fixed in v11, currently waiting for review on the extensions website.

**Comment by AdamKane41** [comment]
oky doky
Ill build/install via the current code instead of gnome extentions site
