### ISSUE TITLE
Gsconnect issue

### ISSUE THREAD

**Issue by soumyatheman** [andyholmes/gnome-shell-extension-gsconnect#1016]
> ***ATTENTION**: GSConnect only supports the latest, stable version of GNOME. We are no longer accepting bug reports for previous versions.*

**Describe the bug**
my phone is connected to my pc via gsconnect. suddenly it gets disconnected and when I open my kde connect app from my phone, it reappears. and then after sometime again the icon of mobile devices it gets disconnected.

**Steps To Reproduce:**

1. Go to 'GSconnect'
2. pair your phone with it
3. wait for sometime
4. you'll see the icon gets disconnected after sometime

**Expected behavior**
the extension should always show the icon until both are connected with same network

**Screenshots**

If applicable, add screenshots to help explain your problem. You can drag-and-drop or cut-and-paste images directly into this edit window, to include them in your report.

**Support Log**

Please generate a support log ([Instructions](../wiki/Help#generate-support-log)) and paste any messages related to this issue between the two ``` lines below.

```

```

**System Details (please complete the following information):**

 - **GSConnect version:** 43
   - **Installed from:** GNOME Extensions Website
 - **GNOME/Shell version:** 3.36
 - **Distro/Release:** POP OS 20.04

**GSConnect environment (if applicable):**

 - **Paired Device(s):** POCO M2 Pro
 - **KDE Connect app version:** 1.15.1
 - **Plugin(s):** [if the issue only occurs when using certain plugin(s)]

**Additional Notes:**

Add any addtional information about the problem or your system.

**Comment by bellegarde-c** [comment]
Looks like an issue on your phone sleeping the app while running in background.

**Comment by soumyatheman** [comment]
> Looks like an issue on your phone sleeping the app while running in background.

No it's showing connected to my pc..and if it's problem of my phone then what should I do. I have already turned off battery restrictions

**Comment by andyholmes** [comment]
You'd have to supply a support log to be sure, but it sounds like the devices are just becoming disconnected and the remote side is just waiting for the connection to timeout (~30 seconds).

**Comment by soumyatheman** [comment]
I had solved the problem. thanks for your help. If anything happens again
then I'll let you know.
