### ISSUE TITLE
[feature] cannot support emacs input

### ISSUE THREAD

**Issue by Freed-Wu** [andyholmes/gnome-shell-extension-gsconnect#1017]
Reproduce Procedures
--------------------

```{.sh}
gnome-tweaks
```

click `Keyboard & Mouses`

enable `Emacs Input`
![Screenshot from 2020-11-14 13-53-12](https://user-images.githubusercontent.com/32936898/99141101-88f08480-2682-11eb-9a02-d1b69074fa2c.png)

Open `gnome-shell-extension-gsconnect`.

Open `Keyboard`

In mobile, open `KDE Connect`.

connect to computer.

then open an input region.

In computer, input some text.
![Screenshot from 2020-11-14 13-52-53](https://user-images.githubusercontent.com/32936898/99141105-960d7380-2682-11eb-9e9a-3e8ff918dc54.png)
![Screenshot_2020-11-14-13-52-49-43](https://user-images.githubusercontent.com/32936898/99141144-13d17f00-2683-11eb-8a3a-a6a766726384.jpg)

input <kbd>Ctrl</kbd> + <kbd>u</kbd>
![Screenshot from 2020-11-14 13-53-02](https://user-images.githubusercontent.com/32936898/99141106-9b6abe00-2682-11eb-8924-50be559e835f.png)
![Screenshot_2020-11-14-13-53-06-23](https://user-images.githubusercontent.com/32936898/99141147-17fd9c80-2683-11eb-99b7-a99fda6f287b.jpg)

Expected Behavior
-----------------

if gnome enable `Emacs Input`, user can use some hotkeys like linereader,
such as:

- press <kbd>Ctrl</kbd> + <kbd>u</kbd> to delete a line
- press <kbd>Ctrl</kbd> + <kbd>h</kbd> to backspace a character
- press <kbd>Ctrl</kbd> + <kbd>d</kbd> to delete a character
- press <kbd>Ctrl</kbd> + <kbd>b</kbd> to move cursor left
- press <kbd>Ctrl</kbd> + <kbd>f</kbd> to move cursor right
- etc...

so press <kbd>Ctrl</kbd> + <kbd>u</kbd>, the computer will delete a line, but
mobile will continue to input.

**Comment by andyholmes** [comment]
This probably won't be supportable. The remote input plugin simply passes keystrokes to the remote device, so if you want emacs shortcuts to work you would have to train KDE Connect or Android to understand those.

**Comment by Freed-Wu** [comment]
thanks for your explanation. i have filed it at <https://bugs.kde.org/show_bug.cgi?id=429509>. thanks!
