### ISSUE TITLE
[bug] cannot input characters which are not english

### ISSUE THREAD

**Issue by Freed-Wu** [andyholmes/gnome-shell-extension-gsconnect#1018]
Reproduce Procedures
--------------------

Open `gnome-shell-extension-gsconnect` in computer and `KDE connect` in
mobile, make them connected together.

Open an input region in mobile and open an `keyboard` in computer, change
input method, input some characters which are not english.
![Screenshot from 2020-11-14 14-17-41](https://user-images.githubusercontent.com/32936898/99141317-2cdb2f80-2685-11eb-91df-52cedf5390dd.png)
![Screenshot from 2020-11-14 14-19-46](https://user-images.githubusercontent.com/32936898/99141324-3a90b500-2685-11eb-912b-8f12f062eb3c.png)
![Screenshot_2020-11-14-14-19-50-96](https://user-images.githubusercontent.com/32936898/99141330-58f6b080-2685-11eb-8670-9df04e239165.jpg)

**Comment by andyholmes** [comment]
You'll have to add some output from a support log to confirm this is actually an issue with GSConnect. See [Generate Support Log](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Help#generate-support-log) in the wiki for more information.

**Comment by Freed-Wu** [comment]
sorry for my stupidity ... where is *Generate Support Log*?

**Comment by andyholmes** [comment]
It's in the preferences window; see the link posted above.

**Comment by Freed-Wu** [comment]
```
GSConnect Version: 28
GSConnect Install: user
GJS: 15602
XDG_SESSION_TYPE: x11
GDMSESSION: gnome
--------------------------------------------------------------------------------
-- Logs begin at Tue 2020-10-20 10:58:02 CST, end at Mon 2020-11-23 14:53:26 CST. --
Nov 23 14:53:09 dhcpcd-gtk[2900]: wlan0: Received scan results
Nov 23 14:53:16 gnome-shell[2681]: [ESC]-*-refresh indicator -A false -F true
Nov 23 14:53:16 gnome-shell[2681]: [ESC]-*-refresh indicator -A false -F false
Nov 23 14:53:16 gnome-shell[2681]: [ESC]-*-refresh indicator -A false -F true
Nov 23 14:53:16 gnome-shell[2681]: [ESC]-*-refresh indicator -A false -F false
Nov 23 14:53:22 gnome-shell[2681]: [ESC]-*-refresh indicator -A false -F true
Nov 23 14:53:22 gnome-shell[2681]: [ESC]-*-refresh indicator -A false -F false
Nov 23 14:53:25 dbus-daemon[2058]: [system] Activating via systemd: service name='org.freedesktop.hostname1' unit='dbus-org.freedesktop.hostname1.service' requested by ':1.104' (uid=1000 pid=5377 comm="gjs /home/wzy/.local/share/gnome-shell/extensions/" label="kernel")
Nov 23 14:53:25 systemd[1]: Starting Hostname Service...
Nov 23 14:53:25 dbus-daemon[2058]: [system] Successfully activated service 'org.freedesktop.hostname1'
Nov 23 14:53:25 systemd[1]: Started Hostname Service.
```

**Comment by andyholmes** [comment]
Seems like you are using a very old version of GSConnect. Support for IBus input was added in v38 which requires GNOME 3.38, or you can try to backport the patch from cd68def yourself.
