### ISSUE TITLE
Gsconnect not mounting mobile storage

### ISSUE THREAD

**Issue by ahmad-sulehari** [andyholmes/gnome-shell-extension-gsconnect#1021]
I'm on ubuntu 20.04 and I've linked my android with disconnect. recently I'm unable to mount the mobile folder onto my pc.
I've given access to my mobile.

**Comment by andyholmes** [comment]
Nothing has changed in the SFTP plugin recently, however there will likely be no more updates for GNOME 3.36.

**Comment by andyholmes** [comment]
You'll want to open a [new issue](https://github.com/GSConnect/gnome-shell-extension-gsconnect/issues/new?assignees=&labels=&template=bug_report.md&title=), with all information filled in and a debug log. You'll also want to read the [Wiki page](https://github.com/GSConnect/gnome-shell-extension-gsconnect/wiki/Help#mount-doesnt-work).
