### ISSUE TITLE
[question] authentication failed

### ISSUE THREAD

**Issue by Freed-Wu** [andyholmes/gnome-shell-extension-gsconnect#1030]
![image](https://user-images.githubusercontent.com/32936898/101991271-7e0f2b00-3ce6-11eb-873f-963212ee318c.png)

i have met this warning. kde connect almostly cannot find computer and computer also cannot connect mobile phone. Excuse me, what reasons can result this warning? thank you!

**Comment by Freed-Wu** [comment]
my kde connect is 1.15.1. and gsconnect is 28.

**Comment by Freed-Wu** [comment]
Thanks for your suggestion! i'll take a try to update my gnome-shell from 3.32 to 3.38 then install a newer gsconnect to see whether the warning exist.

**Comment by andyholmes** [comment]
This is probably a TLS error, but it's hard to say because you haven't provided any logs or information about your system.

**Comment by Freed-Wu** [comment]
Thanks for everyone! i find it is associated with my phone, not my computer. :joy:

hope it can help other who met this warning, too. Thanks!
