### ISSUE TITLE
GS Connect device discovery failing

### ISSUE THREAD

**Issue by xTeixeira** [andyholmes/gnome-shell-extension-gsconnect#105]
I use GS Connect on my computer at work with my phone with no problems.

However, when I try to pair my laptop with the same phone, my phone is never discovered on my laptop nor is my laptop discovered on my phone.

I briefly installed KDE Connect for testing, and using KDE Connect both devices discovered each other and paired with no problems whatsoever.

Also, I'm able to discover other devices on the same network, which consistently show up both on my laptop and my phone, but still my phone/laptop don't see each other.

I'm running the latest version of Gnome and GS Connect on Arch Linux. Also latest version of KDE Connect Android app.

Edit: I just tried it again, and my phone appeared listed on my laptop for a brief moment and disappeared again.

**Comment by andyholmes** [comment]
Could check the debug logs to see what port GSConnect is listening on for devices?

**Comment by xTeixeira** [comment]
Daemon log:
```
JS LOG: [gsconnect@andyholmes.github.io]: UdpListener.send()
JS LOG: [gsconnect@andyholmes.github.io]: UdpListener.receive()
JS LOG: [gsconnect@andyholmes.github.io]: Daemon._addDevice(goldstein)
JS LOG: [gsconnect@andyholmes.github.io]: UdpListener.receive()
JS LOG: [gsconnect@andyholmes.github.io]: Daemon._addDevice(Teixeira)
JS LOG: Daemon: Adding device
JS LOG: [gsconnect@andyholmes.github.io]: Teixeira (81ff0f74664e41f0)
JS LOG: Connecting to '81ff0f74664e41f0'
JS LOG: [gsconnect@andyholmes.github.io]: Teixeira (81ff0f74664e41f0)
JS LOG: [gsconnect@andyholmes.github.io]: Teixeira (81ff0f74664e41f0) already active
JS LOG: [gsconnect@andyholmes.github.io]: UdpListener.receive()
JS LOG: [gsconnect@andyholmes.github.io]: Daemon._addDevice(Teixeira)
JS LOG: Daemon: Updating device
JS LOG: [gsconnect@andyholmes.github.io]: Teixeira (81ff0f74664e41f0)
JS LOG: Received from 'Teixeira'
JS LOG: [gsconnect@andyholmes.github.io]: Teixeira (81ff0f74664e41f0)
JS LOG: [gsconnect@andyholmes.github.io]: Teixeira (81ff0f74664e41f0) already active
JS LOG: Error connecting: Gio.TlsError: Peer sent fatal TLS alert: Unknown certificate
JS LOG: Disconnected from 'Teixeira'
JS LOG: [gsconnect@andyholmes.github.io]: Daemon._removeDevice(/org/gnome/Shell/Extensions/GSConnect/Device/81ff0f74664e41f0)
JS LOG: Daemon: Removing device
```

**Comment by andyholmes** [comment]
> JS LOG: Error connecting: Gio.TlsError: Peer sent fatal TLS alert: Unknown certificate

This means your device `Teixeira (81ff0f74664e41f0)` is using an unexpected TLS certificate. Was this device previously paired, possibly with a previous version of GSConnect? If so, can you unpair it in the KDE Connect app or GSConnect and try repairing?

**Comment by xTeixeira** [comment]
Unpairing did it. Is it intended/normal that I can only pair it to one computer at a time?

**Comment by xTeixeira** [comment]
Alright. I'll start using the version distributed in the AUR then. Thanks.
