### ISSUE TITLE
Implement Repliable Notifications

### ISSUE THREAD

**Issue by aia832003** [andyholmes/gnome-shell-extension-gsconnect#106]
Is there a way to implement the IM protocol to have inline replies to SMS notifications like the ones for Pidgin? https://extensions.gnome.org/extension/782/pidgin-im-integration/

I've been using the Pushbullet plugin for Pidgin, but love the much more native feel here on GSconnect. Keep up the great work!

**Comment by andyholmes** [comment]
In principle, it's probably possible, but I don't know much about telepathy or how to integrate GSConnect with it. If someone wanted to step up and help out with that I'd be happy to merge it though.

**Comment by oromay** [comment]
Replies are working smoothly in KDE Plasma. Would be a great feature to implement.

**Comment by andyholmes** [comment]
Yes, they also do this using telepathy. Polari seems to implement this in part relying on C. If that's necessary then it will be a no-go for GSConnect since it can't rely on architecture dependant code and be distributed as an extension. If it's not necessary then it will depend on someone more familiar with Telepathy-GLib than me.

**Comment by andyholmes** [comment]
This will take a little but of work, but I believe it may be possible to implement with a bit of a hack and bypass telepathy once v13 is merged and stable, so I've set the milestone for then.

**Comment by nicolasfella** [comment]
Quick reply in KDE Connect is implemented in two ways: Via SMS Plugin and Notification Plugin. Neither one is using Telepathy. The SMS plugin way (dropped in master) is simply telling the phone to send an SMS. The notifications one (for Whatsapp etc.) is using the quick reply field provided by the notification. Have a look at the desktop notifications plugin on how to make use of that

**Comment by andyholmes** [comment]
I'm going to close this because it's been implemented and committed to master. The latest release candidate includes this feature.
