### ISSUE TITLE
Problems with discovery (Ubuntu 18.04)

### ISSUE THREAD

**Issue by michalmaria** [andyholmes/gnome-shell-extension-gsconnect#107]
With my personal laptop and Ubuntu Desktop 18.04 everything works as a charm. However in our networked environment (Ubuntu Desktop 18.04 with users logging via OpenLDAP+Kerberos and home directories provided by NFS server), I'm unable to see the desktop in the KDE Connect app. If I tap on refresh, I get this in the journal:

máj 15 08:43:34 paulus gjs[2402]: JS LOG: Daemon: Adding device
máj 15 08:43:34 paulus gjs[2402]: JS LOG: Connecting to '9a0ab5649870a8be'
máj 15 08:43:35 paulus gjs[2402]: JS LOG: Error connecting: Gio.TlsError: Partner odoslal závažnú výstrahu TLS: Unknown certificate
máj 15 08:43:35 paulus gjs[2402]: JS LOG: Disconnected from 'Sony'
máj 15 08:43:35 paulus gjs[2402]: JS LOG: Daemon: Removing device
máj 15 08:43:35 paulus gnome-shell[2154]: Object .Gjs_GSConnectShellPluginButton (0x55c163aeb530), has been already finalized. Impossible to set any property to it.
máj 15 08:43:35 paulus gnome-shell[2154]: Object .Gjs_GSConnectShellPluginButton (0x55c16555f140), has been already finalized. Impossible to set any property to it.
máj 15 08:43:35 paulus org.gnome.Shell.desktop[2154]: == Stack trace for context 0x55c16158a320 ==
máj 15 08:43:35 paulus org.gnome.Shell.desktop[2154]: #0 0x55c161947e48 i   /home/michalmaria/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/extension.js:238 (0x7f823008ba28 @ 21)
máj 15 08:43:35 paulus org.gnome.Shell.desktop[2154]: #1 0x7ffe0d029670 b   resource:///org/gnome/gjs/modules/signals.js:128 (0x7f82484d3230 @ 386)
máj 15 08:43:35 paulus org.gnome.Shell.desktop[2154]: #2 0x55c161947db8 i   resource:///org/gnome/shell/ui/popupMenu.js:1083 (0x7f82482285e8 @ 23)
máj 15 08:43:35 paulus org.gnome.Shell.desktop[2154]: #3 0x7ffe0d02aa00 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7f82484b5de0 @ 71)
máj 15 08:43:35 paulus org.gnome.Shell.desktop[2154]: #4 0x55c161947d30 i   resource:///org/gnome/shell/ui/popupMenu.js:750 (0x7f8248226670 @ 17)
máj 15 08:43:35 paulus org.gnome.Shell.desktop[2154]: #5 0x7ffe0d02bd80 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7f82484b5de0 @ 71)
máj 15 08:43:35 paulus org.gnome.Shell.desktop[2154]: #6 0x55c161947c90 i   resource:///org/gnome/shell/ui/popupMenu.js:738 (0x7f8248226560 @ 81)
máj 15 08:43:35 paulus org.gnome.Shell.desktop[2154]: #7 0x7ffe0d02d100 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7f82484b5de0 @ 71)
máj 15 08:43:35 paulus org.gnome.Shell.desktop[2154]: #8 0x55c161947c08 i   resource:///org/gnome/shell/ui/popupMenu.js:751 (0x7f8248226670 @ 32)
máj 15 08:43:35 paulus org.gnome.Shell.desktop[2154]: #9 0x7ffe0d02e480 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7f82484b5de0 @ 71)
máj 15 08:43:35 paulus org.gnome.Shell.desktop[2154]: #10 0x55c161947b80 i   /home/michalmaria/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/extension.js:442 (0x7f82300b72b8 @ 67)
máj 15 08:43:35 paulus org.gnome.Shell.desktop[2154]: #11 0x7ffe0d02fb80 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7f82484b5de0 @ 71)
máj 15 08:43:35 paulus org.gnome.Shell.desktop[2154]: #12 0x55c161947af8 i   /home/michalmaria/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/extension.js:507 (0x7f82300b74d8 @ 52)
máj 15 08:43:35 paulus org.gnome.Shell.desktop[2154]: #13 0x7ffe0d030f00 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7f82484b5de0 @ 71)
máj 15 08:43:35 paulus org.gnome.Shell.desktop[2154]: #14 0x55c161947a58 i   /home/michalmaria/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/extension.js:734 (0x7f82300b7b38 @ 209)
máj 15 08:43:35 paulus org.gnome.Shell.desktop[2154]: #15 0x7ffe0d032280 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7f82484b5de0 @ 71)
máj 15 08:43:35 paulus org.gnome.Shell.desktop[2154]: #16 0x55c161947998 i   self-hosted:917 (0x7f82484f12b8 @ 394)
máj 15 08:43:35 paulus org.gnome.Shell.desktop[2154]: #17 0x55c1619478c8 i   /home/michalmaria/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/client.js:742 (0x7f82300c13c8 @ 408)
máj 15 08:43:35 paulus org.gnome.Shell.desktop[2154]: #18 0x7ffe0d034650 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7f82484b5de0 @ 71)
máj 15 08:43:35 paulus org.gnome.Shell.desktop[2154]: #19 0x55c161947830 i   /home/michalmaria/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/client.js:708 (0x7f82300bef78 @ 66)
máj 15 08:43:35 paulus org.gnome.Shell.desktop[2154]: == Stack trace for context 0x55c16158a320 ==
máj 15 08:43:35 paulus org.gnome.Shell.desktop[2154]: #0 0x55c161947e48 i   /home/michalmaria/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/extension.js:239 (0x7f823008ba28 @ 38)
máj 15 08:43:35 paulus org.gnome.Shell.desktop[2154]: #1 0x7ffe0d029670 b   resource:///org/gnome/gjs/modules/signals.js:128 (0x7f82484d3230 @ 386)
máj 15 08:43:35 paulus org.gnome.Shell.desktop[2154]: #2 0x55c161947db8 i   resource:///org/gnome/shell/ui/popupMenu.js:1083 (0x7f82482285e8 @ 23)
máj 15 08:43:35 paulus org.gnome.Shell.desktop[2154]: #3 0x7ffe0d02aa00 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7f82484b5de0 @ 71)
máj 15 08:43:35 paulus org.gnome.Shell.desktop[2154]: #4 0x55c161947d30 i   resource:///org/gnome/shell/ui/popupMenu.js:750 (0x7f8248226670 @ 17)
máj 15 08:43:35 paulus org.gnome.Shell.desktop[2154]: #5 0x7ffe0d02bd80 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7f82484b5de0 @ 71)
máj 15 08:43:35 paulus org.gnome.Shell.desktop[2154]: #6 0x55c161947c90 i   resource:///org/gnome/shell/ui/popupMenu.js:738 (0x7f8248226560 @ 81)
máj 15 08:43:35 paulus org.gnome.Shell.desktop[2154]: #7 0x7ffe0d02d100 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7f82484b5de0 @ 71)
máj 15 08:43:35 paulus org.gnome.Shell.desktop[2154]: #8 0x55c161947c08 i   resource:///org/gnome/shell/ui/popupMenu.js:751 (0x7f8248226670 @ 32)
máj 15 08:43:35 paulus org.gnome.Shell.desktop[2154]: #9 0x7ffe0d02e480 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7f82484b5de0 @ 71)
máj 15 08:43:35 paulus org.gnome.Shell.desktop[2154]: #10 0x55c161947b80 i   /home/michalmaria/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/extension.js:442 (0x7f82300b72b8 @ 67)
máj 15 08:43:35 paulus org.gnome.Shell.desktop[2154]: #11 0x7ffe0d02fb80 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7f82484b5de0 @ 71)
máj 15 08:43:35 paulus org.gnome.Shell.desktop[2154]: #12 0x55c161947af8 i   /home/michalmaria/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/extension.js:507 (0x7f82300b74d8 @ 52)
máj 15 08:43:35 paulus org.gnome.Shell.desktop[2154]: #13 0x7ffe0d030f00 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7f82484b5de0 @ 71)
máj 15 08:43:35 paulus org.gnome.Shell.desktop[2154]: #14 0x55c161947a58 i   /home/michalmaria/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/extension.js:734 (0x7f82300b7b38 @ 209)
máj 15 08:43:35 paulus org.gnome.Shell.desktop[2154]: #15 0x7ffe0d032280 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7f82484b5de0 @ 71)
máj 15 08:43:35 paulus org.gnome.Shell.desktop[2154]: #16 0x55c161947998 i   self-hosted:917 (0x7f82484f12b8 @ 394)
máj 15 08:43:35 paulus org.gnome.Shell.desktop[2154]: #17 0x55c1619478c8 i   /home/michalmaria/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/client.js:742 (0x7f82300c13c8 @ 408)
máj 15 08:43:35 paulus org.gnome.Shell.desktop[2154]: #18 0x7ffe0d034650 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7f82484b5de0 @ 71)
máj 15 08:43:35 paulus org.gnome.Shell.desktop[2154]: #19 0x55c161947830 i   /home/michalmaria/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/client.js:708 (0x7f82300bef78 @ 66)
máj 15 08:43:35 paulus gnome-shell[2154]: Object .Gjs_GSConnectShellPluginButton (0x55c1648628c0), has been already finalized. Impossible to set any property to it.
máj 15 08:43:35 paulus gnome-shell[2154]: Object .Gjs_GSConnectShellPluginButton (0x55c16394abc0), has been already finalized. Impossible to set any property to it.
máj 15 08:43:35 paulus org.gnome.Shell.desktop[2154]: == Stack trace for context 0x55c16158a320 ==
máj 15 08:43:35 paulus org.gnome.Shell.desktop[2154]: #0 0x55c161947dc0 i   /home/michalmaria/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/extension.js:238 (0x7f823008ba28 @ 21)
máj 15 08:43:35 paulus org.gnome.Shell.desktop[2154]: #1 0x7ffe0d02a160 b   resource:///org/gnome/gjs/modules/signals.js:128 (0x7f82484d3230 @ 386)
máj 15 08:43:35 paulus org.gnome.Shell.desktop[2154]: #2 0x55c161947d30 i   resource:///org/gnome/shell/ui/popupMenu.js:1083 (0x7f82482285e8 @ 23)
máj 15 08:43:35 paulus org.gnome.Shell.desktop[2154]: #3 0x7ffe0d02b4f0 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7f82484b5de0 @ 71)
máj 15 08:43:35 paulus org.gnome.Shell.desktop[2154]: #4 0x55c161947ca8 i   resource:///org/gnome/shell/ui/popupMenu.js:750 (0x7f8248226670 @ 17)
máj 15 08:43:35 paulus org.gnome.Shell.desktop[2154]: #5 0x7ffe0d02c870 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7f82484b5de0 @ 71)
máj 15 08:43:35 paulus org.gnome.Shell.desktop[2154]: #6 0x7ffe0d02d070 b   resource:///org/gnome/shell/ui/popupMenu.js:738 (0x7f8248226560 @ 81)
máj 15 08:43:35 paulus org.gnome.Shell.desktop[2154]: #7 0x7ffe0d02e480 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7f82484b5de0 @ 71)
máj 15 08:43:35 paulus org.gnome.Shell.desktop[2154]: #8 0x55c161947b80 i   resource:///org/gnome/shell/ui/popupMenu.js:751 (0x7f8248226670 @ 32)
máj 15 08:43:35 paulus org.gnome.Shell.desktop[2154]: #9 0x7ffe0d02f800 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7f82484b5de0 @ 71)
máj 15 08:43:35 paulus org.gnome.Shell.desktop[2154]: #10 0x55c161947af8 i   /home/michalmaria/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/extension.js:442 (0x7f82300b72b8 @ 67)
máj 15 08:43:35 paulus org.gnome.Shell.desktop[2154]: #11 0x7ffe0d030f00 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7f82484b5de0 @ 71)
máj 15 08:43:35 paulus org.gnome.Shell.desktop[2154]: #12 0x55c161947a58 i   /home/michalmaria/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/extension.js:737 (0x7f82300b7b38 @ 247)
máj 15 08:43:35 paulus org.gnome.Shell.desktop[2154]: #13 0x7ffe0d032280 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7f82484b5de0 @ 71)
máj 15 08:43:35 paulus org.gnome.Shell.desktop[2154]: #14 0x55c161947998 i   self-hosted:917 (0x7f82484f12b8 @ 394)
máj 15 08:43:35 paulus org.gnome.Shell.desktop[2154]: #15 0x55c1619478c8 i   /home/michalmaria/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/client.js:742 (0x7f82300c13c8 @ 408)
máj 15 08:43:35 paulus org.gnome.Shell.desktop[2154]: #16 0x7ffe0d034650 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7f82484b5de0 @ 71)
máj 15 08:43:35 paulus org.gnome.Shell.desktop[2154]: #17 0x55c161947830 i   /home/michalmaria/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/client.js:708 (0x7f82300bef78 @ 66)
máj 15 08:43:35 paulus org.gnome.Shell.desktop[2154]: == Stack trace for context 0x55c16158a320 ==
máj 15 08:43:35 paulus org.gnome.Shell.desktop[2154]: #0 0x55c161947dc0 i   /home/michalmaria/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/extension.js:239 (0x7f823008ba28 @ 38)
máj 15 08:43:35 paulus org.gnome.Shell.desktop[2154]: #1 0x7ffe0d02a160 b   resource:///org/gnome/gjs/modules/signals.js:128 (0x7f82484d3230 @ 386)
máj 15 08:43:35 paulus org.gnome.Shell.desktop[2154]: #2 0x55c161947d30 i   resource:///org/gnome/shell/ui/popupMenu.js:1083 (0x7f82482285e8 @ 23)
máj 15 08:43:35 paulus org.gnome.Shell.desktop[2154]: #3 0x7ffe0d02b4f0 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7f82484b5de0 @ 71)
máj 15 08:43:35 paulus org.gnome.Shell.desktop[2154]: #4 0x55c161947ca8 i   resource:///org/gnome/shell/ui/popupMenu.js:750 (0x7f8248226670 @ 17)
máj 15 08:43:35 paulus org.gnome.Shell.desktop[2154]: #5 0x7ffe0d02c870 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7f82484b5de0 @ 71)
máj 15 08:43:35 paulus org.gnome.Shell.desktop[2154]: #6 0x7ffe0d02d070 b   resource:///org/gnome/shell/ui/popupMenu.js:738 (0x7f8248226560 @ 81)
máj 15 08:43:35 paulus org.gnome.Shell.desktop[2154]: #7 0x7ffe0d02e480 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7f82484b5de0 @ 71)
máj 15 08:43:35 paulus org.gnome.Shell.desktop[2154]: #8 0x55c161947b80 i   resource:///org/gnome/shell/ui/popupMenu.js:751 (0x7f8248226670 @ 32)
máj 15 08:43:35 paulus org.gnome.Shell.desktop[2154]: #9 0x7ffe0d02f800 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7f82484b5de0 @ 71)
máj 15 08:43:35 paulus org.gnome.Shell.desktop[2154]: #10 0x55c161947af8 i   /home/michalmaria/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/extension.js:442 (0x7f82300b72b8 @ 67)
máj 15 08:43:35 paulus org.gnome.Shell.desktop[2154]: #11 0x7ffe0d030f00 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7f82484b5de0 @ 71)
máj 15 08:43:35 paulus org.gnome.Shell.desktop[2154]: #12 0x55c161947a58 i   /home/michalmaria/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/extension.js:737 (0x7f82300b7b38 @ 247)
máj 15 08:43:35 paulus org.gnome.Shell.desktop[2154]: #13 0x7ffe0d032280 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7f82484b5de0 @ 71)
máj 15 08:43:35 paulus org.gnome.Shell.desktop[2154]: #14 0x55c161947998 i   self-hosted:917 (0x7f82484f12b8 @ 394)
máj 15 08:43:35 paulus org.gnome.Shell.desktop[2154]: #15 0x55c1619478c8 i   /home/michalmaria/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/client.js:742 (0x7f82300c13c8 @ 408)
máj 15 08:43:35 paulus org.gnome.Shell.desktop[2154]: #16 0x7ffe0d034650 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7f82484b5de0 @ 71)
máj 15 08:43:35 paulus org.gnome.Shell.desktop[2154]: #17 0x55c161947830 i   /home/michalmaria/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/client.js:708 (0x7f82300bef78 @ 66)

What's going on?

**Comment by michalmaria** [comment]
No tunneling, RDC or anything of that. I'm using version 10 from the website. I'm running a normal desktop install, but I'm logged in via OpenLDAP+Kerberos (authentication and user data provided by a remote server - Ubuntu Server 18.04), and the home folder is also provided by the same server via NFS. System and applications are running on the local computer, but they get user data (config, cache and the like) from the home folder, which is not at the local computer - although the apps do not really see that, because NFS... Gnome extensions are installed for the user only - i.e. in they are present inside the home folder.

I would not expect any problem with that, maybe there is some strange issue with the underlying software. (E.g. because of the bugs in the nfs-kernel-server package, the server is ignoring the no_root_squash option with NFS exports and thus the root user on the local computer does not have any access to the home folder - local root gets translated to remote nfs_nobody, courtesy of idmapd. That's why snaps with their current implementation don't work... And they call it an LTS release. :-/)

I'm writing it here, because on my personal laptop, with the exact same distro version and applications (including the dependences from the Wiki) everything works. Maybe the logs will at least clarify whether this is a problem of the extension, or something else.

BTW.: The server-client situation we have here is a completely standard implementation, used especially in enterprise or other institutional networks. There are no special quirks here, no strange proxies, tunnels, VPNs or whatever else. Every computer uses ufw, but the ports 1716, 1717 and 1764 are open (and I did try it with the firewall down completely as well).

One more piece of information: the debug mode provided this while refreshing the device view in the KDE Connect app:
JS LOG: [gsconnect@andyholmes.github.io]: UdpListener.receive()
JS LOG: [gsconnect@andyholmes.github.io]: Daemon._addDevice(Sony)
JS LOG: Daemon: Adding device
JS LOG: [gsconnect@andyholmes.github.io]: Sony (9a0ab5649870a8be)
JS LOG: Connecting to '9a0ab5649870a8be'
JS LOG: Error connecting: Gio.TlsError: Partner odoslal závažnú výstrahu TLS: Unknown certificate
JS LOG: Disconnected from 'Sony'
JS LOG: [gsconnect@andyholmes.github.io]: Daemon._removeDevice(/org/gnome/Shell/Extensions/GSConnect/Device/9a0ab5649870a8be)
JS LOG: Daemon: Removing device

**Comment by andyholmes** [comment]
If you're using v10 there's a good chance you are experiencing #26 which can confuse the Android app into thinking all devices are the same, convincing it to expect the wrong TLS certificate. v11 is available on the releases page.

I would also advise you open just port 1716 and a few ports between 1739-1764 which are used for file transfers (including notification icons) and sftp.

**Comment by michalmaria** [comment]
Installed v11, and it works! When will version 11 be available via the extension website? Folks around here are not used to manually unzip stuff into hidden folders...

**Comment by andyholmes** [comment]
Its already been uploaded but the review process is volunteer driven and pretty lengthy sometimes.

**Comment by michalmaria** [comment]
Allright. I'll wait then. Thanks for the great work!
