### ISSUE TITLE
Phone icon doesn't look right in menu

### ISSUE THREAD

**Issue by solsticedhiver** [andyholmes/gnome-shell-extension-gsconnect#109]
Just to mention what I think is a little graphic bug (?): the phone icon seems to be oversized or stretched.

![capture d ecran de 2018-05-15 11-12-47](https://user-images.githubusercontent.com/105990/40048133-b7d4be28-5831-11e8-9092-9dc53dbbdfbb.png)

This is on ubuntu 18.04 using gnome shell and wayland.

The first part is when using ubuntu-mono-dark icon theme (which is the default ? I don't remember) and the second Moka icon theme.

**Comment by solsticedhiver** [comment]
I installed from extensions.gnome.org. May I ask why the update is not there ?

**Comment by christianfl** [comment]
Because GNOME Shell extensions are security relevant so every update has to be reviewed. The update is in the review state by now.
