### ISSUE TITLE
Phone with circle icon not scaling correctly

### ISSUE THREAD

**Issue by RTheren** [andyholmes/gnome-shell-extension-gsconnect#110]
![crop](https://user-images.githubusercontent.com/12765090/40051300-88857672-583a-11e8-9f7e-a41759f518bb.png)

The icon of a phone with green circle looks like a ellipse, probably due to low resolution of my laptop (1366x768).

Running on Ubuntu 18.04
I have Thinkpad T520

Would it be possible to either change, remove or rescale the icon?

**Comment by christianfl** [comment]
Look at the recently closed issues before filing a new one.

**Comment by RTheren** [comment]
duplicate of #109
