### ISSUE TITLE
iPhone client

### ISSUE THREAD

**Issue by SpaceboyRoss01** [andyholmes/gnome-shell-extension-gsconnect#112]
I'm sure that it's not just me but other people might want to connect using iPhones. So, my question is will there be a way for an iPhone to connect to GNOME using GSConnect possibly in the future?

**Comment by andyholmes** [comment]
Well, obviously someone would have to step up and write an iPhone app implementing the KDE Connect protocol. I don't have have an iPhone or know anything about iPhone apps. Sorry, it's a bit out of scope for this project.
