### ISSUE TITLE
Discovery problem

### ISSUE THREAD

**Issue by ibahnasy** [andyholmes/gnome-shell-extension-gsconnect#113]
The extension and the app are unable to see each other.
I tried building the latest git code as well.
I ran tcpdump and I can see the broadcast packet being received.

Distro: Arch
gnome-shell: 3.28.2

**Comment by andyholmes** [comment]
Hi, could you please post the debug logs from the GSConnect daemon showing what port it is listening on?

**Comment by ibahnasy** [comment]
JS WARNING: [/home/<username>/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/device.js 652]: reference to undefined property "_dbus"
JS ERROR: TypeError: this._dbus is undefined
Device<.destroy@/home/neo/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/device.js:652:9
wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
Daemon<.vfunc_shutdown@/home/neo/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:880:13
wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
@/home/neo/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:889:2

gsignal.c:2641: instance '0x7fcefc001560' has no handler with id '1699'
JS LOG: UdpListener: using port 1717
JS LOG: TcpListener: using port 1717
JS LOG: 0 devices loaded from cache
JS LOG: GSConnect: Shutting down
JS LOG: UdpListener: using port 1717
JS LOG: TcpListener: using port 1717
JS LOG: 0 devices loaded from cache

JS LOG: [gsconnect@andyholmes.github.io]: UdpListener.send()
JS LOG: [gsconnect@andyholmes.github.io]: UdpListener.receive()
JS LOG: [gsconnect@andyholmes.github.io]: Daemon._addDevice(GSConnect)

**Comment by ibahnasy** [comment]
I installed the extension from the extensions site then I captured this error:

JS LOG: [gsconnect@andyholmes.github.io]: Daemon._addDevice(Xiaomi)
JS LOG: Daemon: Updating device
JS LOG: [gsconnect@andyholmes.github.io]: Xiaomi (e64b08372c455eb0)
JS LOG: Received from 'Xiaomi'
JS LOG: [gsconnect@andyholmes.github.io]: Xiaomi (e64b08372c455eb0)
JS LOG: [gsconnect@andyholmes.github.io]: Xiaomi (e64b08372c455eb0) already active
JS LOG: Error connecting: Gio.TlsError: Peer failed to perform TLS handshake
JS LOG: Disconnected from 'Xiaomi'
JS LOG: [gsconnect@andyholmes.github.io]: Daemon._removeDevice(/org/gnome/Shell/Extensions/GSConnect/Device/e64b08372c455eb0)
JS LOG: Daemon: Removing device

**Comment by ibahnasy** [comment]
I installed KDE Connect version 1.8.4 and everything works fine now.
That issue happened on version 1.8.2 from f-droid.
