### ISSUE TITLE
No devices in drop-down menu / icons - ubuntu 18.04 minimal install

### ISSUE THREAD

**Issue by amartos** [andyholmes/gnome-shell-extension-gsconnect#117]
Hi.

Fresh install of 18.04, I went for the new minimal install option. I installed all the dependencies indicated in the wiki, and installed the v11 manually. As shown in the picture, I don't have any device showing up in the menu, despite having linked my phone. Phone unlocked or locked, KDEconnect app opened or not doesn't change anything. I'm using Xorg.

Notifications sharing, media controls, mouse control, sending files from nautilus, all of that do work as intended. I just don't have the device showing up in the menu.

Is there a dependency that I would lack and would not be noted in the wiki ?

![gsconnect issue](https://user-images.githubusercontent.com/32329732/40192899-f6f19d30-5a05-11e8-952b-dd72d561f332.png)
![gsconnect issue 2](https://user-images.githubusercontent.com/32329732/40193509-c20d0526-5a07-11e8-9767-a0791aef5c36.png)

**Comment by andyholmes** [comment]
Are you you don't have KDE Connect installed *or* running on your desktop? Is your device listed in the *Devices* tab of the Preferences window?

**Comment by amartos** [comment]
I did have KDEconnect *before* wiping out the disk, so there are surely config files remaining in my home folder (I restored it by using rsync on the whole folder). But no, KDE connect is not even installed. 

All devices from my LAN are listed, and I can ping and link them.

**Comment by andyholmes** [comment]
I'm not sure what could be causing this, is there any error output in the debug log?

**Comment by amartos** [comment]
`May 18 19:40:45 alex-laptop gnome-shell[1928]: [gsconnect@andyholmes.github.io]: disabling extension
May 18 19:40:45 alex-laptop gnome-shell-ext[17472]: JS LOG: Extension gsconnect@andyholmes.github.io already installed in /home/alexandre/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io. /home/alexandre/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io will not be loaded
May 18 19:40:57 alex-laptop gnome-shell[1928]: [gsconnect@andyholmes.github.io]: enabling extension
May 18 19:40:57 alex-laptop gnome-shell-ext[17472]: JS LOG: Extension gsconnect@andyholmes.github.io already installed in /home/alexandre/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io. /home/alexandre/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io will not be loaded
May 18 19:40:58 alex-laptop gnome-shell[1928]: [gsconnect@andyholmes.github.io]: extension.SystemIndicator._serviceAppeared()
May 18 19:40:58 alex-laptop gnome-shell[1928]: [gsconnect@andyholmes.github.io]: extension.SystemIndicator._deviceAdded(/org/gnome/Shell/Extensions/GSConnect/Device/c638b786bdfeb619)
May 18 19:40:58 alex-laptop gnome-shell[1928]: JS ERROR: Gtk.IconThemeError: L'icône « phone » n'est pas présente dans le thème Paper#012DeviceIcon<._init@/home/alexandre/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/widgets/shell.js:452:21#012wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22#012DeviceButton<._init@/home/alexandre/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/widgets/shell.js:671:20#012wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22#012DeviceMenu<._init@/home/alexandre/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/extension.js:134:29#012wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22#012_Base.prototype._construct@resource:///org/gnome/gjs/modules/_legacy.js:18:5#012Class.prototype._construct/newClass@resource:///org/gnome/gjs/modules/_legacy.js:114:32#012DeviceIndicator<._init@/home/alexandre/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/extension.js:465:27#012wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22#012_Base.prototype._construct@resource:///org/gnome/gjs/modules/_legacy.js:18:5#012Class.prototype._construct/newClass@resource:///org/gnome/gjs/modules/_legacy.js:114:32#012SystemIndicator<._deviceAdded@/home/alexandre/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/extension.js:698:25#012wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22#012SystemIndicator<._serviceAppeared@/home/alexandre/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/extension.js:579:13#012wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22`

I should have done that earlier. Apparently my icon theme (Paper, from ~/.icons) was outdated. I installed another themes from the repos (Numix-light), and now I have all the devices showing up in the menu.

Sorry for the bother.

**Comment by andyholmes** [comment]
No problem, even if it's not my fault it helps me help other people that have the same problem.
