### ISSUE TITLE
GSConnect can't be run from system directory

### ISSUE THREAD

**Issue by Huluti** [andyholmes/gnome-shell-extension-gsconnect#12]
Hi!
I've just tried to use the last version (7) but when I try to open the settings dialog, an error occurred with this message : 
```
Gio.DBusError: Erreur lors de l’appel de StartServiceByName pour org.gnome.Shell.Extensions.GSConnect : GDBus.Error:org.freedesktop.DBus.Error.Spawn.ChildExited: Process org.gnome.Shell.Extensions.GSConnect exited with status 1

Stack trace:
  ProxyBase<._init@/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/client.js:40:9
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  _parent@resource:///org/gnome/gjs/modules/_legacy.js:39:12
  Daemon<._init@/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/client.js:634:9
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  PrefsWidget<._init@/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/prefs.js:98:23
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  buildPrefsWidget@/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/prefs.js:216:23
  Application<._selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:91:22
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  Application<._onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:246:17
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  main@resource:///org/gnome/shell/extensionPrefs/main.js:402:5
  @<main>:1:43
```
That's all for now ;)

**Comment by andyholmes** [comment]
That means that daemon failed to start for some reason, could you run this in a terminal and tell me what it says?

`gjs ~/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js`

**Comment by Huluti** [comment]
It says : 
`L’ouverture du fichier « /home/hugop/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js » a échoué : Aucun fichier ou dossier de ce type`

I understand what is happening now ... I have installed the extension in `/usr/share/gnome-shell/extensions` instead of `~/.local/share/gnome-shell/extensions`. 
Don't know if you have to do something about this, maybe no.

**Comment by andyholmes** [comment]
The extension isn't really meant to be install under `/usr/share` and there's a number of changes that would have to be made to make it compatible with that type of install.

It's probably best just to keep it in the user directory, since it will eventually be updated through extensions.gnome.org and I don't plan on supporting system packages like deb/rpm.

**Comment by Huluti** [comment]
No problem, I understand ;) Btw you do a great work!

**Comment by andyholmes** [comment]
See also: https://aur.archlinux.org/packages/gnome-shell-extension-gsconnect/

**Comment by andyholmes** [comment]
This zip includes a provisional fix for this issue, feedback appreciated:

[gsconnect@andyholmes.github.io.zip](https://github.com/andyholmes/gnome-shell-extension-gsconnect/files/1565287/gsconnect.andyholmes.github.io.zip)

**Comment by SISheogorath** [comment]
The zip file works over here 👋 

Thanks for providing it, but when these changes make it to the next release even better!

**Comment by andyholmes** [comment]
Glad to hear it, I hope to add the possibility to build a true system version, but if this works for now that's great.
