### ISSUE TITLE
Can't connect two devices

### ISSUE THREAD

**Issue by strongthany** [andyholmes/gnome-shell-extension-gsconnect#123]
I have added my home Laptop(thinkpad t420, Ubuntu 18.04), but when I try to add my work laptop(also ubuntu 18.04), the computer does not show up for available devices. I have only been able to get it to connect by clearing data out of the mobile app and restarting it.

**Comment by andyholmes** [comment]
This sounds like a duplcate of #26, are you using v11 from the releases page or v10 from the extensions website?

**Comment by strongthany** [comment]
Version 10. How do I update to 11?

**Comment by samrobbins85** [comment]
Will the Extensions version get updated with time, or is the zip the new correct way to install it?

**Comment by andyholmes** [comment]
v11 was uploaded on April 25th, but the review process for extensions is volunteer based and can take some time.

I'd always recommend using the latest version from the releases page anyways, but that depends on how reliable you find my releases and how much you trust me (unless you personally review the code changes).
