### ISSUE TITLE
Add handler for tel: links

### ISSUE THREAD

**Issue by remcohaszing** [andyholmes/gnome-shell-extension-gsconnect#124]
KDE connect has a handler for `tel:` links. This opens the phone app on the mobile device.

It would be great if gsconnect would support this too.

**Comment by andyholmes** [comment]
Preliminary support for this has been pushed to master and should be included in when v12 is released. You can test it now using this zip:

[gsconnect@andyholmes.github.io.zip](https://github.com/andyholmes/gnome-shell-extension-gsconnect/files/2028429/gsconnect.andyholmes.github.io.zip)
