### ISSUE TITLE
High CPU Usage when using system-wide proxy

### ISSUE THREAD

**Issue by eera5607** [andyholmes/gnome-shell-extension-gsconnect#125]
Hi. Thank you for this great tool and for your hard work developing it. I recently noticed that my laptop fan was making more noise than usual and I checked on the system monitor and I had 1 of 8 CPUs always at 100%. 
![selection_003](https://user-images.githubusercontent.com/5403536/40399644-bf4ba84a-5dfb-11e8-9c16-f3f6b3e4f4f8.png)

I checked the processes and there was one process that was always at 12%. This is the process and its information. 
![selection_002](https://user-images.githubusercontent.com/5403536/40399657-d4a1e1f0-5dfb-11e8-8161-ede0ff1aa539.png)

When I close the process, everything goes back to normal but if I reopen the GSConnect the same thing happens again. I think it might be an issue within my system, I recently manually updated GSConnet to the latest version because it has not  been publish on the Gnome Extensions directory. 

Thanks.

**Comment by andyholmes** [comment]
Yikes, that's really bad! GSConnect should idle at 0% since it only does anything in response to events, whether local or remote. Could you turn on debugging in the _About_ page of _Preferences_ and see if there's any error messages for either Gjs or Gnome Shell?

**Comment by eera5607** [comment]
No, only this. 

`Theme parsing error: gtk.css:2646:51: The :insensitive pseudo-class is deprecated. Use :disabled instead.
Theme parsing error: gtk.css:2648:74: The :insensitive pseudo-class is deprecated. Use :disabled instead.
Theme parsing error: gtk.css:2649:68: The :insensitive pseudo-class is deprecated. Use :disabled instead.
Theme parsing error: gtk.css:2650:59: The :insensitive pseudo-class is deprecated. Use :disabled instead.
Theme parsing error: gtk.css:2651:53: The :insensitive pseudo-class is deprecated. Use :disabled instead.
JS LOG: UdpListener: using port 1716
JS LOG: TcpListener: using port 1716
JS LOG: Connecting to '8dd80dae6b8fd900'
JS LOG: Connecting to 'eea4f47b-939b-4585-adae-a2906eb00473'
JS LOG: 2 devices loaded from cache
`

**Comment by andyholmes** [comment]
Can you tell if `daemon.js` is stopping and restarting repeatedly (the PID should change)?

**Comment by eera5607** [comment]
No, PID is not changing. 3 new lines on debug:

```
JS LOG: [gsconnect@andyholmes.github.io]: UdpListener.send()
JS LOG: [gsconnect@andyholmes.github.io]: UdpListener.receive()
JS LOG: [gsconnect@andyholmes.github.io]: Daemon._addDevice(GSConnect-Laptop)
```

**Comment by andyholmes** [comment]
Have you restarted Gnome Shell since installing v11 manually? Can you tell me what distribution you're running? I'm not sure what could be causing this, especially if there's no output of activity.

**Comment by eera5607** [comment]
Yes I have restarted Gnome Shell and Ubuntu. 
This is a regular Ubuntu 18.04 distribution. I noticed that even after killing the process after some minutes it starts happening again. If I restart the PC, it starts after 4-5 minutes. If I stop the process it does not happen until I continue the process. I'm not sure but I think this may be happening only when neither of the 2 paired devices are available. I can check if this is true when I get back to home.

**Comment by eera5607** [comment]
I did some tests and noticed that it only happens when I'm connected to a network using a proxy configuration on system wide level. I can't connect the other devices to the network so GSConnect in this laptop isn't connected to any of the paired devices. I don't know why but at home I used it without any issues and connected to the 2 different devices and the process always stayed at 0%. I came back to work and tested and some minutes after configuring the proxy as usual, the process started to take one CPU again. I don't know if someone else can reproduce this. Thanks for the help.

**Comment by andyholmes** [comment]
Although I'm still not sure what causes this, I'm going to mark the milestone as wip-rewrite to remember to keep it around, since there's no reason to think it will fixed in that branch (yet).

**Comment by GeorgeRamga** [comment]
me too, I'm usig v11 and all correct.
but v12 I have problems whit proxy

**Comment by andyholmes** [comment]
Hi, just thought I'd reassure you this is still a high priority bug for me, although I don't use a proxy or experience it myself.

I think it's unlikely someone who uses a proxy and knows the code-base exists, so if you can give me a description of how I might setup a system proxy myself (to replicate your same problem), I'll try and set aside some time to re-create this bug so I can try and see it in action.

**Comment by Phantom-Punch** [comment]
> I'll try and set some time aside and setup a "fake" proxy,

Easy way to do that is by setting up a socks proxy to any computer you can ssh to. Just run 

`ssh -D 8080 user@remote`

You now have a socks proxy running at localhost port 8080 that forwards traffic to the remote machine.

I'm also facing the same issue with GSConnect taking up CPU with proxy, I can help if you need any debugging. I need a system wide proxy for other applications to access internet past office firewall but not for GSConnect (both phone and computer are connected to same wifi), can you provide a workaround for GSConnect to ignore proxy settings.

**Comment by andyholmes** [comment]
Hmm, I should've looked earlier, but apparently upstream KDE Connect *totally* ignores proxies with no option. Silence in the development channel indicates that no one remembers why.

Try this Zip here and tell me if this fixes your problem (also I snuck in other no-risk goodies):

[Installing from Zip](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Installation#install-from-zip)

[gsconnect@andyholmes.github.io.zip](https://github.com/andyholmes/gnome-shell-extension-gsconnect/files/2582066/gsconnect.andyholmes.github.io.zip)

**Comment by Phantom-Punch** [comment]
> [gsconnect@andyholmes.github.io.zip](https://github.com/andyholmes/gnome-shell-extension-gsconnect/files/2582066/gsconnect.andyholmes.github.io.zip)

This seems to fix the issue for me. It's been a few hours now and cpu usage is at a solid 0% for gjs. The new shell menu also looks nice. Will report back if the issue pops up again. 
Cheers mate.

**Comment by andyholmes** [comment]
Yay, that's one awful bug down (hopefully)!

**Comment by andyholmes** [comment]
Alright, I'm going to close this for now since I haven't heard any bad news. Please re-open if the issue persists and here's an updated Zip from `master` for you guys (instructions in the Wiki, as usual):

[gsconnect@andyholmes.github.io.zip](https://github.com/andyholmes/gnome-shell-extension-gsconnect/files/2596744/gsconnect.andyholmes.github.io.zip)
