### ISSUE TITLE
  I want to translate it into Chinese  How to do it

### ISSUE THREAD

**Issue by PlexPt** [andyholmes/gnome-shell-extension-gsconnect#126]
How to do it
Because I wasn't a developer before.

**Comment by OlegWock** [comment]
Hello, I'm not sure, but looks like you need to download [this](https://github.com/andyholmes/gnome-shell-extension-gsconnect/blob/master/po/org.gnome.Shell.Extensions.GSConnect.pot) file and translate it (I think  [this](https://developer.wordpress.org/themes/functionality/localization/) will be useful) to po file. Then add it to `po` directory and make pull request

**Comment by andyholmes** [comment]
There's a guide for translating GSConnect in the Wiki here: [Translating](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Translating)

**Comment by PlexPt** [comment]
tks
