### ISSUE TITLE
Duplicate incoming SMS messages

### ISSUE THREAD

**Issue by kg6zvp** [andyholmes/gnome-shell-extension-gsconnect#137]
## Steps to Reproduce

1. Wait for an incoming SMS
1. Click the notification icon
1. Wait for a second SMS in that conversation thread

The second SMS will show up as many as 5 times in the conversation window.

**Comment by Saroufim** [comment]
I think this is because an SMS is treated as two things: A regular notification and an SMS so it gets displayed twice.

**Comment by kg6zvp** [comment]
@Saroufim That would make sense if it appeared in the notifications window, but it actually shows up in the window that displays an ongoing SMS conversation. The first received message appears once and subsequent messages appear many times.

**Comment by kg6zvp** [comment]
Here is a redacted example: ![bildschirmfoto von 2018-06-04 15-20-49](https://user-images.githubusercontent.com/1117846/40944906-5d772fbc-680b-11e8-83e7-297a912e3df6.jpg)

**Comment by andyholmes** [comment]
This seems like it might be a duplicate of #76 and #49. Can you try clearing the cache and force stopping the Android app to see if that fixes it? If it doesn't could check the debug logs to ensure the duplicates are being generated by GSConnect?

**Comment by kg6zvp** [comment]
This solution worked. Not sure why since the app was freshly installed before pairing.
