### ISSUE TITLE
Option to enable or disable Telephony features independently

### ISSUE THREAD

**Issue by TwisX** [andyholmes/gnome-shell-extension-gsconnect#138]
The Telephony feature is great for lowering the volume and pausing media during a phone call, but for those of us who use another SMS desktop app, or simply don't want texts on our PCs, there is no way to disable just the SMS option. It's all or nothing. An option to enable or disable the phone call and SMS features independently would be very useful.

Thanks!

**Comment by andyholmes** [comment]
I'm going to close this now since it's fixed in master; the telephony and sms plugins have been split.
