### ISSUE TITLE
Automatically Mount

### ISSUE THREAD

**Issue by salevdns** [andyholmes/gnome-shell-extension-gsconnect#143]
The "Automatically Mount" option in the "Browse Files" settings doesn't seem to work.
My understanding of this feature is that when it is enabled, the phones storage should be mounted as soon as a connection is established. That is not the case (for me). Can anyone confirm?

**Comment by basilrabi** [comment]
Works for me. Do you have `sshfs` installed?
[see this](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Browse-Files-Plugin)

**Comment by salevdns** [comment]
@basilrabi Yes I have.
@andyholmes Yes it mounts as soon as I click on the browse files icon from the device menu but not automatically on connect.

**Comment by andyholmes** [comment]
Are there any errors in the debug log indicating why it's failing?

**Comment by salevdns** [comment]
Also sorry if my op was misleading. I didn't mean that the toggle itself doesn't work or that it gives some error, just that it has no effect if I turn it on.

**Comment by salevdns** [comment]
Ok as I said I will deliver log in a few days. I still remember, that other plugins have loaded after connection: Notifications came in instantly and media control was available. So i guess it is exclusive to the Sftp plugin.

**Comment by salevdns** [comment]
Ok here is the log:
DE: GNOME 3.28.2

<details><summary>JS LOG</summary>
<p>
<pre>JS LOG: [gsconnect@andyholmes.github.io]: UdpListener.receive()
JS LOG: [gsconnect@andyholmes.github.io]: Daemon._addDevice(Xiaomi)
JS LOG: Daemon: Updating device
JS LOG: [gsconnect@andyholmes.github.io]: Xiaomi (1ea2fe9ceacfaebc)
JS LOG: Received from &apos;Xiaomi&apos;
JS LOG: [gsconnect@andyholmes.github.io]: Xiaomi (1ea2fe9ceacfaebc)
JS LOG: Connecting to &apos;1ea2fe9ceacfaebc&apos;
JS LOG: Authenticating &apos;1ea2fe9ceacfaebc&apos;
JS LOG: Connected to &apos;Xiaomi&apos;
JS LOG: [gsconnect@andyholmes.github.io]: Device.enablePlugin(battery, false)
JS LOG: [gsconnect@andyholmes.github.io]: Battery: request()
JS LOG: [gsconnect@andyholmes.github.io]: LanChannel.send(1ea2fe9ceacfaebc, {&quot;id&quot;:0,&quot;type&quot;:&quot;kdeconnect.battery.request&quot;,&quot;body&quot;:{&quot;request&quot;:true}})
JS LOG: [gsconnect@andyholmes.github.io]: Device.enablePlugin(clipboard, false)
JS LOG: [gsconnect@andyholmes.github.io]: Device.enablePlugin(findmyphone, false)
JS LOG: [gsconnect@andyholmes.github.io]: Device.enablePlugin(mpris, false)
JS LOG: [gsconnect@andyholmes.github.io]: Device.enablePlugin(notification, false)
JS LOG: [gsconnect@andyholmes.github.io]: LanChannel.send(1ea2fe9ceacfaebc, {&quot;id&quot;:0,&quot;type&quot;:&quot;kdeconnect.notification.request&quot;,&quot;body&quot;:{&quot;request&quot;:true}})
JS LOG: [gsconnect@andyholmes.github.io]: Device.enablePlugin(mousepad, false)
JS LOG: [gsconnect@andyholmes.github.io]: Cannot load Caribou virtual keyboard for Unicode support
JS LOG: [gsconnect@andyholmes.github.io]: Device.enablePlugin(runcommand, false)
JS LOG: [gsconnect@andyholmes.github.io]: LanChannel.send(1ea2fe9ceacfaebc, {&quot;id&quot;:0,&quot;type&quot;:&quot;kdeconnect.runcommand.request&quot;,&quot;body&quot;:{&quot;requestCommandList&quot;:true}})
JS LOG: [gsconnect@andyholmes.github.io]: Device.enablePlugin(share, false)
JS LOG: [gsconnect@andyholmes.github.io]: Device.enablePlugin(telephony, false)
JS LOG: [gsconnect@andyholmes.github.io]: Device.enablePlugin(sftp, false)
JS LOG: [gsconnect@andyholmes.github.io]: SFTP: mount()
JS LOG: [gsconnect@andyholmes.github.io]: LanChannel.send(1ea2fe9ceacfaebc, {&quot;id&quot;:0,&quot;type&quot;:&quot;kdeconnect.sftp.request&quot;,&quot;body&quot;:{&quot;startBrowsing&quot;:true}})
JS LOG: [gsconnect@andyholmes.github.io]: MPRIS: _updatePlayers()
JS LOG: [gsconnect@andyholmes.github.io]: MPRIS: _listPlayers()
JS LOG: [gsconnect@andyholmes.github.io]: MPRIS: sendPlayerList()
JS LOG: [gsconnect@andyholmes.github.io]: LanChannel.send(1ea2fe9ceacfaebc, {&quot;id&quot;:0,&quot;type&quot;:&quot;kdeconnect.mpris&quot;,&quot;body&quot;:{&quot;playerList&quot;:[]}})
JS LOG: [gsconnect@andyholmes.github.io]: LanChannel.receive(1ea2fe9ceacfaebc)
JS LOG: [gsconnect@andyholmes.github.io]: Device received: {&quot;id&quot;:1529833756533,&quot;type&quot;:&quot;kdeconnect.battery&quot;,&quot;body&quot;:{&quot;currentCharge&quot;:47,&quot;isCharging&quot;:true,&quot;thresholdEvent&quot;:0}}
JS LOG: Received from &apos;Xiaomi&apos;
JS LOG: [gsconnect@andyholmes.github.io]: Battery: handlePacket()
JS LOG: [gsconnect@andyholmes.github.io]: Battery: receive()
JS LOG: [gsconnect@andyholmes.github.io]: LanChannel.receive(1ea2fe9ceacfaebc)
JS LOG: [gsconnect@andyholmes.github.io]: Device received: {&quot;id&quot;:1529833756580,&quot;type&quot;:&quot;kdeconnect.runcommand.request&quot;,&quot;body&quot;:{&quot;requestCommandList&quot;:true}}
JS LOG: Received from &apos;Xiaomi&apos;
JS LOG: [gsconnect@andyholmes.github.io]: RunCommand: handlePacket()
JS LOG: [gsconnect@andyholmes.github.io]: RunCommand: sendCommandList()
JS LOG: [gsconnect@andyholmes.github.io]: LanChannel.send(1ea2fe9ceacfaebc, {&quot;id&quot;:0,&quot;type&quot;:&quot;kdeconnect.runcommand&quot;,&quot;body&quot;:{&quot;commandList&quot;:&quot;{}&quot;}})
JS LOG: [gsconnect@andyholmes.github.io]: LanChannel.receive(1ea2fe9ceacfaebc)
JS LOG: [gsconnect@andyholmes.github.io]: Device received: {&quot;id&quot;:1529833756576,&quot;type&quot;:&quot;kdeconnect.mpris.request&quot;,&quot;body&quot;:{&quot;requestPlayerList&quot;:true}}
JS LOG: Received from &apos;Xiaomi&apos;
JS LOG: [gsconnect@andyholmes.github.io]: MPRIS: handlePacket()
JS LOG: [gsconnect@andyholmes.github.io]: MPRIS: sendPlayerList()
JS LOG: [gsconnect@andyholmes.github.io]: LanChannel.send(1ea2fe9ceacfaebc, {&quot;id&quot;:0,&quot;type&quot;:&quot;kdeconnect.mpris&quot;,&quot;body&quot;:{&quot;playerList&quot;:[]}})
JS LOG: [gsconnect@andyholmes.github.io]: LanChannel.receive(1ea2fe9ceacfaebc)
JS LOG: [gsconnect@andyholmes.github.io]: Device received: {&quot;id&quot;:
...
</p>
</details>

**Comment by andyholmes** [comment]
```
JS LOG: [gsconnect@andyholmes.github.io]: Device.enablePlugin(sftp, false)
JS LOG: [gsconnect@andyholmes.github.io]: SFTP: mount()
JS LOG: [gsconnect@andyholmes.github.io]: LanChannel.send(1ea2fe9ceacfaebc, {"id":0,"type":"kdeconnect.sftp.request","body":{"startBrowsing":true}})
```

It seems like GSConnect is correctly sending the request to begin the mounting procedure, however the Android app is just not responding to the request, unless the response is just later in log and contains some error. There have been reports of problems with Xiaomi devices in the past wrt the Sftp plugin, although if it mounts manually that may not be relevant.

**Comment by ferdnyc** [comment]
#TIL about [`<details>` in GitHub comments](https://github.com/dear-github/dear-github/issues/166)! (Which appears to be largely undocumented, other than that issue thread. Their official docs only deal with Markdown syntax, which it isn't.) So, thanks for that, @salevdns.

**Comment by andyholmes** [comment]
Although it *might* change, I'm labelling this as 'fixed in rewrite' since the 'automount' setting has been removed in favour of using `-o delay_connect` with `sshfs`. This simply waits until the mountpoint is accessed to actually connect, which I think is a better "one size fits all" solution.

**Comment by andyholmes** [comment]
Closing this now since the rewrite has been merged into master.
