### ISSUE TITLE
Option to temporarily disabled notifications/texts

### ISSUE THREAD

**Issue by kg6zvp** [andyholmes/gnome-shell-extension-gsconnect#144]
Having a personal message pop up on the screen during a presentation is unprofessional and sometimes even embarrassing. It would be great to be able to put gsconnect into "work mode" or something to disable notifications and text messages popping up until after it's switched off.

This can be accomplished by changing the settings for each device, but having a single toggle would be really handy.

**Comment by andyholmes** [comment]
I'm going to close this now since the rewrite has been merged into master.
