### ISSUE TITLE
How can I remove "user@desktop" device? (appears to be a duplicate of "GSConnect" device)

### ISSUE THREAD

**Issue by kwill** [andyholmes/gnome-shell-extension-gsconnect#145]
When I tried to connect my phone and desktop for the first time, my phone picked up a device called "username@desktopname". I was able to transfer a file from the phone, but my phone didn't appear as a device in the desktop interface.

After rebooting, my desktop and phone connect as "GSConnect" and "phone" respectively, and show up in each others interfaces as expected.

The old "username@desktopname" device still appears as a third device in both my desktop and phone interfaces. How can I remove it?

**Comment by andyholmes** [comment]
GSConnect doesn't use identifiers such as "user@hostname" so this is likely a result of trying to run either KDE Connect or MConnect at the same time. Once that service has stopped, it's device should be automatically removed if it's unpaired.

**Comment by kwill** [comment]
Confirmed that I had KDE Connect installed but not visibly running. In my case I uninstalled it, logged out and in, and the extra device disappeared. Thanks!
