### ISSUE TITLE
Add-on (compatibility)

### ISSUE THREAD

**Issue by rugk** [andyholmes/gnome-shell-extension-gsconnect#147]
I guess this won't be compatible with https://addons.mozilla.org/de/firefox/addon/kde_connect/ and even if it is, I guess you would have to install [the binary](https://github.com/pdf/kdeconnect-chrome-extension)…

So maybe you do something here…

**Comment by andyholmes** [comment]
What's wrong with the add-on already availabe?

https://addons.mozilla.org/de/firefox/addon/gsconnect/

**Comment by rugk** [comment]
A, did not see/expect that… :laughing: (It's not linked in the app or so… :wink:)
