### ISSUE TITLE
unable to perform actions on external SD card using gsconnect

### ISSUE THREAD

**Issue by dln949** [andyholmes/gnome-shell-extension-gsconnect#148]
running gsconnect 11 on Ubuntu 17.10.  

Using gsconnect, I am able to connect to and browse the external SD cards on several android devices.  However, I am not able to *DO* anything with them via a graphical file browser window via the gsconnect connection.  I cannot create a file on the card, nor delete a file, nor modify it, nor paste a file onto it.  If, for example I try to paste a file from my Ubuntu desktop computer onto the SD card on the Android device via gsconnect I get the error message show in the first attachment.  (However, I *AM* able to copy a file from the android's SD card via gsconnect and then paste it into a directory on my Ubuntu desktop computer, but then I have the unexpected file permissions that you see in the second attachment.)  

I did not know if what I am describing is too closely related to issue #48.  

My questions are:  

Why am I having these problems?  
How can this be fixed?  

![1](https://user-images.githubusercontent.com/8601150/41824912-ed24df9c-77dd-11e8-84b9-384f27ea85d8.png)

![2](https://user-images.githubusercontent.com/8601150/41824916-f5933386-77dd-11e8-9e82-8d66037f7dbd.png)

**Comment by andyholmes** [comment]
This is an upstream problem with the Android app. Although there is some occasional talk on the mailinglist about it, no one has stepped up to implement the required SAF support and there's nothing GSConnect can do to fix it.

**Comment by dln949** [comment]
Ok, thanks for the explanation, I appreciate it.
