### ISSUE TITLE
Unable to upload file

### ISSUE THREAD

**Issue by Truck5067** [andyholmes/gnome-shell-extension-gsconnect#149]
I am running Ubuntu 18.04 LTS and built GSConnect from source so latest  patch was included

    def __init__(self):
        """Initialize translations"""

        GObject.Object.__init__(self)

        try:

I attach a snippet from the debug screen.

All other options seem to work.

Regards
Stephen Carr
[GSConnect.txt](https://github.com/andyholmes/gnome-shell-extension-gsconnect/files/2147833/GSConnect.txt)

**Comment by andyholmes** [comment]
Your debug logs seem to indicate the the share plugin is not enabled on your ideapad. Are there any errors in the preferences dialog for that plugin?

**Comment by Truck5067** [comment]
Dear Andy

I have checked - there is no File Sharing (See attached) and found this

https://community.ubuntu.com/t/the-default-file-sharing-and-media-sharing-experience-in-18-04/3834

Regards
Stephen Carr
![screenshot from 2018-06-29 15-20-47](https://user-images.githubusercontent.com/29942020/42075504-5df549f2-7bb0-11e8-9f32-041b3faffc34.png)

**Comment by andyholmes** [comment]
The [Share plugin](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Share-Plugin) is a part of GSConnect/KDE Connect and won't appear in the system settings. It should be enabled in the extension Preferences dialog:

![screenshot from 2018-06-28 23-36-24](https://user-images.githubusercontent.com/1265208/42077135-bb2c7a7a-7b2c-11e8-8c75-b3ba4f7b12d6.png)

**Comment by Truck5067** [comment]
Dear Andy

I was looking in the wrong place(s). Now working.

Thanks
Stephen Carr

**Comment by andyholmes** [comment]
No problem. It might be less confusing if I could "inject" stuff into Gnome Settings, but the designers decided to disallow it because of how messy things got in Gnome2 Settings because of that :)
