### ISSUE TITLE
Python 3 crash on Gnome login using Fedora 28

### ISSUE THREAD

**Issue by daleosm** [andyholmes/gnome-shell-extension-gsconnect#150]
It was working fine on install, but once I installed the folks dependency this error occurs on login.
```
__init__.py:343:__init__:OSError: libgobject-2.0.so: cannot open shared object file: No such file or directory

Traceback (most recent call last):
  File "/home/daleosmond/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/folks-cache.py", line 13, in <module>
    pyc.cdll.LoadLibrary('libgobject-2.0.so')
  File "/usr/lib64/python3.6/ctypes/__init__.py", line 421, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib64/python3.6/ctypes/__init__.py", line 343, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libgobject-2.0.so: cannot open shared object file: No such file or directory

Local variables in innermost frame:
_FuncPtr: <class 'ctypes.CDLL.__init__.<locals>._FuncPtr'>
use_last_error: False
use_errno: False
handle: None
mode: 0
name: 'libgobject-2.0.so'
self: <CDLL 'libgobject-2.0.so', handle 0 at 0x7fc914b9fbe0>
flags: 1
```

I tried to locate the file and this was the output.
```
locate libgobject-2.0.so
/usr/lib/vmware-tools/lib32/libgobject-2.0.so.0
/usr/lib/vmware-tools/lib32/libgobject-2.0.so.0/libgobject-2.0.so.0
/usr/lib/vmware-tools/lib64/libgobject-2.0.so.0
/usr/lib/vmware-tools/lib64/libgobject-2.0.so.0/libgobject-2.0.so.0
/usr/lib64/libgobject-2.0.so.0
/usr/lib64/libgobject-2.0.so.0.5600.1
```

**Comment by andyholmes** [comment]
Thanks for the solid error log, it took me just a few seconds to figure out what's happening.

On Ubuntu `libgobject-2.0.so` and `libgobject-2.0.so.0` are (currently) links to `libgobject-2.0.so.0.5600.1`, while I guess Fedora only offers the latter symlink. I'll add a try-catch to check for both symlinks, although I think the linked shared object path will change with versions so I can't really use it directly.

Here's a ZIP built from master you can install using the [instructions in the Wiki](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Installation#installing-from-zip) or you can create a symlink from `libgobject-2.0.so` to `libgobject-2.0.so.0` on your system:

[gsconnect@andyholmes.github.io.zip](https://github.com/andyholmes/gnome-shell-extension-gsconnect/files/2152162/gsconnect.andyholmes.github.io.zip)
