### ISSUE TITLE
security issue: do not log clipboard content

### ISSUE THREAD

**Issue by matclab** [andyholmes/gnome-shell-extension-gsconnect#151]
Looking for something in my machine logs, I've stumble upon lines looking like:
```
JS LOG: [gsconnect@andyholmes.github.io]: Clipboard: send('private  content')
```

When using a passord manager like keepass or pass, the password are copied via the clipboard and end on the logs which is a serious security issue, as a log leak will also end in a password leak.

**Comment by matclab** [comment]
There seems to be a global debug gsetting to prevent debug message going to logs, but I didn't found it… In the meantime, I've commented out the clipboard debug lines, and removed the existing log files.

**Comment by andyholmes** [comment]
The Debug mode toggle is in the About panel and only intended to be using for debugging problems with the extension and developing. It should probably be turned off for both security and performance reasons since it logs messages quite frequently, including every packet received. If turned off, very few messages are logged to journalctl.

In general the Gtk clipboard is quite insecure and passwords should never be copy pasted, since any applications can access it at any time without warning.

**Comment by matclab** [comment]
Thanks for the information.
However, having an application snooping clipboard (keepass clear the
clipboard after 10 secs) and having password staying in the logs for months
is not totally on the same level to me.

I let you close this issue if you deem it should be (I primarily wanted to
attract attention to this problem, but I'm certainly not the one able to
say what should be done).
Thanks again for your useful piece of software.

**Comment by andyholmes** [comment]
I guess what should be clear is that GSConnect doesn't log anything during regular usage. It will only print to the log if _Debug Mode_ is enabled and that should only be enabled for development or fixing bugs. It's not a feature intended for regular users so it's [disabled by default](https://github.com/andyholmes/gnome-shell-extension-gsconnect/blob/master/data/org.gnome.Shell.Extensions.GSConnect.gschema.xml#L4-L8) and must be enabled manually by the user.

As an example, when developing the clipboard plugin it's necessary to print debug messages to confirm that the correct content (length, special characters, etc) is being exchanged between devices. If a plugin is not working correctly _Debug Mode_ can be turned on by a user temporarily to gather logs for a bug report, like was done for #20.

Without debug logs it would be impossible to diagnose these problems, but other than these two situations logging should just be left turned off in which case the `debug()` function does nothing.

**Comment by matclab** [comment]
Of course, you're right and the problem lies between the keyboard and the chair. The default are sane and I just totally forgot that I've enabled debugging when troubleshooting my initial setup.
