### ISSUE TITLE
Can't pair device v11 - Ubuntu 18.04 (Gio.TlsError: Decrypt error)

### ISSUE THREAD

**Issue by Zap123** [andyholmes/gnome-shell-extension-gsconnect#153]
I'm having problem pairing my device with the v11 extension and kdeconnect 1.8.4

```
JS LOG: [gsconnect@andyholmes.github.io]: Warning: failed to initialize GSound: Error: Requiring GSound, version none: Typelib file for namespace 'GSound' (any version) not found
JS LOG: UdpListener: using port 1716
JS LOG: TcpListener: using port 1716
JS LOG: [gsconnect@andyholmes.github.io]: UdpListener.send()
JS LOG: 0 devices loaded from cache
[...]
JS LOG: [gsconnect@andyholmes.github.io]: UdpListener.send()
JS LOG: [gsconnect@andyholmes.github.io]: UdpListener.receive()
JS LOG: [gsconnect@andyholmes.github.io]: Daemon._addDevice(GSConnect)
JS LOG: [gsconnect@andyholmes.github.io]: UdpListener.receive()
JS LOG: [gsconnect@andyholmes.github.io]: Daemon._addDevice(Sony)
JS LOG: Daemon: Adding device
JS LOG: [gsconnect@andyholmes.github.io]: Sony (d537e1436ce6debb)
JS LOG: Connecting to 'd537e1436ce6debb'
JS LOG: [gsconnect@andyholmes.github.io]: Sony (d537e1436ce6debb)
JS LOG: [gsconnect@andyholmes.github.io]: Sony (d537e1436ce6debb) already active
JS LOG: Error connecting: Gio.TlsError: Peer sent fatal TLS alert: Decrypt error
JS LOG: Disconnected from 'Sony'
JS LOG: [gsconnect@andyholmes.github.io]: Daemon._removeDevice(/org/gnome/Shell/Extensions/GSConnect/Device/d537e1436ce6debb)
JS LOG: Daemon: Removing device
```
I have tried downloading the extension from here, from git and from gnome-extension and kdeconnect both from f-droid and playstore.

I have tried resetting with dconf reset -f /org/gnome/shell/extensions/gsconnect and removing the folder .config/gsconnect and regenerating the certificates with kill $(ps aux | grep '[s]ervice/daemon.js' | awk '{print $2}')

Nothing seems to work for me unfortunately.

**Comment by andyholmes** [comment]
Does the Android app think it is paired with your device? What distribution are you using and what is your version of openssl?

**Comment by Zap123** [comment]
No, I have tried uninstalling the app multiple time, there's no sign in the app that the phone is paired. In the extension I can briefly see the phone for half a second and then is removed. 

Ubuntu 18.04
`openssl: Installed: 1.1.0g-2ubuntu4.1` 

Logcat
```
07-06 10:52:08.033   640   678 I KDE/LanLinkProvider: Identity package received from a TCP connection from GSConnect
07-06 10:52:08.034   640   678 I KDE/LanLinkProvider: Starting SSL handshake with GSConnect trusted:false
07-06 10:52:08.154   640  5617 E KDE/LanLinkProvider: Handshake failed with GSConnect
07-06 10:52:08.180   640  5617 W System.err: javax.net.ssl.SSLHandshakeException: Handshake failed
07-06 10:52:08.181   640  5617 W System.err: 	at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:429)
07-06 10:52:08.181   640  5617 W System.err: 	at org.kde.kdeconnect.Backends.LanBackend.LanLinkProvider.lambda$identityPacketReceived$3$LanLinkProvider(LanLinkProvider.java:257)
07-06 10:52:08.181   640  5617 W System.err: 	at org.kde.kdeconnect.Backends.LanBackend.LanLinkProvider$$Lambda$2.run(Unknown Source)
07-06 10:52:08.181   640  5617 W System.err: 	at java.lang.Thread.run(Thread.java:761)
07-06 10:52:08.182   640  5617 W System.err: Caused by: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x51827640: Failure in SSL library, usually a protocol error
07-06 10:52:08.182   640  5617 W System.err: error:04000068:RSA routines:OPENSSL_internal:BAD_SIGNATURE (external/boringssl/src/crypto/rsa/rsa.c:514 0x554e586a:0x00000000)
07-06 10:52:08.183   640  5617 W System.err: error:10000072:SSL routines:OPENSSL_internal:BAD_SIGNATURE (external/boringssl/src/ssl/s3_clnt.c:1275 0x554e586a:0x00000000)
07-06 10:52:08.183   640  5617 W System.err: 	at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
07-06 10:52:08.183   640  5617 W System.err: 	at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:357)
07-06 10:52:08.183   640  5617 W System.err: 	... 3 more
07-06 10:52:08.251  1631  2100 I AsyncOpDispatcher: 122-GetRCNEnabledStatusOperation
07-06 10:52:08.365   587   747 I ActivityManager: Setting hasTopUi=false for pid=807
07-06 10:52:09.018  1631  9175 W DatabaseProcessor: Exiting Adaptive Discovery. Current NetworkInfo is NULL.
```
Maybe it's the phone, it has Android 7.1.2 but it's a custom rom so it's possible that they shipped a not updated version of openssl. I haven't tried in a while with kdeconnect and I'm not sure how to use it with gnome to see if it works or is something that happens only with the extension, I'll try with another device to exclude that.

**Comment by andyholmes** [comment]
It might be the phone, although I don't want to just shift the blame. At least in GJS there aren't good utilities for creating certificates so it's just done using the `openssl` cli, but IIRC that's how KDE Connect does it as well. If you run the following command does it choke at all? Does the output seem pretty much the same?

```sh
$ openssl x509 -in ~/.config/gsconnect/certificate.pem -noout -subject
subject=O = andyholmes.github.io, OU = GSConnect, CN = 51d67273-737a-426f-aef4-3ba082aab1f7
```
If so then there's probably nothing wrong with the generated certificate, although there could be some other problem on the GSConnect side. I think SSL/TLS errors are purposely vague so that information isn't logged that could help an attacker, but it also makes it pretty hard to debug.

From what I understand boringssl is just Google's fork of openssl, but their might be something wrong with your ROM that's only causing problems in this one situation (corrupted ZIP, custom compiler chain, etc). I'm also using a 7.1.2 AOSP based ROM so it's probably not a "Android" problem per se.

**Comment by andyholmes** [comment]
It should be fine...I don't think those are required fields, I've just added them in wip-rewrite. If openssl didn't choke reading the certificate it should be fine. If you want you can `cd` to `~/.config/gsconnect/`, `rm` `private.pem` and `certificate.pem`, run this command, and restart the daemon:

    openssl req -new -x509 -sha256 -newkey rsa:2048 -nodes -keyout private.pem -days 3650 -out certificate.pem -subj /O=andyholmes.github.io/OU=GSConnect/CN=71d6fe7a-07e5-4465-a484-21dfe4c7850c

If openssl can read the certificate fine, then my best guess it's either a problem with the app or Android's ssl library.

**Comment by Zap123** [comment]
Thanks I have tried it and it's the same so it's probably the ROM, maybe the kdeconnect app has a problem with the version of Openssl of this ROM or who knows, at this point I don't think it's something it can be fixed with-in your extension therefore you can close this issue. Thank you again.

**Comment by andyholmes** [comment]
Marking this upstream and closing for now. Re-open if it occurs with other ROMs.

**Comment by ShrirajHegde** [comment]
> Does the Android app think it is paired with your device? What distribution are you using and what is your version of openssl? Can you check logcat on the Android device to see if there's more information?

It was this, clearing data/unpairing device fixes the problem
