### ISSUE TITLE
KDE won't recognize PC, PC won't keep connected to device

### ISSUE THREAD

**Issue by heyhey47** [andyholmes/gnome-shell-extension-gsconnect#157]
First of all hello and thank you so much for putting this extension out here although I can't use it at the moment -
my problem is as follows- I'm on a fresh install of Ubuntu 18.04 LTS, I've installed KDE Connect on my Nexus 6P and I've installed gsconnect through firefox extension and via the GNOME tweak tool.
Both my PC and phone do not see each other, however after manually adding my PC's address onto the KDE app the phone appears in the "Mobile Devices" tab - however it appears as disconnected and will not allow me to actually do anything with it, neither there neither through the settings themselves -
This is the log from the debugger:
```
JS LOG: [gsconnect@andyholmes.github.io]: UdpListener.receive()
JS LOG: [gsconnect@andyholmes.github.io]: Daemon._addDevice(google)
JS LOG: Daemon: Updating device
JS LOG: [gsconnect@andyholmes.github.io]: google (d3d631581466787f)
JS LOG: Received from 'google'
JS LOG: [gsconnect@andyholmes.github.io]: google (d3d631581466787f)
JS LOG: [gsconnect@andyholmes.github.io]: google (d3d631581466787f) already active
JS LOG: [gsconnect@andyholmes.github.io]: UdpListener.receive()
JS LOG: [gsconnect@andyholmes.github.io]: Daemon._addDevice(google)
JS LOG: Daemon: Updating device
JS LOG: [gsconnect@andyholmes.github.io]: google (d3d631581466787f)
JS LOG: Received from 'google'
JS LOG: [gsconnect@andyholmes.github.io]: google (d3d631581466787f)
JS LOG: [gsconnect@andyholmes.github.io]: google (d3d631581466787f) already active
```

I should mention that I am an Ubuntu newbie so it's possible I've messed something very basic up without knowing it

**Comment by andyholmes** [comment]
JS LOG: [gsconnect@andyholmes.github.io]: google (d3d631581466787f) already active

This seems to indicate a connection has been opened to your device; is it disconnected or just unpaired? Are you sure ports 1716-1764 are open for connections on your network? What happens if you hit the pair button on either device?

**Comment by heyhey47** [comment]
>  is it disconnected or just unpaired? 
In the dropdown top bar menu it lists the device but says "Device is disconnected", clicking on reconnect doesn't do anything, the phone is also listed in the Mobile Settings menu where I can't press the pair button
![pair](https://user-images.githubusercontent.com/41194137/42723510-9a4e954e-8767-11e8-85a0-4cf6126d45c7.jpg)

>  Are you sure ports 1716-1764 are open for connections on your network?
I've opened them on UFW with the provided commands so they should def be open - there are other (Windows) devices on this network, could they be the problem?

> What happens if you hit the pair button on either device?
As I've mentioned, on the PC the option isn't available and on the phone end it doesn't list any devices so I've never gotten to try.

**Comment by andyholmes** [comment]
Unfortunately there's not enough information in the log you posted for me to figure out what's going wrong. Can you open the debug log and restart the daemon with this command:

```sh
$ kill $(ps aux | grep '[d]aemon.js' | awk '{print $2}')
```

And the post the logs from the beginning of the service starting?

**Comment by heyhey47** [comment]
Sure
```
JS LOG: [gsconnect@andyholmes.github.io]: Warning: failed to initialize GSound: Error: Requiring GSound, version none: Typelib file for namespace 'GSound' (any version) not found
JS LOG: UdpListener: using port 1716
JS LOG: TcpListener: using port 1716
JS LOG: [gsconnect@andyholmes.github.io]: UdpListener.send()
JS LOG: [gsconnect@andyholmes.github.io]: google (d3d631581466787f)
JS LOG: Connecting to 'd3d631581466787f'
JS LOG: 1 devices loaded from cache
JS LOG: [gsconnect@andyholmes.github.io]: UdpListener.send()
JS LOG: [gsconnect@andyholmes.github.io]: UdpListener.receive()
JS LOG: [gsconnect@andyholmes.github.io]: Daemon._addDevice(GSConnect)
JS LOG: [gsconnect@andyholmes.github.io]: UdpListener.receive()
JS LOG: [gsconnect@andyholmes.github.io]: Daemon._addDevice(GSConnect)
JS LOG: [gsconnect@andyholmes.github.io]: google (d3d631581466787f)
JS LOG: [gsconnect@andyholmes.github.io]: google (d3d631581466787f) already active
JS LOG: [gsconnect@andyholmes.github.io]: UdpListener.receive()
JS LOG: [gsconnect@andyholmes.github.io]: Daemon._addDevice(google)
JS LOG: Daemon: Updating device
JS LOG: [gsconnect@andyholmes.github.io]: google (d3d631581466787f)
JS LOG: Received from 'google'
JS LOG: [gsconnect@andyholmes.github.io]: google (d3d631581466787f)
JS LOG: [gsconnect@andyholmes.github.io]: google (d3d631581466787f) already active
JS LOG: [gsconnect@andyholmes.github.io]: UdpListener.receive()
JS LOG: [gsconnect@andyholmes.github.io]: Daemon._addDevice(google)
JS LOG: Daemon: Updating device
JS LOG: [gsconnect@andyholmes.github.io]: google (d3d631581466787f)
JS LOG: Received from 'google'
JS LOG: [gsconnect@andyholmes.github.io]: google (d3d631581466787f)
JS LOG: [gsconnect@andyholmes.github.io]: google (d3d631581466787f) already active
JS LOG: Error connecting: Gio.IOErrorEnum: Could not connect to 192.168.1.2: Connection timed out
JS LOG: Disconnected from 'google'
JS LOG: [gsconnect@andyholmes.github.io]: Daemon._removeDevice(/org/gnome/Shell/Extensions/GSConnect/Device/d3d631581466787f)
JS LOG: Daemon: Removing device
```
Also thank you very much for addressing my issue, I've had more trouble getting support for software I've actually paid for - I appreciate your attention.

**Comment by andyholmes** [comment]
No problem, even if it's "user error" sometimes figuring out how that happens helps me to program the possibility of those situations out.

    JS LOG: [gsconnect@andyholmes.github.io]: UdpListener.receive()
    JS LOG: [gsconnect@andyholmes.github.io]: Daemon._addDevice(google)
    JS LOG: Daemon: Updating device
    [...]
    JS LOG: Error connecting: Gio.IOErrorEnum: Could not connect to 192.168.1.2: Connection timed out

So the first part here indicates that the device `google` (hostname `d3d631581466787f`), is broadcasting its identity properly and GSConnect is receiving it properly. The second part is when GSConnect responds to the broadcast by opening and outgoing TCP connection. For some reason that connection is timing out (obviously), but it's not clear why.

Two things to try first, check that the device `google`'s IP is actually `192.168.1.2` (in the phone preferrably) and double check by pinging it:

```sh
$ ping 192.168.1.2
```

If that's all good, I would next check your router and make sure it's not blocking any ports, or applying any special rules to WiFi devices. Or if you have some double-router or modem->router situation on your network see that proper traffic is allowed both ways for TCP and UDP.

As a shot in the dark, you might want to check your phone has no weird firewall software. There have been some known problems with the Android app and Android Oreo; are you using that?

**Comment by andyholmes** [comment]
Is this issue still valid or did the problem resolve itself?

**Comment by andyholmes** [comment]
I believe this might be a network error, but I'm going to close this because I think it would be fixed or detected in `master`.
