### ISSUE TITLE
No notifications from messaging apps

### ISSUE THREAD

**Issue by uspoma** [andyholmes/gnome-shell-extension-gsconnect#159]
Hello!

Thanks for GSConnect - great app!

I've read the FAQ but couldn't find an answer to the problem I have.

When my phone receives messages via different messengers like threema, telegram etc. I do not see notifications on the desktop about that. Even though I activated notifications in the settings. Is this a limitation of gsconnect?

All the other features like remote control or file transfer work. Only these notifications do not show up.

Using Ubuntu 18.04 and Gnome.

**Comment by andyholmes** [comment]
Hi, thanks for the kind words. There should be no problem with showing notifications from messaging applications. The only notifications that have any difference are SMS notifications and GSConnect puts some effort into hiding the fact that there is a difference. I don't use many messaging apps, but I do use Telegram and those seem to work fine for me.

In the _About_ page of the Preferences dialog is a switch titled _Debug Mode_ which should open a terminal when enabled and print verbose debug information. If you enable that you should be able to see if there are any errors when receiving notifications, or if the Android app is sending them at all.

**Comment by uspoma** [comment]
Hej! Thanks for replying swiftly.

I activated the debug mode and see for example when I send a ping with kdeconnector I see something like this: Device received: {"id":xxx,"type":"kdeconnect.ping","body":{}}. So this works fine. Also my phone's calender notifications do show up. 

But like I said no messaging notifications. It seems that kdeconnect does not send them. Would you have an idea how to look into that?

Thanks!

**Comment by uspoma** [comment]
Found out that with android 4.4.2 it works. But with android 7.1.2 it does not seem to work. Must be a problem with the kdeconnect on android. I will try to find out.

Closing this ticket for now.
