### ISSUE TITLE
Support scroll packets coming from MousePadPlugin

### ISSUE THREAD

**Issue by Baldrs** [andyholmes/gnome-shell-extension-gsconnect#16]
So in android app there is scroll support:

```java
    public void sendScroll(float dx, float dy) {
        NetworkPackage np = new NetworkPackage(PACKAGE_TYPE_MOUSEPAD_REQUEST);
        np.set("scroll", true);
        np.set("dx", dx);
        np.set("dy", dy);
        device.sendPackage(np);
    }
```

However your implementation only handles mouse delta changes, not scroll packets

**Comment by alozytskyi** [comment]
Oh, so as `generate_mouse_event` does not support it, it has to be done different way, somehow.

**Comment by andyholmes** [comment]
Hmm, I though these might be implemented with `Atspi.generate_keyboard_event()` and `Gdk.KEY_ScrollDown`/`Gdk.KEY_ScrollUp` or `Gdk.KEY_Pointer_Button4`/`Gdk.KEY_Pointer_Button5` but that doesn't appear to work.

Most other implementations I see use the XTest library, which is not introspected (obviously) so this might be a problem.

**Comment by andyholmes** [comment]
After some more investigating, this seems to only be possible via `xdotool`, which will also apply to `singlehold` and `singlerelease` events as well.

Here's a testable Zip using xdotool to implement scrolling and dragging:

[gsconnect@andyholmes.github.io.zip](https://github.com/andyholmes/gnome-shell-extension-gsconnect/files/1561596/gsconnect.andyholmes.github.io.zip)

**Comment by andyholmes** [comment]
Marking closed since it wfm with xdotool
