### ISSUE TITLE
Remote Input broken on HiDPI screens

### ISSUE THREAD

**Issue by MAFiA303** [andyholmes/gnome-shell-extension-gsconnect#160]
I have KDE installed on my laptop and phone, they are paired and options are enabled.
When using remote control, i can move the mouse, but when clicking or scrolling it doesn't work as expected.
clicking behavior: pointer jumps to top left then clicks (checked on xev as well)
scrolling: pointer moves to the right top corner

same behavior with different phones.

laptop used: chromebook pixel 2013
OS: Ubuntu 18.04

phone1: Samsung Note 8
phone2: OnePlus 3

**Comment by andyholmes** [comment]
Could you enable *Debug Mode* in the *About* page of the preferences and post the output when you double-click or scroll?

**Comment by MAFiA303** [comment]
here is the output of the single click

``JS LOG: [gsconnect@andyholmes.github.io]: LanChannel.receive(411a120b5c9d922d)
JS LOG: [gsconnect@andyholmes.github.io]: Device received: {"id":1532865346698,"type":"kdeconnect.mousepad.request","body":{"dx":0.09375,"dy":-0.7347412109375}}
JS LOG: Received from 'Samsung SM-N950U'
JS LOG: [gsconnect@andyholmes.github.io]: Mousepad: handlePacket()
JS LOG: [gsconnect@andyholmes.github.io]: Mousepad: movePointer(0.09375, -0.7347412109375)
JS LOG: [gsconnect@andyholmes.github.io]: LanChannel.receive(411a120b5c9d922d)
JS LOG: [gsconnect@andyholmes.github.io]: Device received: {"id":1532865346713,"type":"kdeconnect.mousepad.request","body":{"dx":0.52960205078125,"dy":-1.088623046875}}
JS LOG: Received from 'Samsung SM-N950U'
JS LOG: [gsconnect@andyholmes.github.io]: Mousepad: handlePacket()
JS LOG: [gsconnect@andyholmes.github.io]: Mousepad: movePointer(0.52960205078125, -1.088623046875)
JS LOG: [gsconnect@andyholmes.github.io]: LanChannel.receive(411a120b5c9d922d)
JS LOG: [gsconnect@andyholmes.github.io]: Device received: {"id":1532865346730,"type":"kdeconnect.mousepad.request","body":{"dx":-0.09600830078125,"dy":-0.6156005859375}}
JS LOG: Received from 'Samsung SM-N950U'
JS LOG: [gsconnect@andyholmes.github.io]: Mousepad: handlePacket()
JS LOG: [gsconnect@andyholmes.github.io]: Mousepad: movePointer(-0.09600830078125, -0.6156005859375)
JS LOG: [gsconnect@andyholmes.github.io]: LanChannel.receive(411a120b5c9d922d)
JS LOG: [gsconnect@andyholmes.github.io]: Device received: {"id":1532865346746,"type":"kdeconnect.mousepad.request","body":{"dx":-0.52734375,"dy":0.81298828125}}
JS LOG: Received from 'Samsung SM-N950U'
JS LOG: [gsconnect@andyholmes.github.io]: Mousepad: handlePacket()
JS LOG: [gsconnect@andyholmes.github.io]: Mousepad: movePointer(-0.52734375, 0.81298828125)
JS LOG: [gsconnect@andyholmes.github.io]: LanChannel.receive(411a120b5c9d922d)
JS LOG: [gsconnect@andyholmes.github.io]: Device received: {"id":1532865346993,"type":"kdeconnect.mousepad.request","body":{"singleclick":true}}
JS LOG: Received from 'Samsung SM-N950U'
JS LOG: [gsconnect@andyholmes.github.io]: Mousepad: handlePacket()
JS LOG: [gsconnect@andyholmes.github.io]: Mousepad: clickPointer(1)

**Comment by MAFiA303** [comment]
to add one thing, before I used my phone input device and as soon as the debug window opened, this was on the debug
g_object_unref: assertion 'G_IS_OBJECT (object)' failed

- it repeated 10 times

**Comment by MAFiA303** [comment]
same behavior with touchpad disabled 
same behavior with touchscreen disabled

**Comment by andyholmes** [comment]
Can you try disabling and re-enabling the mousepad plugin after disabling the touchscreen?

**Comment by MAFiA303** [comment]
below are my steps:
xinput list
⎡ Virtual core pointer               			     	id=2		[master pointer  (3)]
⎜   ↳ Virtual core XTEST pointer              	id=4		[slave  pointer  (2)]
⎜   ↳ Atmel maXTouch Touchpad                 	id=11	[slave  pointer  (2)]
⎜   ↳ Atmel maXTouch Touchscreen              	id=12	[slave  pointer  (2)]


I disabled 11, 12 at the same time and separately and nothing have changed.
I cannot disable 2 or 4 (even with sudo)
command used:
xinput disable 11
xinput disable 12

**Comment by andyholmes** [comment]
And you restarted the mousepad plugin in GSConnect after disabling these?

**Comment by MAFiA303** [comment]
from the look of it, every click halves x and y, measured from the top right corner as (0,0)

**Comment by andyholmes** [comment]
Well, the click events are generated at the current coordinates of the pointer. [Source](https://github.com/andyholmes/gnome-shell-extension-gsconnect/blob/master/src/service/plugins/mousepad.js#L132-L133):
```js
clickPointer: function (button) {
    debug("Mousepad: clickPointer(" + button + ")");

    let event = "b%dc".format(button);

    try {
        let [screen, x, y] = this._pointer.get_position();
        Atspi.generate_mouse_event(x, y, event);
    } catch (e) {
        log("Mousepad: Error simulating mouse click: " + e);
    }
},
```
I'm not sure quite what the problem could be, since there are no errors logged. Presumably the call to Atspi is working correctly, but being interpreted incorrectly. I have multiple pointer devices myself, but no touchscreen so I only assume that's the problem.

**Comment by andyholmes** [comment]
It's not uncommon for there to be some small movements during a click, but keep in mind that the movements are relative, pixel movements. So a movement of `{ "dx": -0.52734375, "dy": 0.81298828125 }` shouldn't really move the cursor at all.

I have a feeling this may be an Atspi or Gnome-related issue, but you could open a bug on [KDE Connect's bug tracker](https://bugs.kde.org/buglist.cgi?quicksearch=kdeconnect&list_id=1505828). They may want you to test it on KDE Connect as well though, before they accept it as a bug with the Android app.

**Comment by mxi-hug** [comment]
The problem seems to be the scaling factor on HiDPI screens. I'm running Ubuntu 18.04 with gnome 3.28 and i'm having the same issue. Mafia's hint to the click halving x and y was helpful. When I reset the scaling factor in gnome options to 100%, every click was at the right place. Returning to 200% made it useless again...

**Comment by andyholmes** [comment]
This probably a bug with Atspi and HiDPI then. I'm going to mark this as upstream until there's evidence GSConnect is doing something wrong.

If someone with a HiDPI screen can confirm this is a bug in Atspi they can [file a bug here](https://gitlab.gnome.org/GNOME/at-spi2-core/issues) and link to it in this issue.

**Comment by mxi-hug** [comment]
As I'm not really familiar with the underlying technologies: could you give me a hint how to check whether it's a bug in Atspi?

**Comment by flipflop97** [comment]
My guess is that this line (gdk) respects the Gnome settings and returns a scaling-independant position;
```js
let [screen, x, y] = this._pointer.get_position();
```

While this line (at-spi) does not and intead used absolute pixel positions.
```js
Atspi.generate_mouse_event(x, y, event);
```

This could probably be fixed by multiplying x and y with Gnomes screen density beefore calling at-spi or if possible replace the at-spi calls with gdk ones like:
```js
this._pointer.warp(screen, x, y);
```
