### ISSUE TITLE
On Fedora 28 with Gnome 3.28.3 gives problems

### ISSUE THREAD

**Issue by xzj8b3** [andyholmes/gnome-shell-extension-gsconnect#161]
Daemon

JS LOG: Error connecting: Gio.TlsError: Errore nell'eseguire l'handshake TLS: È stato ricevuto un parametro non lecito.
JS LOG: Disconnected from 'xzj8b3@x555lp'
JS LOG: Daemon: Removing device
JS LOG: UdpListener: using port 1717
JS LOG: TcpListener: using port 1717
JS LOG: 0 devices loaded from cache
JS ERROR: Gio.IOErrorEnum: Errore nell'inviare il messaggio: La rete non è raggiungibile
UdpListener<.send@/home/xzj8b3/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/protocol.js:207:9
wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
Daemon<.broadcast@/home/xzj8b3/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:374:9
wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
Daemon<.vfunc_startup/<@/home/xzj8b3/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:831:17
@/home/xzj8b3/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:892:2

Extension

Error calling activate: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: Interfaccia «org.gnome.Shell.Extensions.GSConnect.Device» inesistente sull'oggetto nel percorso /org/gnome/Shell/Extensions/GSConnect/Device/_adc51a7b_308d_47b8_a30f_716d289a658b_

**Comment by andyholmes** [comment]
JS LOG: UdpListener: using port 1717
    JS LOG: TcpListener: using port 1717

These lines in your log indicate that another KDE Connect process, either `kdeconnectd` or `mconnectd` are running on your system. Do you or did you have either KDE Connect or MConnect installed? If so you should ensure that those are uninstalled and the process killed:

```sh
$ killall -9 kdeconnectd
$ killall -9 mconnectd
```

Then restart GSConnect by killing the process with the command:

```sh
$ kill $(ps aux | grep '[d]aemon.js' | awk '{print $2}')
```

You may need to enable and disable the extension to restart the GSConnect

**Comment by xzj8b3** [comment]
@andyholmes I installed KDECONNECTD to configure the extension!!!

**Comment by xzj8b3** [comment]
Equal @andyholmes 

JS LOG: TcpListener: using port 1717
JS ERROR: Gio.IOErrorEnum: Errore nell'inviare il messaggio: La rete non è raggiungibile
UdpListener<.send@/home/xzj8b3/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/protocol.js:207:9
wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
Daemon<.broadcast@/home/xzj8b3/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:374:9
wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
set name@/home/xzj8b3/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:251:9
Daemon<.vfunc_startup@/home/xzj8b3/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:809:9
wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
Daemon<._init@/home/xzj8b3/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:213:9
wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
@/home/xzj8b3/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:892:2

JS LOG: 0 devices loaded from cache
JS ERROR: Gio.IOErrorEnum: Errore nell'inviare il messaggio: La rete non è raggiungibile
UdpListener<.send@/home/xzj8b3/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/protocol.js:207:9
wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
Daemon<.broadcast@/home/xzj8b3/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:374:9
wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
Daemon<.vfunc_startup@/home/xzj8b3/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:839:9
wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
Daemon<._init@/home/xzj8b3/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:213:9
wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
@/home/xzj8b3/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:892:2

JS LOG: UdpListener: using port 1716
JS LOG: TcpListener: using port 1716
JS LOG: 0 devices loaded from cache
JS LOG: UdpListener: using port 1717
JS LOG: TcpListener: using port 1717
JS LOG: 0 devices loaded from cache

**Comment by andyholmes** [comment]
JS LOG: UdpListener: using port 1717
    JS LOG: TcpListener: using port 1717

If these messages are showing it means `kdeconnectd` is still running. It probably has to be killed even after it's uninstalled, then GSConnect needs to be restarted:

```sh
$ killall -9 kdeconnectd
$ kill $(ps aux | grep '[d]aemon.js' | awk '{print $2}')
```

This message means there is a problem with your local network:

    JS ERROR: Gio.IOErrorEnum: Errore nell'inviare il messaggio: La rete non è raggiungibile

Not sure if this is to do with GSConnect. If you are using a firewall you should open ports 1716-1764 for TCP and UDP.

**Comment by xzj8b3** [comment]
There is no firewall enabled apart from iptable which I still have not configured..

But make yourself better understand why translators are not always good

In Fedora 27 I followed your guide and worked perfectly

I have now installed equally as KDECONNECTD I have to remove it??? Now works without extension???

**Comment by andyholmes** [comment]
GSConnect is a replacement for KDE Connect. It does not use KDE Connect and will probably cause problems if both are installed.

    JS ERROR: Gio.IOErrorEnum: Errore nell'inviare il messaggio: La rete non è raggiungibile

This is a [low-level error code in Unix](https://github.com/torvalds/linux/blob/master/include/uapi/asm-generic/errno.h#L84), it's just comes with a message that's translated for most languages.

Since your network connection is obviously working, and GSConnect was bound to port 1717, it means there is something between GSConnect and your network preventing the message from being sent. Usually that means a firewall, but there could be some other reason as well.

**Comment by andyholmes** [comment]
I'm going to close this now, as I believe it was a case of the proper port not being available rather than a bug in GSConnect.
