### ISSUE TITLE
gsconnect is not discovered in the android phone in my centos7 desktop

### ISSUE THREAD

**Issue by munish259272** [andyholmes/gnome-shell-extension-gsconnect#164]
I ran gjs ~/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js to check the error and here is what i get 

[msingh@centos log]$ gjs ~/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js
Gjs-Message: JS LOG: Error generating TLS Certificate: GLib.uuid_string_random is not a function
Gjs-Message: JS WARNING: [/home/msingh/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js 218]: reference to undefined property "_certificate"

(org.gnome.Shell.Extensions.GSConnect:26836): Gjs-WARNING **: JS ERROR: TypeError: this.certificate is undefined
get fingerprint@/home/msingh/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:240:9
Daemon<.vfunc_startup@/home/msingh/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:772:1
wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
Daemon<._init@/home/msingh/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:213:9
wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
@/home/msingh/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:892:2

(org.gnome.Shell.Extensions.GSConnect:26836): GLib-GIO-CRITICAL **: g_application_run: assertion '!application->priv->must_quit_now' failed
[msingh@centos log]$

**Comment by andyholmes** [comment]
> Gjs-Message: JS LOG: Error generating TLS Certificate: GLib.uuid_string_random is not a function

This is what's causing the problem, since that function is not available the certificate is not being generated. Which version of GJS and Gnome Shell are you using?

**Comment by munish259272** [comment]
[msingh@centos opt]$ gnome-shell --version
GNOME Shell 3.25.4
[msingh@centos opt]$ gjs --version
gjs 1.50.4
[msingh@centos opt]$

**Comment by andyholmes** [comment]
I believe if you checked your GLib version it would be less than 2.52 when that function was added. I've pushed a polyfilled version of the function that should work, will be released with v12, or you can [build from Git](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Installation#building-from-git) if you don't want to wait.
