### ISSUE TITLE
GSConnect cannot connect phone with KDE Connect

### ISSUE THREAD

**Issue by pepevi83** [andyholmes/gnome-shell-extension-gsconnect#165]
PC: Ubuntu 18.04 - GSConnect v11
Phone: Motorola G5 Plus - Android 7.0 - KDE Connect 1.8.4

I cannot see at ll my PC in KDE Connect, but when I refresh the app I can see for a couple of seconds my phone in GSConnect, then it disappears.

These are the logs:

> JS LOG: [gsconnect@andyholmes.github.io]: UdpListener.receive()
JS LOG: [gsconnect@andyholmes.github.io]: Daemon._addDevice(motorola)
JS LOG: Daemon: Adding device
JS LOG: [gsconnect@andyholmes.github.io]: motorola (7a7412e2b3bfe884)
JS LOG: Connecting to '7a7412e2b3bfe884'
JS LOG: [gsconnect@andyholmes.github.io]: motorola (7a7412e2b3bfe884)
JS LOG: [gsconnect@andyholmes.github.io]: motorola (7a7412e2b3bfe884) already active
JS LOG: Error connecting: Gio.IOErrorEnum: Could not connect to 192.168.1.78: No route to host
JS LOG: Disconnected from 'motorola'
JS LOG: [gsconnect@andyholmes.github.io]: Daemon._removeDevice(/org/gnome/Shell/Extensions/GSConnect/Device/7a7412e2b3bfe884)
JS LOG: Daemon: Removing device

I cannot ping the phone's IP:

> ping 192.168.1.78
PING 192.168.1.78 (192.168.1.78) 56(84) bytes of data.
From 192.168.1.70 icmp_seq=1 Destination Host Unreachable
From 192.168.1.70 icmp_seq=2 Destination Host Unreachable
From 192.168.1.70 icmp_seq=3 Destination Host Unreachable

and I don't have any firewall installed in my PC

> sudo ufw status verbose
Status: inactive

**Comment by andyholmes** [comment]
Sorry, I lost track of this issue.

Seems like you have larger networking issue here. Either KDE Connect on your phone is reporting the wrong IP somehow, or I don't know. I've seen problems with connections being refused, but a host unreachable error usually means the device is not connected to WiFi or the IP is wrong.

If possible I would check your router to see that the IP the Android app is reporting is correct. If it is you should [file a bug upstream](https://bugs.kde.org/buglist.cgi?quicksearch=kdeconnect&list_id=1505828) with KDE Connect. If not, maybe if your PC is wired your router has wireless and wired on different networks?

**Comment by pepevi83** [comment]
I checked the router and I can see my PC and my phone, they are in the same network and both devices are connected via WiFi. 

The only thing I can see is that the PC is connected to the 2.4GHz band and the phone is connected to the 5GHz one, could this be causing the issue?

Thanks for your time,

Jose

**Comment by andyholmes** [comment]
It's possible that your router has those two frequencies separated somehow?

**Comment by andyholmes** [comment]
Is this issue still valid?

**Comment by andyholmes** [comment]
The next version will have quite a few networking changes and detect a lot more problems automatically. When you get a chance it might fix your problem.

**Comment by Anilchaudhary902** [comment]
KDEConnect + GSConnect Not connecting.
I use UFW as a killswitch with ports open for KDEConnect using following commands -


sudo ufw allow 1714:1764/udp

sudo ufw allow 1714:1764/tcp

sudo ufw reload


No devices show up in KDEConnect or GSConnect. 

Any ideas?
 Check this:-------
This is the GSConnect log -


GSConnect Version: 21

GSConnect Install: user

GJS: 15600

XDG_SESSION_TYPE: x11

GDMSESSION: gnome


if issue still going on Whatsapp me

+919501406967

**Comment by AnshuKopite** [comment]
I had a similar problem, turned out it was due my firewall blocking the request from my mobile device, jsut set the appropriate rules and voila.

**Comment by ferdnyc** [comment]
Even 4 months ago, GSConnect version v21 was _extremely_ out of date, and wouldn't have been supported. Back then we were probably weighing the decision of whether we should cut off support at v28, v32, v35... something like that.

(The current version is v41.)
