### ISSUE TITLE
Device does not connect automatically

### ISSUE THREAD

**Issue by krupenja** [andyholmes/gnome-shell-extension-gsconnect#166]
Steps to reproduce:
1. Pair the phone with gsconnect.
2. Turn WiFi of on the phone (or leave the WiFi area so that the device is no longer on the network).
3. Turn WiFi back on.

The device will not connect automatically with gsconnect, you have to manually reconnect by pressing the mobile phone icon in the menu.

Please let me know if you need further details.

PC OS: Manjaro Linux 17.1.11, Gnome 3.28
Phone: Xiaomi Mi A1, Android 8.1

**Comment by andyholmes** [comment]
**Short Answer**

You should add your desktop/laptop IP in the Android app:

![add-devices-by-ip](https://user-images.githubusercontent.com/1265208/44120648-e577e19c-9fd1-11e8-9964-d053d8deadff.png)

**Longer Answer**

The way devices are discovered or known to be online is to have devices send a general [broadcast message](https://en.wikipedia.org/wiki/Broadcast_address). This message contains it's name, IP and other information which your router relays to all other devices on that network. Each (KDE Connect/GSConnect) device that receives one of these messages will respond by opening a connection to the IP in the message.

The KDE Connect Android app should send a broadcast as soon as WiFi connects, but broadcasting doesn't work on a number of Android devices (including mine). When you add your device using the Android app (above), it will first send the general broadcast then send the same message to each IP in the list _directly_, avoiding any broadcasting problems.

**Comment by krupenja** [comment]
Thank you for your prompt reply. I have added my Linux machine by IP and now auto-connect works successfully.
