### ISSUE TITLE
Ubuntu 18.04 - Can't see my contacts in SMS window

### ISSUE THREAD

**Issue by Barben360** [andyholmes/gnome-shell-extension-gsconnect#168]
I'm using Ubuntu 18.04 LTS. I installed "folks" packages (folks-common, folks-tools) as told in the Wiki. My online accounts are bound to my Google account, "contacts" is ticked. However, I can't initiate a SMS conversation in the SMS frame, I can only answer the ones which were acquired when receiving a SMS while my phone is connected to GSconnect. I checked, all my phone contacts are stored in Google Contacts. Any idea ? By the way, where can I find GSconnect logs ?

**Comment by andyholmes** [comment]
For Ubuntu the packages required are named `libfolks-dev` and `libfolks-eds25`, because the dev package pulls in a library file needed by the Python shim.

However, this is only for integrating GSConnect with desktop contacts, so for Google contacts to work you will have to add your account to Gnome Online Accounts. Once that's done you may have to disconnect/connect your phone or just disable/enable the Telephony plugin.

All GSConnect messages can be found in journalctl like any other application. If you turn on *Debug Mode* in the *About* page of the preferences, it should open a log window for you and print extra messages to the log.

**Comment by Barben360** [comment]
Thank you very much, I was actually missing libfolks-eds25 (read the wrong line in the wiki...).
And thank you for your great job with GSConnect, which is absolutely great (probably even the best gnome extension ever).

**Comment by jjlacrampe** [comment]
Hello,
I reopen this discussion because I have a similar problem and cann't solve it : my messages appear in the window, but no contacts, allthough I have verified that my google accounts are correctly managed by gnome online accounts.
Any suggestion?

**Comment by jjlacrampe** [comment]
Here is a log of the connection trial :
**+1: janv. 08 08:25:13 gjs[5414]: GtkDialog mapped without a transient parent. This is discouraged.
janv. 08 08:25:27 gjs[5414]: JS ERROR: TypeError: dynamic is null
                             _onSearchChanged@/home/jean-jacques/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/ui/contacts.js:369:1
                             @/home/jean-jacques/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:753:2
janv. 08 08:25:28 gjs[5414]: JS ERROR: TypeError: dynamic is null
                             _onSearchChanged@/home/jean-jacques/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/ui/contacts.js:369:1
                             @/home/jean-jacques/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:753:2
janv. 08 08:25:28 gjs[5414]: JS ERROR: TypeError: dynamic is null
                             _onSearchChanged@/home/jean-jacques/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/ui/contacts.js:369:1
                             @/home/jean-jacques/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:753:2
janv. 08 08:25:29 gjs[5414]: JS ERROR: TypeError: dynamic is null
                             _onSearchChanged@/home/jean-jacques/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/ui/contacts.js:369:1
                             @/home/jean-jacques/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:753:2
janv. 08 08:25:29 gjs[5414]: JS ERROR: TypeError: dynamic is null
                             _onSearchChanged@/home/jean-jacques/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/ui/contacts.js:369:1
                             @/home/jean-jacques/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:753:2
janv. 08 08:25:29 gjs[5414]: JS ERROR: TypeError: dynamic is null
                             _onSearchChanged@/home/jean-jacques/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/ui/contacts.js:369:1
                             @/home/jean-jacques/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:753:2
janv. 08 08:25:46 org.gnome.Shell.desktop[4799]: [5732:5732:0108/082546.075437:ERROR:media_internals.cc(104)] Cannot get RenderProcessHost**

**Comment by andyholmes** [comment]
Please ensure the following are done first:

* You have installed the [dependencies for Desktop Contacts](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Installation#desktop-contacts)
* You have disabled the [*Contacts* plugin in *Advanced*](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Devices#plugins)

Once this is done, you will probably have to disable, then re-enable the *SMS* plugin.

**Comment by jjlacrampe** [comment]
I had achieved the first two points, but not the last one : _to disable, then re-enable the SMS plugin._
After this operation, it works fine!
Thanx
