### ISSUE TITLE
Pause media player on calls doesn't work

### ISSUE THREAD

**Issue by uwe-007** [andyholmes/gnome-shell-extension-gsconnect#171]
Ubuntu 17.10 and 18.04, gsconnect 1.2, vlc

On incoming and outgoing calls only changing system volume works but not "Pause Media".

**Comment by uwe-007** [comment]
debug output:
`JS WARNING: [/home/uwe/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/telephony.js 415]: reference to undefined property "PlaybackStatus"
`

**Comment by uwe-007** [comment]
After pausing the media player with player control part in the app and hitting the play/pause button again nothing happens. 

Any feedback to this issues, Andy Holmes, would be very nice.

**Comment by andyholmes** [comment]
This seems like it's probably an MPRIS implementation problem. I'll have to download VLC and get back to you.

**Comment by uwe-007** [comment]
I tried this issues with rhythmbox: the song (mp3) continues after hitting pause/play in the app again (ok), but isn't paused on incoming calls too.

**Comment by CBiX** [comment]
I'm having the same issue with VLC, it actually seems to be the faulty MPRIS implementation in VLC (and apparently Spotify), even the KDEConnect guys noticed this: https://bugs.kde.org/show_bug.cgi?id=391900

Quote:

> The MPRIS implementations of VLC and Spotify are kinda broken, so there is not much we can do about that.

Of course we could make a workaround in GSConnect only for VLC but if it's a bug in VLC then it should be fixed there in the long term.

**Comment by andyholmes** [comment]
Sorry, I've been busy and forgot about this. @danieldeng2 submitted a PR for the `CanPlay` bug, but like you said it should be fixed upstream in VLC so I decided to reject it.

I haven't had time to investigate the "resume" bug, but it probably is a GSConnect bug and seems pretty likely. I've been working hard to get the rewrite in shape to merge, but it's still a day or two away yet and there won't be another release before that, sorry.

I'll leave this bug open though, so I remember to double check it works in the rewrite.

**Comment by uwe-007** [comment]
Pausing vlc on incoming calls works with Kubuntu and included kdeconnect 1.3.1, but the play/pause-button bug is there too.

**Comment by andyholmes** [comment]
I believe this part a VLC bug and the other part fixed in master. Please reopen if the problem occurs there.
