### ISSUE TITLE
Feature Request: Send notification when battery level reaches / falls to X%

### ISSUE THREAD

**Issue by meetowl** [andyholmes/gnome-shell-extension-gsconnect#172]
For people who like to keep between 80 and 25 % charge on their phones, it'd be pretty handy if you could set a custom minimun / maximum level which you would get a notification once it reaches that level.
Pretty niche but useful to have, don't think it's too hard to implement but what do I know.

**Comment by andyholmes** [comment]
While it wouldn't be that difficult, it's a duplication of a settings controlled by the device, and I'd rather leave this for the remote device to control. A battery update looks like this:

```js
{
    "id": 1535416917517,
    "type": "kdeconnect.battery",
    "body": {
        "currentCharge": 91,
        "isCharging": false,
        "thresholdEvent": 0
    }
}
```
The device sending the update sets `thresholdEvent` to `1` when it considers its battery level low. For Android this is the same as when you get a low battery notification on the device (usually 25% or 15%), for GSConnect it depends on the desktop settings.

It would be better to [file a feature request upstream](https://bugs.kde.org/buglist.cgi?quicksearch=kdeconnect&list_id=1505828) for the Android app to add this as a setting.
