### ISSUE TITLE
wrong port range for firewalls

### ISSUE THREAD

**Issue by fluxxen** [andyholmes/gnome-shell-extension-gsconnect#173]
Hey guys, it's not an real issue and no big deal, but actually the port range shown in the devices window is wrong:

![image](https://user-images.githubusercontent.com/42601220/44447902-01725300-a5ea-11e8-90a6-dbbba4a51227.png)

Currently the port range is **17*14*:1764**: [KDE Community Wiki
](https://community.kde.org/KDEConnect#I_have_two_devices_running_KDE_Connect_on_the_same_network.2C_but_they_can.27t_see_each_other)

greetz fluxxen

**Comment by andyholmes** [comment]
Thanks, but I think the Wiki must be out of date. KDE Connect has used port 1716-1764 for a couple years now, probably since TLS sockets (protocol version ).

https://github.com/KDE/kdeconnect-kde/blob/master/core/backends/lan/lanlinkprovider.h#L57-L59:

```c
    const static quint16 UDP_PORT = 1716;
    const static quint16 MIN_TCP_PORT = 1716;
    const static quint16 MAX_TCP_PORT = 1764;
