### ISSUE TITLE
Delay in battery indicator icon

### ISSUE THREAD

**Issue by flipflop97** [andyholmes/gnome-shell-extension-gsconnect#175]
The percentage indicated by the battery indicator icon to the right of my device is almost always higher than the actual percentage as displayed in the toast of the battery indicator on the left. It seems to have a delay before updating.

![gsconnect battery indicator delay](https://user-images.githubusercontent.com/13943260/44618145-a7cf8a00-a870-11e8-9ce7-7d15a1d21480.png)

**Comment by andyholmes** [comment]
I can't confirm this myself, but I'll accept the evidence. This will have to be addressed after the wip-rewrite branch is merged (soon).

**Comment by andyholmes** [comment]
I expect this is probably fixed in the rewrite so I'm going to close it. Re-open if it occurs with v13-alpha2 or higher.
