### ISSUE TITLE
[BUG] Entered text in SMS conversation disappears when a new message arrives.

### ISSUE THREAD

**Issue by Arquanite** [andyholmes/gnome-shell-extension-gsconnect#18]
It's a bit frustrating because if my friend sends me something before I send him my message, I need to retype message again.

**Comment by andyholmes** [comment]
Here's a Zip with this fix included:

[gsconnect@andyholmes.github.io.zip](https://github.com/andyholmes/gnome-shell-extension-gsconnect/files/1564404/gsconnect.andyholmes.github.io.zip)
