### ISSUE TITLE
Device connects, partial functionality -- not showing up in Device list

### ISSUE THREAD

**Issue by avantbored** [andyholmes/gnome-shell-extension-gsconnect#182]
Laptop: Ubuntu MATE 18.04 (using Gnome 3) on Dell XPS 9370
Phone: Motorola G4

GSConnect and KDEConnect are communicating. Remote Input, remote control, and ping functions work. I can even send files from Nautilus to my phone.

 However, my phone does not show up in the Devices list on my laptop, nor can the web browser extension find the phone. 

No errors showing up in debug logs w/r/t to connections.

**Comment by andyholmes** [comment]
Was `kdeconnectd` installed or running when GSConnect started?

**Comment by avantbored** [comment]
No. Have re-installed both programs according to recommended procedure; problem is the same.

One thing I've noticed: On the desktop app, I have named my laptop "XPS." However, my phone recognizes it as my Ubuntu name: "ryan@ryan-XPS-13-9370"

**Comment by andyholmes** [comment]
Neither KDE Connect or MConnect are installed? What does `lsof -i :1716` say?

```sh
$ lsof -i :1716
COMMAND  PID   USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
gjs     8354 andrew   18u  IPv4 429812      0t0  UDP *:1716 
gjs     8354 andrew   19u  IPv6 429813      0t0  TCP *:1716 (LISTEN)
gjs     8354 andrew   44u  IPv6 430663      0t0  TCP andy-notebook:1716->192.168.1.65:50494 (ESTABLISHED)
```

**Comment by avantbored** [comment]
Both KDEConnect & GSConnect are installed. Was just clarifying that I had tried to remedy the problem by re-installing and following the recommended procedures.

The output of `lsof` is 

`kdeconnec 1609 ryan   20u  IPv6  29585      0t0  UDP *:1716 
kdeconnec 1609 ryan   21u  IPv6  29586      0t0  TCP *:1716 (LISTEN)
kdeconnec 1609 ryan   27u  IPv6  51512      0t0  TCP ryan-XPS-13-9370:44432->192.168.1.8:1716 (ESTABLISHED)
`

**Comment by avantbored** [comment]
Sorry, I'm a little confused. The instructions say to have KDEConnect installed on my Android device; should I _not_ run KDEConnect after pairing?

**Comment by andyholmes** [comment]
KDE Connect should be on your Android device, GSConnect on your Linux device.

The original KDE Connect project has an Android app and a cross-desktop Linux application. GSConnect is an implementation only for Gnome Shell.

**Comment by avantbored** [comment]
I see. I did a bit of digging and found KDEConnect installed on my desktop. The issue is now resolved.

**Comment by avantbored** [comment]
Also, thank you for your work!! Life-improving app :D
