### ISSUE TITLE
Device not discovered once disconnected.

### ISSUE THREAD

**Issue by rdabra3** [andyholmes/gnome-shell-extension-gsconnect#191]
Hello, I am having a problem with GSConnect since the day I installed it. Once when my phone and laptop are not connected on the same network, it disconnects, but when I connect them to the same network(Laptop hotspot) GSConnect doesn't discovers my phone again. Please help me.

**Comment by rdabra3** [comment]
Note: Even the android KDEConnect app on my phone doesn't find my laptop once disconnected.

**Comment by andyholmes** [comment]
Sorry, I'll need you clarify if I understand the situation correctly.

* You have two devices, a laptop with GSConnect and a phone with the KDE Connect app.
* The devices connect to each other when on a regular network (like a router LAN).
* The devices *don't* connect to each other when the phone uses the laptop hotspot as the network

Is that right? If so, could you check the IP for each when using the hotspot and confirm they are on the same subnet and you can ping the phone from the laptop?

So if the laptop's IP is `192.168.0.100` the phone should have an address like `192.168.0.101` and not something like `192.168.1.101`. If the IP seems right, maybe there is another setting for the hotspot that keeps the laptop and phone separated?

**Comment by rdabra3** [comment]
I always connect my phone to the hotspot to access the internet. And GSConnect works perfectly fine when both devices are connected via GSConnect and kdeconnect, but any time if they are unpaired on GSConnect, it can't discover the other device even though the phone is connected to the laptop hotspot.

**Comment by andyholmes** [comment]
So once the device is disconnected, you just can't get it to reconnect? Can you still ping the phone from your laptop?

**Comment by rdabra3** [comment]
How to ping my phone from laptop? Phone is not connected to laptop via GSConnect and I don't know the IP of my phone.

**Comment by andyholmes** [comment]
Your IP should be in System->About Phone in android somewhere, try pinging that in a terminal:

    $ ping 192.168.1.100

**Comment by rdabra3** [comment]
![screenshot from 2018-09-19 11-57-46](https://user-images.githubusercontent.com/25562421/45734753-44ccdb00-bc03-11e8-8b43-b3e868c49ab5.png)

**Comment by andyholmes** [comment]
Is that a mobile network? You may not be able to send UDP broadcasts on that network. You can try entering your IP manually in the Android app:

![](https://raw.githubusercontent.com/andyholmes/gnome-shell-extension-gsconnect/master/extra/add-devices-by-ip.png)

**Comment by rdabra3** [comment]
What to do after adding the device ip, there's no button to connect.

**Comment by andyholmes** [comment]
use the Refresh item

**Comment by rdabra3** [comment]
It's still not connecting.

**Comment by andyholmes** [comment]
What is your laptop IP?

**Comment by rdabra3** [comment]
172.24.41.108

**Comment by rdabra3** [comment]
![screenshot from 2018-09-19 12-15-26](https://user-images.githubusercontent.com/25562421/45735514-bc036e80-bc05-11e8-867e-286bd8b579ad.png)

**Comment by rdabra3** [comment]
![screenshot_2018-09-19-12-16-51](https://user-images.githubusercontent.com/25562421/45735598-04bb2780-bc06-11e8-9c66-5896f015dd26.png)

**Comment by andyholmes** [comment]
Those seem like they're on different networks. Do these devices always have these addresses? How do you get them to connect the first time?

**Comment by rdabra3** [comment]
The laptop is connected to internet via LAN and phone is connected to the wifi hotspot created by laptop.
The first time when I asked you about indicator missing, you told me how to stop kdeconnect fully and after I did it, the phone got automatically discovered by the GSConnect Program and when I connected it the indicator for the phone appeared.

**Comment by andyholmes** [comment]
Is kdeconnect still installed?

**Comment by rdabra3** [comment]
Yes

**Comment by andyholmes** [comment]
It's probably running again or was when GSConnect started. You should probably uninstall kde connect, it usually starts as a service and will prevent GSConnect from working.

**Comment by rdabra3** [comment]
It's still not working.

**Comment by andyholmes** [comment]
Run this in a terminal:

    $ lsof -i UDP:1716

**Comment by rdabra3** [comment]
How do I get to system logs?

**Comment by andyholmes** [comment]
You can use Gnome Logs or run `journalctl -f -o cat /usr/bin/gjs` in a terminal, while you're trying to connect the devices.

**Comment by rdabra3** [comment]
![screenshot from 2018-09-19 13-02-43](https://user-images.githubusercontent.com/25562421/45737767-5797dd80-bc0c-11e8-99cc-c199e606e0d6.png)
It is saying that it requires proxy authentication but I have signed in my proxy credentials.

**Comment by rdabra3** [comment]
I now know what the problem is. I have to use 'No Proxy' instead of 'Manual Proxy'.

**Comment by rdabra3** [comment]
Thank You So Much For Helping Me. And those features in GSConnect like Send SMS, Filesystem Access and Locate My Phone are really really helpful and so awesome. Thanks once again.
