### ISSUE TITLE
v13 doesn't work in Ubuntu 18.04 with Gnome Shell 3.28.3

### ISSUE THREAD

**Issue by logix2** [andyholmes/gnome-shell-extension-gsconnect#194]
I tried installing v13 from both the provided zip and from Git, and the result in both cases is the same: I get a "Mobile devices" item in the system menu, but clicking on "Mobile settings" does nothing. Trying to open the extension preferences from Gnome Tweaks doesn't work either.

I removed the configuration and cache of the old v12 extension, so there shouldn't be any conflicts. lg doesn't show any errors so I'm not sure how to debug this.

**Comment by andyholmes** [comment]
What happens if you run this in a terminal:

    $ gapplication launch org.gnome.Shell.Extensions.GSConnect

**Comment by logix2** [comment]
When using that command nothing happens for a while and then:
```
$  gapplication launch org.gnome.Shell.Extensions.GSConnect
error sending Activate message to application: Timeout was reached
```

**Comment by andyholmes** [comment]
Could you run`journalctl -f -o cat /usr/bin/gjs` in another terminal while you run that?

**Comment by andyholmes** [comment]
I think I got it. It was well, if bluez wasn't there it tired to call the application before it started.

**Comment by driversti** [comment]
Cannot find the PC from phone and vise versa as well.
Here is the output of above mentioned command:
`$ journalctl -f -o cat /usr/bin/gjs
g_variant_new_string: assertion 'string != NULL' failed
Failed to set property AtkObject.accessible-role to title-bar: Could not parse integer 'title-bar'
Failed to set property AtkObject.accessible-role to link: Could not parse integer 'link'
Failed to set property AtkObject.accessible-role to link: Could not parse integer 'link'
Failed to set property AtkObject.accessible-role to list: Could not parse integer 'list'
Failed to set property AtkObject.accessible-role to link: Could not parse integer 'link'
Failed to set property AtkObject.accessible-role to link: Could not parse integer 'link'
Failed to set property AtkObject.accessible-role to link: Could not parse integer 'link'
Failed to set property AtkObject.accessible-role to list: Could not parse integer 'list'
Failed to set property AtkObject.accessible-role to layered-pane: Could not parse integer 'layered-pane'
`

**Comment by ferdnyc** [comment]
@driversti This (closed) issue is nearly a _year_ old, and concerns GSConnect v13. The current release is v24 (with v25 slated for release imminently).

Please open a new issue for your report, and complete the [template](https://github.com/andyholmes/gnome-shell-extension-gsconnect/issues/new?assignees=&labels=&template=bug_report.md&title=) with details about your environment.
