### ISSUE TITLE
SMS Application does not start

### ISSUE THREAD

**Issue by isantop** [andyholmes/gnome-shell-extension-gsconnect#2]
When I click on the SMS button in the extension, nothing happens. Checking the log file gives this:

```
Error calling openSms: GDBus.Error:org.gnome.gjs.JSError.TypeError: contact.type is null
```

This is happening on the v4 release

**Comment by andyholmes** [comment]
Oops, sorry. Didn't realize contacts could not have a type in Google. Could you tell me if this fixes it?

[gsconnect@andyholmes.github.io.zip](https://github.com/andyholmes/gnome-shell-extension-gsconnect/files/1458975/gsconnect.andyholmes.github.io.zip)

**Comment by isantop** [comment]
Seems to work great!

**Comment by andyholmes** [comment]
Cool, first bug and fix :) Feel free to file more.

**Comment by andyholmes** [comment]
PS. you don't need KDE Connect installed to use this.

**Comment by isantop** [comment]
Yeah, I did remove it to avoid confusion about which device I was pairing to. Seems nice so far!

**Comment by andyholmes** [comment]
Yeah, KDE Connect isn't use to sharing.
