### ISSUE TITLE
[v13-alpha] Mpris current position

### ISSUE THREAD

**Issue by danieldeng2** [andyholmes/gnome-shell-extension-gsconnect#200]
player.position is always 0, so track is not working.

**Comment by andyholmes** [comment]
Is this in master?

**Comment by danieldeng2** [comment]
@andyholmes yes this is the master after the rewrite.

**Comment by andyholmes** [comment]
Okay, I'm looking into this now.

**Comment by andyholmes** [comment]
Are you by chance using Gnome Music? I've been investigating this using Gnome Music which uses GStreamer under the hood, specifically `gst_element_seek_simple(format, seek_flags, seek_pos)`:

> **seek_pos** - position to seek to (relative to the start)

Whereas `Player.Seek(offset)` from the MPRIS spec says:

> Seeks forward in the current track by the specified number of microseconds.
> 
> A negative value seeks back. If this would mean seeking back further than the start of the track, the position is set to 0.

In the case of Gnome Music at least, it seems like "seek" is being interpreted as SetPosition() instead of Seek(). If you're also using Gnome Music I'll open an upstream bug report.

**Comment by danieldeng2** [comment]
No, unfortunately. I've tried it with both VLC player and a browser-mpris plugin and they both yield the same result. This never happened in the older version, as I understand you've fixed it using a different api in the older version.

**Comment by getzze** [comment]
Yes, see here: https://github.com/getzze/gnome-shell-extension-gsconnect/blob/master/src/service/plugins/mpris.js

// Bug with player.Position always returning 0. Must use the cumbersome API
let last_pos = p.prop.GetSync("org.mpris.MediaPlayer2.Player", "Position")[0].get_int64();

**Comment by andyholmes** [comment]
I believe GSConnect does it the same way now:

https://github.com/andyholmes/gnome-shell-extension-gsconnect/blob/f81d05acc324044d43a00a22e94d131dc47cbd3f/src/service/components/mpris.js#L165-L170

https://github.com/andyholmes/gnome-shell-extension-gsconnect/blob/f81d05acc324044d43a00a22e94d131dc47cbd3f/src/service/components/dbus.js#L383-L405

I did some work recently on the MPRIS stuff and it seems to work for me, have you tried building from master again?

**Comment by getzze** [comment]
Working well here too in current master

**Comment by andyholmes** [comment]
Excellent, thanks for testing.
