### ISSUE TITLE
[v13-alpha2] GSConnect forces gnome-shell to use English in some places

### ISSUE THREAD

**Issue by emil1003** [andyholmes/gnome-shell-extension-gsconnect#203]
Enabling GSConnect >= 13 forces some elements of the shell and the lock screen to use English. It results in a weird mashup of languages, like the Bluetooth tab here:
![image](https://user-images.githubusercontent.com/15571767/45932328-b34ec780-bf7a-11e8-93f2-b4500b6f19ac.png)

**Comment by andyholmes** [comment]
Thanks for reporting this, these are hard to catch since I'm a native english speaker. I marked this as fixed in the commit, because I'm pretty sure I got it but let me know if the problem still exists.
