### ISSUE TITLE
Allow to hide application icon in aggregateMenu

### ISSUE THREAD

**Issue by ai** [andyholmes/gnome-shell-extension-gsconnect#204]
@andyholmes Thanks for an amazing tool. I really like it. 

There is only a very small thing which I love to have in the tool. It shows “laptop and phone” icon in top-left GNOME Shell menu.

![5fuw12x](https://user-images.githubusercontent.com/19343/45936154-4985ec00-bf81-11e8-80da-2cb30718e202.png)

Can we add an option to hide it, please?

**Comment by andyholmes** [comment]
Hi, this probably won't be implemented as an option. The service indicator shows whether or not the service is active, and will probably be used to display other states as well in the future.

I understand the icon seems a bit redundant under most circumstances, but it's appropriate to the Gnome Shell design guide for services and the best option at the moment. Offering as an option becomes a setting I have to support in future, and a signal lookup taking a global lock. I'd be more in favour of removing it completely, but the functionality would have to be replaced.

**Comment by ai** [comment]
> I'd be more in favour of removing it completely, but the functionality would have to be replaced.

I like the idea to remove it right now and then we can show it only in special cases

**Comment by andyholmes** [comment]
If it were removed, it would be gone for good. But that won't happen until there is a way to replace it's functionality. For now it will have to stay in.

**Comment by ai** [comment]
@andyholmes maybe I can edit extension source code on my machine and just hide it only for me :D.

Can you point me to the right place of code, please?

**Comment by ai** [comment]
Seems like you need just to replace `true` to `false` here
https://github.com/andyholmes/gnome-shell-extension-gsconnect/blob/master/src/extension.js#L212
