### ISSUE TITLE
Gray out system area icon when no device is connected

### ISSUE THREAD

**Issue by brunelli** [andyholmes/gnome-shell-extension-gsconnect#206]
I don't like to have the indicators showing, but currently that's the only way to quickly know if my phone is connected or not (gray indicator = disconnected, white indicator = connected).

Could the system area icon also be grayed out when there's no device connected?

![captura de tela de 2018-09-24 19-48-17](https://user-images.githubusercontent.com/5755892/45983413-d341c200-c032-11e8-8485-2d4acf6a510b.png)

**Comment by andyholmes** [comment]
I think this is a good idea, I like how it re-uses the existing icon. I'll look into how to best do this.
