### ISSUE TITLE
Web browser integration doesn't work in Chrome 65.0

### ISSUE THREAD

**Issue by NNeto** [andyholmes/gnome-shell-extension-gsconnect#21]
I've installed the Chrome extension but it has a red icon and says "Disconnected from GSConnect". Although I've installed the addon on Firefox Developer Edition and it worked straight away.
I'm using Google Chrome 65.0.3294.5 (Official Build) dev (64-bit) with Fedora 27.

**Comment by andyholmes** [comment]
It's currently only possible to run the WebExtension in one (running) browser at a time since the native messaging host (connector between Shell and Browser) is currently restricted to a single instance. If only Firefox *or* Chrome is running when the extension is loaded it should be able to connect, but both can't connect at the same time.

This is a restriction I might lift in future releases of the Gnome Shell extension, but I haven't investigated the consequences of what might happen if two native messaging hosts are running at the same time or if one fails to exit when the browser closes.

**Comment by NNeto** [comment]
But even before installing the addon on Firefox, it wasn't working on Chrome, and while Firefox isn't running, it still doesn't work here on Chrome.

**Comment by andyholmes** [comment]
Could you open _chrome://extensions/_ then enable "Developer mode" at the top and click "Inspect views: background.html" to see if there are any errors related to connecting to the native messaging host?

![screenshot from 2017-12-17 00-58-46](https://user-images.githubusercontent.com/1265208/34077985-9f5f1280-e2c5-11e7-90f3-52db348f252b.png)

**Comment by indaleto** [comment]
I have this problem with 65.0 chrome version. The message I've found is:
`Disconnected from native host: Specified native messaging host not found.
onDisconnect @ background.js:266`

**Comment by andyholmes** [comment]
Okay, apparently the native messaging host manifest needs to be installed in different directories for chromium, chrome-stable, chrome-beta and chrome-unstable. I'll have to clean this up later, but this zip should work for you (the WebExtension itself works as-is):

[gsconnect@andyholmes.github.io.zip](https://github.com/andyholmes/gnome-shell-extension-gsconnect/files/1592520/gsconnect.andyholmes.github.io.zip)

**Comment by indaleto** [comment]
Thanks for your reply but 
Nop, now it gives multiple errors:
`Error in event handler for runtime.onMessage: TypeError: Cannot read property 'postMessage' of null
    at postMessage (<URL>)
    at onMessage (<URL>)
    at <URL>
background.html:1 Error in event handler for runtime.onMessage: TypeError: Cannot read property 'postMessage' of null
    at postMessage (chrome-extension://jfnifeihccihocjbfcfhicmmgpjicaec/js/background.js:47:10)
    at onMessage (chrome-extension://jfnifeihccihocjbfcfhicmmgpjicaec/js/background.js:67:9)
    at chrome-extension://jfnifeihccihocjbfcfhicmmgpjicaec/js/browser-polyfill.min.js:1:6026`

`background.js:266 Disconnected from native host: Specified native messaging host not found.
onDisconnect @ background.js:266
background.js:64 REQUEST: {"type":"devices"}
background.js:42 SEND: {"type":"devices"}`

`Missing message parameters
postMessage @ background.js:45
background.js:64 REQUEST: {"type":"devices"}
background.js:42 SEND: {"type":"devices"}`

`Disconnected from native host: Specified native messaging host not found.
onDisconnect @ background.js:266
2background.js:266 Disconnected from native host: Specified native messaging host not found.
onDisconnect @ background.js:266
EventImpl.dispatchToListener @ extensions::event_bindings:403
publicClassPrototype.(anonymous function) @ extensions::utils:138
EventImpl.dispatch_ @ extensions::event_bindings:387
EventImpl.dispatch @ extensions::event_bindings:409
publicClassPrototype.(anonymous function) @ extensions::utils:138
dispatchOnDisconnect @ extensions::messaging:378
background.js:64 REQUEST: {"type":"devices"}
background.js:42 SEND: {"type":"devices"}`

**Comment by andyholmes** [comment]
Seems to be the same error, could you confirm the native messaging host manifest was installed correctly?

```sh
$ ls ~/.config/google-chrome-unstable/NativeMessagingHosts/
org.gnome.shell.extensions.gsconnect.json
```
If so try to disable then re-enable the WebExtension

**Comment by NNeto** [comment]
I just had to copy the content from the zip and it's working now without errors here.

**Comment by andyholmes** [comment]
That's great, I'll wait for @indaleto to confirm its fixed with that zip then close the bug. Thanks for testing.

**Comment by NNeto** [comment]
One question: now that the extension is working in both Chrome Unstable and Firefox, and I can send links from both of them while both are open, I don't get what you meant with "If only Firefox or Chrome is running when the extension is loaded it should be able to connect, **but both can't connect at the same time**".

**Comment by andyholmes** [comment]
Yep, that was fixed in v8+, now it can run as many instances as necessary. It will exit whenever the browser exits, so there's no danger in running multiple instances or zombie processes.

You could run it in firefox, chrome, chrome beta and chrome unstable at the same time if you wanted.

**Comment by andyholmes** [comment]
I'm closing this as I'm confident it's been fixed in git.

**Comment by indaleto** [comment]
It's working here too. Thanks...

**Comment by alcarraz** [comment]
I'm having this problem for a while I don't have the ~/.config/google-chrome/NativeMessagingHosts/ folder even though I tried uninstalling and reinstalling the extension.

**Comment by andyholmes** [comment]
Have you enabled _Web Browser Integration_ in the preferences?

**Comment by alcarraz** [comment]
oups didn't remember that step, I feel so ashamed , sadly googling for the message didn't provide that.

**Comment by andyholmes** [comment]
No problem :) In future it will just be installed automatically since it's just a < 1KB file. I guess at the time it made sense to make it a switch and put the links there.
