### ISSUE TITLE
Emoji picker is cropped when sms window is not big enough

### ISSUE THREAD

**Issue by basilrabi** [andyholmes/gnome-shell-extension-gsconnect#211]
Emoji picker is cropped when the sms window is not big enough.

![screenshot](https://user-images.githubusercontent.com/29010952/46182871-b04c3200-c300-11e8-84f6-a154b144f6c5.png)

When adjusting the window to an appropriate size, the whole emoji picker can be seen.

Sometime in v11, in a wayland session, I have not experienced this issue. But in an X session, this issue is present. Right now in master, the cropping issue is present in both wayland and X.

**Comment by andyholmes** [comment]
Hmm, after a bit of digging this seems to be an upstream bug in Gtk, [#534 GtkPopover is constrained to parent window size on non-Wayland backends](https://gitlab.gnome.org/GNOME/gtk/issues/543).

Probably this started affecting Wayland in GSConnect when Gdk was forced to use the x11 backend to fix the clipboard plugin on Wayland.
