### ISSUE TITLE
[v13-alpha2] "Save" Button in Edit/Add Commands Window

### ISSUE THREAD

**Issue by AdamKane41** [andyholmes/gnome-shell-extension-gsconnect#212]
Dont know if it's the intended behavior but it can cause confusion or worst; replace an existing entry with an unwanted new one.

When in the Commands section, once an entry fields is done editing, if we click on another entry before clicking on the "save button" (in the lower right corner) the original entry will remain unchanged and the modifications will be apply to the entry clicked. (.GIF provided if unclear :-) )

When editing an entry, the others should be unselectable to prevent. modification of other commands by mistake.
Peace
![peek 2018-09-28 01-28](https://user-images.githubusercontent.com/30092603/46190189-81ae6700-c2c0-11e8-9bd6-16ec12f9a208.gif)

**Comment by andyholmes** [comment]
Ah I see, good catch. I'll try and clean up the logic there.
