### ISSUE TITLE
No Chromium Icon in Software section

### ISSUE THREAD

**Issue by AdamKane41** [andyholmes/gnome-shell-extension-gsconnect#213]
No Chromium Icon in Software section
Peace
![screenshot from 2018-09-28 03-07-06](https://user-images.githubusercontent.com/30092603/46193383-00f56800-c2cc-11e8-9175-ac9ab7b84afd.png)

**Comment by andyholmes** [comment]
Should be good now, I've moved things around a bit. I think the Chrome Web Store is also used for chromium:

![screenshot from 2018-09-28 17-26-33](https://user-images.githubusercontent.com/1265208/46238712-c16a6280-c343-11e8-9b34-53cbe2c960f2.png)
