### ISSUE TITLE
show message "DIsconnected from GSConnect" on firefox add-on

### ISSUE THREAD

**Issue by Sosha1996** [andyholmes/gnome-shell-extension-gsconnect#219]
i have ubuntu 18.10.
i install GSConnect package from ubuntu repo: `sudo apt install gnome-shell-extension-gsconnect`
in my ubuntu, everythings is good. but in firefox I encountered this message "DIsconnected from GSConnect". how i can fix it?

Firefox Version: 62.0.3
Ubuntu: 18.10 (development branch)
Desktop: GNOME
GNOME Shell Version: GNOME Shell 3.30.0

**Comment by andyholmes** [comment]
Do you already have GSConnect installed as a user extension? Have you enabled the GSConnect extension? Are the native messaging host manifests installed?

    $ locate org.gnome.shell.extensions.gsconnect.json

**Comment by Sosha1996** [comment]
![image](https://user-images.githubusercontent.com/16008585/46511825-c48eb280-c85d-11e8-975c-22e350a3300c.png)

![image](https://user-images.githubusercontent.com/16008585/46511850-e1c38100-c85d-11e8-8427-4fef2b8eb804.png)

`$ locate org.gnome.shell.extensions.gsconnect.json`
nothing

**Comment by andyholmes** [comment]
It seems like the webextension manifests are not installed with that package, so firefox can't connect to gsconnect.

**Comment by Sosha1996** [comment]
![image](https://user-images.githubusercontent.com/16008585/46511957-74642000-c85e-11e8-9f91-28be10adfd40.png)

**Comment by Sosha1996** [comment]
> It seems like the webextension manifests are not installed with that package, so firefox can't connect to gsconnect.

how can i do to fix it?

**Comment by andyholmes** [comment]
You should file a bug with the package in launchpad and link to [Packaging](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Packaging). Although you should keep in mind that both 18.10 and the version of GSConnect in it are still unstable.

**Comment by hkiang01** [comment]
@Sosha1996 did you file a bug? If so, could you provide a link to it?
