### ISSUE TITLE
System menu entries revert their translation to English

### ISSUE THREAD

**Issue by thomazio** [andyholmes/gnome-shell-extension-gsconnect#22]
Happens to the wired and wireless network, VPN, night light, and battery indicator.
Reproducible on bd98e4369624cb4c767e646357cdb2da80a90ab1 using German and possibly any other language.  
Disabling GSConnect and restarting GS turns everything back to normal.

**Comment by andyholmes** [comment]
Thanks for reporting, I probably wouldn't have caught this one.

**Comment by andyholmes** [comment]
Oops, don't run from master just yet, something bad happened

**Comment by andyholmes** [comment]
Okay, should be good.
