### ISSUE TITLE
More aggressive connection re-establishing after disconnect

### ISSUE THREAD

**Issue by Eonfge** [andyholmes/gnome-shell-extension-gsconnect#220]
I have the misfortune in life that I live in a crowded inner city, with a WiFi router ever 5 meters and bandwidth congestion so thick you can park your bike against it.

So my phone occasionally looses the connection with my router. No biggy, it will restore itself. But sadly GConnect will not restore the connection with a phone if it went missing for a minute. If I then press the button 'connect', everything is instantly in order, but I must press the button, no auto-reconnect. I only have one phone, so for me it's not like I have other devices to be considerate about. 

Could it be possible to add a more aggressive connection mode to the plug-in? 

Running Ubuntu 18.04 LTS, with GSconnect 12

**Comment by Eonfge** [comment]
Tried to get some logging, but this was the best I could do:
[gsconnect_log.txt](https://github.com/andyholmes/gnome-shell-extension-gsconnect/files/2475242/gsconnect_log.txt)

The timestamps, 09:00, was about an our before the connection got lost. During that time, I was playing music (with Lollypop and PulseEffects in case that matters) when it failed at some point.

**Comment by andyholmes** [comment]
This should be fixed with 9363209 which tries to reconnect to paired devices every 5 seconds. I think that's reasonably sane.
