### ISSUE TITLE
Add "Reset All..." button to Keyboard Shortcuts

### ISSUE THREAD

**Issue by thomazio** [andyholmes/gnome-shell-extension-gsconnect#23]
I am unable to remove shortcuts or it's not clear how to remove them. I'm assuming it works like the rest of Gnome by pressing ESC while setting a new shortcode, but the shortcut is not being unset.  
Running ba1ffbb.

BTW, to make it even more like Gnome, you could also add a button to remove a shortcut (only when a shortcut is already set). You can see what I mean in by going System Settings -> Devices -> Keyboard.

**Comment by andyholmes** [comment]
Gnome settings uses a custom widget with popup, which I could duplicate, but it's a fair amount of code for a small part of the settings. However, just like the Gnome setting keyboard shortcuts <kbd>Esc</kbd> means "cancel" while <kbd>Backspace</kbd> is used to delete a shortcut, there's just no obvious place to put a label explaining that.

I should be able to add a button to reset all the keybindings for a device though.

**Comment by thomazio** [comment]
Oh that's why it never worked. While translating backspace you can easily mix it up with the translation for DEL in German. D'oh.
Still it may not be clear to everyone as to how it works so I think a button like the one you suggest would be cool.

**Comment by andyholmes** [comment]
I'm having a heck of a time implementing this simple button, for some reason I can't get the TreeView to update. I might have to come back to this later...

**Comment by andyholmes** [comment]
Implemented in the rewrite now
