### ISSUE TITLE
Cannot find my cell (but cell can find computer)

### ISSUE THREAD

**Issue by ouillepouille** [andyholmes/gnome-shell-extension-gsconnect#251]
When I try to refresh my device list, it logs these errors : 

```
JS WARNING: [/home/pichi/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js 194]: reference to undefined property "lan"
JS ERROR: TypeError: this.lan is undefined
broadcast@/home/pichi/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:194:21
@/home/pichi/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:864:2
```

And when I restart service, it give me these errors : 

```
DEBUG: [__init__.js:12]: loading service/__init__.js
DEBUG: [daemon.js:vfunc_startup:743]: Loading 0 device(s) from cache
JS ERROR: Gio.IOErrorEnum: Erreur lors de liaison à l’adresse : Adresse déjà utilisée
_initUdpListener@/home/pichi/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/lan.js:149:13
_init@/home/pichi/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/lan.js:44:9
vfunc_startup@/home/pichi/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:753:24
_init@/home/pichi/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:97:9
@/home/pichi/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:864:2

g_variant_new_string: assertion 'string != NULL' failed

```
I'm on Ubuntu 18.10 (never should have upgraded !)
and version is the latest zip in releases (quoted as compatible with 3.30 ?)
Thanks for your wonderful work... I'm relying on this extension for every day use normally !

**Comment by andyholmes** [comment]
Is KDE Connect running or another service using port 1716? Please see [Network Error](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Help#LanError).

**Comment by ouillepouille** [comment]
Thanks... Ubuntu 18.10 broke URL handling system-wide so I couldn't see the help page when clicking the error notification box.
So I did the kdeconnect thing, and now the error is gone.
I resetted all configs both  on android and on my computer.
Still no go. Now nothing is detected. Connecting manually does absolutely nothing.
I feel so dumb for upgrading to 18.10, lol.

**Comment by ouillepouille** [comment]
Since I posted the issue I tried my best to start ex nihilo, so from scratch
I deleted KDE connect, everything related, and also everything related to GSConnect and started from the zip install found in releases (using install instructions provided).

Now nothing shows up.. but if I try to conncect manually from computer to Moto G, I get nothing
But this is the log : 

> DEBUG: [lan.js:broadcast:282]: Identify to 192.168.2.122
> DEBUG: [lan.js:_onIncomingChannel:98]: remote address: 192.168.2.122
> DEBUG: [daemon.js:_ensureDevice:212]: GSConnect: Adding Motorola Moto G
> DEBUG: [device.js:_handleIdentity:282]: ext is not defined
> @/home/pichi/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/lock.js:12:1
> _handleIdentity@/home/pichi/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/device.js:282:17
> _init@/home/pichi/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/device.js:117:13
> _ensureDevice@/home/pichi/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:226:22
> _onIncomingChannel@/home/pichi/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/lan.js:114:36
> Async*@/home/pichi/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:864:2
> 
>

**Comment by ouillepouille** [comment]
OK somehow after reinstalling a couple of time, it works. 
now the new problem is that I don't get SMS notifications on my desktop (but my settings indicate I should be getting them..)
