### ISSUE TITLE
Installed v13 from ZIP, but could not enable plugin

### ISSUE THREAD

**Issue by notdefine** [andyholmes/gnome-shell-extension-gsconnect#254]
I got this error:
error: GSConnect: Failed to execute program org.gnome.Shell.Extensions.GSConnect: Permission denie

I disabled the old version and removed the files from ~/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io . Then I copy the new Version inside. When I try to enable the Pluging  I got the described error. (Output from journalctl /usr/bin/gnome-shell -f)

The Ubuntu menü now show "mobile Devices" but when i select "Mobile settings" nothing happens.

greetings

**Comment by andyholmes** [comment]
Did you follow the instructions from [Install fro Zip](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Installation#install-from-zip)? It sounds like the files were not unzipped properly or Gnome Shell was not restarted.

**Comment by notdefine** [comment]
Yes, i missed to get the right path. thx
