### ISSUE TITLE
Not executing after installing via Ubuntu Software on Ubuntu 18.10

### ISSUE THREAD

**Issue by matheusreich** [andyholmes/gnome-shell-extension-gsconnect#256]
I get the following error when trying to open the extension settings screen:

Gio.DBusError: Erro ao chamar StartServiceByName para org.gnome.Shell.Extensions.GSConnect: GDBus.Error:org.freedesktop.DBus.Error.Spawn.ChildExited: Process org.gnome.Shell.Extensions.GSConnect exited with status 1

Stack trace:
  _init@/home/matheus/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/client.js:33:9
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  _parent@resource:///org/gnome/gjs/modules/_legacy.js:39:12
  _init@/home/matheus/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/client.js:695:9
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  _init@/home/matheus/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/prefs.js:100:23
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  buildPrefsWidget@/home/matheus/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/prefs.js:215:23
  _selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:83:22
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  _onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:235:17
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  main@resource:///org/gnome/shell/extensionPrefs/main.js:389:5
  @<main>:1:43
  
How can it be fixed?

**Comment by andyholmes** [comment]
It sounds like you are using v12 on Gnome 3.30. You should update to v13 by following the instructions on [Install from Zip](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Installation#install-from-zip) page.
