### ISSUE TITLE
Annoying notification from GSconnect

### ISSUE THREAD

**Issue by Aceler** [andyholmes/gnome-shell-extension-gsconnect#260]
Yes, I know that remote input does not supported with Wayland. GSconnect notify me about it every time Gnome start.

I think, one notification should be enough.

**Comment by andyholmes** [comment]
Unfortunately there is currently no way for GSConnect to know you've seen this notification, or to predict whether you will switch between Xorg and Wayland in the future. If you will continue to use Wayland, you should just disable this plugin in the settings for your device:

![screenshot from 2018-10-25 13-26-58](https://user-images.githubusercontent.com/1265208/47528301-b0851200-d859-11e8-9de8-5154d2296019.png)

**Comment by Aceler** [comment]
Well, where can I find settings for the device? 

Maybe it''s a different bug, because I can't find one, or maybe I just can't find one O:-)

**Comment by Aceler** [comment]
Yes, this is obviously a bug, because I can't see device settings. 

Images here: https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Installation indicates that I should see devices in settings, but there is no devices. 

The device itself is working perfectly. Should I file another bug?

**Comment by Aceler** [comment]
I reset dconf schema for gsconnect and now it is working fine.

So, you need to do a configuration reset when upgrading from previous verion of GSconnect.

**Comment by andyholmes** [comment]
Okay, thanks for reporting that. Upgrading settings from v12 is not something that's well tested yet, so I'll open a issue and try and revisit that ASAP.
