### ISSUE TITLE
Settings GUI freezes

### ISSUE THREAD

**Issue by rugk** [andyholmes/gnome-shell-extension-gsconnect#264]
## What happens

Sometimes the settings GUI just freezes or some stuff like this (it was also not shown in the GNOME application overview once but just had a transparent area instead of a "screenshot").

And in my case, everything is installed.

Possibly it was caused by having it open "too long" in the background or so…

This transparent case looks like this:
![grafik](https://user-images.githubusercontent.com/11966684/47568355-2c9e5900-d931-11e8-990f-f39c8452267a.png)

## What should happen 

Not freeze.

## System 

v13 (upgraded from before)
GNOME 3.28
Fedora 28

**Comment by andyholmes** [comment]
Can you provide more information such as logs of this behaviour?

**Comment by rugk** [comment]
I'll try when I see this behavior again.

**Comment by andyholmes** [comment]
Seems like it's been some time since this bug happened, so maybe it has been fixed in a more recent release. Please re-open if the issue persists with a current version of GSConnect.
