### ISSUE TITLE
GNOME user menu/top bar integration broken after upgrade

### ISSUE THREAD

**Issue by rugk** [andyholmes/gnome-shell-extension-gsconnect#265]
## STR

First, after the upgrade _no devices_ were shown in the user panel and settings for "Display mode" (and other's under "Shell") did change anything at all. 

I saw it like this in the GNOME user menu:
![grafik](https://user-images.githubusercontent.com/11966684/47567504-04155f80-d92f-11e8-9397-231493982147.png)

**A user logout/login was required** then this was fixed.

Now the devices are shown, but _always in offline state_ – in the menu. In the settings it works as expected, also all features work so they are certainly connected. They are just shown as "This device is offline". Always.

So now… I tried to fix this by clicking on "restart service" and first I thought it showed no device again, but I think now it finally shows the battery status icons.

So my workaround would be:
* Logout and login on all devices.
* Click "restart service" on all devices.

## System 

v13 (upgraded from before)
GNOME 3.28
Fedora 28

**Comment by andyholmes** [comment]
Correct, this is described in the Installation page that Gnome Shell must be restarted after upgrade. GSConnect is made of two parts; the service and the Shell extension.

The service will restart itself when updated, and will stop/start when the dekstop session does. The Shell extension can not, and it is usually up to the extension subsystem to ensure extensions are properly upgraded. If you install manually from Zip, you must do this yourself.

**Comment by rugk** [comment]
I did not install it manually via the ZIP, however, but upgraded from extensions.gnome.org.

**Comment by andyholmes** [comment]
Duplicate of #262 

Okay, then I think this one is almost definitely the same as #262. It's impossible to tell from the screenshot if the shell extension was reloaded since that part looks exactly the same in v12, and it's fixed now for you so it would be hard to figure out.

Let's consider this one a duplicate then and leave it closed (the issues will be linked now anyways).
