### ISSUE TITLE
Must not link to Google Play (only)

### ISSUE THREAD

**Issue by rugk** [andyholmes/gnome-shell-extension-gsconnect#268]
I see v13 now links to Google Play (labelled with "Android") and Salfish OS.

So now two problems:
* You may not want to promote Google Play.
* KDEConnect is also available on F-Droid.

Solution:
Of course you could just add two links, but really a more visually pleasing solution would be to just add these two **download buttons** the same as you did for the browser add-ons.

Both Google Play and F-Droid have these badges, so you may use them. :smiley:

**Comment by ferdnyc** [comment]
Fixed in #285
