### ISSUE TITLE
Argument 'object' (type interface) may not be null

### ISSUE THREAD

**Issue by greee-fr** [andyholmes/gnome-shell-extension-gsconnect#270]
_init@/home/myhomedir/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/notification.js:77:9
loadPlugin@/home/myhomedir/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/device.js:783:26
loadPlugins@/home/myhomedir/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/device.js:808:19
@/home/myhomedir/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:864:2

**Comment by andyholmes** [comment]
Duplicate of #246 

Thanks for reporting, there's a fixed Zip and further discussion in the linked issue.
