### ISSUE TITLE
PackageKit install buttons unfocus to "on" state

### ISSUE THREAD

**Issue by ferdnyc** [andyholmes/gnome-shell-extension-gsconnect#273]
Like so many of the issues I open, an admittedly-minor look & feel issue.

On Fedora 28, when the settings window loses focus, the install buttons in Additional Features defocus to an "enabled" / positive state, rather than a deactivated / temporarily-disabled state as one might expect. 

Since the install button is a control rather than a switch, it doesn't make sense to show this kind of state:

![screenshot from 2018-10-27 05-05-07](https://user-images.githubusercontent.com/538020/47602104-c0ab0780-d9a7-11e8-8768-3a5e1e89d8e8.png)

(Compare to the controls in other panes, especially the Service pane's Restart Service button):

![screenshot from 2018-10-27 05-04-50](https://user-images.githubusercontent.com/538020/47602119-e801d480-d9a7-11e8-964f-ed195d506297.png)

![screenshot from 2018-10-27 05-04-59](https://user-images.githubusercontent.com/538020/47602122-ed5f1f00-d9a7-11e8-94ee-dfb581bbcd25.png)

Note: It's possible #263 is in play here, since the detection of installed packages doesn't seem to be working properly on Fedora. I'd be curious to learn how the unfocused state of these controls is rendered on systems where the PackageKit integration is working as expected.

**Comment by andyholmes** [comment]
This is a weird bug I forgot about. I assume it's my fault, but I don't know what's causing it. The coloring is from the class `suggested-action` (you can see `destructive-action` on the Device->Advance->Delete which works fine). For some reason it only shows when the window is unfocused, although a few themes work properly Adwaita and Yaru don't.

I think I'll just remove the coloring since it's probably not appropriate anyways.

**Comment by ferdnyc** [comment]
Ah, yeah I see.

Reading ["Beautiful Buttons" § Suggested actions](https://wiki.gnome.org/HowDoI/Buttons#Suggested_actions), it talks about "the" suggested action, and explicitly sets it up as a companion to the dialog's default action (on typing Enter, for example):
 > This is somewhat complementary to the default activation I've mentioned above. While default activation is more about behaviour, the suggested action is more about the visuals. If you want the one, you probably want the other too.

Which makes me think that having multiple "suggested action"-s in the same dialog is a bit weird, and as you say, probably not appropriate.
