### ISSUE TITLE
Save sms window geometry

### ISSUE THREAD

**Issue by vredesbyyrd** [andyholmes/gnome-shell-extension-gsconnect#28]
This may fall into the OCD category, but it would be a nice if the sms plugin could remember the window geometry of the last open state (width x height + location). I am not sure if the window position can be stored at the application level. or if that is left up to the window manager. But at least saving the windows last dimensions or having the capability to set it at a user level would be a handy enhancement. 

There seemed to be some useful information here:

https://wiki.gnome.org/HowDoI/SaveWindowState

**Comment by andyholmes** [comment]
Although I previously thought this wasn't possible in GJS due to event introspection, I've seen it done it gnome-maps in a slightly different way, so I'm reopening this to track it.

**Comment by vredesbyyrd** [comment]
Interesting. Sounds good to me.
