### ISSUE TITLE
Own repo for browser extensions?

### ISSUE THREAD

**Issue by rugk** [andyholmes/gnome-shell-extension-gsconnect#291]
It would be great to put the browser add-on source code on GitHub too. It would also help to keep the issues separate.

**Comment by andyholmes** [comment]
WebExtension code is already available under the `webextension/` directory, but needs to be in the same repository since it shares translations with the extension.

**Comment by rugk** [comment]
Mhh, you could also use git submodules or cother things for that, but well… your decision.

**Comment by andyholmes** [comment]
Oh I mean it even shares the same POT file so translators translate both at the same time. Before only one or two bothered because you had to do it by hand.
