### ISSUE TITLE
Translatable string with a mysterious variable

### ISSUE THREAD

**Issue by piotrdrag** [andyholmes/gnome-shell-extension-gsconnect#298]
`%d Connected` in src/extension.js:246 has no translator comment, so I don’t know what %d stands for and I can’t translate it.

**Comment by ferdnyc** [comment]
Good point; it is a bit cryptic. `%d` in printf format strings is a number (a base 10 integer, specifically — the "d" indicates signed "d"ecimal notation). Looking at the source, the context is the number of devices currently connected.

**Comment by ferdnyc** [comment]
That's a good point, would this work as the generated output?
```
#. TRANSLATORS: The number of devices connected
#: src/extension.js:247
#, javascript-format
msgid "%d Connected"
msgid_plural "%d Connected"
msgstr[0] ""
msgstr[1] ""
```
(The result of modifying that section of code to
```js
if (this.available.length > 1) {
  //TRANSLATORS: The number of devices connected
  this._item.label.text = gsconnect.ngettext('%d Connected', '%d Connected',
  this.available.length).format(this.available.length);
```

(As you can see, the reality is even more cryptic. `%d` will always be >= 2 when that code path is followed, so the singular form will never actually be used. But that's not a detail translators really need to concern themselves with.)

I'll look around for other strings that involve countable values, and could benefit from `ngettext()`. But let me know if you notice any. There's currently only one other instance of plural translation in the source, the time duration in hours set at `src/shell/donotdisturb.js:263`. But I feel like there are probably other candidates.

**Comment by piotrdrag** [comment]
`TRANSLATORS: %d is the number of devices connected` would be more clear. Apart from that nitpick, it looks good to me.

As for other strings that need ngettext, there is this one:

```
#. TRANSLATORS: Time duration in minutes (eg. 15 minutes)
#: src/service/ui/messaging.js:88 src/service/ui/messaging.js:120
#: src/shell/donotdisturb.js:266
#, javascript-format
msgid "%d minutes"
msgstr ""
```
