### ISSUE TITLE
Can't mount filesysytem

### ISSUE THREAD

**Issue by Pshemas** [andyholmes/gnome-shell-extension-gsconnect#313]
I'm having problems with "browse files" functionality - when I'm trying to open filesystem of my phone nothing happens.
I've browsed the logs and I see:
JS LOG: [gsconnect@andyholmes.github.io]: Device received: {"id":1541508062192,"type":"kdeconnect.sftp","body":{"ip":"192.168.0.28","port":1741,"user":"kdeconnect","password":"somepassword","path":"/storage/emulated/0","multiPaths":["/storage/emulated/0","/storage/emulated/0/DCIM/Camera"],"pathNames":["Wszystkie pliki","Zdjęcia z aparatu"]}}
JS LOG: Received from 'motorola'
JS LOG: [gsconnect@andyholmes.github.io]: SFTP: handlePacket()
JS LOG: [gsconnect@andyholmes.github.io]: SFTP: _prepare()
JS LOG: Sftp: Unable to negotiate with 192.168.0.28 port 1741: no matching host key type found. Their offer: ssh-rsa

I use GSConnect v12 on Opensuse Leap 15 (v13 is not an option due to GNOME 3.28 requirement).

**Comment by ferdnyc** [comment]
Can you post the output of `ls /etc/ssh/` on that system please? It sounds like you may need to generate SSH host keys for your machine.

**Comment by ferdnyc** [comment]
Sorry, ignore my previous comment, I missed the "v12" part of your report.

I know there's been some realignment of GSConnect's ssh encryption support in recent releases, and in the KDE Connect app as well, but I'm not sure what the status is with v12 specifically. Perhaps @andyholmes can provide more information?

(@andyholmes : For the record, after testing with v12 I'm seeing the same thing, I hadn't tried filesystem access recently. Is this just a known issue with v12 and recent KDE Connect / Android versions?)

**Comment by andyholmes** [comment]
> For the record, after testing with v12 I'm seeing the same thing, I hadn't tried filesystem access recently. Is this just a known issue with v12 and recent KDE Connect / Android versions?

Yes, the most recent Android app (v1.10) dropped DSA encryption support, and v12 didn't allow for RSA encryption because it wasn't an option when that was released.

> I use GSConnect v12 on Opensuse Leap 15 (v13 is not an option due to GNOME 3.28 requirement).

@Pshemas v13+ *may* actually work on `gnome-shell >= 3.26`, I've just never tested it. 3.26 was the first version shipping with modern JavaScript that we now heavily rely on. It's just that 3.28 and it's related GJS version are the only versions I make sure I don't use features that came after.

The other alternative, if you won't be upgrading anyways, is to remove this line entirely:

https://github.com/andyholmes/gnome-shell-extension-gsconnect/blob/4098a4536439cea4f78c67ba12780ed8866f735d/src/service/plugins/sftp.js#L122

That line was added to solve the upstream bug [#351725](https://bugs.kde.org/show_bug.cgi?id=351725).

**Comment by Pshemas** [comment]
thx for looking into this.
I've tried replacing v12 with v13 but I might have done it the wrong way. I've deleted the plugin from the ~./local/share.... folder and extracted v13 there. The plugin starts but I get some sort of message about "address being in use" (I get that in Polish so I have no clue how it looks in English).
Also with v12 I've got the icon in the top bar - with v13 I can't see it. 
When I run gjs deamon.js I see:

> Gjs-Message: JS WARNING: [daemon.js 802]: reference to undefined property "_devices"
> 
> (org.gnome.Shell.Extensions.GSConnect:24532): Gjs-WARNING **: JS ERROR: TypeError: this._devices is undefined
> vfunc_dbus_unregister@daemon.js:802:1
> _init@daemon.js:97:9
> @daemon.js:881:

Will try v12 modification you've mentioned. But any suggestion howto make current version work on 3.26 are greatly appreciated.

**Comment by Pshemas** [comment]
ok, so now my Gsconnect is almost completely broken. Removed the files from ./local/share... and installed v12 again, but now the paired devices are not showing on the list and on top of that after toggling displaying icons in the top bar nothing happens. OUch! 
What should I do to completely purge it and start from clean slate?

**Comment by andyholmes** [comment]
Aha, there's a little note about it way [at the bottom of the Help page](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Help#how-can-i-reset-all-settings).

Basically, you'll want to disable the extension (eg. in GNOME Tweaks) and then:

    ~/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io
    dconf reset -f /org/gnome/shell/extensions/gsconnect/
    rm -rf ~/.cache/gsconnect
    rm -rf ~/.config/gsconnect

After that you should restart Gnome Shell so it registers the removal for sure. If you want to give a newer version a second shot, you should start with [v15](https://github.com/andyholmes/gnome-shell-extension-gsconnect/releases/latest). Just as a guess, I think it *should* work, but it's hard to tell from the log you posted if that was an upgrade problem or an incompatibility.

Do be aware that some of UI has changed, so unpaired and offline devices will only appear in the Settings window, and connection/reconnection is automatic now. So devices will automatically appear when they're paired and connected.

**Comment by shemgp** [comment]
On v15 and KDE Connect 1.10 here from Playstore and I can't seem to mount.  How do I see the logs?

**Comment by andyholmes** [comment]
There are some unfinished notes on getting logs in the [Debugging](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Debugging) page. Remember to manually turn of debugging when you are finished, this will quickly fill up your logs and include private information.

One thing worth trying is to force-stop the Android app and reconnect. Sometimes the SFTP server on Android will fail to stop between connections.

**Comment by andyholmes** [comment]
Hi, there have been two releases since the last activity on this bug, and I believe it mostly applies to <= v12. Please re-open if the issue persists with a current version of GSConnect.
