### ISSUE TITLE
New icon names

### ISSUE THREAD

**Issue by varlesh** [andyholmes/gnome-shell-extension-gsconnect#32]
https://github.com/Bajoja/indicator-kdeconnect/commit/ab39a753252d8a4597cbb2d804e651025f2d84f9

https://cgit.kde.org/kdeconnect-kde.git/commit/icon/sc-status-smartphoneconnected.svg?id=e72bbfe1d2efcc7dcc31408bf59af69408426430

**Comment by varlesh** [comment]
desktop-trusted, desktop-connected, desktop-disconnected need rename too (for standard) on Papirus

**Comment by varlesh** [comment]
Tree on KDE repo:
https://cgit.kde.org/kdeconnect-kde.git/tree/icon

**Comment by varlesh** [comment]
icons already renamed on Papirus

**Comment by andyholmes** [comment]
Thanks for remembering me ;)
