### ISSUE TITLE
issue after unpairing

### ISSUE THREAD

**Issue by abuakram** [andyholmes/gnome-shell-extension-gsconnect#321]
Hi...
First of all... this is a great extension... 
I have unpaired my connected devices (Ubuntu 18.04), but am still getting notifications from my whatsapp account... This is weird... 

What do I have to do?

**Comment by andyholmes** [comment]
That seems pretty strange. If a device is unpaired it will discard all incoming traffic except for pair requests. Are you sure you aren't also `kdeconnectd`?

**Comment by abuakram** [comment]
no... just the gnome-extension

**Comment by andyholmes** [comment]
And it's also unpaired in the Android app? If so, it can't be coming from GSConnect.

If it's unpaired in the Android app, the app won't send any data. If an unpaired device sends GSConnect data it will be ignored and respond by unpairing again.

https://github.com/andyholmes/gnome-shell-extension-gsconnect/blob/7aae6ca13330807c9e32b1fa7b49ca7d7acc1f97/src/service/device.js#L357-L370

**Comment by abuakram** [comment]
hi andy...

Android notifications continue popping on my desktop eventhough I *unpaired* the device, and turned the extension off. 
But as soon I reboot the extension turns on by itself, and the unpaired device shows up...

What informations do you need from me to look in this issue?

**Comment by abuakram** [comment]
I went and removed gsconnect-extension... and removed kdeconnect ...
but the notification popups from my device continues....
That is a security issue

**Comment by andyholmes** [comment]
Extensions don't have a way of turning themselves on or off, so probably you have installed it twice or are also running KDE Connect.

First, check that it's actually unpaired:

![screenshot from 2018-11-13 17-39-23](https://user-images.githubusercontent.com/1265208/48454401-f142bd80-e76b-11e8-8d12-08783a6ca028.png)
![screenshot_20181113-173854](https://user-images.githubusercontent.com/1265208/48454421-00297000-e76c-11e8-95fa-1ddc66a85fe2.png)
![screenshot_20181113-173919](https://user-images.githubusercontent.com/1265208/48454428-03246080-e76c-11e8-835c-3d897592a34c.png)

Check that `kdeconnectd` is not running (should return nothing):

    $ pidof kdeconnectd

Check that GSConnect is only installed in one location:

    $ ls ~/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io
    extension.js  _gsconnect.js  locale  metadata.json  nautilus-gsconnect.py  org.gnome.Shell.Extensions.GSConnect.gresource  prefs.js  schemas  service  shell  stylesheet.css

    $ ls /usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io
    ls: cannot access '/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io': No such file or directory

**Comment by abuakram** [comment]
I turned gsconnect off through the app tweaks... but as you said it can't be turned off completely.
I did earlier the steps you mentioned, and I am free now of disturbing notifications...
What annoyed me, that although I unpaired both devices (the mobile in ubuntu & ubuntu in mobile) notifications kept flowing in... On my mobile when opening kdeConnect there is no device connected, but still notifications show up...

Anyhow, it is solved now... I am definetly going to install it again, a very useful app.

Thanks for your response...
