### ISSUE TITLE
improve error message "operation canceled"

### ISSUE THREAD

**Issue by FlorianLudwig** [andyholmes/gnome-shell-extension-gsconnect#326]
I received a gnome notification "operation canceled" from GSConnect.

I have no idea which operation.

**Comment by andyholmes** [comment]
Sorry, I'm not sure either. "Operation Cancelled" is an [enumerated error in Gio](https://developer.gnome.org/gio/stable/gio-GIOError.html#G-IO-ERROR-CANCELLED:CAPS). Can you tell me what is not working in GSConnect or what you were doing when it happened?

Are there any further messages in the log from that time?

**Comment by andyholmes** [comment]
If there are no errors in log from that time and nothing is broken, I would just take it as a warning and close it. Operation Cancelled usually just means a call in a thread was cancelled from the main thread.

**Comment by FlorianLudwig** [comment]
I would like to argue that if nothing is broken nothing should be shown to the end-user ;)

**Comment by andyholmes** [comment]
You _could_ mute those errors by commenting out this line:

https://github.com/andyholmes/gnome-shell-extension-gsconnect/blob/2f51511d2392672e4574288231e515c8ebd006b6/src/extension.js#L301

But then you would get no notice if anything went wrong starting the service...

**Comment by FlorianLudwig** [comment]
To be honest my knowledge of gio is rather limited and the inner workings of gsconnect even more so.  Not sure what the right solution is, how to distinguish between different errors.

> Operation Cancelled usually just means a call in a thread was cancelled from the main thread.

Is that something that happens during "normal operations" and is expected behavior?  If so I would expect this to not raise an error. (at least not to the user)

**Comment by andyholmes** [comment]
No errors should happen during normal operation generally. The most likely cause of this would be [gnome-shell's #177](https://gitlab.gnome.org/GNOME/gnome-shell/issues/177) repetitively loading/unloading extensions, but there's not much I can do about that.
