### ISSUE TITLE
First message gray (like unsend)

### ISSUE THREAD

**Issue by Garbulix** [andyholmes/gnome-shell-extension-gsconnect#339]
When I write a message, the first one is marked as gray, like hasn't sent (but it is sent) and next, messages are normal. Why is that? There is a screenshot ("test" message is the first one).
I've installed the newest version of extension from **extensions.gnome.org**.

![test](https://user-images.githubusercontent.com/22769121/48623548-4409b880-e9aa-11e8-9a5c-414742fc58fd.jpg)

Sorry for my english. Thank you for help.

**Comment by andyholmes** [comment]
Yes, this was an idea that didn't work.

Basically when we send a SMS we guess "message number + 1", then wait for Android to tell us it was sent and make it not-gray. Unfortunately the real message number is not always right, so we think it has never been sent.

The new message UI fixes this. If you want to try it out, you can use this Zip:

[gsconnect.andyholmes.github.io.zip](https://github.com/andyholmes/gnome-shell-extension-gsconnect/files/2588869/gsconnect.andyholmes.github.io.zip)

You can install it using these instructions: [Installing from Zip](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Installation#install-from-zip)
