### ISSUE TITLE
Annoying notifications asking to install packages

### ISSUE THREAD

**Issue by ricvelozo** [andyholmes/gnome-shell-extension-gsconnect#344]
**Describe the bug**
Annoying notifications asking to install packages for extra features, popping every time I boot.

**To Reproduce**
1. Boot the OS'
2. Get notification

**Expected behavior**
Don't send notifications at all, maybe?

**System Details (please complete the following information):**
 - GSConnect version: 15
 - Installed from: extensions.gnome.org
 - GNOME/Shell version: 3.30.2
 - Distro/Release: Fedora 29

**Comment by andyholmes** [comment]
Could you tell me if there are any dependencies you don't have installed or use? For example if you use Wayland and don't use the Mousepad plugin?

**Comment by ricvelozo** [comment]
On X.org, Mousepad and Share plugins disabled. Just Contacts and Sound Effects enabled.

![captura de tela de 2018-11-21 18-51-02](https://user-images.githubusercontent.com/1834764/48867846-b4577600-edbe-11e8-9128-6d4eeb74b3c4.png)

**Comment by andyholmes** [comment]
Okay, I think I can improve this before v17. 

Usually these happen when plugins loads and realizes it's missing something. It's just awkward because now all plugins are loaded by default, so that's probably when it happens. I'll have look a bit later.

**Comment by andyholmes** [comment]
All fixed. As per the commit message:

> All DependencyError notifications are now removed. Any missing software
> or disabled functionality will now have to be identified by the user,
> through system logs if necessary.
