### ISSUE TITLE
Contacts with non-numeric address/phone confuse Messaging app

### ISSUE THREAD

**Issue by sredman** [andyholmes/gnome-shell-extension-gsconnect#355]
**Describe the bug**
I have a conversation in the SMS interface which properly shows the correct preview text (in the left panel), but clicking the contact pulls up the wrong conversation

**To Reproduce**
1. Open SMS interface
2. Click on this particular contact (others that I have clicked seem okay)
3. Wrong conversation is opened

**Expected behavior**
The conversation history for this contact should be opened

**Screenshots**
Here is a screen shot of the SMS GUI - Notice that the preview text under the selected contact does not match the actually-shown message:
![messagemismatch](https://user-images.githubusercontent.com/1900703/48916811-148efc00-ee41-11e8-9de6-b9949a3a0e4f.png)

Here is the screenshot of the same conversation from the phone:
![mismatchoriginal](https://user-images.githubusercontent.com/1900703/48916821-1658bf80-ee41-11e8-92ae-dcb892068e1f.png)

**Debug output**
I have debug output but I do not see anything relevant-looking

**System Details (please complete the following information):**
 - GSConnect version: 16 (git commit tag cdc4015b7af613327f0add7bef80fb748b162ba3)
   - Installed from: Github
 - GNOME/Shell version: Plasma (gjs 1.52.3)
 - Distro/Release: Fedora 28

**GSConnect environment (if applicable):**
 - Paired Device(s): OnePlus 6T
 - KDE Connect app version: 1.10 (master build)
 - Plugin(s): SMS

**Comment by zabi94** [comment]
I have the same problem, all conversations seem to be affected, in my case. The content shown is the one from the least recent conversation (at the bottom of the list)

Ubuntu 18.04 - GSConnect 16 installed from Github
OnePlus6 - KDE Connect app v1.10

**Comment by andyholmes** [comment]
Do you also have conversations with contacts whose address/phone number is non-numeric (eg. an e-mail address?).

**Comment by andyholmes** [comment]
Here's an updated Zip including the fix from bef2fec:

[gsconnect@andyholmes.github.io.zip](https://github.com/andyholmes/gnome-shell-extension-gsconnect/files/2621757/gsconnect.andyholmes.github.io.zip)

**Comment by andyholmes** [comment]
Sorry, sorry. Properly fixed in cc219a4:

[gsconnect@andyholmes.github.io.zip](https://github.com/andyholmes/gnome-shell-extension-gsconnect/files/2622291/gsconnect.andyholmes.github.io.zip)

**Comment by shoetten** [comment]
Thank you for a great app! My friends are happy, that i'm finally replying to sms again ;)
