### ISSUE TITLE
Logs getting hammered with old Mconnect extension

### ISSUE THREAD

**Issue by RobertZito** [andyholmes/gnome-shell-extension-gsconnect#365]
Your work is astounding I loved Mconnect but love GSconnect so much more. I made the switch pretty easy between mconnect to gsconnect. I uninstalled Mconnect but now my logs are being flooded with dbus-daemon: RuntimeError: object at 0x7f5670502e60 of type MConnectShareExtension is not initialized 
dbus-daemon: Failed to open file “/home/rzito/.local/share/gnome-shell/extensions/mconnect@andyholmes.github.io/share.js”: No such file or directory

How can I correct this in Ubuntu 18.04

Thanks

**Comment by andyholmes** [comment]
Hi, thanks for kind words! Probably just the old Nautilus extension has been left over by accident. You should be able to fix this just removing that file and restarting Nautilus:

```sh
$ rm -f ~/.local/share/nautilus-python/extensions/nautilus-send-mconnect.py
$ nautilus -q
```

That will close any open Nautilus windows you have, so be prepared for that.

**Comment by RobertZito** [comment]
Thank you, logs cleared up, no more Mconnect messages
