### ISSUE TITLE
[REQUEST] Hide icon in status menu

### ISSUE THREAD

**Issue by arngo** [andyholmes/gnome-shell-extension-gsconnect#37]
I'd like there to be an option to hide the icon in the status menu. Currently it doesn't indicate anything useful.

![image](https://user-images.githubusercontent.com/27396817/35486782-0634c6ac-0441-11e8-86d3-e5339f8bbf0f.png)

**Comment by andyholmes** [comment]
Probably I won't implement this. Currently the icon indicates the service is active, just like Night Light, although it rarely seems to stop running (fortunately). In future it will probably be used for other service statuses like 'Do Not Disturb'. Sorry about that.

**Comment by beanaroo** [comment]
If anybody else came looking for a way to clean up the status area, commenting out the below line removes the extra icon.
```
userMenuTray.insert_child_at_index(this.indicators, 0);
```
The status menu entry is still present, indicating the service is active and providing a link to settings.

@andyholmes if you're open to the idea, I can submit a PR for an option. I don't believe the icon is necessary when "Show Indicators" is enabled.

**Comment by andyholmes** [comment]
I won't be adding an option to remove this icon, sorry. The status icon in question represents the status of the GSConnect service (which is a separate process), like other desktop services, and is unrelated to the status of particular devices. Currently it shows that the service is running and active, and in future will be used to indicate other states of the service.
