### ISSUE TITLE
Addesss already in use but no KDE

### ISSUE THREAD

**Issue by Jau-Al** [andyholmes/gnome-shell-extension-gsconnect#371]
Hello, 
The extension tells me the address is already in use but There is no KDE connect on this machine. 

The weird part is that the phone sees the desktop computer and I can remote control the mouse cursor.
But the desktop refuses to see the mobile. Shouldn't it be the opposite ?!

![capture d ecran de 2018-12-01 17-21-36](https://user-images.githubusercontent.com/15030964/49330363-c3dc7900-f58d-11e8-86c9-031176029773.png)

Thanks

**Comment by andyholmes** [comment]
Hi, can you please follow the steps from the [Help](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Help#network-error) page and post the output?

    $ pidof kdeconnectd
    $ lsof -i UDP:1716

If you have to kill `kdeconnectd` you will have to restart the service afterwards.

**Comment by Jau-Al** [comment]
Hi, 
Thanks you. You were right. It's here. 
I don't understand. KDE environment has never been installed on this machine. Not even kdebase-runtime ! 
How is this possible ? Do you know a package that could have brought this with it's own packages ?

**Comment by andyholmes** [comment]
I don't think anything else depends on it. It's possible in the past you installed [indicator-kdeconnect](https://github.com/Bajoja/indicator-kdeconnect/issues) and just forgot? Probably nothing to worry about :stuck_out_tongue:
