### ISSUE TITLE
transfer failed to samsung s9

### ISSUE THREAD

**Issue by edencorbin** [andyholmes/gnome-shell-extension-gsconnect#372]
**Describe the bug**
GSConnect share file fails to transfer, no information on why.

**To Reproduce**
1. GSConnect drop down, 
2. select Samsung S9, 
3. click share, 
4. select a file. 

It says transfering then after time says transfer failed (~4mb mp3). No data on what/why it failed.

**Expected behavior**
Should transfer the file, although it would be great to also know/select where?

**Screenshots**
not required

**Debug output**
I can test follow up here if needed

```

```

**System Details (please complete the following information):**
- ubuntu 18.04
- gs connect shell extension and sudo apt install gnome-shell-extensions installation.

**GSConnect environment (if applicable):**
 - Paired Device(s): [e.g. Samsung S9]

**Comment by andyholmes** [comment]
Hi, currently the version of GSConnect in Ubuntu repositories is quite old (v11), while v17 was released a few days ago.

You can request a version bump on Launchpad for GSConnect, but until the Ubuntu maintainers have time to update the package I would recommend you uninstall the system package and install from [extensions.gnome.org](https://extensions.gnome.org/extension/1319/gsconnect/).

    $ sudo apt-get remove gnome-shell-extension-gsconnect

You will probably have to resart GNOME Shell after this.

**Comment by edencorbin** [comment]
This worked for me on a different install (going to test again on original), I thiink I didn't notice the phone needed to provide a permission after starting the transfer.
