### ISSUE TITLE
Nautilus Extension/Remote Filesystem entries are confusing

### ISSUE THREAD

**Issue by g3blv** [andyholmes/gnome-shell-extension-gsconnect#375]
I have installed KDE Connect on my phone and the GSConnect extension on my computer where I'm running Ubuntu 18.04 with Gnome 3.28. I'm running the "standard" Gnome rather than the Ubuntu DE.
I've got **Filesystem expose** ticked on the Plugin settings on the phone (everything is ticked besides **Receive notifications**). I've given KDE Connect access to the files on the phone.

On the computer I have all  Plugins ticked and I have installed `python-nautilus` and `gir1.2-nautilus-3.0`.

I've manged to share a file from the phone to the computer and it works. So I guess the phone has connected fine to the computer. 

**How To Reproduce**
1. Open GSConnect
2. Select my phone
3. Clicking the 3 dots in the top right corner opens a menu where I can see Messaging, Locate, Share, Encrypt Info and Unpair but there is no item for Mount.

Is there something I have missed in the setup?

**System Details (please complete the following information):**
 - GSConnect version: 17
   - Installed from: extensions.gnome.org
 - GNOME/Shell version: 3.28]
 - Distro/Release: Ubuntu 18.04

**GSConnect environment (if applicable):**
 - Paired Device(s): OnePlus 2
 - KDE Connect app version: 1.10.1

**Comment by g3blv** [comment]
Thanks that worked. Do I still need `python-nautilus` and `gir1.2-nautilus-3.0`?

**Comment by andyholmes** [comment]
Yeah, sorry the wording is confusing (right now) because "Files" is the user-facing name of Nautilus.

If you have python-nautilus installed, you can send files (in Files :wink:) to devices from the context menu (right-click) in Nautilus.

**Comment by andyholmes** [comment]
Fixed in e749bd9

**Comment by ferdnyc** [comment]
> Yeah, sorry the wording is confusing (right now) because "Files" is the user-facing name of Nautilus.

Because while the package names don't match up with the displayed names anymore, it makes things "less confusing" for users. Obviously: :unamused: 

![image](https://user-images.githubusercontent.com/538020/49847444-21e33a80-fd9e-11e8-99ff-dbf00db6bda3.png)

(That's Nemo and Nautilus, installed side-by-side on Fedora 29. The low-res Nautilus icon is just gravy.)

I'm surprised they haven't renamed Gnome Shell to "Screen" yet.
