### ISSUE TITLE
Can't send SMS from computer

### ISSUE THREAD

**Issue by gautierlabarre** [andyholmes/gnome-shell-extension-gsconnect#378]
Hello, i love this app, so i post my bug instead of waiting for someone else to have it : 

**Describe the bug**
The window to display contact and message is not showing up on my screen (so i can't send sms from my computer)

**To Reproduce**
1. Click on 'message' (messagerie in french)
2. Nothing happens

**Expected behavior**
The list of contact and messages should be displayed.

**Debug output**

I have to different stacktrace for you :
**First stacktrace : Displayed multiple times**

```
JS ERROR: TypeError: row.contact.name is undefined
_filter@/home/gautier/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/ui/contacts.js:351:1
add_contact_number@/home/gautier/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/ui/contacts.js:401:9
add_contact@/home/gautier/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/ui/contacts.js:386:20
_populate@/home/gautier/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/ui/contacts.js:380:13
_init@/home/gautier/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/ui/contacts.js:279:9
_init@/home/gautier/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/ui/messaging.js:723:29
get window@/home/gautier/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/sms.js:219:28
sms@/home/gautier/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/sms.js:455:9
_activateAction@/home/gautier/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/base.js:71:17
@/home/gautier/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:839:2
```

**below this,  i have a json showing my messages and then a second list of errors :**
```
JS ERROR: Error: Invalid value 'undefined' for property label in object initializer.
_init/Gtk.Widget.prototype._init@resource:///org/gnome/gjs/modules/overrides/Gtk.js:60:9
_init@/home/gautier/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/ui/messaging.js:233:20
_populateConversations@/home/gautier/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/ui/messaging.js:876:17
_handleMessages@/home/gautier/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/sms.js:341:17
async*handlePacket@/home/gautier/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/sms.js:231:13
receivePacket@/home/gautier/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/device.js:381:21
receive/<@/home/gautier/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/core.js:405:25
@/home/gautier/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:839:2
```

**System Details (please complete the following information):**
 - GSConnect version: 17
   - Installed from: extensions.gnome.org
 - GNOME/Shell version: 3.30.1
 - Distro/Release: Ubuntu 18.10

**GSConnect environment (if applicable):**
 - Paired Device(s): Oneplus 6
 - KDE Connect app version: latest from 29  november

**Additional context**
Yesterday it worked and i upgraded nothing but chrome. I do have notifications from Texts.
I tried : 
Reinstalling GSConnect, Empty the cache, restart pairing device, ...

**Comment by andyholmes** [comment]
Hi and thanks for the report with thorough information.

It seems like this might be related to a bug that was reported to me in the matrix channel (so no GitHub issue). With that user's help, I believe the problem was fixed in master, but unfortunately my laptop died and while I wait for a new one to be delivered there won't an official release.

If you're up to it, you can try building from master which is really easy as long as you have `git` and `meson` installed:

    sudo apt install git meson
    git clone https://github.com/andyholmes/gnome-shell-extension-gsconnect.git
    meson gnome-shell-extension-gsconnect/ _build
    ninja -C _build install-zip

I managed to get a number of bugs related to contacts fixed before my laptop died, and there won't be anything unexpected or unstable in `master` right now.

**Comment by andyholmes** [comment]
> Short story is : all the messages i write on gsconnect are displayed properly on my phone (i use textra) but they are never received).

Hmm, yep sounds like a different issue :) When you get the chance, two things that might help: check that you're getting the confirmation of "sent", so the message should "unfade" meaning it entered your SMS history. Second is you may need a logcat from Android for this, but let me know in you bug report when you get time ;)

I know another user who is using Textra, so this should be working.
