### ISSUE TITLE
Update suggestions for wiki: Install instructions and FAQ

### ISSUE THREAD

**Issue by psiphi75** [andyholmes/gnome-shell-extension-gsconnect#38]
It took me a while to figure out how to install the latest stable release.   I have created a PR to improve this on the main README.md, but it would be good to have step-by-step installation and pairing instructions added as well.  I suggest the install instructions are near the top of of the wiki content sidebar.

My install instruction and FAQ suggestions are below.

**==== START: Installation Instructions ====**
**Installation and Pairing Instructions**
The following steps will guide you on how to install GSConnect for Gnome.  This Gnome extension has not yet been published as an extension and requires manual installation.
1) Download the [latest stable release](https://github.com/andyholmes/gnome-shell-extension-gsconnect/releases).
2) Follow the [standard install instructions](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Installation#installing-from-zip). Once installed:
 * Gnome may ask you to restart Nautilus.
 * In the Gnome system menu you will see a new "Mobile Devices" menu.  
3) Install the KDE Connect app from [Google Play](https://play.google.com/store/apps/details?id=org.kde.kdeconnect_tp) or [F-Droid](https://f-droid.org/packages/org.kde.kdeconnect_tp/).
4) Open the KDE Connect app and you should see your "GSConnect" under "Available Devices".  Tap on this and the tap "Request Pairing".
5) A notification will appear in Gnome and request that you accept the pairing, click "Accept".

Your mobile device and your Gnome desktop are now paired and will remain paired when they are on the same network.  You can now [configure](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Preferences) your device.

If you have any issues see the [Frequently Asked Questions](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Frequently-Asked-Questions).
**==== END ====**

**==== START: Suggested Update to FAQ ====**
Why don't I see the "Mobile Devices" menu in the Gnome System menu?

Make sure the Gnome extension has not been disabled using the "Gnome Tweak Tool" or at https://extensions.gnome.org/local/.
**==== END ====**

**Comment by Procerus** [comment]
I followed the instructions above, when I went to Gnome Tweak tool or the .org it says its out dated, am I missing something? 
This is the error
Error: can't convert default_value to an integer

Stack trace:
  @resource:///org/gnome/gjs/modules/overrides/GObject.js:295

**Comment by andyholmes** [comment]
Thanks for taking an interest in this, sorry I haven't acknowledged this issue. I'm really involved with a rewrite of several parts of GSConnect for v10, but I'll merge your pull request #36 now. I'll also open up the wiki to edits (as long as it doesn't get mangled by bots) so you can edit the Wiki if you like. Otherwise I'll get back to this when I can.

**Comment by psiphi75** [comment]
Done.  Wiki has been updated.  Thanks.
