### ISSUE TITLE
With the possibility of making a cast it would be a complete extension

### ISSUE THREAD

**Issue by TeoColuccio** [andyholmes/gnome-shell-extension-gsconnect#382]
It would be nice to be able to cast images, videos or screen from the smartphone to the PC

**Comment by andyholmes** [comment]
As described in the Issue Template, any feature requests that require protocol changes or support in the Android app should be filed upstream with KDE Connect.

You can open a feature request using the [KDE bug tracker](https://bugs.kde.org/enter_bug.cgi?product=kdeconnect) or get involved using [Phabricator](https://phabricator.kde.org/project/view/159/).
