### ISSUE TITLE
Can enable battery sharing for device without battery

### ISSUE THREAD

**Issue by rugk** [andyholmes/gnome-shell-extension-gsconnect#385]
**Describe the bug**
After https://github.com/andyholmes/gnome-shell-extension-gsconnect/issues/274 is fixed, I now have the "contrary" bug.

**To Reproduce**
Two GSConnect devices. DeviceB has a battery, DeviceA has not.

1. On DeviceB, in menu for DeviceA, you have a "battery" switch that I can enable. (I assume this is correct as it enables sharing battery info _from_ device B to A)
2. On DeviceA, in menu for DeviceB, you have a "battery" switch that I can enable.

**Expected behavior**
AFAIK the DeviceA (point 2 above) should not have that menu, as it has no battery.  

That is also correctly detected in the gnome-control-center:
![image](https://user-images.githubusercontent.com/11966684/49686590-ed018a00-faf6-11e8-8635-2e3931a4cc59.png)

**Debug output**

could not see any messages when toggling the "battery switch".

**System Details (please complete the following information):**
 - GSConnect version: 17
   - Installed from: extensions.gnome.org
 - GNOME/Shell version: 3.30
 - Distro/Release: Fedora 29
(both devices)

**Additional context**
On device B, in the GNOME menu deviceA is shown with an "unknown battery icon", i.e. a question mark inside of the battery icon.

When disabling both battery settings, the status does not seem to get updated, and both devices continue to show the respective battery icons.

**Comment by ferdnyc** [comment]
@rugk :
It seems that part of the detection process involves querying `/sys/class/dmi/id/chassis_type` (an integer), and determining whether the system is a laptop or desktop — laptops _may_ have a battery, desktops are shortcut-exempted. Only a `chassis_type` in `[8, 9, 10, 14]` will be considered laptops. (My desktop is a `6`.)

https://github.com/andyholmes/gnome-shell-extension-gsconnect/blob/1859249acf8a30455e39ed1720be32d2ce4ac39f/src/service/daemon.js#L162-L173

So, can you also provide the output of `cat /sys/class/dmi/id/chassis_type` on DeviceA?

**Comment by rugk** [comment]
DeviceA is a desktop PC. 

```sh
$ cat /sys/class/dmi/id/chassis_type                    
3
$ cat /sys/class/dmi/id/chassis_vendor
To Be Filled By O.E.M.
```

![image](https://user-images.githubusercontent.com/11966684/49699662-3b388b00-fbd4-11e8-873e-1283e4bb6283.png)

![image](https://user-images.githubusercontent.com/11966684/49699672-658a4880-fbd4-11e8-9804-0f4321e1820a.png)

**Comment by ferdnyc** [comment]
@rugk : Hmmm... thanks. That is very curious.

I'll try to look at the code some more, see if I can figure out where it might be going wrong. Unfortunately, I'm somewhat hampered by the fact that I don't have any device available to me that **_does_** have a battery, so I can't test how the detection process would proceed to reach the conclusion that a battery is present. This may have to wait for @andyholmes to get back up and running with his new laptop.

**Comment by andyholmes** [comment]
Yay, new laptop. I've got a bunch of stuff I saved from my old laptop to sort through, but 5e25de6 should at least remove the option for non-supporting devices. You should be sure to disable the option before upgrading and restarting the service.
