### ISSUE TITLE
GSConnect does not find tablet

### ISSUE THREAD

**Issue by GlennStrazds** [andyholmes/gnome-shell-extension-gsconnect#387]
**Describe the bug**

your app is not discovering my device Samsung tab a tablet

problem appears to be in the debugger

no bluetooth on my notebook
says can't find "No such file or directory"

**Expected behavior**

expect it to work? or work at it till it does work

**Screenshots**
If applicable, add screenshots to help explain your problem. You can drag-and-drop or cut-and-paste images directly into this edit window, to include them in your report.

**Debug output**
If you have been able to reproduce the problem with debugging enabled (see [instructions in the wiki](wiki/Debugging)), paste any log messages related to this issue between the two ``` lines below.
 samsung tab a 
```
WARNING: ValueError: Namespace Folks not available
WARNING: GSConnect: Bluetooth Error: Error calling StartServiceByName for org.bluez: GDBus.Error:org.freedesktop.DBus.Error.TimedOut: Failed to activate service 'org.bluez': timed out (service_start_timeout=25000ms)
WARNING: Gio.IOErrorEnum: Error opening file /home/glenn/.cache/gsconnect/contacts.json: No such file or directory
g_variant_new_string: assertion 'string != NULL' failed
WARNING: ValueError: Namespace Folks not available
WARNING: GSConnect: Bluetooth Error: Error calling StartServiceByName for org.bluez: GDBus.Error:org.freedesktop.DBus.Error.TimedOut: Failed to activate service 'org.bluez': timed out (service_start_timeout=25000ms)
WARNING: Gio.IOErrorEnum: Error opening file /home/glenn/.cache/gsconnect/contacts.json: No such file or directory
g_variant_new_string: assertion 'string != NULL' failed
WARNING: ValueError: Namespace Folks not available
WARNING: GSConnect: Bluetooth Error: Error calling StartServiceByName for org.bluez: GDBus.Error:org.freedesktop.DBus.Error.TimedOut: Failed to activate service 'org.bluez': timed out (service_start_timeout=25000ms)
DEBUG: [lan.js:broadcast:276]: BWARNING: ValueError: Namespace Folks not available
WARNING: GSConnect: Bluetooth Error: Error calling StartServiceByName for org.bluez: GDBus.Error:org.freedesktop.DBus.Error.TimedOut: Failed to activate service 'org.bluez': timed out (service_start_timeout=25000ms)
WARNING: Gio.IOErrorEnum: Error opening file /home/glenn/.cache/gsconnect/contacts.json: No such file or directory
g_variant_new_string: assertion 'string != NULL' failed
WARNING: ValueError: Namespace Folks not available
WARNING: GSConnect: Bluetooth Error: Error calling StartServiceByName for org.bluez: GDBus.Error:org.freedesktop.DBus.Error.TimedOut: Failed to activate service 'org.bluez': timed out (service_start_timeout=25000ms)
WARNING: Gio.IOErrorEnum: Error opening file /home/glenn/.cache/gsconnect/contacts.json: No such file or directory
g_variant_new_string: assertion 'string != NULL' failed
WARNING: ValueError: Namespace Folks not available
WARNING: GSConnect: Bluetooth Error: Error calling StartServiceByName for org.bluez: GDBus.Error:org.freesee abovedesktop.DBus.Error.TimedOut: Failed to activate service 'org.bluez': timed out (service_start_timeout=25000ms)
DEBUG: [lan.js:broadcast:276]: Broadcasting to LAN
DEBUG: [lan.js:broadcast:276]: Broadcasting to LAN
roadcasting to LAN
DEBUs): [e.g. Galaxy Note 8, Pixel 2, Honor 9, ...]G: [lan.js:broadcast:276]: Broadcasting to LAN
```

**System Details (please complete the following information):**
 - GSConnect version: [e.g. 16, 15, ... (displayed in the GSConnect "About" window)]
 i see no about window - latest  

- Installed from: extensions.gnome.org, GitHub Release download,

- GNOME/Shell version: 3.28.2

 - Distro/Release: [e.g. Ubuntu 18.04, 

**GSConnect environment (if applicable):**
 - Paired Device  samsung tab A
 - KDE Connect app version: [e.g. ]
 - Plugin(s): [if the issue only occurs when using certain plugin(s)]

**Additional context**

ked connect is on the tablet
the version with mobility devices in the  main menu
s): [e.g. Galaxy Note 8, Pixel 2, Honor 9, ...]

**Comment by andyholmes** [comment]
Can you try steps 4 & 5 from [Connecting an Android Device](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Help#connecting-an-android-device) in the Wiki and tell me if that helps?

**Comment by GlennStrazds** [comment]
Your comment is not currently available; I tried item #4 and #5 
the android kde app connected devices is blank says no devices
I added the ip for both devices to have the same result - No devices
and the gsconnect app on my notebook also says no devices where I also added the ip for the device 
its blank!

**Comment by andyholmes** [comment]
> An active wireless connection, in infrastructure mode, involves no access point?

Are you sure you are connected on the same network as your tablet? Can you ping the tablet from your computer?

    ping 192.168.x.x

**Comment by GlennStrazds** [comment]
i'm in a Barns and Noble on wifi did a ping from my notebook

glenn@glenn-HP-15-Notebook-PC:~$ ping 10.129.28.129
PING 10.129.28.129 (10.129.28.129) 56(84) bytes of data.
64 bytes from 10.129.28.129: icmp_seq=1 ttl=64 time=1.29 ms
64 bytes from 10.129.28.129: icmp_seq=2 ttl=64 time=9.57 ms
64 bytes from 10.129.28.129: icmp_seq=3 ttl=64 time=4.50 ms
64 bytes from 10.129.28.129: icmp_seq=4 ttl=64 time=1.32 ms
64 bytes from 10.129.28.129: icmp_seq=5 ttl=64 time=1.38 ms
64 bytes from 10.129.28.129: icmp_seq=6 ttl=64 time=1.31 ms
64 bytes from 10.129.28.129: icmp_seq=7 ttl=64 time=17.4 ms
64 bytes from 10.129.28.129: icmp_seq=8 ttl=64 time=1.88 ms
64 bytes from 10.129.28.129: icmp_seq=9 ttl=64 time=1.32 ms
64 bytes from 10.129.28.129: icmp_seq=10 ttl=64 time=1.24 ms
64 bytes from 10.129.28.129: icmp_seq=11 ttl=64 time=7.25 ms
64 bytes froglenn@glenn-HP-15-Notebook-PC:~$ 
m 10.129.28.129: icmp_seq=12 ttl=64 time=1.28 ms
64 bytes from 10.129.28.129: icmp_seq=13 ttl=64 time=1.27 ms
64 bytes from 10.129.28.129: icmp_seq=14 ttl=64 time=1.24 ms
^[64 bytes from 10.129.28.129: icmp_seq=15 ttl=64 time=1.30 ms
64 bytes from 10.129.28.129: icmp_seq=16 ttl=64 time=1.27 ms
64 bytes from 10.129.28.129: icmp_seq=17 ttl=64 time=3.35 ms
64 bytes from 10.129.28.129: icmp_seq=18 ttl=64 time=1.46 ms
64 bytes from 10.129.28.129: icmp_seq=19 ttl=64 time=1.27 ms
64 bytes from 10.129.28.129: icmp_seq=20 ttl=64 time=9.91 ms
64 bytes from 10.129.28.129: icmp_seq=21 ttl=64 time=2.21 ms
64 bytes from 10.129.28.129: icmp_seq=22 ttl=64 time=1.30 ms
64 bytes from 10.129.28.129: icmp_seq=23 ttl=64 time=1.29 ms
64 bytes from 10.129.28.129: icmp_seq=24 ttl=64 time=21.2 ms
^C
--- 10.129.28.129 ping statistics ---
24 packets glenn@glenn-HP-15-Notebook-PC:~$ glenn@glenn-HP-15-Notebook-PC:~$ glenn@glenn-HP-15-Notebook-PC:~$ transmitted, 24 received, 0% packet loss, time 23028ms
rtt min/avg/max/mdev = 1.245/4.041/21.234/5.294 ms

**Comment by andyholmes** [comment]
> 10.129.28.129

This doesn't seem like a standard LAN address

> i'm in a Barns and Noble on wifi did a ping from my notebook

Probably ports 1716-1764 are not open on this public WiFi. These ports are required for KDE Connect to function. You might be able to double-check with `telnet`:

    telnet 10.129.28.129 1716
    Trying 10.129.28.129...
    telnet: Unable to connect to remote host: No route to host

**Comment by GlennStrazds** [comment]
I'm pinging the notebook from the tablet - says destination is unreachable!

**Comment by andyholmes** [comment]
Yep, that's a network problem, nothing wrong with KDE Connect or GSConnect.

**Comment by GlennStrazds** [comment]
yes i typed in ending in .224 from the tablet; the ping is responding with end in .149 destination unreachable.

Ok I will try this elsewhere and report back

**Comment by ferdnyc** [comment]
> > 10.129.28.129
> 
> This doesn't seem like a standard LAN address

The `10.*.*.*` class A network is an unroutable private LAN space, same as the `192.168.*.*` class B. It's typically used for outbound-only local nets sitting behind a NAT router with a single public IP.

Because it's so huge (~ 16.5 million IPs), the `10.x.y.z` space is mostly used in enterprise environments. Whereas `192.168.x.y` (which can only address a paltry 65,000 IPs) is more common in consumer networks. So, yeah, not surprising for a Barnes & Noble WiFi LAN.
