### ISSUE TITLE
Odd interference issue with other equipment

### ISSUE THREAD

**Issue by x52x58** [andyholmes/gnome-shell-extension-gsconnect#392]
Ok, so I've got a really odd issue with the software.  I'm an Industrial Programmer and was at a treatment plant to work on some unrelated system issues.  Here's where it gets odd.  I had installed GSConnect and been using it without any issues for a few weeks prior.  I got on site and connected my laptop (Ubuntu 18.04.1 LTS) to the plant network.  A few minutes later an operator calls me to let me know that several PLC's (Programmable Logic Controllers) had lost communications with the SCADA(HMI) system.  I take a look and find I cannot see them on the network, nor ping them from the system.  Walking out to the offending equipment I find the network modules are locked up in error.  Only by cycling power on each unit locked up fixes the issue.  

Then I find about 10 minutes or so later the same issue happens.  I decide to unplug my laptop just in case it's causing the issue and proceed to reset the equipment again.  Wait about an hour(went to lunch) and decide whatever cause the issue must be cleared, as we had a phone company tech working on the DSL Modem. I figure it's ok to plug my computer back in again.  A few minutes later, boom everything drops again.  

Just by deduction and a good guess I figure it might be GSConnect causing the issue.  Since it presumably does a broadcast across the network and was one of the most recent programs added to my laptop since I had been to this site last. 

I disconnect my laptop again and reset the plant equipment.  I then disable GSConnect and reboot my computer.  Reconnect it to the network and thus no issues.

So yeah, it's a odd probably isolated case issue.  I'm mostly submitting the error report because I'd hate for a similar issue to happen to someone at a larger plant or somewhere with critical equipment. Luckily in my case it was a small plant and could stand to have  equipment shut down and restarted.

**To Reproduce**
1. Connect laptop with GSConnect running
2. Plant PLC's error out
3. Disable GSConnect
4. Reset PLC's and test.
5. PLC's ok.

**Expected behavior**
Connect Laptop with GSConnect enabled and cause PLC network cards to error

**Screenshots**
No information on screen, all issues happen on plant equipment.

**Debug output**
If needed I could probably see about running it on a test rig, I'd rather not take the plant PLC's down again.  They weren't happy with it the last time.
```

```

**System Details (please complete the following information):**
 - GSConnect version: 17
   - Installed from: extensions.gnome.org
 - GNOME/Shell version: 3.28.2
 - Distro/Release: Ubuntu 18.04

**GSConnect environment (if applicable):**
 - Paired Device(s): Samsung Galaxy S9+
 - KDE Connect app version: 1.10
 - Plugin(s): N/A

**Additional context**
Here's links to the type of PLC's and network card in them in case you wanted to know.
PLC:
https://www.automationdirect.com/adc/shopping/catalog/programmable_controllers/directlogic_series_pl
cs_(micro_to_small,_brick_-a-_modular)/directlogic_405_(small_modular_plc)/cpus/d4-454

Network adapter for PLC:
https://www.automationdirect.com/adc/shopping/catalog/programmable_controllers/directlogic_series_plcs_(micro_to_small,_brick_-a-_modular)/directlogic_405_(small_modular_plc)/communications_-a-_networking/h4-ecom100

OK, there you go. I'm thinking it might be something like a brodcast issue or something that the PLC Network cards just don't like.  So it might be nothing that can be done about it.  They're old model PLC's and the newer PLC's that have been installed recently had no issues.

**Comment by andyholmes** [comment]
I've added [mention of it in the Wiki](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Help#interference-with-other-equipment). Since there's not much we can do about this without breaking protocol, I'm going to close this now. Thanks for reporting.
