### ISSUE TITLE
Provide a installation instruction

### ISSUE THREAD

**Issue by Octav14n** [andyholmes/gnome-shell-extension-gsconnect#4]
At the moment you are pointing to a possibility to download a zip file in the "installation" section. There is no mention of what to do with this file (or its content).

I have tried exporting the content to "~/GSConnect@gsconnect.andyholmes.github.io/" but that does not seem to work. (You could also mention that with X11 you can restart gnome-shell by pressing Alt+F2, type "r" and hit enter)

**Comment by andyholmes** [comment]
The contents should be extracted to `~/gsconnect@andyholmes.github.io/` unfortunately Github doesn't allow uploading files with the `@` symbol in them. The easiest way used be to install the ZIP with Gnome Tweaks, but apparently they've removed that option now. I guess that was too advanced for an advanced options application :/

I'll add some instructions to the Install page.

**Comment by andyholmes** [comment]
Some instructions [here](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Installation#installing-from-zip)

**Comment by Octav14n** [comment]
I successfully installed GSConnect (I had no prior version installed). I had to use the `unzip` line without the `o` flag however (only the `d` flag), if I didn't it gave the following error:
```
octavian@octavian-pc:~/Downloads$ unzip gsconnect.andyholmes.github.io.zip -do ~/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io
Archive:  gsconnect.andyholmes.github.io.zip
caution: filename not matched:  /home/octavian/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io
```

If my description above was not understandable. This line worked:
```
unzip gsconnect.andyholmes.github.io.zip -d ~/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io
```

**Comment by andyholmes** [comment]
Ah, unzip is weird and doesn't seem to allow just regular create and overwrite if it exists behaviour. I'll update it so it just prompts the user. Thanks for pointing that out.

**Comment by ferdnyc** [comment]
The problem, I think, is the position of the flags. `-d` takes an argument, so you can't combine it with the `-o` flag; `-do` is literally telling it to extract the zip into a directory named `o`. This:
````
unzip -o gsconnect.andyholmes.github.io.zip -d ~/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io
````
will work fine, and will force the overwrites.

**Comment by andyholmes** [comment]
@ferdnyc Ah cool, I've updated the Wiki, thanks.
