### ISSUE TITLE
v18 release notes & SMS legacy info

### ISSUE THREAD

**Issue by ferdnyc** [andyholmes/gnome-shell-extension-gsconnect#404]
I was just thinking, given that :
>* Legacy SMS UI
>
>    Since many users have reported their devices do not (yet) support SMS history, a simple legacy UI has been added until these problems can be fixed. Currently this must be enabled manually with the command:
`dconf write /org/gnome/shell/extensions/gsconnect/device/<device-id>/plugin/sms/legacy true`

...it might be good to mention something like, "A list of (valid/configured/active)? `<device-id>`s can be retrieved with the command: `dconf read /org/gnome/shell/extensions/gsconnect/devices`".

**Comment by andyholmes** [comment]
Good idea, all done. I'm not sure if I'll put it in the settings officially, since I consider it to be an ugly workaround. It would be nice not having the extra code floating around if we can get this fixed upstream.

**Comment by ferdnyc** [comment]
Yeah, obviously it would be ideal not to have to do it at all — I guess, in terms of exposing it in the UI, it would come down to the question: How likely is it to be fixed upstream, and how soon?

Along similar lines, you mention that Gio support is used iff `sshfs` isn't available — since I can't _remove_ `sshfs` from my machine (I use it for other things) but would be willing to test Gio, is there any way to force its use through a hidden setting or similar? I could check the code, but... **#laaaazy**.

**Comment by andyholmes** [comment]
> How likely is it to be fixed upstream, and how soon?

It's hard to say. One known issue was a discrepancy between `int` and `long` being used for the `thread_id` on some devices. That's been fixed, but it hasn't been released yet, so it's hard to say how many people will have these issues solved.

I think some apps like Signal that use encrypted databases can't be supported, but then it's questionable whether we should be sharing messages in that case anyways. Security and convenience are often mutually-exclusive and that's something users will have to deal with (not to put too fine a point on it).

> is there any way to force its use through a hidden setting or similar?

Probably easiest would just be to change this to return `false`:

https://github.com/andyholmes/gnome-shell-extension-gsconnect/blob/5a16066fba42ba4b2ade850c657dd2e7076b3d79/src/service/plugins/sftp.js#L54-L56

**Comment by ferdnyc** [comment]
> That's been fixed, but it hasn't been released yet, so it's hard to say how many people will have these issues solved.

\*nod* Makes sense. If it does drag on, might make sense to display the device ID string somewhere out of the way, say at the bottom of Device > Advanced. (Or maybe as an addition to the "Encryption Info" popup, to make it even more hidden.) That way it's retrievable on a per-device basis if need be, but still relatively unobtrusive.

> Probably easiest would just be to change this to return `false`

Thanks! I ended up patching in a hidden pref:
```diff
diff --git a/data/org.gnome.Shell.Extensions.GSConnect.gschema.xml b/data/org.gnome.Shell.Extensions.GSConnect.gschema.xml
index 7052443d..37b4deca 100644
--- a/data/org.gnome.Shell.Extensions.GSConnect.gschema.xml
+++ b/data/org.gnome.Shell.Extensions.GSConnect.gschema.xml
@@ -142,7 +142,11 @@
       <default>{}</default>
     </key>
   </schema>
-  <schema id="org.gnome.Shell.Extensions.GSConnect.Plugin.SFTP"/>
+  <schema id="org.gnome.Shell.Extensions.GSConnect.Plugin.SFTP">
+    <key name="disable-sshfs" type="b">
+      <default>false</default>
+    </key>
+  </schema>
   <schema id="org.gnome.Shell.Extensions.GSConnect.Plugin.Share"/>
   <schema id="org.gnome.Shell.Extensions.GSConnect.Plugin.SMS">
     <key name="legacy" type="b">
diff --git a/src/service/plugins/sftp.js b/src/service/plugins/sftp.js
index cd1b2939..f959ff4f 100644
--- a/src/service/plugins/sftp.js
+++ b/src/service/plugins/sftp.js
@@ -52,6 +52,10 @@ var Plugin = GObject.registerClass({
     }
 
     get has_sshfs() {
+        if (this.settings.get_boolean('disable-sshfs')) {
+            return false;
+        }
+
         return GLib.find_program_in_path(gsconnect.metadata.bin.sshfs);
     }
 
-- 
2.20.1
```
A little `dconf write /org/gnome/shell/extensions/gsconnect/device/<id>/plugin/sftp/disable-sshfs true` and it's off to the races.

**Comment by ferdnyc** [comment]
P.S> That change is also the branch `sshfs-pref` in [my fork](https://github.com/ferdnyc/gnome-shell-extension-gsconnect/).

**Comment by andyholmes** [comment]
Alright, added some notes here and there about legacy SMS, so I'm going to close this one up.
