### ISSUE TITLE
No localizations with v18

### ISSUE THREAD

**Issue by DeadMetaler** [andyholmes/gnome-shell-extension-gsconnect#405]
**Describe the bug**
No any localization with zip an git installing v18. 

Found some difference with **zh.po** file and  **zh_CN** string in LINGUAS file.

**Comment by ferdnyc** [comment]
Actually, looking at the [release zip file](https://github.com/andyholmes/gnome-shell-extension-gsconnect/releases/download/v18/gsconnect.andyholmes.github.io.zip), it seems like the translations may have been left out. I don't see a `locale` dir at all.

**Comment by andyholmes** [comment]
Ah great. I guess we're bumping to v19 :disappointed:

**Comment by andyholmes** [comment]
v19 released, should fix this.

**Comment by andyholmes** [comment]
@DeadMetaler I see you signed up for Crowdin. Could you try updating the translation so I can see how if it works well? There are still some issues with some languages, but it mostly seems to work okay.

**Comment by andyholmes** [comment]
This seems to work okay for Belarusian, but for most languages Crowdin seems to totally thrash the `po` files. It's been removing copyright information for translators, modifying plural forms, erasing fuzzy matches completely and won't recognize `sr@latin` which is the standard for GNOME projects.

I'm still emailing with tech support, but I may have to pass on Crowdin if they can't help me fix this stuff.

**Comment by ferdnyc** [comment]
As another possibility if Crowdin doesn't work out, [OpenShot](http://github.com/OpenShot/openshot-qt) uses Ubuntu's Launchpad [translations service](https://translations.launchpad.net/openshot), which is pretty explicitly gettext-friendly, and definitely has no issues with Serbian Latin (`sr@latin`) or the like. As an Ubuntu package, GSConnect would be eligible to crowdsource translations through [its launchpad project](https://translations.launchpad.net/ubuntu/+source/gnome-shell-extension-gsconnect).

(In fact, OpenShot converts to and from gettext in order to use Launchpad Translations, even though it's a Qt application and the final translation format is QTranslator-compatible .qm files.)

**Comment by ferdnyc** [comment]
And now that it comes up, I'm suddenly surprised GitHub never built a translations service/module.

**Comment by andyholmes** [comment]
Hmm, well it might not be hopeless yet. I'd still like to sort these things out before I commit, but Crowdin is really bending over backwards for me and answering my e-mails *really* fast.

> It seems there is no solution for now but how can we leave you without a surprise on Christmas? :) Asking developers to customize the exported for your project, so we'll export languages inside PO files exactly the same as you've defined in languages mapping for GitHub integration. Will keep you updated!

One of them even signed up as a translator and fixed the broken plurals in three of the translations 😳. I might actually have to write a non-paying customer testimonial for Crowdin.

**Comment by Madis0** [comment]
@andyholmes Please do let us know when/if we can translate on Crowdin. I would much prefer their UI to POEdit (or equivalent), even though it takes away the possibility of instant testing.

**Comment by andyholmes** [comment]
@DeadMetaler @Madis0 

For now there seem to be a few possible problems, but I think that's mostly up to translators. So you guys and go ahead and translate with Crowdin. :)

For other languages, I will just let people request their languages and I'll set them up if Crowdin works for them.
