### ISSUE TITLE
Settings crash

### ISSUE THREAD

**Issue by HerrWurstwasser** [andyholmes/gnome-shell-extension-gsconnect#41]
Hi!
When I try to open the extensions settings I get this stacktrace:
```
Error: can't convert default_value to an integer

Stack trace:
  @resource:///org/gnome/gjs/modules/overrides/GObject.js:295
  @/home/bjarne/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/client.js:137
  @/home/bjarne/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/prefs.js:24
  Application<._getExtensionPrefsModule@resource:///org/gnome/shell/extensionPrefs/main.js:74
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178
  Application<._selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:89
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178
  Application<._onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:239
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178
  main@resource:///org/gnome/shell/extensionPrefs/main.js:377
  @<main>:1
```
  
Distro is Debian 9

**Comment by andyholmes** [comment]
Hi, what version of GSConnect and Gnome Shell are you using?

**Comment by HerrWurstwasser** [comment]
Hi,

I use GSConnect v9 and the latest Gnome Shell (I have installed Debian on this machine yesterday)
I can tell you the exact version code when I am using this computer next time

**Comment by andyholmes** [comment]
Try this version to see if it fixes the problem:

[gsconnect@andyholmes.github.io.zip](https://github.com/andyholmes/gnome-shell-extension-gsconnect/files/1693204/gsconnect.andyholmes.github.io.zip)

**Comment by HerrWurstwasser** [comment]
Still same issue and same stacktrace.
Tweak-Tool shows also a yellow triangle. When i hover on it, I get the message (translated) "Error loading the extension"

**Comment by andyholmes** [comment]
And you are using Gnome Shell 3.24+?

**Comment by HerrWurstwasser** [comment]
Latest Debian uses GNOME Shell 3.22.3

**Comment by andyholmes** [comment]
Unfortunately only 3.24+ is supported,  GJS is too old before then.

**Comment by HerrWurstwasser** [comment]
Ok, thats bad. Debian often uses old versions. But that is not your fault.
Thank you for your help ;)

**Comment by andyholmes** [comment]
No problem, when debian hits Gnome Shell 3.26 it will be a lot better since Gnome Shell 3.26/GJS 1.50 is now parallel with the stable Mozilla Javascript engine. It's pretty stable if you find a way to upgrade.
