### ISSUE TITLE
Repliable notifications stopped working since v17

### ISSUE THREAD

**Issue by amitkeret** [andyholmes/gnome-shell-extension-gsconnect#410]
First off - thank you so much for this extension, I love it and it's super useful! However... a large part of its usefulness stopped working recently, hence this bug report.

**Describe the bug**
Since updated to v17, no actions are displayed when WhatsApp / SMS messages appear as notifications on the desktop. I have since upgraded to v19 and the issue persists.
This was working as expected prior to an upgrade from an older version to v17 in late November.

I am not entirely sure this is a GSConnect issue - I cannot pinpoint the exact time when the issue began; Ubuntu and GNOME versions have unchanged since, however other components / libraries may have been upgraded unbeknownst to me. Another possible culprit is KDE Connect which upgraded on my device 29 Nov 2018.

**Expected behavior**
Once the pointer hovers over a WhatsApp / SMS notification, actions appear underneath it (eg. "Reply")

**Debug output**
The following was logged when a message was received and then when clicked the "x" button (phone number and contact name have been purposefully replaced; this is not part of the error).
```
GSConnect Version: 19
GSConnect Install: user
GJS: 15403
XDG_SESSION_TYPE: x11
GDMSESSION: ubuntu
--------------------------------------------------------------------------------
Dec 27 20:48:48 org.gnome.Shell.Extensions.GSConnect[5027]: [/service/core.js:receive/<:436]: OnePlus One: {
  "id": 1545907728043,
  "type": "kdeconnect.notification",
  "body": {
    "payloadHash": "8aa59ac2d0e786fcee8168840528819d",
    "id": "0|com.whatsapp|1|00000000000@s.whatsapp.net|10148",
    "appName": "WhatsApp",
    "isClearable": true,
    "ticker": "xxxx xxxx: Test",
    "title": "xxxx xxxx",
    "text": "Test",
    "time": "1545907728027"
  },
  "payloadSize": 18198,
  "payloadTransferInfo": {
    "port": 1740
  }
}
Dec 27 20:48:58 org.gnome.Shell.Extensions.GSConnect[5027]: [/service/plugins/notification.js:closeNotification:520]: "0|com.whatsapp|1|00000000000@s.whatsapp.net|10148"
Dec 27 20:48:58 org.gnome.Shell.Extensions.GSConnect[5027]: [/service/core.js:send:482]: OnePlus One: {
  "id": 1545907738252,
  "type": "kdeconnect.notification.request",
  "body": {
    "cancel": "0|com.whatsapp|1|00000000000@s.whatsapp.net|10148"
  }
}
```

**System Details:**
 - GSConnect version:
   - 17, installed from extensions.gnome.org
   - 19, installed from GitHub Release download
 - GNOME/Shell version: 3.30.1
 - Distro/Release: Ubuntu 18.10

**GSConnect environment:**
 - Paired Device(s): OnePlus One running Android 6.0.1
 - KDE Connect app version: 1.10.1

**Comment by albertvaka** [comment]
I don't think that patch could break this, and it certainly shouldn't change `requestReplyId`.

Just to be sure, @amitkeret can you try installing an older version of the Android app and see if it works? You can get older versions from F-Droid (although you will need to uninstall the version from the Play Store first): 

https://f-droid.org/en/packages/org.kde.kdeconnect_tp/

**Comment by ferdnyc** [comment]
One thought: This part of the report struck me as odd. 
> Since updated to v17, no actions are displayed when WhatsApp / SMS messages appear as notifications on the desktop. 
> **Expected Behavior:** Once the pointer hovers over a WhatsApp / SMS notification, actions appear underneath it (eg. "Reply")

@amitkeret, are  you saying that the notifications you were seeing _used to_ have actions attached to them?

I ask because, prior to (I think) GSConnect v19, GSConnect notifications _didn't_ have action buttons. Repliable notifications just had a text box built right into the notification. (Right @andyholmes? Or were there other types with actions attached?) 

This may be a stupid question, I guess, but is it possible the notifications you used to receive were actually web notifications coming through Firefox/Chrome? (I got tricked myself on that once, YouTube was sending me notifications in Chrome that I _thought_ were from GSConnect.)

**Comment by andyholmes** [comment]
> I ask because, prior to (I think) GSConnect v19, GSConnect notifications didn't have action buttons. Repliable notifications just had a text box built right into the notification. (Right @andyholmes? Or were there other types with actions attached?)

If I recall, repliable notifications (notifications that carry a `requestReplyId`) were first implemented in v13; as of v19 you could only reply to these using a text entry in the notification. As of v20-rc1 clicking on the body of the notification will open a dialog (shamelessly stolen from kdeconnect).

It was the case for a long that clicking on an SMS notification, which may have had a *Reply* button, would open an SMS window for that contact. I can't really remember when that was removed to be honest, but it was part of the giant hack GSConnect used to use before Simon implemented proper SMS support.

**Comment by amitkeret** [comment]
@ferdnyc 
> is it possible the notifications you used to receive were actually web notifications coming through Firefox/Chrome?

I don't remember ever receiving repliable notifications from WhatsApp web. Just to make sure, I disabled GSConnect and enabled web notifications, and no action buttons were present.
(good thought though!)

@albertvaka haven't had a chance to install a previous version, will do this shortly and report.

**Comment by amitkeret** [comment]
OK...
* tried downgrading KDEConnect to 1.10 - no change.
*  tried downgrading GSConnect to v16 - still no reply option.
* (I deletes configuration files on my PC in between attempts)
* @ferdnyc I checked in both WhatsApp and SMS notifications

I've also since upgraded GSConnect to v20 in hopes something would fix this, with no luck.
I did notice one *very* strange behaviour - after re-installing KDEConnect and pairing the devices, I had to again allow "notification access" on the phone. When I did that, I immediately got all "pending" (= unseen) phone notifications. One, though, had the repliable text-field - it wasn't even a chat message, just a notification from one of my apps! It wasn't even *meant* to be repliable.
I unfortunately did not have debugging enabled, and I was not able to reproduce this. I'm just describing as it happened to maybe help you guys connect the dots...



Anything else I can do to try and debug this? this feature is **so** great and I hate not having it without even understanding why! Plz help :cry:

**Comment by andyholmes** [comment]
It seems like the bug is happening in Android, not in GSConnect, so I'd have to say your best bet is to file an upstream bug report against the Android app. If possible, try to get a logcat from Android for when these messages are received to help the developers track down the cause.

https://bugs.kde.org/enter_bug.cgi?product=kdeconnect
