### ISSUE TITLE
GVFS causes problems when registering public key with ssh-add

### ISSUE THREAD

**Issue by 1989gironimo** [andyholmes/gnome-shell-extension-gsconnect#417]
I tried to update today to the newest available version on extensions.gnome.org. First the shell hang and wasn't responsive at all. I tried to restart the gnome shell, but the hang continued so I restarted the computer. After the restart, the icon to connect to my phone vanished and don't start anymore, the configuration tab doesn't open as well.

-> A reinstall via extensions.gnome.org works without any errors, but the issue persists.
-> I cannot provide a debug log, because I cannot access the appropriate menu option.

**System Details (please complete the following information):**
 - GSConnect version: Newest available version on extensions.gnome.org on 30. December 2018
   - Installed from: extensions.gnome.org
 - GNOME/Shell version: 3.30.1
 - Distro/Release: Ubuntu 18.10

**GSConnect environment (if applicable):**
 - Paired Device(s): Nexus 5X
 - KDE Connect app version: 1.3.1-1

**Comment by ferdnyc** [comment]
Hi @1989gironimo , sorry you're having trouble. Do you happen to know what version of the extension you were upgrading _from_? (If it was the previous e.g.o release, that would've been `v17`, but I'm curious if perhaps you were running an older version or one installed via different means?) It's not critical, just curious so we can track what versions these issues crop up in.

As far as logs/messages, if you press <kbd>Alt</kbd>+<kbd>F2</kbd>, then type the command `lg` (the letters ell and gee) and hit <kbd>Enter</kbd>, that'll bring up the Shell's Looking Glass tool. In the upper right corner there's an "Extensions" selection which will list all of the installed extensions: GSConnect should be among them. That'll indicate (at the bottom of the box) whether the extension is "Enabled" or "Disabled", and/or whether the Shell has encountered any errors — there's also a "Show Errors" link at the very end of the box, to display the details of any errors detected (if there were any).

Regardless what you find there (possibly nothing informative), to get GSConnect working again please try [these steps from the Wiki](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Help#how-can-i-reset-the-settings) to completely clear out your GSConnect settings; after a Shell restart or logout/login cycle, the extension should show up normally and you'll be able to re-pair your device(s).

**Comment by yngman** [comment]
Hi there,

I had the exact same issue this morning. Re-installing and rebooting *did not help*.

However, resetting everything via

    gnome-shell-extension-tool -d gsconnect@andyholmes.github.io
    rm -rf ~/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io
    rm -rf ~/.cache/gsconnect
    rm -rf ~/.config/gsconnect
    dconf reset -f /org/gnome/shell/extensions/gsconnect/

And then purging and re-installing the Android app, installing from [gnome.org](extensions.gnome.org)  and setting up the pairing anew *did* work!

**However**, I was requested for a passphrase to encrypt a new GPG key (the agent was storing in my keyring), obivously belonging to gsconnect, when installing the extension. This was before *any pairing* with my phone was attempted. I left it empty and clicked on. I did not see this when upgrading 17 -> 19 (before resetting) and might thus be the issue?

My version information below.

--------

**System Details (please complete the following information):**

* GSConnect version: 19
      
  * Installed from: extensions.gnome.org

* GNOME/Shell version: 3.28.3

* Distro/Release: Ubuntu 18.04.1 LTS

**GSConnect environment (if applicable):**

* Paired Device(s): OnePlus 3

* KDE Connect app version: 1.10.1

**Comment by 1989gironimo** [comment]
Ok, reset everything and it's working again, but had a hanging shell after installing which was gone after approx. 10 seconds.

Had the gpg-dialog as well, just pressed ok and everything's fine now.

**Comment by andyholmes** [comment]
Here is an updated Zip with the commited fix for this issue:

[gsconnect@andyholmes.github.io.zip](https://github.com/andyholmes/gnome-shell-extension-gsconnect/files/2717469/gsconnect.andyholmes.github.io.zip)
