### ISSUE TITLE
[Ubuntu 18.04] Can't view or send SMS messages

### ISSUE THREAD

**Issue by cbs228** [andyholmes/gnome-shell-extension-gsconnect#423]
It is not possible to open any SMS Messaging conversation, or send any messages, in GSConnect r19. I believe Messaging was working OK for me in r18.

**To Reproduce**
1. Open the Messaging window for a telephony device
2. Click on any contact entry. Alternatively, try clicking the `+` button to start a new conversation.
3. Nothing happens. The conversation is not opened, and no error message is displayed. The right pane of the Messaging window continues to display, "`No conversation selected. Select or start a conversation.`"

**Expected behavior**
The applicable conversation should be displayed in the right pane. Controls for sending messages should be made visible.

**Debug output**
When clicking on a single contact entry in the Messaging window, the following is logged:

```
GSConnect Version: 19
GSConnect Install: user
GJS: 15201
XDG_SESSION_TYPE: wayland
GDMSESSION: gnome
--------------------------------------------------------------------------------
-- Logs begin at Fri 2018-08-24 23:45:51 CDT, end at Tue 2019-01-01 14:29:37 CST. --
Jan 01 14:29:32 gjs[10289]: GtkDialog mapped without a transient parent. This is discouraged.
Jan 01 14:29:37 gjs[10289]: Error building template class 'GSConnectConversationWidget' for an instance of type 'GSConnectConversationWidget': .:3:2808 Invalid property: GtkEntry.enable_emoji_completion
Jan 01 14:29:37 gjs[10289]: JS ERROR: Error: Argument 'target' (type interface) may not be null
                            _init@/home/ubuntu/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/ui/messaging.js:312:9
                            set address@/home/ubuntu/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/ui/messaging.js:798:28
                            _onConversationSelected@/home/ubuntu/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/ui/messaging.js:897:13
                            @/home/ubuntu/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:774:2
```

**System Details:**
 - GSConnect version: `19` from extensions.gnome.org.
 - GNOME/Shell version: `3.28.3-0ubuntu0.18.04.3`
 - Distro/Release: `Ubuntu 18.04.1 LTS`

**GSConnect environment:**
 - Paired Device(s): `Android 8.1.0` with OmniROM OS
 - KDE Connect app version: `1.10.1` from f-droid

**Additional context**
The Messaging window also takes almost one minute to open and logs many messages like the following to syslog. I am not sure if these issues are related.

```
Jan 01 13:03:11 machine gjs[5822]: JS ERROR: TypeError: row.contact.name is undefined
                                      _filter@/home/ubuntu/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/ui/contacts.js:326:1
                                      add_contact_number@/home/ubuntu/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/ui/contacts.js:382:9
                                      add_contact@/home/ubuntu/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/ui/contacts.js:366:20
                                      _populate@/home/ubuntu/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/ui/contacts.js:360:13
                                      _init@/home/ubuntu/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/ui/contacts.js:260:9
                                      _init@/home/ubuntu/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/ui/messaging.js:731:29
                                      get window@/home/ubuntu/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/sms.js:224:28
                                      sms@/home/ubuntu/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/sms.js:467:9
                                      _activateAction@/home/ubuntu/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/base.js:71:17
                                      @/home/ubuntu/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:774:2
```

**Legacy/Fallback Mode**
I also tried the legacy mode, i.e:

```bash
dconf write /org/gnome/shell/extensions/gsconnect/device/<device_id>/plugin/sms/legacy true
```

The legacy mode dialog displays correctly, but no messages can be sent.

**Comment by RobertZito** [comment]
Same issue here:

GSConnect Version: 19
GSConnect Install: user
GJS: 15201
XDG_SESSION_TYPE: x11
GDMSESSION: pop
--------------------------------------------------------------------------------
-- Logs begin at Fri 2018-10-12 13:07:20 EDT, end at Tue 2019-01-01 17:34:00 EST. --
Jan 01 17:33:43 gjs[2251]: GtkDialog mapped without a transient parent. This is discouraged.
Jan 01 17:33:47 gnome-shell[1755]: Ignoring excess values in shadow definition
Jan 01 17:33:47 gnome-shell[1755]: Ignoring excess values in shadow definition
Jan 01 17:33:48 gnome-shell[1755]: Ignoring excess values in shadow definition
Jan 01 17:33:48 gnome-shell[1755]: Ignoring excess values in shadow definition
Jan 01 17:33:48 gnome-shell[1755]: Ignoring excess values in shadow definition
Jan 01 17:33:48 gnome-shell[1755]: Ignoring excess values in shadow definition

**Comment by andyholmes** [comment]
@RobertZito Could you try this updated Zip which fixes some of the issues above?

[gsconnect@andyholmes.github.io.zip](https://github.com/andyholmes/gnome-shell-extension-gsconnect/files/2719695/gsconnect.andyholmes.github.io.zip)

`unzip -o gsconnect.andyholmes.github.io.zip -d ~/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io`

**Comment by RobertZito** [comment]
Still no luck

**Comment by RobertZito** [comment]
Actually it did work

**Comment by cbs228** [comment]
7c9fece516 fixes the inability to send or view SMS messages for me. The GSConnect Messaging window remains slow to open for me, but this is a separate issue. I will mark this one as closed for now.

**Comment by booilakaha** [comment]
> @RobertZito Could you try this updated Zip which fixes some of the issues above?
> 
> [gsconnect@andyholmes.github.io.zip](https://github.com/andyholmes/gnome-shell-extension-gsconnect/files/2719695/gsconnect.andyholmes.github.io.zip)
> 
> `unzip -o gsconnect.andyholmes.github.io.zip -d ~/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io`

Still cant view previous and active conversation(or am i mistaken and it is not intended to work as an SMS app)  also any newly recieved messages donot show up.
![screenshot from 2019-01-07 01-10-11](https://user-images.githubusercontent.com/46388265/50740832-c0867e00-121a-11e9-8931-952f7d2acef0.png)

**Comment by andyholmes** [comment]
@booilakaha are you using Signal or another SMS app that encrypts it's messages? Or are you using one of the devices from this list:

* Samsung S8
* Motorola G6
* Huawei P10 Lite

If not, what is your phone model?
