### ISSUE TITLE
Wiki build instructions are... weird?

### ISSUE THREAD

**Issue by ferdnyc** [andyholmes/gnome-shell-extension-gsconnect#424]
The [Install from Git](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Installation#install-from-git) section of the wiki's Installation article currently reads:

> You can build or install from git with Meson:
> ```
> git clone https://github.com/andyholmes/gnome-shell-extension-gsconnect.git
> meson gnome-shell-extension-gsconnect/ _build
> mkdir -p ~/.local/share/gnome-shell/extensions
> ninja -C _build install-zip

That strikes me as... strange, because:
1. As far as I can tell, the positional args to `meson` are actually backwards, and it's just autodetecting that they're reversed and compensating because it's the only interpretation that makes sense.
   (The output of `meson help setup` shows the positonal args as `[builddir] [sourcedir]`.)
1. This will create the `_build` dir _outside_ of (and alongside) the `gnome-shell-extension-gsconnect` cloned repo dir, which is unusual. (And since the checked-in `.gitignore` at the root of the repo includes `_build`, doesn't seem necessary from a source-tree-management perspective.)

Wouldn't something like this be more typical?
```
git clone https://github.com/andyholmes/gnome-shell-extension-gsconnect.git
cd gnome-shell-extension-gsconnect
meson _build .
mkdir -p ~/.local/share/gnome-shell/extensions
ninja -C _build install-zip
```

**Comment by andyholmes** [comment]
Sure, I changed it. I usually keep the build directory separate from the source, especially since you have to call `-C` anyways and changing directories is just one more command, but it doesn't matter. Creating the extensions directory shouldn't be necessary anymore, so I removed that too.
