### ISSUE TITLE
Once paired Devices can't 'find' each other anymore.

### ISSUE THREAD

**Issue by hyphenc** [andyholmes/gnome-shell-extension-gsconnect#429]
**Describe the bug**
Devices can't 'find' each other anymore.

**To Reproduce**
1. Open GSConnect or KDEconnect app
2. No devices discovered
3. Direct IP connecting doesn't work
4. (I don't know how to connect the devices)

**Expected behavior**
One device detects the other and pairing can be initiated.

**Debug output**

```
GSConnect Version: 19
GSConnect Install: user
GJS: 15403
XDG_SESSION_TYPE: x11
GDMSESSION: gnome
--------------------------------------------------------------------------------
-- Logs begin at Fri 2018-09-28 21:33:22 CEST, end at Sat 2019-01-05 20:23:39 CET. --
Jan 05 20:23:04 org.gnome.Shell.Extensions.GSConnect[1054]: [/service/lan.js:broadcast:278]: "Broadcasting to LAN"
Jan 05 20:23:04 gjs[1054]: WARNING: [boxed instance proxy GIName:GLib.Error jsobj@0x7f9f64168970 native@0x561ba6226eb0]
Jan 05 20:23:07 org.gnome.Shell.Extensions.GSConnect[1054]: [/service/lan.js:broadcast:278]: "Broadcasting to LAN"
Jan 05 20:23:07 gjs[1054]: WARNING: [boxed instance proxy GIName:GLib.Error jsobj@0x7f9f64168760 native@0x561ba64ccec0]
Jan 05 20:23:09 org.gnome.Shell.Extensions.GSConnect[1054]: [/service/lan.js:broadcast:278]: "Broadcasting to LAN"
Jan 05 20:23:09 gjs[1054]: WARNING: [boxed instance proxy GIName:GLib.Error jsobj@0x7f9f64168df0 native@0x561ba62839c0]
Jan 05 20:23:14 org.gnome.Shell.Extensions.GSConnect[1054]: [/service/lan.js:broadcast:278]: "Broadcasting to LAN"
Jan 05 20:23:14 gjs[1054]: WARNING: [boxed instance proxy GIName:GLib.Error jsobj@0x7f9f64180130 native@0x561ba64122a0]
Jan 05 20:23:19 org.gnome.Shell.Extensions.GSConnect[1054]: [/service/lan.js:broadcast:278]: "Broadcasting to LAN"
Jan 05 20:23:19 gjs[1054]: WARNING: [boxed instance proxy GIName:GLib.Error jsobj@0x7f9f64190dc0 native@0x561ba6412650]
Jan 05 20:23:20 org.gnome.Shell.Extensions.GSConnect[1054]: [/service/lan.js:broadcast:273]: "Identifying to 192.168.178.42"
Jan 05 20:23:20 gjs[1054]: WARNING: [boxed instance proxy GIName:GLib.Error jsobj@0x7f9f64168a30 native@0x561ba62839a0]
Jan 05 20:23:24 org.gnome.Shell.Extensions.GSConnect[1054]: [/service/lan.js:broadcast:278]: "Broadcasting to LAN"
Jan 05 20:23:24 gjs[1054]: WARNING: [boxed instance proxy GIName:GLib.Error jsobj@0x7f9f64180190 native@0x561ba6412090]
Jan 05 20:23:29 org.gnome.Shell.Extensions.GSConnect[1054]: [/service/lan.js:broadcast:278]: "Broadcasting to LAN"
Jan 05 20:23:29 gjs[1054]: WARNING: [boxed instance proxy GIName:GLib.Error jsobj@0x7f9f64180700 native@0x561ba6287400]
Jan 05 20:23:34 org.gnome.Shell.Extensions.GSConnect[1054]: [/service/lan.js:broadcast:278]: "Broadcasting to LAN"
Jan 05 20:23:35 gjs[1054]: WARNING: [boxed instance proxy GIName:GLib.Error jsobj@0x7f9f64168cd0 native@0x7f9f280016a0]
Jan 05 20:23:39 org.gnome.Shell.Extensions.GSConnect[1054]: [/service/lan.js:broadcast:278]: "Broadcasting to LAN"
Jan 05 20:23:39 gjs[1054]: WARNING: [boxed instance proxy GIName:GLib.Error jsobj@0x7f9f64180430 native@0x561ba64126b0]
```

**System Details (please complete the following information):**
 - GSConnect version: 19
   - Installed from: extensions.gnome.org
 - GNOME/Shell version: 3.30
 - Distro/Release: Arch (Kernel: linux 4.20)

**GSConnect environment (if applicable):**
 - Once Paired Device: LG G6
 - KDE Connect app version: 1.10.1 (F-Droid)

**Additional context**
KDEConnect/GSConnect worked fine until today, when my phone just wasn't showing up anymore in GSConnect (and my PC not in the KDEconnect app), it just said disconnected/unreachable.
I tried direct IP connecting, unpairing the devices, reinstalling KDEconnect and reinstalling GSConnect (including [resetting](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Help#how-can-i-reset-the-settings)) to no avail.

Because this occured just now and the devices worked fine together before, I assume the error is on my side, but I can't really figure out why this is happening.

**Comment by hyphenc** [comment]
I installed from git and now everything works again (device discovery, etc.), don't know what was going on... maybe the extensions.gnome.org version was too outdated ("The GNOME Extensions website reviews all submissions and often distributes an older version." - 'Installation' Wiki page).

**Comment by andyholmes** [comment]
Oh good, I think I broke more than a few things in the last release, so maybe that just means I fixed it :D

If it happens again at least it should print a proper error message now.

**Comment by hyphenc** [comment]
Ok, closing this issue.
