### ISSUE TITLE
Error in the Installed extension in Tweaker

### ISSUE THREAD

**Issue by Procerus** [andyholmes/gnome-shell-extension-gsconnect#43]
I am running Gnome on ubuntu 16.04. I tried installing it using git and installing using unzip into the extensions folder. When I try to turn it on in Tweaker it says error and when I try to bring up settings this shows up

Error: can't convert default_value to an integer

Stack trace:
  @resource:///org/gnome/gjs/modules/overrides/GObject.js:295
  @/home/procerus/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/client.js:144
  @/home/procerus/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/prefs.js:21
  Application<._getExtensionPrefsModule@resource:///org/gnome/shell/extensionPrefs/main.js:79
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178
  Application<._selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:94
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178
  Application<._onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:259
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178
  main@resource:///org/gnome/shell/extensionPrefs/main.js:397
  @<main>:1

**Comment by andyholmes** [comment]
Did you get the Zip from here?

https://github.com/andyholmes/gnome-shell-extension-gsconnect/releases/tag/v9

**Comment by Procerus** [comment]
Yup I tried that one and I tried v8 as well.

**Comment by andyholmes** [comment]
Give this one a try:

[gsconnect@andyholmes.github.io.zip](https://github.com/andyholmes/gnome-shell-extension-gsconnect/files/1692441/gsconnect.andyholmes.github.io.zip)

**Comment by Procerus** [comment]
Still got an error and a different one 

TypeError: Object.assign is not a function

Stack trace:
  Stack<._init@/home/procerus/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/widgets/preferences.js:265
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178
  _parent@resource:///org/gnome/gjs/modules/lang.js:131
  PrefsWidget<._init@/home/procerus/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/prefs.js:99
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178
  buildPrefsWidget@/home/procerus/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/prefs.js:218
  Application<._selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:95
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178
  Application<._onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:259
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178
  main@resource:///org/gnome/shell/extensionPrefs/main.js:397
  @<main>:1

![screenshot from 2018-02-03 21-27-14](https://user-images.githubusercontent.com/5898521/35774196-398a449a-092e-11e8-9e5b-71cf45dcacac.png)

**Comment by andyholmes** [comment]
Ah, then you are using an older Gnome Shell. Only version 3.24+ is supported unfortunately, GJS is just too old at that point.
