### ISSUE TITLE
gsconnect cannot find devices (unbuntu 18.04)

### ISSUE THREAD

**Issue by jjlacrampe** [andyholmes/gnome-shell-extension-gsconnect#434]
**Describe the bug**
when I start GSconnect on my PC, my ASUS ultra under android 7.0 running KDE connect find no devices.
**To Reproduce**
Appareils mobiles in menu
parameters
3.gsconnect windowopens

**Expected behavior**
I would like it to find my smartphone.
**Screenshots**
![image](https://user-images.githubusercontent.com/46439070/50757578-16c9e000-1260-11e9-95ba-1e1e77886b0e.png)

**Debug output**

GSConnect Version: 19
GSConnect Install: user
GJS: 15201
XDG_SESSION_TYPE: x11
GDMSESSION: ubuntu
--------------------------------------------------------------------------------
-- Logs begin at Fri 2018-12-28 14:48:27 CET, end at Mon 2019-01-07 09:27:09 CET. --
janv. 07 09:27:00 gjs[23846]: GtkDialog mapped without a transient parent. This is discouraged.
janv. 07 09:27:04 org.gnome.Shell.Extensions.GSConnect[23846]: [/service/lan.js:broadcast:278]: "Broadcasting to LAN"
janv. 07 09:27:04 gjs[23846]: WARNING: [boxed instance proxy GIName:GLib.Error jsobj@0x7fd46c08a640 native@0x560546bfad00]
janv. 07 09:27:09 org.gnome.Shell.Extensions.GSConnect[23846]: [/service/lan.js:broadcast:278]: "Broadcasting to LAN"
janv. 07 09:27:09 gjs[23846]: WARNING: [boxed instance proxy GIName:GLib.Error jsobj@0x7fd46c0998b0 native@0x560546c16c70]

**System Details (please complete the following information):**
 - GSConnect version: [e.g. 16, 15, ... (displayed in the GSConnect "About" window)]
   - Installed from: [e.g. extensions.gnome.org, GitHub Release download, distro package, ...]
 - GNOME/Shell version:3.28.2
 - Distro/Release: Ubuntu 18.04.1 
![image](https://user-images.githubusercontent.com/46439070/50757722-8213b200-1260-11e9-95d2-84a613481434.png)

**GSConnect environment (if applicable):**
 - Paired Device(s): ASUS_A001 Android 7.0
 - KDE Connect app version: 1.10.1
 
**Additional context**
I have tried to connect via IP address (from PC end from smartphone) : failed
I verified by telnet that the port 1716 is free : it is free
I verified on the router that the PC and the smartphone are in the same net : ok
I've tried to install/reinstall/purge forom apt and from zip after erasing all the necessary files in .config : no effect
I've tried to install kde connect on ubuntu : it works (of course I purged it before reinstalling gsconnect.

What else can I do?

Thanks for your help

Jean-Jacques

**Comment by gautierlabarre** [comment]
Hello,

I'm not good with network (telnet, etc.), so it's maybe a silly question, but do you have a firewall ? I had the same issue, not long ago :smile:

**Comment by andyholmes** [comment]
Hi, I believe you are experiencing a bug which affects Ubuntu 18.04. Please try the [latest release candidate v20-rc3](https://github.com/andyholmes/gnome-shell-extension-gsconnect/releases/tag/v20-rc3). You can install it like this, then restart Gnome Shell:

    rm -rf ~/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io
    unzip -o gsconnect.andyholmes.github.io.zip -d ~/.local/share/gnome- 
    shell/extensions/gsconnect@andyholmes.github.io

**Comment by jjlacrampe** [comment]
> Hello,
> 
> I'm not good with network (telnet, etc.), so it's maybe a silly question, but do you have a firewall ? I had the same issue, not long ago

Hello Gautier, thanx for this suggestion, but my firewall was not active for these tests.

**Comment by jjlacrampe** [comment]
**You are right andyholmes**, all is in order with this version! 
I'm amazed by tour so fast and efficient diagnostic.
Now I'll try to learn how to manage sms from my PC...
