### ISSUE TITLE
cannot access mobile settings

### ISSUE THREAD

**Issue by dln949** [andyholmes/gnome-shell-extension-gsconnect#437]
Ubuntu 18.04.1, gnome shell 3.28.3, gsconnect 19.  

Suddenly today I am not able to access the gsconnect settings.  When I attempt to do that, instead of getting the settings window, I get a strange gsconnect icon on the dash that is not responsive to any clicking actions.  

I have attempted rebooting the computer, turning gsconnect off and then back on, but I still have this problem.  

Since I cannot access the settings, I cannot generate a log for you.  

I have attached a screenshot that shows what I am getting in the dash.  

![screenshot from 2019-01-07 20-34-13](https://user-images.githubusercontent.com/8601150/50806463-5b836480-12bc-11e9-952e-fa051bca9062.png)

**Comment by andyholmes** [comment]
Hi, there were lots of problems with v19 for Ubuntu 18.04. Could you please install this zip and restart GNOME Shell:

[gsconnect@andyholmes.github.io.zip](https://github.com/andyholmes/gnome-shell-extension-gsconnect/files/2735071/gsconnect.andyholmes.github.io.zip)

**Comment by dln949** [comment]
I installed the files you provided, the problem seems to be solved now.  Thanks.  

One other question, though:  In the settings window, if I select a device, and then click on "Advanced", I see a long list of plugins.  Some of the plugins have an odd symbol over on the far right, it looks like a paint brush?  What does that symbol mean?  I cannot tell because nothing happens when I click on those symbols.

**Comment by andyholmes** [comment]
> Some of the plugins have an odd symbol over on the far right, it looks like a paint brush? What does that symbol mean?

These are for clearing the cached plugin data. Generally you should not use any of the settings in *Advanced* unless you have a reason to, since these are not for regular use and may cause problems.

**Comment by dln949** [comment]
> > Some of the plugins have an odd symbol over on the far right, it looks like a paint brush? What does that symbol mean?
> 
> These are for clearing the cached plugin data. Generally you should not use any of the settings in _Advanced_ unless you have a reason to, since these are not for regular use and may cause problems.

Oops.   

I didn't realize that.  Well, I hope I didn't wreck anything by clicking on them.
