### ISSUE TITLE
SMS writing page does not appear

### ISSUE THREAD

**Issue by Barben360** [andyholmes/gnome-shell-extension-gsconnect#438]
**Describe the bug**
When I click on new message (+ button) and select a contact, the message writing page should appear. Instead, the name of the selected contact appears on the top bar and the page remains on the contact list. Log doesn't show anything interesting. This happens since last update, tested on both my computers on Ubuntu 18.04.

**System Details (please complete the following information):**
 - GSConnect version: 19
   - Installed from: extensions.gnome.org
 - GNOME/Shell version: 3.28.3
 - Distro/Release: Ubuntu 18.04

**GSConnect environment (if applicable):**
 - Paired Device(s): Samsung Galaxy S7
 - KDE Connect app version: 1.10
 - Plugin(s): None

**Comment by andyholmes** [comment]
Hi, I believe you are experiencing a bug which affects Ubuntu 18.04. Please try the [latest release candidate v20-rc4](https://github.com/andyholmes/gnome-shell-extension-gsconnect/releases/tag/v20-rc4). You can install it like this, then restart Gnome Shell:

    rm -rf ~/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io
    unzip -o gsconnect.andyholmes.github.io.zip -d ~/.local/share/gnome- 
    shell/extensions/gsconnect@andyholmes.github.io

**Comment by Barben360** [comment]
That indeed fixed it! Thanks a lot for your great job on what is for me the best existing gnome extension, and for your support.
