### ISSUE TITLE
Gnome SMS notifs only show up when 'Legacy SMS' feature is ON

### ISSUE THREAD

**Issue by ouillepouille** [andyholmes/gnome-shell-extension-gsconnect#445]
**Describe the bug**
I get no notifs if I don't use the experimental legacy SMS management option.
Please note that everything is fine with the normal SMS management (the SMS history window works, shows contacts, etc.) except that I don't ever get a notif. When I use the legacy=ON option, I start getting gnome notifications again (a feature which is essential to me)

**Comment by ouillepouille** [comment]
GSConnect latest version. Generic Android SMS App. Permission good. 

Log : 
```

GSConnect Version: 20
GSConnect Install: user
GJS: 15403
XDG_SESSION_TYPE: x11
GDMSESSION: ubuntu
--------------------------------------------------------------------------------
-- Logs begin at Wed 2018-10-24 17:18:15 EDT, end at Sun 2019-01-13 21:28:37 EST. --
Jan 13 21:28:22 signal-desktop.desktop[26470]: {"name":"log","hostname":"---","pid":28045,"level":30,"msg":"Sending a keepalive message","time":"2019-01-14T02:28:22.112Z","v":0}
Jan 13 21:28:36 gnome-shell[26470]: clutter_actor_remove_child: assertion 'child->priv->parent != NULL' failed
Jan 13 21:28:36 gnome-shell[26470]: Attempting to remove actor of type 'StWidget' from group of class 'ShellGenericContainer', but the container is not the actor's parent.
Jan 13 21:28:37 gnome-shell[26470]: Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.
Jan 13 21:28:37 org.gnome.Shell.desktop[26470]: == Stack trace for context 0x5605e1661220 ==
Jan 13 21:28:37 gnome-shell[26470]: The offending signal was destroy on ClutterClone 0x5605e3043b00.
Jan 13 21:28:37 gnome-shell[26470]: Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.
Jan 13 21:28:37 org.gnome.Shell.desktop[26470]: == Stack trace for context 0x5605e1661220 ==
Jan 13 21:28:37 gnome-shell[26470]: The offending signal was destroy on ClutterClone 0x5605e5fece20.
Jan 13 21:28:37 gnome-shell[26470]: Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.
Jan 13 21:28:37 org.gnome.Shell.desktop[26470]: == Stack trace for context 0x5605e1661220 ==
Jan 13 21:28:37 gnome-shell[26470]: The offending signal was destroy on ClutterClone 0x5605e3042a20.
Jan 13 21:28:37 org.gnome.Shell.desktop[26470]: == Stack trace for context 0x5605e1661220 ==
Jan 13 21:28:37 gnome-shell[26470]: Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.
Jan 13 21:28:37 gnome-shell[26470]: The offending signal was destroy on ClutterClone 0x5605e3043440.
Jan 13 21:28:37 gnome-shell[26470]: Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.
Jan 13 21:28:37 gnome-shell[26470]: The offending signal was destroy on ClutterClone 0x5605e5fec400.
Jan 13 21:28:37 org.gnome.Shell.desktop[26470]: == Stack trace for context 0x5605e1661220 ==
Jan 13 21:28:37 gnome-shell[26470]: Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.
Jan 13 21:28:37 gnome-shell[26470]: The offending signal was destroy on ClutterClone 0x5605e30437a0.
Jan 13 21:28:37 gnome-shell[26470]: Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.
Jan 13 21:28:37 gnome-shell[26470]: The offending signal was destroy on ClutterClone 0x5605e3043e60.
Jan 13 21:28:37 gnome-shell[26470]: Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.
Jan 13 21:28:37 gnome-shell[26470]: The offending signal was destroy on StLabel 0x5605e6746460.
Jan 13 21:28:37 gnome-shell[26470]: Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.
Jan 13 21:28:37 org.gnome.Shell.desktop[26470]: == Stack trace for context 0x5605e1661220 ==
Jan 13 21:28:37 gnome-shell[26470]: The offending signal was destroy on StBin 0x5605e15ded00.
```

**Comment by andyholmes** [comment]
From your log it doesn't look like you received any SMS packets or notification packets during this period, so it would have to be a bug in the Android app then.

**Comment by andyholmes** [comment]
The legacy packets (`kdeconnect.telephony`) are deprecated for SMS and due to removed upstream in kdeconnect-android. These aren't usually used for desktop notifications because they aren't related to notification packets (`kdeconnect.notification`), and so can't be used to close remote notifications.

The `kdeconnect.telephony` packets are sent only once, when an SMS is received and never again. So if your device is disconnected you will never get a desktop notification for these packets.

'kdeconnect.notification` packets are sent with an `id` that lets us close the remote notification, and we get a packet for each existing notification when we connect to the remote device. These are also the packets that carry the `requestReplyId` that allows for repliable notifications.

In your log, there are neither packets for `kdeconnect.telephony` nor `kdeconnect.notification` which are printed to the log immediately after being read from the socket (if the *Generate Support Log* dialog is open):

https://github.com/andyholmes/gnome-shell-extension-gsconnect/blob/575386c0723d9d933b08cff3b268654f2b272028/src/service/core.js#L305-L317

So either there were no SMS or notifications during the period you had the *Generate Support Log* dialog open, or Android didn't send them. If there were no events during that period then GSConnect has no work to do and if Android is not sending those packets there is also nothing that can be done in GSConnect to fix that.

**Comment by ouillepouille** [comment]
OK... didn't understand the 'while the dialog is open' thing... sorry.
Here's a log for a dummy SMS

> 
> 
> GSConnect Version: 20
> GSConnect Install: user
> GJS: 15403
> XDG_SESSION_TYPE: x11
> GDMSESSION: ubuntu
> --------------------------------------------------------------------------------
> -- Logs begin at Wed 2018-10-24 17:18:15 EDT, end at Mon 2019-01-14 11:33:16 EST. --
> Jan 14 11:33:14 org.gnome.Shell.Extensions.GSConnect[9078]: [/service/core.js:receive/<:311]: Motorola Moto G: {
>                                                               "id": 1547483593704,
>                                                               "type": "kdeconnect.telephony",
>                                                               "body": {
>                                                                 "event": "sms",
>                                                                 "messageBody": "yoyoyyo",
>                                                                 "phoneNumber": "1113002738"
>                                                               }
>                                                             }
> Jan 14 11:33:14 org.gnome.Shell.Extensions.GSConnect[9078]: [/service/core.js:receive/<:311]: Motorola Moto G: {
>                                                               "id": 1547483593723,
>                                                               "type": "kdeconnect.telephony",
>                                                               "body": {
>                                                                 "event": "sms",
>                                                                 "messageBody": "yoyoyyo",
>                                                                 "phoneNumber": "1113002738"
>                                                               }
>                                                             }
> Jan 14 11:33:14 org.gnome.Shell.Extensions.GSConnect[9078]: [/service/core.js:receive/<:311]: Motorola Moto G: {
>                                                               "id": 1547483593738,
>                                                               "type": "kdeconnect.telephony",
>                                                               "body": {
>                                                                 "event": "sms",
>                                                                 "messageBody": "yoyoyyo",
>                                                                 "phoneNumber": "1113002738"
>                                                               }
>                                                             }
> Jan 14 11:33:14 org.gnome.Shell.Extensions.GSConnect[9078]: [/service/core.js:receive/<:311]: Motorola Moto G: {
>                                                               "id": 1547483593754,
>                                                               "type": "kdeconnect.telephony",
>                                                               "body": {
>                                                                 "event": "sms",
>                                                                 "messageBody": "yoyoyyo",
>                                                                 "phoneNumber": "1113002738"
>                                                               }
>                                                             }
> Jan 14 11:33:14 org.gnome.Shell.Extensions.GSConnect[9078]: [/service/core.js:receive/<:311]: Motorola Moto G: {
>                                                               "id": 1547483593806,
>                                                               "type": "kdeconnect.telephony",
>                                                               "body": {
>                                                                 "event": "sms",
>                                                                 "messageBody": "yoyoyyo",
>                                                                 "phoneNumber": "1113002738"
>                                                               }
>                                                             }
> Jan 14 11:33:14 org.gnome.Shell.Extensions.GSConnect[9078]: [/service/core.js:receive/<:311]: Motorola Moto G: {
>                                                               "id": 1547483593821,
>                                                               "type": "kdeconnect.telephony",
>                                                               "body": {
>                                                                 "event": "sms",
>                                                                 "messageBody": "yoyoyyo",
>                                                                 "phoneNumber": "1113002738"
>                                                               }
>                                                             }
> Jan 14 11:33:14 org.gnome.Shell.Extensions.GSConnect[9078]: [/service/core.js:receive/<:311]: Motorola Moto G: {
>                                                               "id": 1547483593991,
>                                                               "type": "kdeconnect.sms.messages",
>                                                               "body": {
>                                                                 "messages": [
>                                                                   {
>                                                                     "address": "1113002738",
>                                                                     "body": "yoyoyyo",
>                                                                     "date": 1547483593700,
>                                                                     "type": 1,
>                                                                     "read": 0,
>                                                                     "thread_id": 201,
>                                                                     "_id": 9713,
>                                                                     "event": 1
>                                                                   }
>                                                                 ],
>                                                                 "event": "batch_messages"
>                                                               }
>                                                             }
> Jan 14 11:33:14 org.gnome.Shell.Extensions.GSConnect[9078]: [/service/core.js:receive/<:311]: Motorola Moto G: {
>                                                               "id": 1547483593987,
>                                                               "type": "kdeconnect.telephony",
>                                                               "body": {
>                                                                 "event": "sms",
>                                                                 "messageBody": "yoyoyyo",
>                                                                 "phoneNumber": "1113002738"
>                                                               }
>                                                             }
> Jan 14 11:33:14 org.gnome.Shell.Extensions.GSConnect[9078]: [/service/core.js:receive/<:311]: Motorola Moto G: {
>                                                               "id": 1547483594002,
>                                                               "type": "kdeconnect.telephony",
>                                                               "body": {
>                                                                 "event": "sms",
>                                                                 "messageBody": "yoyoyyo",
>                                                                 "phoneNumber": "1113002738"
>                                                               }
>                                                             }
> Jan 14 11:33:14 org.gnome.Shell.Extensions.GSConnect[9078]: [/service/core.js:receive/<:311]: Motorola Moto G: {
>                                                               "id": 1547483594017,
>                                                               "type": "kdeconnect.telephony",
>                                                               "body": {
>                                                                 "event": "sms",
>                                                                 "messageBody": "yoyoyyo",
>                                                                 "phoneNumber": "1113002738"
>                                                               }
>                                                             }
> Jan 14 11:33:14 org.gnome.Shell.Extensions.GSConnect[9078]: [/service/core.js:receive/<:311]: Motorola Moto G: {
>                                                               "id": 1547483594033,
>                                                               "type": "kdeconnect.telephony",
>                                                               "body": {
>                                                                 "event": "sms",
>                                                                 "messageBody": "yoyoyyo",
>                                                                 "phoneNumber": "1113002738"
>                                                               }
>                                                             }
> Jan 14 11:33:14 org.gnome.Shell.Extensions.GSConnect[9078]: [/service/core.js:receive/<:311]: Motorola Moto G: {
>                                                               "id": 1547483594065,
>                                                               "type": "kdeconnect.sms.messages",
>                                                               "body": {
>                                                                 "messages": [
>                                                                   {
>                                                                     "address": "1113002738",
>                                                                     "body": "yoyoyyo",
>                                                                     "date": 1547483593700,
>                                                                     "type": 1,
>                                                                     "read": 0,
>                                                                     "thread_id": 201,
>                                                                     "_id": 9713,
>                                                                     "event": 1
>                                                                   }
>                                                                 ],
>                                                                 "event": "batch_messages"
>                                                               }
>                                                             }
> Jan 14 11:33:14 org.gnome.Shell.Extensions.GSConnect[9078]: [/service/core.js:receive/<:311]: Motorola Moto G: {
>                                                               "id": 1547483594056,
>                                                               "type": "kdeconnect.telephony",
>                                                               "body": {
>                                                                 "event": "sms",
>                                                                 "messageBody": "yoyoyyo",
>                                                                 "phoneNumber": "1113002738"
>                                                               }
>                                                             }
> Jan 14 11:33:14 org.gnome.Shell.Extensions.GSConnect[9078]: [/service/core.js:receive/<:311]: Motorola Moto G: {
>                                                               "id": 1547483594074,
>                                                               "type": "kdeconnect.telephony",
>                                                               "body": {
>                                                                 "event": "sms",
>                                                                 "messageBody": "yoyoyyo",
>                                                                 "phoneNumber": "1113002738"
>                                                               }
>                                                             }
> Jan 14 11:33:14 org.gnome.Shell.Extensions.GSConnect[9078]: [/service/core.js:receive/<:311]: Motorola Moto G: {
>                                                               "id": 1547483594088,
>                                                               "type": "kdeconnect.telephony",
>                                                               "body": {
>                                                                 "event": "sms",
>                                                                 "messageBody": "yoyoyyo",
>                                                                 "phoneNumber": "1113002738"
>                                                               }
>                                                             }
> Jan 14 11:33:14 org.gnome.Shell.Extensions.GSConnect[9078]: [/service/core.js:receive/<:311]: Motorola Moto G: {
>                                                               "id": 1547483594103,
>                                                               "type": "kdeconnect.telephony",
>                                                               "body": {
>                                                                 "event": "sms",
>                                                                 "messageBody": "yoyoyyo",
>                                                                 "phoneNumber": "1113002738"
>                                                               }
>                                                             }
> Jan 14 11:33:15 org.gnome.Shell.Extensions.GSConnect[9078]: [/service/core.js:receive/<:311]: Motorola Moto G: {
>                                                               "id": 1547483594118,
>                                                               "type": "kdeconnect.telephony",
>                                                               "body": {
>                                                                 "event": "sms",
>                                                                 "messageBody": "yoyoyyo",
>                                                                 "phoneNumber": "1113002738"
>                                                               }
>                                                             }
> Jan 14 11:33:15 org.gnome.Shell.Extensions.GSConnect[9078]: [/service/core.js:receive/<:311]: Motorola Moto G: {
>                                                               "id": 1547483594134,
>                                                               "type": "kdeconnect.telephony",
>                                                               "body": {
>                                                                 "event": "sms",
>                                                                 "messageBody": "yoyoyyo",
>                                                                 "phoneNumber": "1113002738"
>                                                               }
>                                                             }
> Jan 14 11:33:15 org.gnome.Shell.Extensions.GSConnect[9078]: [/service/core.js:receive/<:311]: Motorola Moto G: {
>                                                               "id": 1547483594149,
>                                                               "type": "kdeconnect.telephony",
>                                                               "body": {
>                                                                 "event": "sms",
>                                                                 "messageBody": "yoyoyyo",
>                                                                 "phoneNumber": "1113002738"
>                                                               }
>                                                             }
> Jan 14 11:33:15 org.gnome.Shell.Extensions.GSConnect[9078]: [/service/core.js:receive/<:311]: Motorola Moto G: {
>                                                               "id": 1547483594165,
>                                                               "type": "kdeconnect.telephony",
>                                                               "body": {
>                                                                 "event": "sms",
>                                                                 "messageBody": "yoyoyyo",
>                                                                 "phoneNumber": "1113002738"
>                                                               }
>                                                             }
> Jan 14 11:33:15 org.gnome.Shell.Extensions.GSConnect[9078]: [/service/core.js:receive/<:311]: Motorola Moto G: {
>                                                               "id": 1547483594180,
>                                                               "type": "kdeconnect.telephony",
>                                                               "body": {
>                                                                 "event": "sms",
>                                                                 "messageBody": "yoyoyyo",
>                                                                 "phoneNumber": "1113002738"
>                                                               }
>                                                             }
> Jan 14 11:33:15 org.gnome.Shell.Extensions.GSConnect[9078]: [/service/core.js:receive/<:311]: Motorola Moto G: {
>                                                               "id": 1547483594238,
>                                                               "type": "kdeconnect.sms.messages",
>                                                               "body": {
>                                                                 "messages": [
>                                                                   {
>                                                                     "address": "1113002738",
>                                                                     "body": "yoyoyyo",
>                                                                     "date": 1547483593700,
>                                                                     "type": 1,
>                                                                     "read": 0,
>                                                                     "thread_id": 201,
>                                                                     "_id": 9713,
>                                                                     "event": 1
>                                                                   }
>                                                                 ],
>                                                                 "event": "batch_messages"
>                                                               }
>                                                             }
> Jan 14 11:33:15 org.gnome.Shell.Extensions.GSConnect[9078]: [/service/core.js:receive/<:311]: Motorola Moto G: {
>                                                               "id": 1547483594348,
>                                                               "type": "kdeconnect.sms.messages",
>                                                               "body": {
>                                                                 "messages": [
>                                                                   {
>                                                                     "address": "1113002738",
>                                                                     "body": "yoyoyyo",
>                                                                     "date": 1547483593700,
>                                                                     "type": 1,
>                                                                     "read": 0,
>                                                                     "thread_id": 201,
>                                                                     "_id": 9713,
>                                                                     "event": 1
>                                                                   }
>                                                                 ],
>                                                                 "event": "batch_messages"
>                                                               }
>                                                             }
> Jan 14 11:33:15 org.gnome.Shell.Extensions.GSConnect[9078]: [/service/core.js:receive/<:311]: Motorola Moto G: {
>                                                               "id": 1547483594562,
>                                                               "type": "kdeconnect.sms.messages",
>                                                               "body": {
>                                                                 "messages": [
>                                                                   {
>                                                                     "address": "1113002738",
>                                                                     "body": "yoyoyyo",
>                                                                     "date": 1547483593700,
>                                                                     "type": 1,
>                                                                     "read": 0,
>                                                                     "thread_id": 201,
>                                                                     "_id": 9713,
>                                                                     "event": 1
>                                                                   }
>                                                                 ],
>                                                                 "event": "batch_messages"
>                                                               }
>                                                             }
> Jan 14 11:33:15 org.gnome.Shell.Extensions.GSConnect[9078]: [/service/core.js:receive/<:311]: Motorola Moto G: {
>                                                               "id": 1547483594611,
>                                                               "type": "kdeconnect.sms.messages",
>                                                               "body": {
>                                                                 "messages": [
>                                                                   {
>                                                                     "address": "1113002738",
>                                                                     "body": "yoyoyyo",
>                                                                     "date": 1547483593700,
>                                                                     "type": 1,
>                                                                     "read": 0,
>                                                                     "thread_id": 201,
>                                                                     "_id": 9713,
>                                                                     "event": 1
>                                                                   }
>                                                                 ],
>                                                                 "event": "batch_messages"
>                                                               }
>                                                             }
> Jan 14 11:33:15 org.gnome.Shell.Extensions.GSConnect[9078]: [/service/core.js:receive/<:311]: Motorola Moto G: {
>                                                               "id": 1547483594645,
>                                                               "type": "kdeconnect.sms.messages",
>                                                               "body": {
>                                                                 "messages": [
>                                                                   {
>                                                                     "address": "1113002738",
>                                                                     "body": "yoyoyyo",
>                                                                     "date": 1547483593700,
>                                                                     "type": 1,
>                                                                     "read": 0,
>                                                                     "thread_id": 201,
>                                                                     "_id": 9713,
>                                                                     "event": 1
>                                                                   }
>                                                                 ],
>                                                                 "event": "batch_messages"
>                                                               }
>                                                             }
> Jan 14 11:33:15 org.gnome.Shell.Extensions.GSConnect[9078]: [/service/core.js:receive/<:311]: Motorola Moto G: {
>                                                               "id": 1547483594669,
>                                                               "type": "kdeconnect.sms.messages",
>                                                               "body": {
>                                                                 "messages": [
>                                                                   {
>                                                                     "address": "1113002738",
>                                                                     "body": "yoyoyyo",
>                                                                     "date": 1547483593700,
>                                                                     "type": 1,
>                                                                     "read": 0,
>                                                                     "thread_id": 201,
>                                                                     "_id": 9713,
>                                                                     "event": 1
>                                                                   }
>                                                                 ],
>                                                                 "event": "batch_messages"
>                                                               }
>                                                             }
> Jan 14 11:33:15 org.gnome.Shell.Extensions.GSConnect[9078]: [/service/core.js:receive/<:311]: Motorola Moto G: {
>                                                               "id": 1547483594697,
>                                                               "type": "kdeconnect.sms.messages",
>                                                               "body": {
>                                                                 "messages": [
>                                                                   {
>                                                                     "address": "1113002738",
>                                                                     "body": "yoyoyyo",
>                                                                     "date": 1547483593700,
>                                                                     "type": 1,
>                                                                     "read": 0,
>                                                                     "thread_id": 201,
>                                                                     "_id": 9713,
>                                                                     "event": 1
>                                                                   }
>                                                                 ],
>                                                                 "event": "batch_messages"
>                                                               }
>                                                             }
> Jan 14 11:33:15 org.gnome.Shell.Extensions.GSConnect[9078]: [/service/core.js:receive/<:311]: Motorola Moto G: {
>                                                               "id": 1547483594699,
>                                                               "type": "kdeconnect.notification",
>                                                               "body": {
>                                                                 "id": "0|com.android.mms|123|null|10028",
>                                                                 "isCancel": true
>                                                               }
>                                                             }
> Jan 14 11:33:15 org.gnome.Shell.Extensions.GSConnect[9078]: [/service/core.js:receive/<:311]: Motorola Moto G: {
>                                                               "id": 1547483594725,
>                                                               "type": "kdeconnect.sms.messages",
>                                                               "body": {
>                                                                 "messages": [
>                                                                   {
>                                                                     "address": "1113002738",
>                                                                     "body": "yoyoyyo",
>                                                                     "date": 1547483593700,
>                                                                     "type": 1,
>                                                                     "read": 0,
>                                                                     "thread_id": 201,
>                                                                     "_id": 9713,
>                                                                     "event": 1
>                                                                   }
>                                                                 ],
>                                                                 "event": "batch_messages"
>                                                               }
>                                                             }
> Jan 14 11:33:15 org.gnome.Shell.Extensions.GSConnect[9078]: [/service/core.js:receive/<:311]: Motorola Moto G: {
>                                                               "id": 1547483594789,
>                                                               "type": "kdeconnect.sms.messages",
>                                                               "body": {
>                                                                 "messages": [
>                                                                   {
>                                                                     "address": "1113002738",
>                                                                     "body": "yoyoyyo",
>                                                                     "date": 1547483593700,
>                                                                     "type": 1,
>                                                                     "read": 0,
>                                                                     "thread_id": 201,
>                                                                     "_id": 9713,
>                                                                     "event": 1
>                                                                   }
>                                                                 ],
>                                                                 "event": "batch_messages"
>                                                               }
>                                                             }
> Jan 14 11:33:16 org.gnome.Shell.Extensions.GSConnect[9078]: [/service/core.js:receive/<:311]: Motorola Moto G: {
>                                                               "id": 1547483594829,
>                                                               "type": "kdeconnect.sms.messages",
>                                                               "body": {
>                                                                 "messages": [
>                                                                   {
>                                                                     "address": "1113002738",
>                                                                     "body": "yoyoyyo",
>                                                                     "date": 1547483593700,
>                                                                     "type": 1,
>                                                                     "read": 0,
>                                                                     "thread_id": 201,
>                                                                     "_id": 9713,
>                                                                     "event": 1
>                                                                   }
>                                                                 ],
>                                                                 "event": "batch_messages"
>                                                               }
>                                                             }
> Jan 14 11:33:16 org.gnome.Shell.Extensions.GSConnect[9078]: [/service/core.js:receive/<:311]: Motorola Moto G: {
>                                                               "id": 1547483594847,
>                                                               "type": "kdeconnect.sms.messages",
>                                                               "body": {
>                                                                 "messages": [
>                                                                   {
>                                                                     "address": "1113002738",
>                                                                     "body": "yoyoyyo",
>                                                                     "date": 1547483593700,
>                                                                     "type": 1,
>                                                                     "read": 0,
>                                                                     "thread_id": 201,
>                                                                     "_id": 9713,
>                                                                     "event": 1
>                                                                   }
>                                                                 ],
>                                                                 "event": "batch_messages"
>                                                               }
>                                                             }
> Jan 14 11:33:16 org.gnome.Shell.Extensions.GSConnect[9078]: [/service/core.js:receive/<:311]: Motorola Moto G: {
>                                                               "id": 1547483594865,
>                                                               "type": "kdeconnect.sms.messages",
>                                                               "body": {
>                                                                 "messages": [
>                                                                   {
>                                                                     "address": "1113002738",
>                                                                     "body": "yoyoyyo",
>                                                                     "date": 1547483593700,
>                                                                     "type": 1,
>                                                                     "read": 0,
>                                                                     "thread_id": 201,
>                                                                     "_id": 9713,
>                                                                     "event": 1
>                                                                   }
>                                                                 ],
>                                                                 "event": "batch_messages"
>                                                               }
>                                                             }

**Comment by andyholmes** [comment]
This here in your log is the only packet actually related to notifications, and it's a signal that the remote notification has been closed:

```
Jan 14 11:33:15 org.gnome.Shell.Extensions.GSConnect[9078]: [/service/core.js:receive/<:311]: Motorola Moto G: {
    "id": 1547483594699,
    "type": "kdeconnect.notification",
    "body": {
        "id": "0|com.android.mms|123|null|10028",
        "isCancel": true
    }
}
```

All of the other packets are either SMS history (`kdeconnect.sms.messages`) or legacy SMS packets (`kdeconnect.telephony`). So the reason you're not receiving SMS notifications is that the Android app is not sending them to GSConnect.

The best thing to do then is to [file an upstream bug report](https://bugs.kde.org/enter_bug.cgi?product=kdeconnect), with the SMS app you're using, Android OS version and preferably a `logcat` output so the developers can figure out why the notification is not being sent.

**Comment by andyholmes** [comment]
Going to close this one up, since there's nothing I can do to fix this in GSConnect.
