### ISSUE TITLE
Combine indicators when "show indicators" is toggled

### ISSUE THREAD

**Issue by AccountOneOff** [andyholmes/gnome-shell-extension-gsconnect#45]
If two or more devices are connected they show up in their own separate indicators. If at all possible please combine these like the default design.

![screenshot from 2018-02-07 00-11-31](https://user-images.githubusercontent.com/15083452/35905662-c41be7c4-0b9c-11e8-8da3-c02471fb987a.png)

**Comment by andyholmes** [comment]
Probably I won't implement this, it would need a fair amount of extra code to add a third display option, and this is essentially what putting the devices in the User Menu was for. Sorry about that.
