### ISSUE TITLE
SMS History Incorrect for some contacts (not all)

### ISSUE THREAD

**Issue by jgoulet1994** [andyholmes/gnome-shell-extension-gsconnect#456]
**Describe the bug**
Some contact histories (right pane) are correct, and some are *very* old.  The contacts effected are seemingly random.  The most recently sent or received message is displayed correctly for all contacts in the left pane.  To reiterate, only the right pane is incorrect and only for some contacts.

**To Reproduce**
1. Go to messages
2. Click on a contact
3. See incorrect history

**Expected behavior**
Histories are fully synced from android to gsconnect.

**Screenshots**
This is an example screenshot, but note that there are also contacts where history is displayed, but the history is not up to date.  For example, some contacts will display that the most recent message was from April 2018 (even though I had texted them last week).

![image](https://user-images.githubusercontent.com/4106435/52006619-997a3f80-249a-11e9-928d-dd4c967d6096.png)

**Debug output**
I don't think the log provides anything of use.  For this issue.

**System Details (please complete the following information):**
 - GSConnect version: 20
   - Installed from: GitHub Release download
 - GNOME/Shell version: 3.28
 - Distro/Release: Ubuntu 18.04

**GSConnect environment (if applicable):**
 - Paired Device(s): LG V20
 - KDE Connect app version: 1.10
 - Plugin(s): SMS

**Additional context**
I believe this bug is very similar to [#379](https://github.com/andyholmes/gnome-shell-extension-gsconnect/issues/379).

**Comment by andyholmes** [comment]
Hi, thanks for reporting.

Unfortunately without some logged errors it's impossible to determine what might be going wrong. Other than looking through the journal (eg GNOME Logs), the easiest way to get logs for this is to use the generate log feature something like this:

![peek 2019-01-30 13-19](https://user-images.githubusercontent.com/1265208/52013383-c6762480-2491-11e9-996c-0f280b8d2ef9.gif)

Probably after opening the message window you should select one of the covnersations known to be broken. Although debug messages probably aren't relevant here and there should be regular old error messages in GNOME Logs.

**Comment by jgoulet1994** [comment]
Here is the log.  Sorry about that.

[gsconnect_log.txt](https://github.com/andyholmes/gnome-shell-extension-gsconnect/files/2814647/gsconnect_log.txt)

**Comment by jgoulet1994** [comment]
I have attached both logs.

[gsconnect_log.txt](https://github.com/andyholmes/gnome-shell-extension-gsconnect/files/2814682/gsconnect_log.txt)


[log messages.txt](https://github.com/andyholmes/gnome-shell-extension-gsconnect/files/2814674/log.messages.txt)

**Comment by andyholmes** [comment]
There's a number of receives that look like this:

```js
{
  "id": 1548885500968,
  "type": "kdeconnect.sms.messages",
  "body": {
    "messages": [],
    "event": "batch_messages"
  }
}
```
Can I assume you deleted the messages for privacy? If not then it seems that something is going wrong in Android, perhaps the conversation is too large.

I don't see any errors with GSConnect parsing or displaying the conversations. Could you check the file at: `~/.cache/gsconnect/<your-device-id>/sms.json` and see if it looks like the conversation is complete? The dates are in unix epoch, but you should probably be able to figure out if any are missing since they're your texts.

**Comment by andyholmes** [comment]
Hmm, it may be a problem on the Android side, but it's hard to say at this point. Could you try clearing the SMS cache in the *Advanced Settings*, then press the [+] button in the messaging window to resync?

![screenshot from 2019-01-30 14-47-53](https://user-images.githubusercontent.com/1265208/52018131-44d8c380-249e-11e9-82f5-d2a262775e10.png)

**Comment by jgoulet1994** [comment]
The issue persists.  I ran the log generator and this is repeated many times:

`Jan 30 17:54:39 org.gnome.Shell.Extensions.GSConnect[2054]: [/service/core.js:send:352]: John's VS995: {
                                                              "id": 1548888879688,
                                                              "type": "kdeconnect.sms.request_conversation",
                                                              "body": {
                                                                "threadID": 118
                                                              }
                                                            }`

**Comment by andyholmes** [comment]
Are the responses (`/service/core.js:receive`) empty or populated?

**Comment by jgoulet1994** [comment]
They are populated.  For example:
`Jan 30 17:54:39 org.gnome.Shell.Extensions.GSConnect[2054]: [/service/core.js:receive/<:311]: John's VS995: {
                                                              "id": 1548888878279,
                                                              "type": "kdeconnect.contacts.response_uids_timestamps",
                                                              "body": {
                                                                "uids": [`

contains an array of characters (which I believe is the intent from "uids").


Then other instances of `Jan 30 17:54:39 org.gnome.Shell.Extensions.GSConnect[2054]: [/service/core.js:receive/<:311]: John's VS995: {
                                                              "id": 1548888878279,
                                                              "type": "kdeconnect.contacts.response_uids_timestamps",
                                                              "body": {
                                                                "uids": [`

also exist for the text messages ("body": { "messages": ..." and those are populated.  The messages that do not appear in the message history (the right pane) are missing (but still show up in the left pane).

**Comment by jgoulet1994** [comment]
Here is an example of a populated message:

`Jan 30 17:54:41 org.gnome.Shell.Extensions.GSConnect[2054]: [/service/core.js:receive/<:311]: John's VS995: {
                                                              "id": 1548888880271,
                                                              "type": "kdeconnect.sms.messages",
                                                              "body": {
                                                                "messages": [
                                                                  {
                                                                    "address": "(removed)",
                                                                    "body": "this is a test",
                                                                    "date": 1548827236117,
                                                                    "type": 1,
                                                                    "read": 1,
                                                                    "thread_id": 18,
                                                                    "_id": 29380,
                                                                    "event": 1
                                                                  },`

I removed the phone number, but everything else was left as is.

**Comment by andyholmes** [comment]
Can you give me an example of one of the messages that's not being shown that should be? The only difference between the summaries (left) and the message list (right) is that the message list ignores messages with `type` other than `1` or `2`, since these rare cases caused errors to be thrown for another user.

**Comment by jgoulet1994** [comment]
The only messages appearing in the logs are messages that show up properly in the message list.  All messages appear to have "type": 1 or 2.  Oddly enough, sms.json contains all sms messages that have been sent and received. 

I noticed another thing.  In the message list, sometimes the message history displays a message that was actually sent by a different contact.  I think I have found something though.  Is each instance of 

`/service/core.js:receive/<:311]: John's VS995: {
                                                              "id": 1548901983990,
                                                              "type": "kdeconnect.sms.messages",
                                                              "body": {
                                                                "messages": [
                                                                  {` 

supposed to represent a different contact?  I noticed that there are some cases where there are different addresses inside of one thread_id (which is all under an instance of /service/core.js:receive).  The address correctly matches the content in the body, but displays under an incorrect contact in the message list.

Below is an example of this inside my log.  I changed the numbers and the content, but these are both under the same /service/core.js;receive 


`               {
                                                                    "address": "Number A",
                                                                    "body": "Content A",
                                                                    "date": 1495829850000,
                                                                    "type": 1,
                                                                    "read": 1,
                                                                    "thread_id": 6,
                                                                    "_id": 21962,
                                                                    "event": 1
                                                                  },`

`                                                                  {
                                                                    "address": "Number B",
                                                                    "body": "Content B",
                                                                    "date": 1492328134000,
                                                                    "type": 2,
                                                                    "read": 1,
                                                                    "thread_id": 6,
                                                                    "_id": 1030,
                                                                    "event": 1
                                                                  },`

**Comment by andyholmes** [comment]
> The only messages appearing in the logs are messages that show up properly in the message list. All messages appear to have "type": 1 or 2. Oddly enough, sms.json contains all sms messages that have been sent and received.

GSConnect will only request threads for new or unknown messages, so it's normal that not all messages are in the debug logs.

> I noticed another thing. In the message list, sometimes the message history displays a message that was actually sent by a different contact. I think I have found something though. Is each instance of...

Generally Android can send whatever it wants. When a client first requests conversations (`kdeconnect.sms.request_conversations`) Android responds with a digest of the last message in each thread. This is a list (`[]`) of message objects (`{address, thread_id, _id, date}`) we take the `thread_id` from and use to request the full conversation for any threads where the newest message has a later `date` that the one we have cached for that `thread_id`.

> I noticed that there are some cases where there are different addresses inside of one thread_id (which is all under an instance of /service/core.js:receive). The address correctly matches the content in the body, but displays under an incorrect contact in the message list.

There are a couple different ways for `address` to be formatted (eg. local dialing, human readable, E.164, etc), but they should be effectively the same and each `thread_id` should only have messages from one contact (since SMS doesn't support multi-recipient conversations). If a `thread_id` contains messages from different contacts that will definitely confuse GSConnect.

Since `thread_id` is how conversations are requested and received, as well as ordered internally by `_id`, there may not be much that could be done about this. Creating a whole new sorting algorithm on top of Android's is probably not possible if we can't rely on SMS threads (`thread_id`) being unique to a contact, and messages (`_id`) being ordered and unique to a thread.

The Sms code in [kdeconnect-android](https://invent.kde.org/kde/kdeconnect-android/blob/master/src/org/kde/kdeconnect/Helpers/SMSHelper.java) is fairly straightforward, so it doesn't seem to be and obvious problem with the app, however KDE Connect still hasn't shipped their SMS app so there has been very little testing of this outside of GSConnect. I've messaged the developer of the SMS plugin, so I'll see what he has to say.

**Comment by jgoulet1994** [comment]
Then I think the problem lies in that thread_id **does** contain messages from different contacts.  

Additionally, messages appear properly while gsconnect is open.  For example, if I send a text message (using my phone or gsconnect) the message will display properly in the message pane (right), the same occurs if I receive a message while gsconnect is running.  These messages do not remain in the message pane after a reboot.

I guess it could also be device / application specific.  I am using an LG V20 with Textra as my messaging app.

**Comment by andyholmes** [comment]
So I talked with the upstream KDE COnnect developer about this and took a look through the related code in Android, and it seems like it's most likely an issue in Textra somehow.

I guess what's confusing is I assume messages are all working in Textra properly,  so my best guess would Textra is not using the SMS database `thread_id` field in the standard manner. I think the next step would be to ask the Textra developers if that is the case.

The only other option to rewrite all the SMS handling code to avoid the `thread_id` field, but that would mean a significant performance hit and resyncing all SMS history on any change.

**Comment by jgoulet1994** [comment]
I think I have resolved the issue.  The steps I took are as follows:

1.  Backup SMS database (I used SMS Backup and Restore on the Google Play Store)
2.  Delete SMS database (SMS Backup and Restore can do this, you need root otherwise).  
3.  Restore SMS backup
4.  "Resync" using Textra (Settings > About > Resync Textra).

I will report back if the issue reoccurs within the next few days.

**Comment by jgoulet1994** [comment]
Gsconnect appears to be receiving texts appropriately!  There is a new issue though (i don't know if you want me to start a new issue).

**Issue**
Clicking on a message does not mark it as read in the gsconnect window (even after restart).  Similarly, new messages do not come to the top in the summaries (left) pane.  If I clear the cache and resync, both the summaries and the message pane are updated properly.  I believe that the window is not updating sms.json for some reason.

**Screenshots**
![image](https://user-images.githubusercontent.com/4106435/52356364-10b35480-2a02-11e9-8f20-0fdd1f3b322b.png)

In the attached image, notice that the newest message (at the bottom) was not moved to the top. Clicking on that message does not remove the bold text (remains marked as unread).  

**Support Log**
The support log does not give much to work with:

`
GSConnect Version: 20
GSConnect Install: user
GJS: 15205
XDG_SESSION_TYPE: x11
GDMSESSION: ubuntu-communitheme-snap
--------------------------------------------------------------------------------
-- Logs begin at Tue 2019-01-29 23:22:25 EST, end at Wed 2019-02-06 11:30:40 EST. --
Feb 06 11:30:40 gjs[2275]: GtkDialog mapped without a transient parent. This is discouraged.
`

**Comment by jgoulet1994** [comment]
Related to my previous comment, logging out and logging back in will update the left pane to sort correctly.  The bolded messages remain that way unless I mark the message as read from my phone, then log out / log in.

**Comment by andyholmes** [comment]
> Clicking on a message does not mark it as read in the gsconnect window (even after restart).

That's expected behaviour, really. Android won't give permission for a 3rd part app to change the READ status of message. The bold could be removed in GSConnect by manually marking read, but it would revert at the next sync. `sms.json` is strictly a cache of the remote device's SMS database.

> In the attached image, notice that the newest message (at the bottom) was not moved to the top. Clicking on that message does not remove the bold text (remains marked as unread).

The sort order can be fixed, a sort just needs to be triggered when the conversations are updated. As with above, the read status can't be changed from GSConnect, though.

**Comment by jgoulet1994** [comment]
Gsconnect seems to be working properly now.
