### ISSUE TITLE
Glitchy Files-sub-menu animations with gnome-shell 3.31

### ISSUE THREAD

**Issue by jnsh** [andyholmes/gnome-shell-extension-gsconnect#459]
The animations of the "Files" sub-menu in gnome-shell device-menu has some oddities with gnome-shell 3.31.

Here's a slowed down gif of the animations on gnome-shell 3.31. Pay attention to the right edge of the menu, the "Do not disturb" on/off switch, and battery charge indicator.
![gsconnect331](https://user-images.githubusercontent.com/39574454/52271661-f9665f80-294c-11e9-931b-f3ad05e83006.gif)

I'm quite sure this is unrelated to #458. I can bisect the commit that introduced this issue later, if this isn't something obvious.

**Comment by andyholmes** [comment]
Well, the sub menu animation has always been pretty hacky. It does something similar in 3.30, but I'm not sure I'll be able to do anything about this until 3.32 is out and I get a chance to test it. More than likely this is due to performance improvements in Clutter just making the effect visible.

Ill have a look when I get a chance.

**Comment by jnsh** [comment]
I bisected gnome-shell anyway, and it appears that [the removal of Shell.GenericContainer](https://gitlab.gnome.org/GNOME/gnome-shell/merge_requests/153) caused this.

**Comment by ferdnyc** [comment]
This actually seems like it's sorted itself out, at least on GNOME 3.32.2 on my now-upgraded Fedora 30 box. The only weirdness is the momentary visibility of the sliding sections, to the right of the menu area, but it's really not a concern. (Ignore the flash right after the first click, that's just an OBS capture glitch.)

![GSConnect-SubpanelAnimF30](https://user-images.githubusercontent.com/538020/58371687-70663a80-7ee1-11e9-836f-8fba80473549.gif)

(In unrelated news, it appears that shared-folder mounting is now working again on my system. Not sure if it was the F30 upgrade that fixed that, too, but I'll take it.)

**Comment by ferdnyc** [comment]
...OK, I guess actually this is doing the same thing as in @jnsh 's original report. It's just faster, and so not as noticeable. \*shrug\*

**Comment by andyholmes** [comment]
Yeah, I'm not very proficient at using clipping areas and stuff in Clutter. I've been meaning to take a look at this, but I find working with stuff like that very arduous :P

**Comment by Pajn** [comment]
This bug is extreamly noticable with multiple displays when you have a secondary monitor to the right of the primary display. The whole submenu is rendered on the secondary screen and then slid into the monitor on the correct screen. I don't know how to create these fancy clips but it's fantastically hideous :smile:

**Comment by ferdnyc** [comment]
> This bug is extremely noticeable with multiple displays when you have a secondary monitor to the right of the primary display. The whole submenu is rendered on the secondary screen and then slid into the monitor on the correct screen.

Ouch! 🤦‍♂️ I saw that coming as soon as I started reading your first sentence.

@andyholmes I wonder if you could use a [GtkRevealer](https://developer.gnome.org/gtk3/stable/GtkRevealer.html) to show/hide the submenu, rather than hand-animating the transition?

**Comment by andyholmes** [comment]
Should be (mostly fixed) in b39318a4. It's not really doing a true "viewport pan", so if you run it real slow it's not so glorious, but it's much better.

@ferdnyc unfortunately it's all Clutter in GNOME Shell. I had a look a gtkstack.c to see how they did it, but it looks like Gtk3 does all this stuff with vanilla cairo. Clutter on the other hand, has about a half-dozen methods for tweening/animations, 5/6 of which are deprecated, so finding good examples was a lost cause :(
