### ISSUE TITLE
segfault with glib-2.59 in Ubuntu 19.04

### ISSUE THREAD

**Issue by veyselerden** [andyholmes/gnome-shell-extension-gsconnect#468]
**Describe the bug**
It crashes and restarts frequently, the icon appears and disappears for a second and slows down whole system until I uninstall it.

**To Reproduce**
I don't think it's reproducable as probably I am the only one encounters with this strange bug.

**Expected behavior**
not crashing

**Screenshots**
I have a gif:

![2019-02-18 19-04-43](https://user-images.githubusercontent.com/12845347/52963472-dd34da80-33b0-11e9-9e7a-6ad1b92417ce.gif)

**Debug output**
It crashes and restarts frequently so I can't gather a debug file. I look into Logs app but it just says something like "gsconnect service started successfully" and keeps giving this output as it crashes and restarts again.

```

```

**System Details (please complete the following information):**
 - GSConnect version: [20]
   - Installed from: [both extensions.gnome.org and git]
 - GNOME/Shell version: [3.30 - 3.31.90]
 - Distro/Release: [Ubuntu 19.04 - Fedora 29/30(current Rawhide)]

**Additional**
I've installed every required package (AFA the ones I got from your wiki)

**Comment by andyholmes** [comment]
Hi, you can try manually enable debug logging using `dconf`:

    $ dconf write /org/gnome/shell/extensions/gsconnect/debug true

However GSConnect hasn't been tested with Gnome 3.32 so I don't consider it to be officially supported yet.

**Comment by payonpowbl** [comment]
Gnome 3.32 is only available on Fedora Rawhide at the moment. This exists in 3.30 either. I'll post the debug.

**Comment by payonpowbl** [comment]
Unfortunately, there is no such key in dconf so I am not able to enable it with both gui and the command you've given

![screenshot from 2019-02-19 08-33-30](https://user-images.githubusercontent.com/12845347/52992410-8f0bef80-3421-11e9-9ae8-2b45fff62283.png)

**Comment by andyholmes** [comment]
The logged messages will be in journalctl or GNOME Logs.

**Comment by payonpowbl** [comment]
This is what's written in journalctl:

```
Feb 19 09:37:41 ubuntu-PC gnome-software[1458]: failed to rescan: Failed to parse /home/xit/.local/share/applications/org.gnome.Shell.Extensions.GSConnect.desktop file: cannot process file of type application/x-desktop (ntp.ubuntu.com).
Feb 19 09:37:47 ubuntu-PC gnome-shell[1065]: JS ERROR: ReferenceError: debug is not defined
                                             _init_async/<@/home/xit/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/extension.js:175:25
Feb 19 09:37:47 ubuntu-PC dbus-daemon[819]: [session uid=1000 pid=819] Activating service name='org.gnome.Shell.Extensions.GSConnect' requested by ':1.21' (uid=1000 pid=1065 comm="/usr/bin/gnome-shell " label="unconfined")
Feb 19 09:37:47 ubuntu-PC org.gnome.Shell.Extensions.GSConnect[1944]: [/service/core.js::23]: "Setting socket options for Linux"
Feb 19 09:37:47 ubuntu-PC dbus-daemon[819]: [session uid=1000 pid=819] Successfully activated service 'org.gnome.Shell.Extensions.GSConnect'
Feb 19 09:37:47 ubuntu-PC org.gnome.Shell.Extensions.GSConnect[1944]: [/service/daemon.js:vfunc_startup:661]: "Loading 0 device(s) from cache"
Feb 19 09:37:47 ubuntu-PC org.gnome.Shell.Extensions.GSConnect[1944]: [/service/lan.js:broadcast:278]: "Broadcasting to LAN"
Feb 19 09:37:47 ubuntu-PC kernel: traps: gjs[1944] general protection ip:7fc4ec6c8fd8 sp:7ffea3583120 error:0 in libgio-2.0.so.0.5902.0[7fc4ec668000+101000]
```

That and this repeating endlessly:

```
Feb 19 09:37:47 ubuntu-PC dbus-daemon[819]: [session uid=1000 pid=819] Activating service name='org.gnome.Shell.Extensions.GSConnect' requested by ':1.21' (uid=1000 pid=1065 comm="/usr/bin/gnome-shell " label="unconfined")
Feb 19 09:37:47 ubuntu-PC org.gnome.Shell.Extensions.GSConnect[1963]: [/service/core.js::23]: "Setting socket options for Linux"
Feb 19 09:37:47 ubuntu-PC dbus-daemon[819]: [session uid=1000 pid=819] Successfully activated service 'org.gnome.Shell.Extensions.GSConnect'
Feb 19 09:37:47 ubuntu-PC org.gnome.Shell.Extensions.GSConnect[1963]: [/service/daemon.js:vfunc_startup:661]: "Loading 0 device(s) from cache"
Feb 19 09:37:47 ubuntu-PC org.gnome.Shell.Extensions.GSConnect[1963]: [/service/lan.js:broadcast:278]: "Broadcasting to LAN"
Feb 19 09:37:47 ubuntu-PC kernel: traps: gjs[1963] general protection ip:7fd500b22fd8 sp:7ffd8c08aa00 error:0 in libgio-2.0.so.0.5902.0[7fd500ac2000+101000]
```

Package containing `libgio-2.0.so.0` is `libglib2.0-0` and it's installed with all dependencies. So it's not lacking.

**Comment by andyholmes** [comment]
This issue is being tracked upstream at https://gitlab.gnome.org/GNOME/gjs/issues/227.

If you can reproduce this in Ubuntu 18.10 with GNOME 3.30, could you please post logs for that as well? As far as I can tell this issue only happens with glib2-2.59.x which isn't yet shipped with a stable distribution.

**Comment by payonpowbl** [comment]
Tried both 18.04 and 18.10. Both seems to work.

**Comment by andyholmes** [comment]
Fix has been merged upstream, closing now.
