### ISSUE TITLE
No devices are showing up on KDE app.

### ISSUE THREAD

**Issue by abhish3kk** [andyholmes/gnome-shell-extension-gsconnect#47]
I have been trying to get it work for quite sometime now. I can see the Mobile Menu in Gnome system menu. Also, I get this if I turn on debug mode
```
JS LOG: UdpListener: using port 1716
JS LOG: TcpListener: using port 1716
JS LOG: 0 devices loaded from cache
JS LOG: UdpListener: using port 1716
JS LOG: TcpListener: using port 1716
JS LOG: 0 devices loaded from cache
JS LOG: UdpListener: using port 1716
JS LOG: TcpListener: using port 1716
JS LOG: 0 devices loaded from cache
```
I just installed ubuntu 17.10. Using gnome version 26.2 and GSconnect v9.

**Comment by andyholmes** [comment]
Sorry to hear your not having an easy time, but it looks like GSConnect is running fine.

* Are you sure ports 1716-1764 are open on your network for UDP/TCP?
* Are there any leftover running KDE Connect processes on your desktop?

**Comment by abhish3kk** [comment]
For some reason, I broke my system and had to re-install Ubuntu. I just tried the extension again and it is working now. Thanks.
