### ISSUE TITLE
On Fedora 29 does not connect

### ISSUE THREAD

**Issue by xzj8b3** [andyholmes/gnome-shell-extension-gsconnect#477]
How can I fix it?

GSConnect Version: 19
GSConnect Install: user
GJS: 15403
XDG_SESSION_TYPE: x11
GDMSESSION: gnome-xorg
--------------------------------------------------------------------------------
-- Logs begin at Mon 2019-02-18 12:05:44 CET, end at Sat 2019-03-02 23:24:36 CET. --
mar 02 23:24:09 audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=systemd-localed comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
mar 02 23:24:11 audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=systemd-hostnamed comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
mar 02 23:24:20 geoclue[4160]: Service not used for 60 seconds. Shutting down..
mar 02 23:24:20 audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=geoclue comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
mar 02 23:24:21 realmd[4223]: quitting realmd service after timeout
mar 02 23:24:21 realmd[4223]: stopping service
mar 02 23:24:21 audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=realmd comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
mar 02 23:24:28 gnome-shell[4529]: Ignoring excess values in shadow definition
mar 02 23:24:28 gnome-shell[4529]: Ignoring excess values in shadow definition
mar 02 23:24:28 gnome-shell[4529]: Ignoring excess values in shadow definition
mar 02 23:24:28 gnome-shell[4529]: Ignoring excess values in shadow definition
mar 02 23:24:28 gnome-shell[4529]: Ignoring excess values in shadow definition
mar 02 23:24:28 gnome-shell[4529]: Ignoring excess values in shadow definition
mar 02 23:24:31 gjs[5655]: JS ERROR: TypeError: this.lan is undefined
                           broadcast@/home/xzj8b3/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:198:21
                           _refresh@/home/xzj8b3/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/ui/settings.js:478:13
                           _init@/home/xzj8b3/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/ui/settings.js:452:9
                           _settings@/home/xzj8b3/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:401:28
                           @/home/xzj8b3/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:774:2
mar 02 23:24:36 gjs[5655]: JS ERROR: TypeError: this.lan is undefined
                           broadcast@/home/xzj8b3/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:198:21
                           _refresh@/home/xzj8b3/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/ui/settings.js:478:13
                           @/home/xzj8b3/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:774:2

**Comment by andyholmes** [comment]
Hi, thanks for reporting.

> mar 02 23:24:31 gjs[5655]: JS ERROR: TypeError: this.lan is undefined

This seems to indicate the LAN service failed to start. Can you confirm `kdeconnectd` is [not installed or running](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Help#network-error) and if possible [update to v20](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Installation#install-from-zip)?

**Comment by xzj8b3** [comment]
> Ciao, grazie per aver segnalato.
> 
> > mar 02 23:24:31 gjs [5655]: JS ERRORE: TypeError: this.lan non è definito
> 
> Questo sembra indicare che il servizio LAN non è stato avviato. Puoi confermare che [non](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Help#network-error)`kdeconnectd` è [installato o in esecuzione](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Help#network-error) e se possibile [aggiornare a v20](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Installation#install-from-zip) ?

Of course it is installed and works also in part ...but it continues to return errors

**Comment by xzj8b3** [comment]
> > Ciao, grazie per aver segnalato.
> > > mar 02 23:24:31 gjs [5655]: JS ERRORE: TypeError: this.lan non è definito
> > 
> > 
> > Questo sembra indicare che il servizio LAN non è stato avviato. Puoi confermare che [non](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Help#network-error)`kdeconnectd` è [installato o in esecuzione](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Help#network-error) e se possibile [aggiornare a v20](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Installation#install-from-zip) ?
> 
> Ovviamente è installato e funziona anche in parte ... ma continua a restituire errori

He continues to say that it is linked to an old address .... but it has been re-installed system and disconnected and reconnected several times to try to associate it correctly but nothing!!!!

**Comment by andyholmes** [comment]
Sorry, I see you are translating so there might be confusion.

To be clear: KDE Connect can *not* be installed *or* running. GSConnect + KDE Connect = broken.

    $ killall -9 kdeconnectd

**Comment by xzj8b3** [comment]
> Sorry, I see you are translating so there might be confusion.
> 
> To be clear: KDE Connect can _not_ be installed _or_ running. GSConnect + KDE Connect = broken.
> 
> ```
> $ killall -9 kdeconnectd
> ```

What do I have to do, remove kde connect?

**Comment by xzj8b3** [comment]
> Scusa, vedo che stai traducendo così potrebbe esserci confusione.
> 
> Per essere chiari: KDE Connect _non_ può essere installato _o in_ esecuzione. GSConnect + KDE Connect = rotto.
> 
> ```
> $ killall -9 kdeconnectd
> ```

What should I install then GSConnect does not detect anything

**Comment by xzj8b3** [comment]
> Ciao, grazie per aver segnalato.
> 
> > mar 02 23:24:31 gjs [5655]: JS ERRORE: TypeError: this.lan non è definito
> 
> Questo sembra indicare che il servizio LAN non è stato avviato. Puoi confermare che [non](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Help#network-error)`kdeconnectd` è [installato o in esecuzione](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Help#network-error) e se possibile [aggiornare a v20](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Installation#install-from-zip) ?

[IMG]http://i66.tinypic.com/149zj7m.jpg[/IMG]
Okay now go, what do you need to install on Fedora to mount device?


I had to delete files and caches...now it seems to work

**Comment by xzj8b3** [comment]
> Scusa, vedo che stai traducendo così potrebbe esserci confusione.
> 
> Per essere chiari: KDE Connect _non_ può essere installato _o in_ esecuzione. GSConnect + KDE Connect = rotto.
> 
> ```
> $ killall -9 kdeconnectd
> ```

Do not mount it on Btrfs device

**Comment by andyholmes** [comment]
There are no additional dependencies required for mounting devices.

**Comment by xzj8b3** [comment]
> Non ci sono altre dipendenze necessarie per il montaggio dei dispositivi.

App Applied Solved and all working thanks!
