### ISSUE TITLE
Ubuntu default video player Totem multimedia controls / file sending issue

### ISSUE THREAD

**Issue by willhubs** [andyholmes/gnome-shell-extension-gsconnect#485]
When I first installed gsconnect on Ubuntu 18.10 from the gnome-shell-extensions website, I could not get a few features to work.  

One of the main issues was sending files to the downloads folder on the desktop.  This was fixed by unpair and paring the device a second time.  It has worked flawlessly after that.

The second issue was that the presentation remote was not working in Impress, I fixed this by updating to version 21-rc1

The third issue was that the default video player in Ubuntu, Totem/GNOME Videos, the media controls didn't work.  This is easily fixed by opening Totem, going to Preferences>Plugins and enabling the plugin MPRIS D-Bus Interface.

I was thinking maybe this could/should be added to the wiki but wasn't sure if it was a common or uncommon issue.

**Comment by andyholmes** [comment]
You could add this to the wiki if you want, although there will be countless application specific settings to list that don't really have anything to do with GSConnect. Probably these should be on a separate page than *Help* which is really for issues with GSConnect itself.

**Comment by andyholmes** [comment]
Will close this now; feel free to add it to the wiki if you haven't already.
