### ISSUE TITLE
GUI Missing and service/daemon.js running at just under 100% CPU

### ISSUE THREAD

**Issue by prurigro** [andyholmes/gnome-shell-extension-gsconnect#488]
**Describe the bug**
I'm not sure exactly when this started happening, but I noticed my PC's fan was running high today and opened htop to find `gjs` executing the `service/daemon.js` script at nearly 100% CPU. Disabling Gsconnect wouldn't stop the script either so I had to kill it, and a few seconds after re-enabling Gsconnect the same near 100% cpu usage by `service/daemon.js` started back up.

My phone is able to use gsconnect features like remote input and send files, and a notification pops up when the file arrives on my desktop, but the menu ui doesn't show a phone, and clicking  "Mobile Settings" or the settings icon in gnome tweak tool adds a GSConnect entry to the alt-tab list but no GUI appears.

**To Reproduce**
1. Enable the Gsconnect extension
2. Check `htop` or another process monitor and sort by CPU
3. See `gjs` running `services/daemon.js` at nearly 100%
4. Confirm KDE Connect is connected to GSConnect on your phone
5. Check the gnome menu and see that your phone doesn't appear to be connected
6. Try to open "Mobile Settings" and note "GSConnect" in alt+tab but no GUI 

**Expected behavior**
Running GSConnect doesn't use nearly 100% CPU, does show phone as connected and brings up its GUI when "Mobile Settings" is clicked.

**Debug output**
The runaway process still happens when GSConnect is started after killing KDE Connect on my phone, so there wouldn't be any communication happening.

**System Details (please complete the following information):**
 - GSConnect version: 19
   - Installed from: [e.g. extensions.gnome.org
 - GNOME/Shell version: 3.30.2 however)
 - Distro/Release: Archlinux (up to date as of today)

**GSConnect environment (if applicable):**
 - Paired Device(s): Pixel 2 XL on the final security update of AOSP 8.1 with microg instead of gapps (this hasn't changed for months however, and the issue still occurs without being connected)
 - KDE Connect app version: 1.12 (f-droid)

**Additional context**
I can't say for sure when this started, but I only noticed it for the first time today and a number of non-essential gnome packages were upgraded to 3.32 today as well, so that could be related? Here's the list of packages upgraded to 3.32:

gnome-characters
gnome-contacts
gnome-disk-utility
gnome-documents
gnome-maps
gnome-menus
gnome-user-docs
gnome-weather

Also, glib2 was recently updated to 2.60.0, which caused an issue with gnome-control-center that was fixed with an update to a more recent revision of 3.30.4.

**Comment by andyholmes** [comment]
This is a result of upgrading to glib2 >= 2.60.0. You should upgrade to v21-rc2 and/or wait until the appropriate fix is backported to glib2 on your distribution.

**Comment by prurigro** [comment]
Ahh sorry, I should have looked at the releases and not just read commit messages :) Thanks for pointing me in the right direction-- I guess I'll wait for the rest of 3.32 to arrive and then switch to v21-rc2.
