### ISSUE TITLE
Breaks in Gnome 3.32 on Arch Linux

### ISSUE THREAD

**Issue by Zappo-II** [andyholmes/gnome-shell-extension-gsconnect#489]
**Describe the bug**
After Upgrade of Gnome-Shell to 3.32 on ArchLinux the ShellExtension status states "ERROR" and does not show up in the menu anymore.

**To Reproduce**
1. Install ArchLinux
2. Install Gnome-Shell 3.32
3. Install ShellExtension
4. LogIn

**Expected behavior**
Gnome-Shell-Extension shows Extension to be installed and working, Configuration Dialog is accessible.

**Screenshots**
![Auswahl-20190318-135151-001](https://user-images.githubusercontent.com/31073175/54531258-22830280-4985-11e9-8ba9-f49f2f01ac37.png)

**Debug output**
...none...

```

```

**System Details (please complete the following information):**
 - GSConnect version: latest extensions.gnome.org
   - Installed from: extensions.gnome.org
 - GNOME/Shell version: 3.32
 - Distro/Release: Arch

**GSConnect environment (if applicable):**
 - Paired Device(s): ...irrelevant...?
 - KDE Connect app version: ...irrelevant...?
 - Plugin(s): ...irrelevant...?

**Additional context**
Worked as expected before, nothing else but gnome-shell version changed...

**Comment by Dariasteam** [comment]
Same behaviour here

**Comment by Dariasteam** [comment]
It's fixed using the [latest version](https://github.com/andyholmes/gnome-shell-extension-gsconnect/releases/tag/v21).

**Comment by Zappo-II** [comment]
Can confirm @Dariasteam 

Issue is fixed with [v21](https://github.com/andyholmes/gnome-shell-extension-gsconnect/releases/tag/v21) from git...

```
mkdir temp
cd temp
git clone https://github.com/andyholmes/gnome-shell-extension-gsconnect.git
cd gnome-shell-extension-gsconnect/
meson _build .
ninja -C _build install-zip
```

After that `alt-f2` and `r` ...working...

**Comment by Zappo-II** [comment]
v21 is now confirmed and available via [extensions.gnome.org](https://extensions.gnome.org/extension/1319/gsconnect/) no more need to git clone any more...
