### ISSUE TITLE
Duplicate SMS messages

### ISSUE THREAD

**Issue by aspalding** [andyholmes/gnome-shell-extension-gsconnect#49]
Hello, whenever I receive an SMS message, the chat interface displays five duplicate messages. Here is the relevant debug information: 

```
JS LOG: [gsconnect@andyholmes.github.io]: LanChannel.receive(12345)
JS LOG: [gsconnect@andyholmes.github.io]: Device received:
{"id":1518047754579,"type":"kdeconnect.telephony","body":{"event":"sms","messageBody":"Message
","contactName":"Name","phoneThumbnail":"","phoneNumber":"+11231231234"}}
JS LOG: Received from 'essential'
JS LOG: [gsconnect@andyholmes.github.io]: Telephony: handlePacket()
JS LOG: [gsconnect@andyholmes.github.io]: Telephony: _handleSMS()
JS LOG: [gsconnect@andyholmes.github.io]: Telephony: _hasWindow(+11231231234)
JS LOG: [gsconnect@andyholmes.github.io]: LanChannel.receive(12345)
JS LOG: [gsconnect@andyholmes.github.io]: Device received:
{"id":1518047754603,"type":"kdeconnect.telephony","body":{"event":"sms","messageBody":"Message
","contactName":"Name","phoneThumbnail":"","phoneNumber":"+11231231234"}}
JS LOG: Received from 'essential'
JS LOG: [gsconnect@andyholmes.github.io]: Telephony: handlePacket()
JS LOG: [gsconnect@andyholmes.github.io]: Telephony: _handleSMS()
JS LOG: [gsconnect@andyholmes.github.io]: Telephony: _hasWindow(+11231231234)
JS LOG: [gsconnect@andyholmes.github.io]: LanChannel.receive(12345)
JS LOG: [gsconnect@andyholmes.github.io]: Device received:
{"id":1518047754624,"type":"kdeconnect.telephony","body":{"event":"sms","messageBody":"Message
","contactName":"Name","phoneThumbnail":"","phoneNumber":"+11231231234"}}
JS LOG: Received from 'essential'
JS LOG: [gsconnect@andyholmes.github.io]: Telephony: handlePacket()
JS LOG: [gsconnect@andyholmes.github.io]: Telephony: _handleSMS()
JS LOG: [gsconnect@andyholmes.github.io]: Telephony: _hasWindow(+11231231234)
JS LOG: [gsconnect@andyholmes.github.io]: LanChannel.receive(12345)
JS LOG: [gsconnect@andyholmes.github.io]: Device received:
{"id":1518047754660,"type":"kdeconnect.telephony","body":{"event":"sms","messageBody":"Message
","contactName":"Name","phoneThumbnail":"","phoneNumber":"+11231231234"}}
JS LOG: Received from 'essential'
JS LOG: [gsconnect@andyholmes.github.io]: Telephony: handlePacket()
JS LOG: [gsconnect@andyholmes.github.io]: Telephony: _handleSMS()
JS LOG: [gsconnect@andyholmes.github.io]: Telephony: _hasWindow(+11231231234)
JS LOG: [gsconnect@andyholmes.github.io]: LanChannel.receive(12345)
JS LOG: [gsconnect@andyholmes.github.io]: Device received:
{"id":1518047754685,"type":"kdeconnect.telephony","body":{"event":"sms","messageBody":"Message
","contactName":"Name","phoneThumbnail":"","phoneNumber":"+11231231234"}}
JS LOG: Received from 'essential'
JS LOG: [gsconnect@andyholmes.github.io]: Telephony: handlePacket()
JS LOG: [gsconnect@andyholmes.github.io]: Telephony: _handleSMS()
JS LOG: [gsconnect@andyholmes.github.io]: Telephony: _hasWindow(+11231231234)
JS LOG: [gsconnect@andyholmes.github.io]: LanChannel.receive(12345)
```
I pulled down the the project and was able to build and run it, but I'm actually not receiving texts at all on the master branch, and the chat interface seems to be in limbo on the v10 branch. I'd be interested in looking into this bug!

**Comment by andyholmes** [comment]
Hi, v10 and master are currently pretty unstable. If you've recently updated to KDE Connect 1.7.1 Android, there have been permission changes which you may have to allow in the Android app, and may require you to force-stop the app, and possibly even clear the settings and repair.

> {"id":1518047754579,"type":"kdeconnect.telephony" ...
> {"id":1518047754603,"type":"kdeconnect.telephony" ...
> {"id":1518047754624,"type":"kdeconnect.telephony" ...
> {"id":1518047754660,"type":"kdeconnect.telephony" ...
> {"id":1518047754685,"type":"kdeconnect.telephony" ...

The `id` field here is actually a millsecond timestamp, so these duplicate SMS _are_ being sent by the app, and not mistakenly generated by GSConnect. I had this problem myself on upgrade, although I don't remember how far I had to go to fix it. First try opening the app, accepting any new permissions and force-stopping. If that doesn't work clearing the app data and restarting should do it.

I'd appreciate if you'd inform me of your results, since you're the only other user that's had this same problem as me!

**Comment by aspalding** [comment]
Force quitting the application on my phone seems to have resolved the issue. I checked [bugs.kde.org](https://bugs.kde.org/buglist.cgi?bug_status=__all__&comp=android-&content=multiple%20sms&no_redirect=1&order=component%2Cproduct%2Cchangeddate%20DESC%2Cpriority%2Cbug_severity&product=kdeconnect&query_format=specific), but I'm not seeing anything. 

This extension is pretty cool. I'm glad to see this being implemented for gnome!

**Comment by andyholmes** [comment]
I reported it on the mailing list the day 1.7.1 was released, but perhaps no one else was seeing it yet. I'm glad a force stop is all that needs to be done. Thanks for reporting back.

**Comment by derekatkins** [comment]
@andyholmes -- I am having this issue myself on a Pixel XL -- when an incoming SMS comes I get 5, 6, 8 copies on my laptop desktop.  I have force-stopped the android app, cleared the cache, cleared the data, re-paired... I've done everything I could think of (on the app side) to reset it, but it's still happening to me.  Makes it quite annoying when my screen fills up if I receive ~3 SMS messages in a row!  Any other suggestions?

(I'll note that I'm using kdeconect, and not gsconnect)

**Comment by andyholmes** [comment]
@derekatkins I guess if the bug is in KDE Connect Android your best bet is to file a bug for that: https://bugs.kde.org/enter_bug.cgi?product=kdeconnect

If possible you should try to supply a logcat from that time perios to help the developers track it down.

**Comment by andyholmes** [comment]
> Do you think https://bugs.kde.org/show_bug.cgi?id=401366 applies? Or do I need a new one? I don't really use KDE and definitely don't have a KDE bz account.

@derekatkins This seems related, but what is needed is a bug opened against the Android app with a logcat so the developers can diagnose and fix the problem.

> Is there a non-KDE app I could use instead? I'm happy to swap out to something else if you have a better suggestion?

Not sure what you mean? The Android app is written in Java and doesn't have anything to do with KDE libraries or the desktop. There is no alternative Android app available.
