### ISSUE TITLE
 GSconnect 21 : No device appears in the parameters !

### ISSUE THREAD

**Issue by JPThiel** [andyholmes/gnome-shell-extension-gsconnect#490]
![No device in parametres](https://user-images.githubusercontent.com/48735520/54643033-47b36600-4a96-11e9-913b-bedb6d4f6c4e.png)
**1)** It may be after a first scan of the smartphone folders (that is OK), a second click has no effect to open a folder. Just "Disassemble" before reading again the folder.

**2)** No device appears in the parameters ! and yet GSconnect 21 works with Huawei P9 Lite

_Extension :_ GSconnect version 21 on Ubuntu 18.04.2 LTS  and Gnome 3.28.2
_Smartphone :_ Huawei P9 Lite

**Comment by andyholmes** [comment]
This appears to be a problem with the latest version of KDE Connect Android from the Play Store. I would recommend you install from [F-Droid](https://f-droid.org/packages/org.kde.kdeconnect_tp/).
