### ISSUE TITLE
SFTP: Gvfs broken in kdeconnect-android 1.12

### ISSUE THREAD

**Issue by andyholmes** [andyholmes/gnome-shell-extension-gsconnect#491]
As of kdeconnect-android 1.12 the SFTP plugin has had changes to its backend which break mounting with Gvfs.

It appears Gvfs is expecting output on stdout/stderr that it's no longer receiving which causes a series of assertion failures in `gvfsbackendsftp.c`, eventually resulting in the ssh process exiting.

Manually connecting using `sftp` works, so there is no problem with the server or protocol, however it remains to be seen if this can be fixed externally to Gvfs or if the removal of `sshfs` support will have to be reverted.

**Comment by mavit** [comment]
FWIW, I just updated to KDE Connect for Android version 1.12.3 and found that mounting filesystems from the Android device stopped working.  I'm still running GSConnect 19, which I understand still uses `sshfs`.

**Comment by andyholmes** [comment]
> I'm still running GSConnect 19, which I understand still uses sshfs.

v19 supports `sshfs`, but will still fallback to Gvfs if it's not installed.

**Comment by andyholmes** [comment]
Should be fixed once upstream merges [!35 into kdeconnect-android](https://invent.kde.org/kde/kdeconnect-android/merge_requests/35).

**Comment by andyholmes** [comment]
Fix has been merged upstream. APK for testing purposes only:

[kdeconnect-android-debug.apk.zip](https://github.com/andyholmes/gnome-shell-extension-gsconnect/files/2993280/kdeconnect-android-debug.apk.zip)
