### ISSUE TITLE
Test  with KDEconnect 1.12.4

### ISSUE THREAD

**Issue by JPThiel** [andyholmes/gnome-shell-extension-gsconnect#497]
Just the result of my test:
**1)**  With KDEconnect 1.12.4, messaging works again! Thank you
**2)**  'Files' does not work.
The folder I configured in KDEconnect 1.12.3 appears but does not open.
![Files 0 KO](https://user-images.githubusercontent.com/48735520/54782102-63e20f00-4c1e-11e9-9a88-db194f5e2e42.png)
![Files 1 KO](https://user-images.githubusercontent.com/48735520/54782109-67759600-4c1e-11e9-91b6-f733566012d4.png)

_Thank you for your work._

Ubuntu 18.04.2 and GSconnect21
Huawei P9Lite and KDEconnect 1.12.4

**Comment by cemcoral** [comment]
I believe this is fixed. Update KDEConnect to 1.12.5

**Comment by andyholmes** [comment]
Yep, should be fixed. Albert pushed through a special release for us.
