### ISSUE TITLE
BUG: my laptop is not see my devices

### ISSUE THREAD

**Issue by evgeniy-webmaster** [andyholmes/gnome-shell-extension-gsconnect#507]
**Describe the bug**
Devices (phone and tablet) is not see my laptop and my laptop is not see my devices.
Please, Help me to fix this.

**To Reproduce**

Install gnome-shell-extension-gsconnect on manjaro linux.

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. You can drag-and-drop or cut-and-paste images directly into this edit window, to include them in your report.

**Debug output**

I generate journal in settings, all output from journal:

GSConnect Version: 21
GSConnect Install: user
GJS: 15600
XDG_SESSION_TYPE: x11
GDMSESSION: gnome
--------------------------------------------------------------------------------
-- Logs begin at Sun 2018-10-28 14:17:10 +04, end at Sat 2019-03-30 19:15:34 +04. --
мар 30 19:15:04 gjs[1586]: JS ERROR: Error: 0x40000020 is not a valid value for flags GSocketMsgFlags
                              _onIncomingIdentity@/home/g0thic/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/protocol/lan.js:200:20
                              @/home/g0thic/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:744:2
мар 30 19:15:09 gjs[1586]: JS ERROR: Error: 0x40000020 is not a valid value for flags GSocketMsgFlags
                              _onIncomingIdentity@/home/g0thic/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/protocol/lan.js:200:20
                              @/home/g0thic/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:744:2
мар 30 19:15:14 gjs[1586]: JS ERROR: Error: 0x40000020 is not a valid value for flags GSocketMsgFlags
                              _onIncomingIdentity@/home/g0thic/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/protocol/lan.js:200:20
                              @/home/g0thic/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:744:2
мар 30 19:15:19 gjs[1586]: JS ERROR: Error: 0x40000020 is not a valid value for flags GSocketMsgFlags
                              _onIncomingIdentity@/home/g0thic/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/protocol/lan.js:200:20
                              @/home/g0thic/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:744:2
мар 30 19:15:24 gjs[1586]: JS ERROR: Error: 0x40000020 is not a valid value for flags GSocketMsgFlags
                              _onIncomingIdentity@/home/g0thic/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/protocol/lan.js:200:20
                              @/home/g0thic/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:744:2
мар 30 19:15:29 gjs[1586]: JS ERROR: Error: 0x40000020 is not a valid value for flags GSocketMsgFlags
                              _onIncomingIdentity@/home/g0thic/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/protocol/lan.js:200:20
                              @/home/g0thic/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:744:2
мар 30 19:15:34 org.gnome.Shell.Extensions.GSConnect[1586]: [/service/protocol/lan.js:broadcast:315]: "Broadcasting to LAN"
мар 30 19:15:34 gjs[1586]: JS ERROR: Error: 0x40000020 is not a valid value for flags GSocketMsgFlags
                              _onIncomingIdentity@/home/g0thic/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/protocol/lan.js:200:20
                              @/home/g0thic/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:744:2

```

```

**System Details (please complete the following information):**
 - GSConnect version: 21
   - Installed from: extensions.gnome.org
 - GNOME/Shell version: 3.32
 - Distro/Release: manjaro linux

**GSConnect environment (if applicable):**
 - Paired Device(s): Sumsung s8 and Sumsung Tab A
 - KDE Connect app version: 1.12.6
 - Plugin(s): [if the issue only occurs when using certain plugin(s)]

**Additional context**

**Comment by andyholmes** [comment]
> gjs[1586]: JS ERROR: Error: 0x40000020 is not a valid value for flags GSocketMsgFlags

This error means your system is running a version of glib2 which doesn't include the fix from [!729](https://gitlab.gnome.org/GNOME/glib/merge_requests/729) merged as [f79f7341](https://gitlab.gnome.org/GNOME/glib/commit/f79f7341a0d28481a080b50caa652a4add2d5434). This issue was discussed in #468 in GSConnect and [#227 in gjs](https://gitlab.gnome.org/GNOME/gjs/issues/227).

You should contact the maintainer of the glib package in Manjaro and advise them to update to at least [f79f7341](https://gitlab.gnome.org/GNOME/glib/commit/f79f7341a0d28481a080b50caa652a4add2d5434).

**Comment by evgeniy-webmaster** [comment]
Thank you, I will create bug report to glib manjaro package.
