### ISSUE TITLE
Cant mount Pixel 2

### ISSUE THREAD

**Issue by RobertZito** [andyholmes/gnome-shell-extension-gsconnect#508]
Ever since upgrading GSconnect the system no longer mounts to my phone everything else works bu I cant connect, her are the logs.

GSConnect Version: 21
GSConnect Install: user
GJS: 15205
XDG_SESSION_TYPE: x11
GDMSESSION: pop
--------------------------------------------------------------------------------
-- Logs begin at Fri 2018-10-12 13:07:20 EDT, end at Sat 2019-03-30 14:41:04 EDT. --
Mar 30 14:41:00 gjs[2178]: JS ERROR: google (sftp): Error: No property 'username' in property list (or its value was undefined)
                           _mount@/home/rzito/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/sftp.js:137:22
                           @/home/rzito/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:744:2
Mar 30 14:41:00 gnome-shell[1821]: Object .GSConnectShellIconButton (0x55a39fe70600), has been already finalized. Impossible to get any property from it.
Mar 30 14:41:00 org.gnome.Shell.desktop[1821]: == Stack trace for context 0x55a39faa5340 ==
Mar 30 14:41:00 org.gnome.Shell.desktop[1821]: #0 0x55a39ff5ed90 i   /home/rzito/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/shell/gmenu.js:514 (0x7fc3e72224d8 @ 124)
Mar 30 14:41:00 org.gnome.Shell.desktop[1821]: #1 0x7fff2469ee30 b   self-hosted:922 (0x7fc42c2f12b8 @ 469)
Mar 30 14:41:04 gjs[2178]: GtkDialog mapped without a transient parent. This is discouraged.

**Debug output**
If you have been able to reproduce the problem with debugging enabled (see [instructions in the wiki](wiki/Debugging)), paste any log messages related to this issue between the two ``` lines below.

```

```

**System Details (please complete the following information):**
 - GSConnect version: [e.g. 16, 15, ... (displayed in the GSConnect "About" window)]
   - Installed from: [e.g. extensions.gnome.org, GitHub Release download, distro package, ...]
 - GNOME/Shell version: [e.g. 3.30, 3.28, ...]
 - Distro/Release: [e.g. Ubuntu 18.04, Fedora 29, Arch, ...]

**GSConnect environment (if applicable):**
 - Paired Device(s): [e.g. Galaxy Note 8, Pixel 2, Honor 9, ...]
 - KDE Connect app version: [e.g. ]
 - Plugin(s): [if the issue only occurs when using certain plugin(s)]

**Comment by andyholmes** [comment]
> Mar 30 14:41:00 gjs[2178]: JS ERROR: google (sftp): Error: No property 'username' in property list (or its value was undefined)

This error means that the username for the Sftp server was not received from the Android app. Most likely you have not setup the SFTP plugin in Android since upgrading to 1.12.x or there is bug in the app.

As of adf2dd5 we no longer use user/password authentication, so you can check your settings in the Android up, [file an upstream bug](https://bugs.kde.org/) for the app, or use a Zip built from >= adf2dd5 ([gsconnect@andyholmes.github.io.zip](https://github.com/andyholmes/gnome-shell-extension-gsconnect/files/3025883/gsconnect%40andyholmes.github.io.zip)).
