### ISSUE TITLE
copy from typora will get null

### ISSUE THREAD

**Issue by ruinb0w** [andyholmes/gnome-shell-extension-gsconnect#509]
**Bug description**
Copy from [typora](https://typora.io/) will get "null" string on my phone, but copy from other apps will be fine.
Copy via kdeconnect + mconnet is fine, but in gnome 3.32 mconnect was broken.

Hope you guys can find and fix it, I really love gsconnect.

---
OS: manjaro newest
kdeconnect-android: newest
gsconnect: newest

**Comment by andyholmes** [comment]
Probably this will happen if you try to copy an image.

As of the commit 57a8b8f if the clipboard content is not pure text it will not be synced, avoiding sending null. However syncing non-text is not supported by the KDE Connect protocol, so I can't fix that.

**Comment by ferdnyc** [comment]
@ruinb0w To determine whether typora does "rich" copies, one test would be to copy something and paste it into the Google Docs app (locally on the device). If images or formatting are included, then KDE Connect won't be able to sync that content to the PC. (Copied text from typora that _doesn't_ include rich content may still sync, though.)

**Comment by andyholmes** [comment]
Closing this since 57a8b8f is included in v22.
