### ISSUE TITLE
Settings do not open

### ISSUE THREAD

**Issue by howels** [andyholmes/gnome-shell-extension-gsconnect#513]
**Describe the bug**

**To Reproduce**
1. Open settings

**Expected behavior**
Settings is shown.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can drag-and-drop or cut-and-paste images directly into this edit window, to include them in your report.

**Debug output**

Log full of this message:

`Apr 07 17:45:33 stephen-desktop gjs[26830]: JS ERROR: Error: 0x40000020 is not a valid value for flags GSocketMsgFlags
                                            _onIncomingIdentity@/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/lan.js:198:24
                                            Async*@/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:753:2`

**System Details (please complete the following information):**
 - GSConnect version: 21
   - Installed from: [extensions.gnome.org]
 - GNOME/Shell version: [3.32]
 - Distro/Release: [Ubuntu 19.04]

**GSConnect environment (if applicable):**
 - Paired Device(s): [none, attempting initial setup]
 - KDE Connect app version: [latest]
 - Plugin(s): []

**Additional context**

Clean Gnome install, clean install of gsconnect.

**Comment by howels** [comment]
Edit: Worked after a reboot. Closing.

**Comment by ferdnyc** [comment]
@howels 
Just FYI (and for anyone else who might run into the same issue), these paths:
> `onIncomingIdentity@/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/lan.js`

indicate that there's _also_ a system install of GSConnect on your machine — there's no way extensions.gnome.org can install to `/usr/share/gnome-shell/extensions/`, only to your personal `$HOME/.local/share/gnome-shell/extensions/`. 

So, there must be a gsconnect package that was installed system-wide with `apt`, which initially interfered with your downloaded version. After the reboot (or a logout/login cycle), your local copy would take precedence and the systemwide install would be ignored.
