### ISSUE TITLE
 A normal in-app exit option would have been great. (I am talking about mobile app, not the gnome extension installed on a computer)

### ISSUE THREAD

**Issue by PranavBhattrai** [andyholmes/gnome-shell-extension-gsconnect#515]
Right now, we have to go to setting, find the app and use "force stop" to exit the app.
It's a very time consuming annoying and frustrating process to follow on a day-to-day basis.

Please give us an "exit" button for a normal shutdown of an app.

**Comment by andyholmes** [comment]
GSConnect runs as a service, so generally an exit option doesn't apply to this type of program. The service itself is DBus activated, so even with an exit option it's likely something will restart the service anyways.

What's the use case for stopping the service?

**Comment by PranavBhattrai** [comment]
> What's the use case for stopping the service?
OMG, do u want people to use this app 24/7 a day! I know this is a great app/concept. People go to work, school, etc. And u want to run this app even then? It useless to keep the app running around in background when u r miles away from ur computer. It drains the mobile battery. Even with the computer, we don't always "need" to run this app. 

I have 100+ apps installed in my app. If I continue to run each & every app running in the background even when it's not in use, it's the dumbest thing I ever do. And there are millions of people like me who have installed at least 60+ apps on their phone. 

People do their work and close it, That it. That's how things are done.
 
An exit option is a very normal but vital component for the user to provide. And it is weird that I have to even preach this as if u don't know.

**Comment by andyholmes** [comment]
You seem to be confusing GSConnect, which is a desktop service, with the KDE Connect Android app.

You can report bugs and request features for the Android app at https://bugs.kde.org/ under the `android-application` component:

https://bugs.kde.org/buglist.cgi?component=android-application&product=kdeconnect
