### ISSUE TITLE
Notification Tray icon not appearing on Ubuntu 19.04

### ISSUE THREAD

**Issue by rakshith-ravi** [andyholmes/gnome-shell-extension-gsconnect#517]
**Describe the bug**
When I install this from the ubuntu 19.04 apt repositories (`20-0ubuntu1`), the extension briefly works and then stops working. There is no notification tray icon (or whatever the name for it in Gnome is).

**To Reproduce**
Not sure exactly, but here's what I did:
1. Install ubuntu 18.10
2. Install Gsconnect
3. Upgrade to Ubuntu 19.04.
4. There's no icon on the top right panel.

**Expected behavior**
Everything works as expected.

**Screenshots**
Irrelevant

**Debug output**
```

GSConnect Version: 20
GSConnect Install: system
GJS: 15403
XDG_SESSION_TYPE: x11
GDMSESSION: ubuntu
--------------------------------------------------------------------------------
-- Logs begin at Sun 2019-04-14 07:18:02 IST, end at Wed 2019-04-17 00:20:41 IST. --
Apr 17 00:20:10 gjs[4459]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Apr 17 00:20:10 gjs[4459]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Apr 17 00:20:29 gjs[4459]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Apr 17 00:20:29 gjs[4459]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Apr 17 00:20:35 dbus-daemon[2520]: [session uid=1000 pid=2520] Activating service name='org.gnome.ControlCenter.SearchProvider' requested by ':1.21' (uid=1000 pid=2686 comm="/usr/bin/gnome-shell " label="unconfined")
Apr 17 00:20:35 dbus-daemon[2520]: [session uid=1000 pid=2520] Activating service name='org.gnome.Contacts.SearchProvider' requested by ':1.21' (uid=1000 pid=2686 comm="/usr/bin/gnome-shell " label="unconfined")
Apr 17 00:20:35 dbus-daemon[2520]: [session uid=1000 pid=2520] Activating service name='org.gnome.Nautilus' requested by ':1.21' (uid=1000 pid=2686 comm="/usr/bin/gnome-shell " label="unconfined")
Apr 17 00:20:35 dbus-daemon[2520]: [session uid=1000 pid=2520] Activating service name='org.gnome.Calendar' requested by ':1.21' (uid=1000 pid=2686 comm="/usr/bin/gnome-shell " label="unconfined")
Apr 17 00:20:35 dbus-daemon[2520]: [session uid=1000 pid=2520] Activating service name='org.gnome.clocks' requested by ':1.21' (uid=1000 pid=2686 comm="/usr/bin/gnome-shell " label="unconfined")
Apr 17 00:20:35 dbus-daemon[2520]: [session uid=1000 pid=2520] Activating service name='org.gnome.Photos' requested by ':1.21' (uid=1000 pid=2686 comm="/usr/bin/gnome-shell " label="unconfined")
Apr 17 00:20:35 dbus-daemon[2520]: [session uid=1000 pid=2520] Successfully activated service 'org.gnome.ControlCenter.SearchProvider'
Apr 17 00:20:35 dbus-daemon[2520]: [session uid=1000 pid=2520] Successfully activated service 'org.gnome.clocks'
Apr 17 00:20:35 dbus-daemon[2520]: [session uid=1000 pid=2520] Successfully activated service 'org.gnome.Calendar'
Apr 17 00:20:35 dbus-daemon[2520]: [session uid=1000 pid=2520] Successfully activated service 'org.gnome.Contacts.SearchProvider'
Apr 17 00:20:35 dbus-daemon[2520]: [session uid=1000 pid=2520] Successfully activated service 'org.gnome.Photos'
Apr 17 00:20:35 dbus-daemon[2520]: [session uid=1000 pid=2520] Successfully activated service 'org.gnome.Nautilus'
Apr 17 00:20:36 gnome-shell[2686]: g_environ_setenv: assertion 'value != NULL' failed
Apr 17 00:20:36 dbus-daemon[2520]: [session uid=1000 pid=2520] Activating service name='com.intel.dleyna-renderer' requested by ':1.153' (uid=1000 pid=10103 comm="/usr/bin/gnome-photos --gapplication-service " label="unconfined")
Apr 17 00:20:36 dleyna-renderer-service[10219]: dLeyna core version 0.4.0
Apr 17 00:20:36 dleyna-renderer-service[10219]: dleyna-renderer-service version 0.4.0
Apr 17 00:20:36 dleyna-renderer-service[10219]: Type[0] Level[0x13] Mask[0x4C] Flags[0x4F]
Apr 17 00:20:36 dleyna-renderer-service[10219]: Load file [/home/rakshith/.config/dleyna-renderer-service.conf]
Apr 17 00:20:36 dleyna-renderer-service[10219]: [General settings]
Apr 17 00:20:36 dleyna-renderer-service[10219]: Never Quit: F
Apr 17 00:20:36 dleyna-renderer-service[10219]: Connector Name: dbus
Apr 17 00:20:36 dleyna-renderer-service[10219]: [Logging settings]
Apr 17 00:20:36 dleyna-renderer-service[10219]: Log Type : 0
Apr 17 00:20:36 dleyna-renderer-service[10219]: Log Level: 0x13
Apr 17 00:20:36 dleyna-renderer-service[10219]: [Network filtering settings]
Apr 17 00:20:36 dleyna-renderer-service[10219]: Enabled : F
Apr 17 00:20:36 dleyna-renderer-service[10219]: Entries: (null)
Apr 17 00:20:36 dbus-daemon[2520]: [session uid=1000 pid=2520] Successfully activated service 'com.intel.dleyna-renderer'
Apr 17 00:20:36 dleyna-renderer-service[10219]: Calling GetRenderers method
Apr 17 00:20:36 dleyna-renderer-service[10219]: Client :1.153 lost
Apr 17 00:20:37 dbus-daemon[945]: [system] Activating via systemd: service name='org.freedesktop.hostname1' unit='dbus-org.freedesktop.hostname1.service' requested by ':1.1016' (uid=1000 pid=10206 comm="/usr/bin/python3 /usr/bin/gnome-tweaks " label="unconfined")
Apr 17 00:20:37 systemd[1]: Starting Hostname Service...
Apr 17 00:20:37 org.gnome.Shell.desktop[2686]: Window manager warning: last_focus_time (1288853000) is greater than comparison timestamp (1289893).  This most likely represents a buggy client sending inaccurate timestamps in messages such as _NET_ACTIVE_WINDOW.  Trying to work around...
Apr 17 00:20:37 dbus-daemon[945]: [system] Successfully activated service 'org.freedesktop.hostname1'
Apr 17 00:20:37 systemd[1]: Started Hostname Service.
Apr 17 00:20:38 dleyna-renderer-service[10219]: dLeyna: Exit
Apr 17 00:20:41 gjs[4459]: AT-SPI: Unable to open bus connection: Failed to connect to socket /run/user/1000/at-spi2-ZZXK0Z/socket: No such file or directory
```

**System Details (please complete the following information):**
 - GSConnect version: 20
   - Installed from: Apt repositories
 - GNOME/Shell version: 3.32.1
 - Distro/Release: Ubuntu 19.04

**GSConnect environment (if applicable):**
 Not applicable

**Additional context**
In case it matters, when I upgraded to 19.04, I automatically got KDE Connect installed in my system, not sure how. I had to manually uninstall it.
Also, when I open `gnome-tweaks`, it shows Gsconnect there but shows an exclamation icon (!) saying "Error loading extension" and doesn't let me enable it. However, I can click on the settings icon and open the gsconnect settings. In fact, I'm even able to send commands from my phone (like right click, etc.). Not exactly sure what the issue is.

Do let me know how I can help. I'm not sure how else to generate logs so this is all I have

**Comment by ferdnyc** [comment]
@rakshith-ravi 
Thanks for the report. GSConnect v20 is rather old, at this point... at least compared to GNOME 3.32, which is very new. As I recall there were some fixes that went into GSConnect for compatibility with 3.32, and I'm almost certain they went in after v20.

Could you please try [using the manual install procedure](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Installation#install-from-zip) to download and install the v22-rc1 ZIP file? That should get you sorted out, running under Ubuntu 19.04.

**Comment by rakshith-ravi** [comment]
Okay, I just installed 22-rc1 and I'm still facing the same issue. The only difference is that now there's no settings button in 'gnome-tweaks` application. It just says "Error loading extension". How can I find out what the error is and get some sort of logs?

**Comment by AdamPS** [comment]
So to summarise, it seems that the apt package is totally broken for the newer versions of Ubuntu 19.04 and 19.10.  The included version of GSConnect is not compatible with the included version of GNOME.  Please can you try and get this resolved for 20.04?

**Comment by andyholmes** [comment]
Sorry, I'm not quite sure what you mean here. We really have no control over distribution packages or what versions they ship.

Ultimately, there is no benefit to installing a distribution package or system install of GSConnect, it's just something we support in the meson build for those that requested it.

**Comment by rakshith-ravi** [comment]
I understand. Is there a procedure to apply for updating the version of GSConnect shipped in Ubuntu's universe?

Also, can we perhaps maintain a PPA or something that can be updated? I can help with that if required.

**Comment by AdamPS** [comment]
Thanks for the reply.  As a clarification of what I mean, I find a benefit in installing a distribution package because it is very quick to do.  I maintain a script that installs a set of packages and I run this every I install Linux for me or someone.  The packages then get automatically updated so it is very convenient.

I agree with @rakshith-ravi idea.  It seems that there ought to be a mechanism to trigger Ubuntu to update their package, but if not then a PPA would be convenient.  Many other tools distribute like that.

Anyway that's the idea in case you might consider it, thank you for reading my comment.

**Comment by andyholmes** [comment]
The launchpad package is [here](https://launchpad.net/ubuntu/+source/gnome-shell-extension-gsconnect), which still seems to be tracking version 20. It looks like [version bumps have been requested several times](https://bugs.launchpad.net/ubuntu/+source/gnome-shell-extension-gsconnect), but likely Ubuntu just doesn't have the resources to support this package.

You're welcome to start a PPA for GSConnect if you like, but I have little time to commit to GSConnect at this point, let alone to provide and support distribution packages.

**Comment by ferdnyc** [comment]
@rakshith-ravi 

> I understand. Is there a procedure to apply for updating the version of GSConnect shipped in Ubuntu's universe?
> 
> Alternatively, can we perhaps maintain a PPA or something that can be updated? I can help with that if required.

...Why? The procedure for updating GSConnect, tested and working well, is to install from https://extensions.gnome.org/ — which will automatically match it to the GNOME release the user is running. (And I should've directed you there, really, as it would've been an easier fix.)

The fact that distros insist on packaging GNOME Shell extensions, and then fail to maintain those packages, is a demonstration of why they're unnecessary in the first place. It's not a problem that should be combated with _more_ unnecessary distro packaging. That'd just be chasing our own tail.

I mean, I suppose we could publish a PPA containing nothing but a script that launches the GSConnect listing page at .e.g.o in the user's browser, but we still can't make them click "Install".

**Comment by AdamPS** [comment]
@andyholmes Thanks for investigating.

@ferdnyc e.g.o. is a fair suggestion and certainly better than manual install.  I don't agree that packages are unnecessary.  They have significant advantages for scripted/automated installs which as far as I can see isn't readily available for e.g.o.

A PPA that launches e.g.o seems like a waste of time.  True, a package that is brokenly outdated is worse than useless.  Nonetheless a working package is a clear advantage to a segment of the community.

**Comment by andyholmes** [comment]
To be clear, I'm not opposed to a PPA (or COPR repo, etc) I/we just don't have time to produce or maintain these ourselves.

If official packages are something you want to contribute and maintain, you are welcome to set them up and submit PRs for any DEB/RPM/etc files in the main repository. The Github project is currently "stuck" under my user name, but if you need any special access or approval to get those hooked up with Launchpad or whatever, feel free to ask.

Assuming you got that all working, you could probably apply to be the package maintainer in Ubuntu, too.

**Comment by AdamPS** [comment]
@andyholmes I understand, thanks for clarification.  Unfortunately I don't have time to maintain that either.  My intention was to put forward the point of view that packages are definitely useful to some people as a balance to the other comment stating that they are unnecessary.
