### ISSUE TITLE
The underlying SSH process exited

### ISSUE THREAD

**Issue by RobertZito** [andyholmes/gnome-shell-extension-gsconnect#518]
When I copy and paste my music from my laptop to my android phone I am getting errors. The message says "The connection is closed (the underlying SSH process exited)". Also when I attempt to I try and to share a file from the laptop to the phone I get a message on the phone that says "Failed receiving file from pop-os". When I send music from my phone to my laptop it works fine. I also noticed the icon started in the upper right hand corner started to disappear and no matter what I do the only way to get GS Connect to work again  is restarting the laptop. I copied and pasted the logs I was able to capture, any help in resolving the would greatly be appreciated.

**-- Logs begin at Sun 2018-11-11 11:16:24 EST, end at Fri 2019-04-19 09:44:30 EDT. --
Apr 19 09:44:16 dbus-daemon[951]: [system] Activating via systemd: service name='org.freedesktop.hostname1' unit='dbus-org.freedesktop.hostname1.service' requested by ':1.124' (uid=1000 pid=3980 comm="/usr/bin/nautilus --gapplication-service " label="unconfined")
Apr 19 09:44:16 systemd[1]: Starting Hostname Service...
Apr 19 09:44:17 dbus-daemon[951]: [system] Successfully activated service 'org.freedesktop.hostname1'
Apr 19 09:44:**17** systemd[1]: Started Hostname Service.
Apr 19 09:44:19 gjs[2173]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Apr 19 09:44:19 gjs[2173]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Apr 19 09:44:19 gjs[2173]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Apr 19 09:44:19 gjs[2173]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Apr 19 09:44:19 gjs[2173]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Apr 19 09:44:19 gjs[2173]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Apr 19 09:44:19 gjs[2173]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Apr 19 09:44:19 gjs[2173]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Apr 19 09:44:19 gjs[2173]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Apr 19 09:44:20 gjs[2173]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Apr 19 09:44:20 gjs[2173]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Apr 19 09:44:20 gjs[2173]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Apr 19 09:44:20 gjs[2173]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Apr 19 09:44:20 gjs[2173]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Apr 19 09:44:20 gjs[2173]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Apr 19 09:44:29 gjs[2173]: GtkDialog mapped without a transient parent. This is discouraged.**

**Comment by RobertZito** [comment]
Here are some more logs:

-------------------------------------------------------------------------------
-- Logs begin at Sun 2018-11-11 11:16:24 EST, end at Fri 2019-04-19 10:20:42 EDT. --
Apr 19 10:20:23 gjs[2173]: JS ERROR: sftp://192.168.1.10:1743//Music: Gio.IOErrorEnum: The specified location is not mounted
                           window.open_uri/<@/home/rzito/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/__init__.js:84:13
                           @/home/rzito/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:744:2
Apr 19 10:20:26 gjs[2173]: JS ERROR: sftp://192.168.1.10:1743//Music: Gio.IOErrorEnum: The specified location is not mounted
                           window.open_uri/<@/home/rzito/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/__init__.js:84:13
                           @/home/rzito/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:744:2

**Comment by andyholmes** [comment]
I can't reproduce these problems, and there doesn't seem to be anything indicating that GSConnect is where the problem lies.

Can you please list the versions of GSConnect and KDE Connect Android you're using, and if possible a logcat from Android for the kdeconnect app?

**Comment by ferdnyc** [comment]
@RobertZito @andyholmes Distro name/flavor and version, as well as gnome release, would also be helpful.

**Comment by dal00** [comment]
I'm experiencing this on Ubuntu 18.04 with the latest KDEConnect from the play store (1.12.6).
One folder is added to be shared in KDE connect.

**Comment by andyholmes** [comment]
Since I can't reproduce this myself and none of the provided logs from GSConnect indicate anything wrong on our side, the next step would be for someone affected to get a logcat from the Android app.

Once `adb` is installed and authenticated with the phone, you can start logging kdeconnect-android with the following command, then try to share a file or mount the phone's filesystem:

    adb logcat --pid=$(adb shell pidof -s org.kde.kdeconnect_tp)

I'm fairly certain this is not a problem with GSConnect, since nothing has really changed in the sftp/share plugins that should cause problems, but logs will let us be certain.

**Comment by dal00** [comment]
Here it is!

`21 13:27:49.095 15847 15847 W DecorView[]: The visibility of the navigation bar is low, color=ff000000, hasLightNavBar=true, isFloating=false
04-21 13:30:27.330 15847 16252 D AndroidSafSshFile: setAttributes()
04-21 13:30:27.596 15847 16257 W DocumentsContract: Failed to create document
04-21 13:30:27.596 15847 16257 W DocumentsContract: java.lang.IllegalArgumentException: Failed to determine if primary:DownloadTest Test Test test [testing test test] is child of primary:Download: java.io.FileNotFoundException: Missing file for primary:DownloadTest Test Test test [testing test test] at /storage/emulated/0/DownloadTest Test Test test [testing test test]
04-21 13:30:27.596 15847 16257 W DocumentsContract: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:165)
04-21 13:30:27.596 15847 16257 W DocumentsContract: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
04-21 13:30:27.596 15847 16257 W DocumentsContract: 	at android.content.ContentProviderProxy.call(ContentProviderNative.java:651)
04-21 13:30:27.596 15847 16257 W DocumentsContract: 	at android.content.ContentProviderClient.call(ContentProviderClient.java:492)
04-21 13:30:27.596 15847 16257 W DocumentsContract: 	at android.provider.DocumentsContract.createDocument(DocumentsContract.java:1171)
04-21 13:30:27.596 15847 16257 W DocumentsContract: 	at android.provider.DocumentsContract.createDocument(DocumentsContract.java:1153)
04-21 13:30:27.596 15847 16257 W DocumentsContract: 	at org.kde.kdeconnect.Plugins.SftpPlugin.AndroidSafSshFile.create(AndroidSafSshFile.java:188)
04-21 13:30:27.596 15847 16257 W DocumentsContract: 	at org.kde.kdeconnect.Plugins.SftpPlugin.AndroidSafSshFile.create(AndroidSafSshFile.java:182)
04-21 13:30:27.596 15847 16257 W DocumentsContract: 	at org.apache.sshd.server.sftp.SftpSubsystem.process(SftpSubsystem.java:520)
04-21 13:30:27.596 15847 16257 W DocumentsContract: 	at org.apache.sshd.server.sftp.SftpSubsystem.run(SftpSubsystem.java:427)
04-21 13:30:27.596 15847 16257 W DocumentsContract: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
04-21 13:30:27.596 15847 16257 W DocumentsContract: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
04-21 13:30:27.596 15847 16257 W DocumentsContract: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
04-21 13:30:27.596 15847 16257 W DocumentsContract: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
04-21 13:30:27.596 15847 16257 W DocumentsContract: 	at java.lang.Thread.run(Thread.java:764)
`

**Comment by RobertZito** [comment]
The problem is related to my VPN, when I shut it off GSConnect works fine. Thanks for the quick response.

**Comment by dal00** [comment]
I don't think GSConnect should stop working because there is a VPN running? 
Also I don't have a vpn running.

**Comment by andyholmes** [comment]
@dal00 it seems like you are experiencing a different problem than the original reporter. I expect this is a problem in the Android app's SAF implementation, but I haven't had a chance to test it locally myself yet.

**Comment by andyholmes** [comment]
@dal00 Seems like your problem might be fixed in [kdeconnect-android !59](https://invent.kde.org/kde/kdeconnect-android/merge_requests/59) as reported in [#40607](https://bugs.kde.org/show_bug.cgi?id=406707), although it may be sometime before this is released.

If this is important to you or you want to help test the fix, there's brief instructions on the [KDE Connect Wiki](https://community.kde.org/KDEConnect#Android) for building the Android app, just substitute the above branch from Erik's MR.

**Comment by sagescrub** [comment]
FWIW I am encountering this issue too, copying a 3gb video from ubuntu to android over wifi. The error seems to happen at about 1.8 GB transferred for me. I tried with my firewall off and disabling sleep on android, plugged in.

**Comment by andyholmes** [comment]
You probably want to open a new issue, although this is likely a problem with GVfs and not GSConnect.
