### ISSUE TITLE
Network error after upgrading from Ubuntu 18.10 to 19.04

### ISSUE THREAD

**Issue by OffifialMITX** [andyholmes/gnome-shell-extension-gsconnect#520]
**Describe the bug**
I never had KDE installed (on this system), but after upgrading it doesn't work any more, showing me "Network error" whenever I try to start it. I already tried to reinstall but no avail.

**To Reproduce**
1. Install on ubuntu 19.04 64bit
2. … see error(?)

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. You can drag-and-drop or cut-and-paste images directly into this edit window, to include them in your report.

**Log output**
https://gist.github.com/OffifialMITX/cb717d24611aaba6298dfd0ac29ae02b

**System Details:**
 - GSConnect version: **21**
   - Installed from: **extensions.gnome.org**
 - GNOME/Shell version: **3.32.1**
 - Distro/Release: **Ubuntu 19.04**

**Comment by andyholmes** [comment]
Clicking that notification should lead you to [Network Error](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Help#network-error).

This almost always means you have `kdeconnectd` running, although you may also have another instance of GSConnect installed and running or some other program blocking port 1716. Please paste the output of:

    $ lsof -i UDP:1716
    $ ps aux | grep gsconnect

**Comment by OffifialMITX** [comment]
Ok, so it seems that I have kdeconnect installed for some reason…
```user@Computer:~$ apt search kdeconnect
Sorting... Done
Full Text Search... Done
kdeconnect/disco,now 1.3.4-0ubuntu1 amd64 [installed,automatic]
  connect smartphones to your KDE Plasma Workspace

nuntius/disco 0.2.0-5build1 amd64
  share notifications from Android phone or tablet via Bluetooth or LAN

user@Computer:~$ lsof -i UDP:1716
COMMAND    PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
kdeconnec 3312 user   20u  IPv6  70095      0t0  UDP *:1716 
user@Computer:~$ ps aux | grep gsconnect
user      3479  0.8  1.3 2433936 53088 ?       Sl   16:09   0:03 gjs /home/user/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js
user      4810  0.0  0.8 1652332 31392 tty2    Sl+  16:12   0:00 gjs /home/user/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/nativeMessagingHost.js /home/user/.mozilla/native-messaging-hosts/org.gnome.shell.extensions.gsconnect.json gsconnect@andyholmes.github.io
user      5266  0.0  0.0   9320  2736 pts/0    S+   16:15   0:00 grep --color=auto gsconnect
user@Computer:~$ ps aux | grep kde
root        33  0.0  0.0      0     0 ?        S    16:04   0:00 [kdevtmpfs]
user      3312  0.0  1.2 531476 48556 tty2     Sl+  16:09   0:00 /usr/lib/x86_64-linux-gnu/libexec/kdeconnectd
user      5318  0.0  0.0   9320   912 pts/0    S+   16:16   0:00 grep --color=auto kde
```
I'm gonna try to remove it and see how it goes.

**Comment by OffifialMITX** [comment]
Yup it works now. I have no idea why I had kdeconnect installed, but thanks for helping me to find out and sorry for bothering.
