### ISSUE TITLE
Ubuntu 19.04 keybind always says "... is already in use. "

### ISSUE THREAD

**Issue by danieldeng2** [andyholmes/gnome-shell-extension-gsconnect#522]
![Screenshot from 2019-04-26 20-35-55](https://user-images.githubusercontent.com/36489683/56832182-27c84c80-6863-11e9-823c-b91bdade84cb.png)
![Screenshot from 2019-04-26 20-34-46](https://user-images.githubusercontent.com/36489683/56832199-3151b480-6863-11e9-8bd9-2923c5c3b1b0.png)

**Comment by danieldeng2** [comment]
`
GSConnect Version: 21
GSConnect Install: user
GJS: 15403
XDG_SESSION_TYPE: x11
GDMSESSION: gnome-xorg
--------------------------------------------------------------------------------
-- Logs begin at Sat 2019-02-09 19:36:40 GMT, end at Fri 2019-04-26 20:52:49 BST. --
Apr 26 20:52:23 systemd[1]: systemd-hostnamed.service: Succeeded.
Apr 26 20:52:46 org.gnome.Shell.Extensions.GSConnect[2619]: [/service/protocol/core.js:receive/<:177]: OnePlus 5T: {
                                                              "id": 1556306925468,
                                                              "type": "kdeconnect.battery",
                                                              "body": {
                                                                "currentCharge": 33,
                                                                "isCharging": false,
                                                                "thresholdEvent": 0
                                                              }
                                                            }
Apr 26 20:52:49 gjs[2619]: gtk_widget_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed
Apr 26 20:52:49 gjs[2619]: gtk_widget_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed
Apr 26 20:52:49 gjs[2619]: gtk_widget_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed
`

**Comment by andyholmes** [comment]
Thanks for reporting, should be fixed in de44f41. Here's an updated Zip for convenience:

[gsconnect@andyholmes.github.io.zip](https://github.com/andyholmes/gnome-shell-extension-gsconnect/files/3123029/gsconnect%40andyholmes.github.io.zip)

**Comment by danieldeng2** [comment]
wow thanks that was fast.

**Comment by andyholmes** [comment]
I happened to be here, and to be honest it was a lot easier to fix than a harder problem I'm working on :P
