### ISSUE TITLE
Oneplus 5t doesnt recognize my laptop

### ISSUE THREAD

**Issue by sictiburon** [andyholmes/gnome-shell-extension-gsconnect#524]
I just installed the gsconnect, im using ubuntu 18.04, the extension finds my phone with no issues, but my phone cannot find the gsconnect to pair (sorry for my english)

GSConnect Version: 22
GSConnect Install: user
GJS: 15205
XDG_SESSION_TYPE: x11
GDMSESSION: ubuntu
--------------------------------------------------------------------------------
-- Logs begin at Mon 2019-04-29 19:32:09 CEST, end at Wed 2019-05-01 13:18:16 CEST. --
may 01 13:18:09 gjs[3709]: JS ERROR: Gio.IOErrorEnum: Could not connect to 192.168.1.34: Connection timed out
                           _onIdentity/connection</<@/home/sictiburonlinux/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/protocol/lan.js:279:33
                           @/home/sictiburonlinux/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:744:2
may 01 13:18:09 gjs[3709]: JS ERROR: Gio.IOErrorEnum: Could not connect to 192.168.1.34: Connection timed out
                           _onIdentity/connection</<@/home/sictiburonlinux/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/protocol/lan.js:279:33
                           @/home/sictiburonlinux/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:744:2
may 01 13:18:09 gjs[3709]: JS ERROR: Gio.IOErrorEnum: Could not connect to 192.168.1.34: Connection timed out
                           _onIdentity/connection</<@/home/sictiburonlinux/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/protocol/lan.js:279:33
                           @/home/sictiburonlinux/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:744:2
may 01 13:18:16 gjs[3709]: GtkDialog mapped without a transient parent. This is discouraged.

**Comment by sictiburon** [comment]
My computer finds the cell but no otherwise

**Comment by andyholmes** [comment]
> Gio.IOErrorEnum: Could not connect to 192.168.1.34: Connection timed out

Hi, it seems like there is a problem on your local network. To connect a device you must be on the same subnet (192.168.**X**.0) and ports 1716-1764 must be open.

You should check your firewall and router for these settings.

**Comment by sictiburon** [comment]
Thanks a lot Andy, i will give it a try

**Comment by andyholmes** [comment]
Closing for now. Re-open if the issue persists or there's new information to help diagnose.
