### ISSUE TITLE
Error while installing Chrome Extension on Chromium: Package is invalid. Details: 'Messages file is missing for locale. /tmp/scoped_dirObOYdr/CRX_INSTALL/_locales/ja/messages.json'.

### ISSUE THREAD

**Issue by Samleo8** [andyholmes/gnome-shell-extension-gsconnect#528]
**Describe the bug**
Error while installing Chrome Extension on Chromium:
`Package is invalid. Details: 'Messages file is missing for locale. /tmp/scoped_dirObOYdr/CRX_INSTALL/_locales/ja/messages.json'.`

**To Reproduce**
1. Go to https://chrome.google.com/webstore/detail/gsconnect/jfnifeihccihocjbfcfhicmmgpjicaec?hl=en on Chromium 73.0.3683.86 (Official Build)
2. Click on 'Add to Chrome' > 'Add Extension'
3. See error `Package is invalid. Details: 'Messages file is missing for locale. /tmp/scoped_dirHCgOrg/CRX_INSTALL/_locales/ja/messages.json'.`

Notes:
1. No difference when phone is paired/unpaired

**Expected behavior**
Chrome Extension downloads successfully.

**Screenshots**
![Screenshot from 2019-05-04 11-48-00](https://user-images.githubusercontent.com/2712664/57173434-7e84e600-6e62-11e9-8be8-28ca6370e3a5.png)

**System Details (please complete the following information):**
 - GSConnect version: 23
 - Installed from: extensions.gnome.org
 - GNOME/Shell version: 3.30.2
 - Distro/Release: Ubuntu 18.10
 - Chromium Version: 73.0.3683.86

**Comment by andyholmes** [comment]
Sorry about that. I've uploaded a new version which should be available soon.

**Comment by andyholmes** [comment]
Closing since the WebExtension should have distributed updates by now. Re-open if the problem reoccurs.
