### ISSUE TITLE
Can't receive notifications or share files between host and guest.

### ISSUE THREAD

**Issue by nlpsuge** [andyholmes/gnome-shell-extension-gsconnect#533]
**Describe the bug**
I expect to receive notification or share files between host and guest. The guest OS is Window 7 running in VirtualBox. 
I install KDE Connect from https://binary-factory.kde.org/view/Windows%2064-bit/job/kdeconnect-kde_Nightly_win64/lastSuccessfulBuild/artifact/kdeconnect-kde-master-5-windows-msvc2017_64-cl.exe.

**To Reproduce**
1. install this extension
2. Download the file https://binary-factory.kde.org/view/Windows%2064-bit/job/kdeconnect-kde_Nightly_win64/lastSuccessfulBuild/artifact/kdeconnect-kde-master-5-windows-msvc2017_64-cl.exe
3. Install kdeconnect-kde-master-5-windows-msvc2017_64-cl.exe in Windows 7 running in VirtualBox
4. The Network Adapter is 'bridged Adapter'.
![image](https://user-images.githubusercontent.com/2271720/57291927-0a14a600-70f3-11e9-903d-0193a35c799b.png)
5. Pair host and guest
6. Send messages to guest, but host can't receive any notification. Also can't share files between host and guest.
7. If failed to share files, there are some error messages in 'journalctl':
JS ERROR: test-kde-connect: Gio.TlsError.TlsError: Error performing TLS handshake: A disallowed SNI server name has been received.
_handshake/</<@/home/username/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/protocol/lan.js:383:33
@/home/username/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:744:2

**Expected behavior**
Can receive notifications or share files between host and guest.

**System Details (please complete the following information):**
 - GSConnect version:
23
 - Installed from: 
extensions.gnome.org
 - GNOME/Shell version: 
3.32
 - Distro/Release: 
Fedora 30

**Comment by andyholmes** [comment]
> JS ERROR: test-kde-connect: Gio.TlsError.TlsError: Error performing TLS handshake: A disallowed SNI server name has been received.

Apparently [SNI is a part of TLS](https://en.wikipedia.org/wiki/Server_Name_Indication) that allows multiple certificates to come from the same host or something like that. GSConnect is not very well tested in virtual machines, but this may need additional network configuration for your VM.

It's possible the host name in the certificate or TLS handshake is not the same as what is being reported by the VM network interface.

**Comment by andyholmes** [comment]
I'm labelling this `can't fix` and closing, since I don't see any way this can be addressed in GSConnect, especially given Gio lacking SNI support as @ferdnyc points out.
