### ISSUE TITLE
Allow commands to be imported/exported

### ISSUE THREAD

**Issue by timoschwarzer** [andyholmes/gnome-shell-extension-gsconnect#537]
**Is your feature request related to a problem? Please describe.**
I've multiple computers running with GSConnect and I use the command feature extensively. Currently I have to type in all commands by hand each time I set up a computer from scratch.

**Describe the solution you'd like**
A simple import/export commands to a *.json file (or whatever file format)

**System Details (please complete the following information):**
 - GSConnect version: 23
 - Installed from: extensions.gnome.org

**Comment by andyholmes** [comment]
This should be possible already using `dconf`:

    $ dconf dump /org/gnome/shell/extensions/gsconnect/device/<device-id>/plugin/runcommand/ > cmds.dump
    $ cat cmds.dump | dconf load /org/gnome/shell/extensions/gsconnect/device/<device-id>/plugin/runcommand/

Most settings are stored in GSettings/dconf, at least for plugins.

**Comment by andyholmes** [comment]
Closing this, since export/import of settings can be done with `dconf` if necessary and a baking it in will only make adding or changing GSettings difficult.
