### ISSUE TITLE
Option/switch to toggle GSConnect function (other than notification)

### ISSUE THREAD

**Issue by daitau** [andyholmes/gnome-shell-extension-gsconnect#538]
When I am copying/pasting sensitive information (e.g. in gnome-terminal) I would like to have the option to turn off GSConnect temporarily so that the content would not be shared to other devices. A global switch to temporarily disconnect from other devices would be handy in this case. I have looked at #144 but I am not sure if that will help in this case.

**Comment by andyholmes** [comment]
Closing since I believe this issue is solvable by using the available clipboard options.
