### ISSUE TITLE
GSConnect doesn't inform KDE Connect that media has ended

### ISSUE THREAD

**Issue by pwd-github** [andyholmes/gnome-shell-extension-gsconnect#542]
**Describe the bug**
A couple of versions ago, this would work properly, whereby if you start Clementine, you would get the notification on your phone and when you stopped it, it would close the notification. Now though, it doesn't close the notification.

**To Reproduce**
1. On desktop, start Clementine (or VLC)
2. Play a song (or video)
3. Stop song (or video)

**Expected behavior**
KDE Connect should remove the media wallpaper and remove the notification.

**Screenshots**
N/A

**Debug output**
N/A

**System Details (please complete the following information):**
 - GSConnect version: 24
   - Installed from: EGO Website
 - GNOME/Shell version: 3.32.2
 - Distro/Release: Fedora 30

**GSConnect environment (if applicable):**
 - Paired Device(s): LG G6 and Nvidia Shield Tablet
 - KDE Connect app version: 1.12.7
 - Plugin(s): N/A

**Additional context**
N/A

**Comment by andyholmes** [comment]
It seems GSConnect is sending the correct information to the Android app. If I play then stop media it sends:

```js
[/service/protocol/core.js:send:220]: Google Nexus 4: {
  "id": 1558387870740,
  "type": "kdeconnect.mpris",
  "body": {
    "pos": 0,
    "isPlaying": true,
    "canPause": true,
    "canPlay": true,
    "canGoNext": true,
    "canGoPrevious": true,
    "canSeek": true,
    "nowPlaying": "Pixies - Manta Ray",
    "albumArtUrl": "file:///home/andrew/.cache/vlc/art/artistalbum/Pixies/Pixies%20at%20the%20BBC/art.jpg",
    "length": 133619,
    "volume": 100,
    "player": "VLC media player"
  }
}
[/service/protocol/core.js:send:220]: Google Nexus 4: {
  "id": 1558387870834,
  "type": "kdeconnect.mpris",
  "body": {
    "player": "VLC media player",
    "pos": 175
  }
}
[/service/protocol/core.js:send:220]: Google Nexus 4: {
  "id": 1558387873979,
  "type": "kdeconnect.mpris",
  "body": {
    "pos": 0,
    "isPlaying": false,
    "canPause": false,
    "canPlay": true,
    "canGoNext": true,
    "canGoPrevious": true,
    "canSeek": false,
    "nowPlaying": "Pixies - Manta Ray",
    "albumArtUrl": "file:///home/andrew/.cache/vlc/art/artistalbum/Pixies/Pixies%20at%20the%20BBC/art.jpg",
    "length": 133619,
    "volume": 100,
    "player": "VLC media player"
  }
}
```
If I clear the playlist it sends:

```js
[/service/protocol/core.js:send:220]: Google Nexus 4: {
  "id": 1558388132164,
  "type": "kdeconnect.mpris",
  "body": {
    "pos": 0,
    "isPlaying": false,
    "canPause": false,
    "canPlay": false,
    "canGoNext": true,
    "canGoPrevious": true,
    "canSeek": false,
    "volume": 100,
    "player": "VLC media player"
  }
}
```

I had a quick look at the source for the Android plugin and it doesn't seem like it does what you want. In fact the most [recent commit](https://invent.kde.org/kde/kdeconnect-android/commit/d95026643147b63328a719fb0dac0c51ec7af678) says *"Don't close notification for last player if not playing"*.

You should request this in the [upstream bug tracker](https://bugs.kde.org/buglist.cgi?component=android-application&product=kdeconnect) in the `android-application` component.

**Comment by pwd-github** [comment]
Sorry Andy, just to confirm, you're saying that if I close VLC, by design, the notification should remain?

**Comment by andyholmes** [comment]
In my testing what happened was that when I stopped playback, the Android app registered that, but didn't remove the notification or clear the lock-screen background. Clearing the playlist didn't seem to do anything more. When I exited VLC it removed the notification, but didn't reset the background.

The notification behaviour seems to be intentional. I think it *should* be removed when the MPRIS player reports `canPlay: false` (which happens eg. when you empty the playlist in VLC) because the controls basically become useless.

The lock-screen background doesn't ever get reset and will probably only change when some Android app changes it. I think that's fair to call a straight-up bug.

**Comment by ferdnyc** [comment]
> The lock-screen background doesn't ever get reset and will probably only change when some Android app changes it. I think that's fair to call a straight-up bug.

*in the KDE Connect app, specifically. (Rather than GSConnect.) KDE Connect bugs can be reported at the [upstream bug tracker](https://bugs.kde.org/buglist.cgi?component=android-application&product=kdeconnect) link that Andy provided earlier.

**Comment by pwd-github** [comment]
Thanks you @andyholmes and @ferdnyc

**Comment by pwd-github** [comment]
Filed: https://bugs.kde.org/show_bug.cgi?id=407812

**Comment by andyholmes** [comment]
There's a pending MR here that should fix the wallpaper: https://invent.kde.org/kde/kdeconnect-android/merge_requests/74
