### ISSUE TITLE
Expose the phones media as an MPRIS service

### ISSUE THREAD

**Issue by Pajn** [andyholmes/gnome-shell-extension-gsconnect#547]
**Is your feature request related to a problem? Please describe.**
I use my phone to listen to music, not the computer. However my keyboard has fancy multimedia keys and it would be very nice to have them _just work_

**Describe the solution you'd like**
When media is playing on the phone (and creates one of those media notifications) an MPRIS service should be exposed on the computer that support basic playback controls and information. Seek, playlists and similar is not needed and might not even be possible via the Android API.

**Describe alternatives you've considered**
Picking up my phone like a peasant :)

**System Details (please complete the following information):**
 - GSConnect version: 24
   - Installed from: extensions.gnome.org

**Additional context**
The current Media Players feature works great, but in the completely opposite way of how I would like it.

#### App Support

I don't know if this is possible with the Android App right now. It has notification support so I'm thinking that it might but otherwise I will have to submit an request upstream.

**Comment by andyholmes** [comment]
Currently the Android app doesn't export any media information to remote devices, so that would have to be implemented upstream first.

GSConnect also doesn't export any MPRIS interfaces, even for devices that do send MPRIS updates. It's not impossible, it's just a bit complicated to account for all the possibilities (eg. multiple devices, each with possibly multiple MPRIS players, etc).

**Comment by ferdnyc** [comment]
The first step to making this happen would be to open a feature request [in the KDE Connect bug tracker](https://bugs.kde.org/buglist.cgi?component=android-application&product=kdeconnect) and convince them to implement it in the Android app.

**Comment by ferdnyc** [comment]
@Pajn @andyholmes 

And KDE Connect 1.12.9 just showed up on my phone, with this new feature listing:
> \- Enable controlling Android media players remotely.

**Comment by Pajn** [comment]
Yeah, I saw that to and was about to post about it.

Here seems to be the relevant code giving insight to the API https://github.com/KDE/kdeconnect-android/blob/master/src/org/kde/kdeconnect/Plugins/MprisReceiverPlugin/MprisReceiverPlugin.java

I have also thought a bit more about what I would want. And while a MPRIS interface would be fancy, a much simpler implementation with just beeing able to binding global hotkeys that only work if a single device is currently playing in only a single source would come a very long way.

**Comment by andyholmes** [comment]
MPRIS mirroring should be mostly working, but there are some quirks that are hard to deal with. I wouldn't consider this 100% MPRISv2 compliant and there's no good way to stop the remote device from sending it's own notifications that I know of.

**Comment by Pajn** [comment]
Initial testing seems to work nice. I could disable all notifications from YoutTube Music in the KDEConnect Android app and still get the mpris interface to work so I think doing that for all media player apps that I use is a fine workaround.

Thanks!
