### ISSUE TITLE
[mpris] GSConnect does not handle servers which do not expose the volume property

### ISSUE THREAD

**Issue by ptitjano** [andyholmes/gnome-shell-extension-gsconnect#548]
**Describe the bug**

The MPRIS volume support has recently been [removed](https://gitlab.gnome.org/GNOME/gnome-music/commit/2bd7fb6bfc76036c43c3326375445ab00f4d33c5) from GNOME Music because the application does not have any ui to change it. 
When GNOME Music is used in combination with GSConnect, GNOME Music crashes at startup because GSConnect tries to access an unhandled property.  See this [bug report](https://gitlab.gnome.org/GNOME/gnome-music/issues/287).

**Steps To Reproduce:**

1. install the nightly version of [GNOME Music](https://wiki.gnome.org/Apps/Nightly)
2. launch GSConnect
3. launch GNOME Music
4. GNOME Music crashes

**Expected behavior**

According to [MPRIS mailing-list](https://lists.freedesktop.org/archives/mpris/2018q1/000071.html), the client should detect that the server does not handle the volume property and adapt accordingly. 

```

```

**System Details (please complete the following information):**

 - **GSConnect version:** 24
   - **Installed from:** GNOME Extensions Website
 - **GNOME/Shell version:** 3.32
 - **Distro/Release:** debian unstable/experimental

**GSConnect environment (if applicable):**

 - **Paired Device(s):** Sony Xperia X2
 - **KDE Connect app version:** 1.12.7
 - **Plugin(s):** ?

**Comment by ferdnyc** [comment]
A fix was made to GNOME Music that prevents it crashing when volume is queried, so this has been addressed upstream and should no longer be a problem. Closing as fixed in [GNOME Music commit 2e44076](https://gitlab.gnome.org/GNOME/gnome-music/commit/2e440761162fa79f3c579fc7cd36195decc189a7).
