### ISSUE TITLE
Brave Browser - "Service Unavailable"

### ISSUE THREAD

**Issue by RKB2000** [andyholmes/gnome-shell-extension-gsconnect#555]
**Describe the bug**

The Brave Browser web extension displays 'Service Unavailable'.

**Steps To Reproduce:**

1. Install extension on brave browser.
2. Click on the extension's icon.
3. 'Service Unavailable'

**Expected behavior**

Should have the option to send page to device.

**System Details (please complete the following information):**

 - **GSConnect version:** Web Extension Version 7
 - **Installed from:** Chrome Web Store

**Additional Notes:**

I have found that the Brave uses its own file structure. I just had to move a copy of:
`home/.config/chromium/NativeMessagingHosts/org.gnome.shell.extensions.gsconnect.json`
to:
`home/.config/BraveSoftware/Brave-Browser/NativeMessagingHosts/`

This seems to have fixed the issue.

**Comment by ferdnyc** [comment]
Yeah, it seems the universe of possible script destinations is growing for everyone. (KeePassXC is [up to six browsers](https://raw.githubusercontent.com/keepassxreboot/keepassxc/master/utils/keepassxc-snap-helper.sh) now, and they don't even address the `google-chrome{,-unstable,-beta}` duplication.)

GSConnect already installs to all of the following locations:
https://github.com/andyholmes/gnome-shell-extension-gsconnect/blob/255363f628ccf3c583b1c1df3fa6f85edfd40908/src/_gsconnect.js#L176-L186

But from googling around, it sounds like the only solution may be to add one more. 

I wonder, though, if — given the growing set of destinations — it might be better to test whether the _parent_  exists for each of those `NativeMessagingHosts` directories, and only create/install manifests in the ones that do. That way, e.g. `$HOME/.config/BraveSoftware/Brave-Browser/NativeMessagingHosts/org.gnome.shell.extensions.gsconnect.json` will only get created if the user already has a `$HOME/.config/BraveSoftware/Brave-Browser` directory.

Already, my system has two directory hierarchies that only exist to host the GSConnect native messaging manifest:
```
$HOME/.config/chromium/NativeMessagingHosts/
$HOME/.config/google-chrome-beta/NativeMessagingHosts/
```
Not too keen on adding a third.

**Comment by ferdnyc** [comment]
I tagged this "webextension" because it's _related_, but still not sure whether I think that's the correct tagging.

**Comment by andyholmes** [comment]
@RKB2000 Thanks for reporting, I've added Brave to the list of manifest locations.

@ferdnyc it's possible to do these checks, however we only actually call `installService()` once when the extension is initialized (in `init()`). This means if a user installs a browser while GSConnect is running, the new manifest wouldn't be installed until the GNOME session is reloaded, I think that might result in some confusion/irritating bug reports.

Alternatively we can run the manifest checks on every call to `enable()`, but these do blocking I/O so I don't really like doing that at all, let alone more than once a session. I'm not sure there's a better approach here, but I think the <1kb file is not a bad compromise. I'd be open to a cleaner solution though.

**Comment by zi-crypto** [comment]
The File `org.gnome.shell.extensions.gsconnect.json` is already there in `BraveSoftware/Brave-Browser/NativeMessagingHosts/` and it is giving the same error here!!
