### ISSUE TITLE
gjs - reference to undefined property "GSocketOutputStream"

### ISSUE THREAD

**Issue by tapsiturtle** [andyholmes/gnome-shell-extension-gsconnect#560]
Hi. I just found this message in my log:
```
Jun 15 11:15:17 turtlebook gjs[1099]: JS WARNING: [/home/tapsiturtle/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/protocol/lan.js 518]: reference to undefined property "GSocketOutputStream"
```

**System Details (please complete the following information):**

 - **GSConnect version:** 24
   - **Installed from:** GNOME Extensions Website
 - **GNOME/Shell version:** 3.32
 - **Distro/Release:** Arch

**GSConnect environment (if applicable):**

 - **Paired Device(s):** Fairphone 2

**Comment by andyholmes** [comment]
Thanks for reporting. This is a warning in GJS, probably somewhere in the Gio bindings. There's nothing much I can do about this, but it seems mostly harmless anyways.
