### ISSUE TITLE
KDE Connect 1.12.9 update triggers storm of AuthenticationErrors

### ISSUE THREAD

**Issue by ferdnyc** [andyholmes/gnome-shell-extension-gsconnect#561]
Well, that was a bit unpleasant. Immediately after my phone installed KDE Connect 1.12.9 via Play Store update, my desktop started showing a barrage of notification popups from GSConnect, claiming authentication errors attempting to communicate with the phone's IP.

My user journal is full of these messages (with paths shortened and leading spaces removed, for readability):
```
Jun 15 10:33:35 teevey gjs[2778]: JS ERROR: AuthenticationError
_authenticate@/../gsconnect@andyholmes.github.io/service/protocol/lan.js:415:33
async*_clientEncryption@/../gsconnect@andyholmes.github.io/service/protocol/lan.js:444:16
accept@/../gsconnect@andyholmes.github.io/service/protocol/lan.js:543:38
async*_onIncomingChannel@/../gsconnect@andyholmes.github.io/service/protocol/lan.js:121:19
Async*@/../gsconnect@andyholmes.github.io/service/daemon.js:744:2

Jun 15 10:33:40 teevey gjs[2778]: JS ERROR: AuthenticationError
_authenticate@/../gsconnect@andyholmes.github.io/service/protocol/lan.js:415:33
async*_clientEncryption@/../gsconnect@andyholmes.github.io/service/protocol/lan.js:444:16
accept@/../gsconnect@andyholmes.github.io/service/protocol/lan.js:543:38
async*_onIncomingChannel@/../gsconnect@andyholmes.github.io/service/protocol/lan.js:121:19
Async*@/../gsconnect@andyholmes.github.io/service/daemon.js:744:2

Jun 15 10:33:45 teevey gjs[2778]: JS ERROR: AuthenticationError
_authenticate@/../gsconnect@andyholmes.github.io/service/protocol/lan.js:415:33
async*_clientEncryption@/../gsconnect@andyholmes.github.io/service/protocol/lan.js:444:16
accept@/../gsconnect@andyholmes.github.io/service/protocol/lan.js:543:38
async*_onIncomingChannel@/../gsconnect@andyholmes.github.io/service/protocol/lan.js:121:19
Async*@/../gsconnect@andyholmes.github.io/service/daemon.js:744:2

Jun 15 10:33:50 teevey gjs[2778]: JS ERROR: AuthenticationError
_authenticate@/../gsconnect@andyholmes.github.io/service/protocol/lan.js:415:33
async*_clientEncryption@/../gsconnect@andyholmes.github.io/service/protocol/lan.js:444:16
accept@/../gsconnect@andyholmes.github.io/service/protocol/lan.js:543:38
async*_onIncomingChannel@/../gsconnect@andyholmes.github.io/service/protocol/lan.js:121:19
Async*@/../gsconnect@andyholmes.github.io/service/daemon.js:744:2
```

Unpairing and re-pairing the phone cleared it up, and everything seems fine now. \*shrug\* Just thought I'd record it in case others hit the same thing.

**System Details (please complete the following information):**

 - **GSConnect version:** 24
   - **Installed from:** e.g.o
 - **GNOME/Shell version:** 3.32.2
 - **Distro/Release:** Fedora 30

**GSConnect environment (if applicable):**

 - **Paired Device(s):** Galaxy S6
 - **KDE Connect app version:** 1.12.9
 - **Plugin(s):** ---

**Comment by didierga** [comment]
Same issue since update to KDE Connect 1.12.9 using it with GSConnect 24.
Annoying !

**Comment by ferdnyc** [comment]
@didierga Yeah, KDE Connect freaked out on me a bit, too, trying to re-pair, I ended up having to send pair requests from _both_ ends to get them paired back up.

**Comment by andyholmes** [comment]
It's possible this was caused by the patch [Re-generate cert if it's for a different device ID](https://invent.kde.org/kde/kdeconnect-android/commit/ea136498b491c620c9f274e8452ae8770d99ec5a). Have either of you backed-up & restored from a different phone, android version or something else that could have changed your device's hostname?

Basically the way we check for certificate, is to look for a local certificate based on the remote id's device. If the certificate we have doesn't match the one provided by the remote device, we consider it an authentication error.

Unfortunately, these situations are pretty rare, so neither GSConnect or KDE Connect deal with them terribly well in terms of UX. Meaning the devices don't really stop trying to connect to each other, so GSConnect will just show a notification and I think KDE Connect silently closes the connection.

**Comment by ferdnyc** [comment]
@andyholmes Not that I can think of. And device ID from GSConnect's end was definitely the same after the unpair/repair cycle, as before. I'd opened `dconf-editor` and was digging around looking at things like IDs and certificates, when the problem started, so I was able to observe the device being re-paired with the exact same ID.

Last night my phone got a _new_ build of KDE Connect 1.12.9, with no visible changes / changelog info. That build failed to cause any new freakouts, which is good, so perhaps it contains a fix for whatever happened with the previous update. (But, of course, it's just as possible that the reason for the non-freakout was simply that I'd already unpaired and re-paired.)

**Comment by didierga** [comment]
I dissociated desktop on KDE Connect and I dissociated and deleted phone on GSConnect then I tried to associate it again.
I get on KDE Connect following message (translation) "KDE Connect is stopped / Report OK"
If I DONT click anything on phone, I let message on, I stay connected and I can transfer photos between phone and desktop.
If I click on OK, I lose connection.

**Comment by ferdnyc** [comment]
@didierga Oh, this is _still_ happening to you!? I didn't realize.

One other thing I did when trying to fix this, but then forgot to mention, was clear the _cache_ for KDE Connect on my phone. (Not the data, just the cache.) You could give that a try, see if it helps. Or, restarting your phone might clear it up.

**Comment by ferdnyc** [comment]
Another day, _another_ new 1.12.9 build via Google Play. I'm still signed up to the beta program, but I don't think these are even betas. (Betas should have a different version identifier, no?) No, clearly they're still tweaking 1.12.9, so I'm becoming more convinced this was probably a bug on the device app side.

**Comment by ferdnyc** [comment]
This appears to have been resolved on the KDE Connect app end, closing.
