### ISSUE TITLE
Add CLI interface

### ISSUE THREAD

**Issue by logix2** [andyholmes/gnome-shell-extension-gsconnect#564]
Is there a way to send a file from the command line using GSConnect, similar to kdeconnect-cli? If not, would it be possible to implement it? That's useful if for example you want to integrate it into some command that you trigger from the KDE Connect Android app, which sends you a file back to the phone upon command completion.

**Comment by andyholmes** [comment]
Currently there's no way to do this (easily). You can *technically* invoke any GAction registered by a device using something like:

```
$ gapplication action org.gnome.Shell.Extensions.GSConnect device "('your_device_id', 'shareFile', true, <('/path/to/file.txt', false)>)"
```

Clearly this is super obvious to everyone and fun to do :wink: 

GSConnect is a lot more amenable to use over DBus at the moment. I can try to add a proper CLI interface, but it might be awhile. I don't have much free time and there are some upcoming breaking changes in the KDE Connect protocol, as well as a number of other unfinished projects.

**Comment by andyholmes** [comment]
Okay, so I guess I got bored and just did it :confused:. Maybe you want to try this Zip and tell me what you think?

[gsconnect@andyholmes.github.io.zip](https://github.com/andyholmes/gnome-shell-extension-gsconnect/files/3317563/gsconnect%40andyholmes.github.io.zip)

If you want to run commands from the command-line you have enter the extension directory or call the full path of the script:

```
$ cd ~/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io
$ ./daemon.js --help
Usage:
  org.gnome.Shell.Extensions.GSConnect [OPTION…]

Help Options:
  -h, --help                    Show help options
  --help-all                    Show all help options
  --help-gapplication           Show GApplication options
  --help-gtk                    Show GTK+ Options

Application Options:
  -l, --list-devices            List all devices
  -a, --list-available          List available devices (connected and paired
  -d, --device=<device-id>      ID of a device to handle command
  -f, --file=<filepath|URI>     Share a local or remote file, by URI or absolute file path
  -n, --notification            Send a notification
  -c, --photo                   Take a photo with the device camera
  -p, --ping                    Ping the device
  -r, --ring                    Ring the device
  -s, --sms=<phone-number>      Send an SMS message
  -u, --url=<URL>               Send a URL
  -t, --title=<title>           Set the title for a notification
  -b, --body=<body>             Set the body for a notification, ping or SMS
  -i, --icon=<icon-name>        Set the icon name for a notification
  -v, --version                 Show release version
  --display=DISPLAY             X display to use
```

However, scripting from a command shared with a device is a little easier:

```sh
#!/bin/bash

echo $GSCONNECT;             # Path to the application (`daemon.js`)
echo $GSCONNECT_DEVICE_DBUS; # DBus object path, useful for Python, GJS or other script
echo $GSCONNECT_DEVICE_ID;
echo $GSCONNECT_DEVICE_NAME;
echo $GSCONNECT_DEVICE_ICON;

${GSCONNECT} --device ${GSCONNECT_DEVICE_ID} --file ${HOME}/test.jpg \
                                             --file ${HOME}/test.gif
```

Files and urls can be supplied more than once. The `--body` tag applies to a few commands, and you can run each command at least once in a single command. So this would work, it just might do more than you expect it to:

```
#!/bin/bash

${GSCONNECT} --device ${GSCONNECT_DEVICE_ID} \
             --file ${HOME}/test.jpg \
             --notification
             --sms "555-5555" \
             --ping \
             --ring \
             --photo \
             --body "Gets sent as the notification, ping AND sms body" \
             --title "Notification Title" \
             --icon "dialog-information-symbolic" \
             --url "https://www.gnome.org/"
```

Have fun and let me know how it goes :)

**Comment by logix2** [comment]
Sorry for answering so late, I was sick for the last few days. It's working great, thank you very much!

To anyone else reading this, note that the daemon.js file is in the service folder, and not in the root GSConnect folder. At least in the .zip attached above.

**Comment by jcursiolf** [comment]
Hey @andyholmes , sorry to bother you by opening it again. I tried to use your 2nd zip and many commands work, some not. The ones that do not work with my OnePlus 5 (model A5000 with the altests stable Android/Oxigen OS 9.0.6) are `--file`, `--sms`, and `--photo` (the app has all permissions and the same functions do work normally through GUI or `gapplication`).

_Semi-related:_ Just as a tip for anybody that wanted to use `kdeconnect-cli` to create a command to trigger a screenshot from the computer that is saved on the phone, this worked for me:

`file=/tmp/$(hostname)_$(date "+%Y%m%d_%H%M%S").png; gnome-screenshot -f "${file}" && gapplication action org.gnome.Shell.Extensions.GSConnect device "('599c464b1328e364', 'shareFile', true, <('${file}', false)>)"`

**Comment by andyholmes** [comment]
I'm marking this as closed, since the CLI interface is in v25. However, some of the options changed and might change again before v26. Hopefully I'll have a wiki page up by then documenting the whole thing.
