### ISSUE TITLE
Save geometry for all windows

### ISSUE THREAD

**Issue by andyholmes** [andyholmes/gnome-shell-extension-gsconnect#566]
Could you may Workaround it and made the Window a bit wider and higher?

_Originally posted by @Mannshoch in https://github.com/andyholmes/gnome-shell-extension-gsconnect/issues/556#issuecomment-502337909_

**Comment by ferdnyc** [comment]
Regarding the conversation window, specifically, what about using `GtkEntry`'s "Width in characters" property? Setting something like
```glade
        <property name="width_chars">50</property>
```
would likely make it wide enough for the emoji popup right from the start.

**Comment by andyholmes** [comment]
I thought about doing something more fixed, I'm just not sure how the emoji popup's size is constrained (if at all) and whether that might change with font family, size etc.

I think it's just going to be easier in the long run to make a generalized window geometry schema for gsettings and apply it per-window. It also means I only have to do it once :)

**Comment by ferdnyc** [comment]
Makes sense! Though for the messaging window, would setting some reasonable minimum `width_chars` help to prevent a new, empty conversation window from always coming up too narrow the first time it's used?
