### ISSUE TITLE
I tried installing it in Fedora but I can't configure the extension

### ISSUE THREAD

**Issue by Fatih20** [andyholmes/gnome-shell-extension-gsconnect#567]

**Comment by ferdnyc** [comment]
Hi @Fatih20, a few questions so we can help you:

1. How did you install the extension? (extensions.gnome.org, Zip file download, the Fedora package repository, or some other method....)
2. If you installed GSConnect to your user account (extensions.gnome.org or zipfile download), are you sure it isn't _also_ installed systemwide? Having installs in both places can cause problems. 

   If you want to make sure, just open a terminal and run `sudo dnf remove gnome-shell-extension-gsconnect`. If it comes back `Nothing to do.`, then everything's fine. But if DNF asks you to confirm an uninstall ("Is this OK [y/N]:") then you should answer "Y" to remove the systemwide copy.
3. [Have you tried turning it off and on again?](https://www.youtube.com/watch?v=nn2FB1P_Mn8) ...Sorry, just joking.

   But really: Have you logged out and logged back in again? (Or just restart the computer.) You'll also need to do that if you end up uninstalling a systemwide `gnome-shell-extension-gsconnect` in the previous step.

**Comment by ferdnyc** [comment]
Closing this due to lack of response.
