### ISSUE TITLE
Clarify that "Do Not Disturb" does not change mode on the phone, too

### ISSUE THREAD

**Issue by xuiqzy** [andyholmes/gnome-shell-extension-gsconnect#572]
**Is your feature request related to a problem? Please describe.**
I was testing the Do Not Disturb functionality and about to file a bug request for the feature not working until I realized in a related bug report that it is only for silencing notifications from the phone on the desktop and not on the phone itself.

**Describe the solution you'd like**
It would probably be better if Do Not Disturb would actually be activated on the phone, too, since when one doesn't want the notifications on the desktop, one most likely also doesnt want their phone to be vibrating / making a sound or turning the display on.

**Describe alternatives you've considered**
It should at least be clear that only notifications on the desktop are silenced. Show a "(on desktop)" string after Do not disturb. Renaming the option to make the distinction clear could help, but is probably more confusing and could give problems with people translating that to a string that is identical to Android or a silence feature on a connected device.
Additionally and more importantly, explain the situation in the popup shortly like "Notifications on the phone itself won't be silenced, but the notifications from the phone won't interrupt on this desktop".

**System Details (please complete the following information):**
 - GSConnect version:  24
   - Installed from: extensions.gnome.org through Gnome Software on Gnome Shell in Arch Linux

**Additional context**
If supporting Do Not Disturb on the phone, too, the important, priority, alarms only and total silence modes could be used.

**Comment by andyholmes** [comment]
This is the popup that appears when the item is selected:
![Screenshot from 2019-07-23 18-07-16](https://user-images.githubusercontent.com/1265208/61757317-e3225380-ad74-11e9-9b8f-8a2634444219.png)

The subtitle text could be changed, but this is the best place to clarify the behaviour. The GNOME Shell user menu has a fixed width, so making the text longer in the menu is not a good idea, especially given how long things can get when translated.

> It would probably be better if Do Not Disturb would actually be activated on the phone, too, since when one doesn't want the notifications on the desktop, one most likely also doesnt want their phone to be vibrating / making a sound or turning the display on.

This would have to be implemented at the protocol level and therefore must be discussed upstream with KDE Connect developers. You can open an issue for that here: https://bugs.kde.org/buglist.cgi?component=android-application&list_id=1646262&product=kdeconnect

**Comment by andyholmes** [comment]
I'm not keen on injecting a giant paragraph explaining the difference between silencing notifications from remote devices vs silencing remote device notifications; especially this close to v27. For now the subtitle reads *"Silence Notifications from Mobile Devices"*, which should clarify it somewhat.

Ultimately, this feature should either be supported by the protocol or implemented as a local feature in gnome-shell. It doesn't really make sense for us to do this on our side anyways which is why we don't have a "Receive Notifications" option, or for someone to only want to be undisturbed by just remote notifications, since the whole point is to sync notifications.
