### ISSUE TITLE
Doesn't work in Ubuntu Gnome 16.04

### ISSUE THREAD

**Issue by jeroen7s** [andyholmes/gnome-shell-extension-gsconnect#58]
using GNOME Shell 3.18.5
it gives me an error:
Error: can't convert default_value to an integer

Stack trace:
  @resource:///org/gnome/gjs/modules/overrides/GObject.js:295
  @/home/jeroene/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/client.js:140
  @/home/jeroene/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/prefs.js:24
  Application<._getExtensionPrefsModule@resource:///org/gnome/shell/extensionPrefs/main.js:79
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178
  Application<._selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:94
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178
  Application<._onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:259
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178
  main@resource:///org/gnome/shell/extensionPrefs/main.js:397
  @<main>:1

**Comment by andyholmes** [comment]
Sorry about that. Only Gnome Shell 3.24+ is supported, the versions of GJS shipped with Gnome Shell just has too many limitations prior to that.
