### ISSUE TITLE
Approved wrong translations

### ISSUE THREAD

**Issue by to-ba** [andyholmes/gnome-shell-extension-gsconnect#590]
Approved wrong translations
@andyholmes you have approved all german translations on crowdin but there are many mistakes in your approved translations. Please unlock ore remove your wrong translations.

**Comment by ferdnyc** [comment]
@to-ba I unlocked the ones you'd voted incorrect, and left a couple of questions for you on ones where you'd left suggestions. Purely driven by Crowdin's own auto-suggestions and the "GTranslate ping-pong method" of attempting to arrive at a bidirectional translation. I don't claim to speak German at all (I barely speak English) so I'm just raising issues to double-check, but ultimately I'm happy to defer to your expertise.

**Comment by to-ba** [comment]
@ferdnyc Thanks.
But there are many more wrong.
I never used GTranslate looks like you have to pay for it.

**Comment by andyholmes** [comment]
All approvals for German (de) have been removed now, closing.
