### ISSUE TITLE
Re-confirm simultaneous IPv4 & IPv6 support

### ISSUE THREAD

**Issue by andyholmes** [andyholmes/gnome-shell-extension-gsconnect#593]
Just wanted to say that this was my exact issue with connecting through a Wireguard VPN. I couldn't figure out why I wasn't getting a connection but it turned out that GSConnect on the desktop wasn't listening on IPv4 and therefore the VPN wouldn't facilitate the connection. Disabling IPv6 fixed the issue. Thank you!

_Originally posted by @decaby7e in https://github.com/andyholmes/gnome-shell-extension-gsconnect/issues/69#issuecomment-522130271_

**Comment by ferdnyc** [comment]
I wonder if this has something to do with the kernel tunable `/proc/sys/net/ipv6/bindv6only`? Apparently simultaneous binding of IPv4 and IPv6 is _configurable_ (via that `/proc` path), and different distros might set it differently.

It's `0` on my Fedora 30 box, so the IPv4 binding is implied by the IPv6 binding. But on any systems where it's set to `1`, they presumably wouldn't have GSConnect listening on IPv4 automatically, unless you were to bind the port twice. (Of course, then if you do manually perform both bindings, the IPv4 attempt will fail on systems where it's set to `0`. But that can be ignored if the IPv6 binding succeeds, as long as IPv6 is attempted first. That's [what MPD does](https://github.com/MusicPlayerDaemon/MPD/issues/557).)

**Comment by andyholmes** [comment]
I think I've actually done this in GLib/C before...I just also thought `GSocketService`/`GSocketListener` did this automatically for sockets. IIRC you just bind IPv6 socket and if it succeeds *and* `g_socket_speaks_ipv4 ()` is `TRUE` you're all done; otherwise failure or success you open an IPv4 socket.

**Comment by ferdnyc** [comment]
The weird thing, too, is that the current code for the UDP listener explicitly requests IPv4...

https://github.com/andyholmes/gnome-shell-extension-gsconnect/blob/3b6d45742e858b0accb2d5d732651ab87fd43f3b/src/service/protocol/lan.js#L151-L164

So it's weird that it would be listening _**only**_ on IPv6 under _any_ circumstances, in that case. Unless the fact that you're listening on the IPv4 UDP port makes something think that it _shouldn't_ auto-bind the IPv4 address for the TCP listener?

(Why is UDP IPv4-only? A quick check of `netstat` on my phone shows that KDE Connect itself has both TCP and UDP listeners bound to `:::1716`.)

**Comment by decaby7e** [comment]
Just wanted to stop in and say that everything is currently working just as it should and my original issue has been resolved. My original statement about it being fixed jinxed me at first but I tried it again just today and things are working now.

**Comment by ferdnyc** [comment]
@decaby7e Hmm. Well, then fingers crossed that things _continue_ to work correctly in v25, now that the IPv4/IPv6 binding has been changed to handle such situations better — and hopefully not exactly the opposite.
