### ISSUE TITLE
Feature request: Backup & restore commands 

### ISSUE THREAD

**Issue by fakhamatia** [andyholmes/gnome-shell-extension-gsconnect#609]
Please add an option to backup and restore commands.

**Comment by andyholmes** [comment]
As discussed in #537, this probably won't be built in as a feature. It's possible to manually backup and restore commands using dconf:

    $ dconf dump /org/gnome/shell/extensions/gsconnect/device/<device-id>/plugin/runcommand/ > cmds.dump
    $ cat cmds.dump | dconf load /org/gnome/shell/extensions/gsconnect/device/<device-id>/plugin/runcommand/
