### ISSUE TITLE
Settings don't open under Ubuntu 17.10

### ISSUE THREAD

**Issue by sojusnik** [andyholmes/gnome-shell-extension-gsconnect#61]
Hey!

When I try to open the settings, the following appears:

```
Error: Wrong type integer; string expected

Stack trace:
  _init/Gtk.Widget.prototype._init@resource:///org/gnome/gjs/modules/overrides/Gtk.js:48:9
  AboutWidget<._init@/home/sojusnik/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/prefs.js:56:28
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  PrefsWidget<._init@/home/sojusnik/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/prefs.js:140:27
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  buildPrefsWidget@/home/sojusnik/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/prefs.js:215:23
  Application<._selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:91:22
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  Application<._onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:246:17
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  main@resource:///org/gnome/shell/extensionPrefs/main.js:402:5
  @<main>:1:43
```
Pairing with the device itself works. The plugins also seem to work.

Using Ubuntu 17.10 with Gnome 3.26.2 (Xorg, not Wayland) and installed your addon from the Gnome extensions website.

**Comment by andyholmes** [comment]
Arg, such a silly mistake on my part. I've just pushed a new release to the extensions site which should be reviewed shortly. You can download it now from the [releases](https://github.com/andyholmes/gnome-shell-extension-gsconnect/releases) page, or add `toString()` to line [56 of prefs.js](https://github.com/andyholmes/gnome-shell-extension-gsconnect/blob/master/src/prefs.js#L56) yourself, if that's easier.

````js
let aboutVersion = new Gtk.Label({ label: ext.metadata.version.toString() });
this.add(aboutVersion);
````

Thanks for reporting this, I can't believe I missed it
