### ISSUE TITLE
Type Error when installing GSConnect

### ISSUE THREAD

**Issue by nroomy** [andyholmes/gnome-shell-extension-gsconnect#611]
**Describe the bug**

I try to install the GSConnect through Gnome extensions or even Git or even meson, and I get this error as soon as I finish Installing. GSC doesnt work, cannot pair any device to it.

**Steps To Reproduce:**

Installing GSConnect will cause this error.

**Expected behavior**

GSC to be installed and device to be paired. 

**Screenshots**

https://ibb.co/Mnd7C10

**Support Log**

-- Logs begin at Tue 2019-09-10 10:42:16 +0530, end at Tue 2019-09-10 13:13:49 +0530. --
Sep 10 13:13:34 wpa_supplicant[1017]: wlp2s0: WPA: Group rekeying completed with 00:10:f3:73:f9:c8 [GTK=TKIP]
Sep 10 13:13:45 gjs[5940]: Failed to set property AtkObject.accessible-role to title-bar: Could not parse integer 'title-bar'
Sep 10 13:13:45 gjs[5940]: Failed to set property AtkObject.accessible-role to link: Could not parse integer 'link'
Sep 10 13:13:45 gjs[5940]: Failed to set property AtkObject.accessible-role to link: Could not parse integer 'link'
Sep 10 13:13:45 gjs[5940]: Failed to set property AtkObject.accessible-role to list: Could not parse integer 'list'
Sep 10 13:13:45 gjs[5940]: Failed to set property AtkObject.accessible-role to link: Could not parse integer 'link'
Sep 10 13:13:45 gjs[5940]: Failed to set property AtkObject.accessible-role to link: Could not parse integer 'link'
Sep 10 13:13:45 gjs[5940]: Failed to set property AtkObject.accessible-role to link: Could not parse integer 'link'
Sep 10 13:13:45 gjs[5940]: Failed to set property AtkObject.accessible-role to list: Could not parse integer 'list'
Sep 10 13:13:45 gjs[5940]: Failed to set property AtkObject.accessible-role to layered-pane: Could not parse integer 'layered-pane'
Sep 10 13:13:49 gjs[5940]: GtkDialog mapped without a transient parent. This is discouraged.

**System Details**

 - **GSConnect version:**
v25

   - **Installed from:**
GNOME Extensions, GitHub, Meson build

 - **GNOME/Shell version:** 
3.28

 - **Distro/Release:**
PopOS (Based on Ubuntu 18.04)

 - **Paired Device(s):** 
None, tried to pair to a Honor Play.

 - **KDE Connect app version:** 
1.13
 -

**Additional Notes:**
None

**Comment by bentolor** [comment]
Related to #612 ?

**Comment by nroomy** [comment]
@andyholmes

Thanks for the quick fix! Works perfectly now :)
