### ISSUE TITLE
Support Gnome 3.34

### ISSUE THREAD

**Issue by taaem** [andyholmes/gnome-shell-extension-gsconnect#625]
It would be nice to have 3.34 support (I don't know if there are changes under the hood).

If there are no extension changes, than this should be a one-liner change.

**Comment by andyholmes** [comment]
Seems to work for me, but should probably be tested more.

**Comment by andyholmes** [comment]
Sorry, this is not fixed. It looks like we'll probably have to drop support for <= 3.32 in order to sanely support 3.34+. I'm not entirely sure when that will be.

**Comment by blackwolf12333** [comment]
I am having an issue with the webextension that seems to be doing something weird to the mpris interface?
When I started playing something on youtube the following error happened, this didn't happen in 3.32 I think

    Sep 20 10:54:09 coffee gnome-shell[878]: JS ERROR: Exception in callback for signal: changed: TypeError: this._player.trackArtists.join is not a function
                                         _update@resource:///org/gnome/shell/ui/mpris.js:60:23
                                         _emit@resource:///org/gnome/gjs/modules/signals.js:142:27
                                         _updateState@resource:///org/gnome/shell/ui/mpris.js:180:9
    Sep 20 10:54:09 coffee gnome-shell[878]: JS ERROR: Exception in callback for signal: show: TypeError: this._player.trackArtists.join is not a function
                                         _update@resource:///org/gnome/shell/ui/mpris.js:60:23
                                         MediaMessage@resource:///org/gnome/shell/ui/mpris.js:47:9
                                         _addPlayer/<@resource:///org/gnome/shell/ui/mpris.js:222:31
                                         _emit@resource:///org/gnome/gjs/modules/signals.js:142:27
                                         _updateState@resource:///org/gnome/shell/ui/mpris.js:187:17
                                         _onPlayerProxyReady@resource:///org/gnome/shell/ui/mpris.js:169:9
                                         _makeProxyWrapper/</<@resource:///org/gnome/gjs/modules/overrides/Gio.js:243:21

Should I report this as a separate issue or is this a good place to gather incompatibilities?

**Comment by ferdnyc** [comment]
> I am having an issue with the webextension that seems to be doing something weird to the mpris interface?
> When I started playing something on youtube the following error happened, this didn't happen in 3.32 I think

@blackwolf12333  I just double-checked, there's no MPRIS code in the GSConnect web extension at all. And nothing in that log appears to involve GSConnect. (The logs are coming from `gnome-shell`, not `gjs`.)

Is it possible that could be caused by another extension, like Chrome's own MPRIS plugin (present in the newest Unstable builds, at least) or something like `plasma-browser-integration`?

**Comment by andyholmes** [comment]
@blackwolf12333 As @ferdnyc said, there's no MPRIS code in the webextension, and in fact it's really just a simple shim to invoke two actions on DBus.

However, that doesn't mean something didn't change in GNOME or GNOME Shell we might have to address, and you're welcome to use this issue for anything that might be 3.34 related.

This might be a tricky one to track down, but you might be able to use [Bustle](https://flathub.org/apps/details/org.freedesktop.Bustle) or `dbus-monitor` to help track the true source.

**Comment by laichiaheng** [comment]
Sometimes, the battery icon becomes really huge without any reason in Gnome3.34, but it becomes normal after I click on it.

**Comment by blackwolf12333** [comment]
@andyholmes @ferdnyc I investigated a bit more. @ferdnyc your suggestion that it might be a different chrome extension was correct. I was unaware I had the `plasma-browser-integration` extension installed as well, that causes the error I saw.

**Comment by ferdnyc** [comment]
@blackwolf12333 I hope that gets fixed before the Fedora 31 release! I am waaaay too much in love with `plasma-browser-integration` to give it up now! :laughing:

**Comment by laichiaheng** [comment]
> Sometimes, the battery icon becomes really huge without any reason in Gnome3.34, but it becomes normal after I click on it.

By the way, it looks like this:
![2019-09-21 22-52-06 的螢幕擷圖](https://user-images.githubusercontent.com/9532105/65375035-715a7d80-dcc3-11e9-9f59-be22c4a567dc.png)

**Comment by ferdnyc** [comment]
@laichiaheng From the detail there, am I right in thinking you have a HiDPI screen? It's probably somewhere in the scaling support that GSConnect is going wrong, maybe they made changes for 3.34.

**Comment by laichiaheng** [comment]
@ferdnyc No, just a usual 1080p monitor.

**Comment by ferdnyc** [comment]
@laichiaheng Hm! Surprising, but good to know, thanks.

**Comment by andyholmes** [comment]
FYI, I have a pretty good idea why the icon does that (even though I can't reproduce), it's just weird it started happening now. Basically, we don't bother drawing the icon until the menu is actually mapped to avoid updating it when it can't possibly be seen.

**Comment by andyholmes** [comment]
@laichiaheng The large icon bug may be specific to Arch; there is now a bug open against GNOME Shell [#1708](https://gitlab.gnome.org/GNOME/gnome-shell/issues/1708) that describes the same behaviour.

**Comment by jkotra** [comment]
https://github.com/andyholmes/gnome-shell-extension-gsconnect/issues/655

**Comment by blackwolf12333** [comment]
I updated my arch install recently and now I'm getting this warning about deprecated usage:

    Oct 04 13:08:50 rubberduck gnome-shell[1259]: Usage of object.actor is deprecated for Indicator
                                              get@resource:///org/gnome/shell/ui/environment.js:242:29
                                              _sync@/home/peter/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/extension.js:155:17
                                              _onDeviceAdded@/home/peter/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/extension.js:248:13
                                              _onInterfacesAdded@/home/peter/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/shell/remote.js:347:13
                                              async*_onNameOwnerChanged@/home/peter/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/shell/remote.js:390:27
                                              async*start@/home/peter/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/shell/remote.js:448:9
                                              async*_init_async@/home/peter/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/extension.js:134:19
                                              async*ServiceIndicator@/home/peter/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/extension.js:115:9
                                              enable@/home/peter/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/extension.js:361:24
                                              _callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:131:13
                                              _enableAllExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:486:17
                                              _enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:485:13
                                              _sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:513:13
                                              _emit@resource:///org/gnome/gjs/modules/signals.js:135:27
                                              _sync@resource:///org/gnome/shell/ui/sessionMode.js:205:9
                                              popMode@resource:///org/gnome/shell/ui/sessionMode.js:174:9
                                              _continueDeactivate@resource:///org/gnome/shell/ui/screenShield.js:1198:13
                                              deactivate/<@resource:///org/gnome/shell/ui/screenShield.js:1184:39
                                              finish@resource:///org/gnome/shell/gdm/authPrompt.js:492:13
                                              finish@resource:///org/gnome/shell/ui/unlockDialog.js:134:9
                                              deactivate@resource:///org/gnome/shell/ui/screenShield.js:1184:13
                                              ScreenShield</</<@resource:///org/gnome/shell/ui/screenShield.js:533:52
                                              _emit@resource:///org/gnome/gjs/modules/signals.js:135:27
                                              _convertToNativeSignal@resource:///org/gnome/gjs/modules/overrides/Gio.js:169:5

**Comment by JohannPopper** [comment]
Not that just asking here is very scientific, but is anyone else here experiencing a big delay between received texts on their phone vs when it's pushed to shell notification? Like as serious as up to a few minutes between receipt on phone and when GSConnect displays it. If so, I'll assume it's not a bad 3.34 update on my part. Until then, I'll try to find the cause and post any anomalies here -- for now all I know is it didn't start until I updated to 3.34.

**Comment by ferdnyc** [comment]
> Not that just asking here is very scientific, but is anyone else here experiencing a big delay between received texts on their phone vs when it's pushed to shell notification? Like as serious as up to a few minutes between receipt on phone and when GSConnect displays it. If so, I'll assume it's not a bad 3.34 update on my part. Until then, I'll try to find the cause and post any anomalies here -- for now all I know is it didn't start until I updated to 3.34.

You could run in Generate Support Log mode and send yourself a text (or have someone else...), check the timestamps for when the messages comes over the network — GSConnect should display whatever it receives whenever it receives it, if there's a delay it's usually on the Android side. Sometimes device power saving can prevent KDE Connect from waking up to relay the notification, by as much as several minutes. We've definitely seen that. (KDE Connect also updated recently, perhaps that changed something.)

**Comment by andyholmes** [comment]
You can also watch DBus to see when GSConnect send the notification. I've recently noticed notifications seem to be doing some blocking of the packet socket in the Android client, but thought it was just my flaky router. `dbus-monitor --session` should show when GSConnect sends the notification to the notification server.
