### ISSUE TITLE
[Feature thinking] Using XMPP

### ISSUE THREAD

**Issue by Postroutine** [andyholmes/gnome-shell-extension-gsconnect#63]
Actually, GSConnect use the KDE Connect protocol.

But what about using XMPP?

You can use :
-   [XEP-0174: Serverless Messaging](https://xmpp.org/extensions/xep-0174.html) for communicate on local network without an XMPP account or server
-   A classic XMPP account to communicate through Internet
-   [XEP-0050: Ad-Hoc Commands](https://xmpp.org/extensions/xep-0050.html) for requests  between devices (PC and phone), file system exploration, notification sending, request GPS position, etc
-   [XEP-0166: Jingle](https://xmpp.org/extensions/xep-0166.html) for audio communication (like phone call from PC)
-   [XEP-0234: Jingle File Transfer](https://xmpp.org/extensions/xep-0234.html) for file transfer
-   [XEP-0030: Service Discovery](https://xmpp.org/extensions/xep-0030.html) to let the phone and the PC discover which features the other side provide
-   Using one of the [400 extensions](https://xmpp.org/extensions/) or create your own for future features

It's just a thinking, but it could be useful to GSConnect.

**Comment by andyholmes** [comment]
That's a good idea, but after a quick look there seem to be few, if any, Android clients that support those extensions. Being able to re-use the KDE Connect Android app is a big help, and rationale, for using the KDE Connect protocol.

There are number of existing XMPP clients for the Gnome desktop that could probably be adapted or re-used for such a purpose and that would work well for developing a cross-desktop standard to replace the KDE Connect protocol.

Unfortunately it's a little out of the scope of this project, but if you were interested in re-using the GSConnect code base, I'd be happy to help explain some the internals.

**Comment by Postroutine** [comment]
> but if you were interested in re-using the GSConnect code base, I'd be happy to help explain some the internals.

I take notes. :)
