### ISSUE TITLE
Do Not Disturb toggle is not working

### ISSUE THREAD

**Issue by molaeiali** [andyholmes/gnome-shell-extension-gsconnect#630]
**Describe the bug**
Do Not Disturb toggle is not working

**Steps To Reproduce:**

1. Go to Top Right Menu of Gnome
2. Click on Phone Name (GS-Connect)
3. Click on Do Not Disturb Toggle to turn it on
4. See error (It do noting)

**Expected behavior**
Turn on the Do not Disturb mode

**Support Log**
I get this error log in my journalctl
```
Sep 22 11:53:46 archlinux gnome-shell[1182]: JS ERROR: TypeError: this._getDurationLabel is not a function
                                             Dialog@/home/ali/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/shell/donotdisturb.js:186:17
                                             MenuItem/<@/home/ali/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/shell/donotdisturb.js:300:30
                                             toggle@resource:///org/gnome/shell/ui/popupMenu.js:371:9
                                             activate@resource:///org/gnome/shell/ui/popupMenu.js:358:13
                                             _onButtonReleaseEvent@resource:///org/gnome/shell/ui/popupMenu.js:134:9
```

**System Details:**

 - **GSConnect version:** 26
   - **Installed from:** GNOME Extensions Website
 - **GNOME/Shell version:** 3.34
 - **Distro/Release:** Arch

**GSConnect environment (if applicable):**

 - **Paired Device(s):** Galaxy S7
 - **KDE Connect app version:** 1.13.1

**Comment by andyholmes** [comment]
Thanks for reporting. v26 does not support GNOME Shell 3.34, so you'll have to install from git or wait for v27 to run GSConnect on 3.34.

See Issue #625 for more information.
