### ISSUE TITLE
No JS module 'lock' found in search path (v26)

### ISSUE THREAD

**Issue by Znert** [andyholmes/gnome-shell-extension-gsconnect#647]
**Describe the bug**

After updating to version 26 I get the error mentioned above every time I boot the machine via a system notification.

The stack trace is as follows:
_loadPlugin@/home/shayden/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/device.js:903:17
_loadPlugins@/home/shayden/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/device.js:924:19
async*_init@/home/shayden/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/device.js:154:9
vfunc_startup@/home/shayden/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:680:26
vfunc_handle_local_options@/home/shayden/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:1090:13
@/home/shayden/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:1157:2

**Steps To Reproduce:**

1. Update to v26
2. Wait or reboot the machine

**Expected behavior**

No error is thrown.

**Screenshots**

Not really applicable.

**Support Log**

```
GSConnect Version: 26
GSConnect Install: user
GJS: 15602
XDG_SESSION_TYPE: wayland
GDMSESSION: gnome
--------------------------------------------------------------------------------
-- Logs begin at Mon 2018-08-27 10:21:59 CEST, end at Mon 2019-09-30 07:30:47 CEST. --
-- No entries --
```
Note that the error already occurred, but the log is still empty. This was after 

**System Details (please complete the following information):**

 - **GSConnect version:** 26
   - **Installed from:** GNOME Extensions Website
 - **GNOME/Shell version:** 3.32
 - **Distro/Release:** Fedora 30

**Comment by andyholmes** [comment]
It looks like you have some very old settings lying around. I'd recommend you clear the `supported-plugins` setting for your device, or specifically remove the `lock` plugin from the list of supported plugins. With `dconf`:

    $ dconf reset /org/gnome/shell/extensions/gsconnect/device/<device-id>/supported-plugins

Or with `dconf-editor`:

![Screenshot from 2019-09-30 11-25-38](https://user-images.githubusercontent.com/1265208/65905249-12f16700-e375-11e9-9512-bab62ce9a8ac.png)

**Comment by ferdnyc** [comment]
> Note that the error already occurred, but the log is still empty. This was after

\*nod* Generate Support Log only captures any output produced _**while**_ it's actively collecting — it's only useful (and is meant to be used) in the cases where you can reproduce a repeatable issue after activating it, to collect more detailed logs.

For problems that have already occurred, best thing is to just copy-paste whatever logs/errors you encountered into an issue.

**Comment by Znert** [comment]
Sorry for answering so late, I hadn't had access to my work laptop recently and then forgot to do what you told me.

The thing is, there was no `lock` in the supported plugins array. I tried to reset the key anyways, which just resulted in an empty list being shown in the settings for this device. So I fully removed the plugin following the Wiki entry, paired my phone once again and the error still occurs with the same stack trace.

These are the supported plugins from the only device connected to the laptop:

![Screenshot from 2019-10-08 08-21-39](https://user-images.githubusercontent.com/18900196/66371950-0c7e7300-e9a5-11e9-8eac-8108065ce190.png)

So maybe some further details I forgot to mention initially:
* I'm running on wayland since its the default by Fedora anyways
* My phone is a Nokia 7 Plus with Android 9
* The version of KDE Connect on the phone is 1.13.2 (according to the Play Store)

**Comment by ferdnyc** [comment]
@Znert As @andyholmes says, GSConnect hasn't had a JavaScript file `lock.js` since... forever ago. Some thoughts:

* Are you sure the "No JS module 'lock' found in search path" message is being triggered by GSConnect, and not some other Gnome Shell extension/component?
* Could an older GSConnect be installed in a system location? You might want to check for a `gnome-shell-extension-gsconnect` package installed on the system via `dnf`, and remove it if there is.
* To view all messages involving GSConnect in your user journal, you can run a command like:
   ```
   journalctl --user --grep gsconnect -n 100000 -e
   ```
   * `-e` tells journalctl to start from the end of the logs (most recent)
   * `-n 100000` is the number of messages to scan — that's _before_ the grep, and the journal is a noisy place
   * the rest of the options should be self-explanatory

**Comment by ferdnyc** [comment]
Reopening for the moment.

**Comment by Znert** [comment]
Once again sorry for my delayed answer...

But since the second or so reboot after I reinstalled GSConnect fully the error messages are gone. I can't really figure out why, but now I can't even feed you more information on the issue, so sorry for that!

Maybe you are right and for some reason an older instance of the extension was lying around somewhere (maybe cached?). I didn't find any other installed GSConnect instances after the fact though.

**Comment by Znert** [comment]
Here are finally the logs :)

They are quite verbose, since I have the extension for a while...

Hope they help!

[gsconnect-error.log](https://github.com/andyholmes/gnome-shell-extension-gsconnect/files/3727573/gsconnect-error.log)

**Comment by ferdnyc** [comment]
Wow, there is a _lot_ going on there. You've basically collected a complete set of every GSconnect error we've ever seen, in the space of just 10 days' worth of logs! It'd be impressive if it wasn't so horrifying. :scream:  

Here's _one_ problem, though (but hardly the only one) — seems to be that, at one point a week or so ago, ­the system somehow got it into its head that it should be running two copies of GSConnect at the same time!

See here, in the space between these two reboots? 

<details>
<summary>Log excerpt, unfold to reveal</summary>

<pre style="white-space: pre-line">
-- Reboot --
Okt 08 08:17:20 <hostname> systemd[2308]: Created slice dbus\x2d:1.2\x2dorg.gnome.Shell.Extensions.GSConnect.slice.
Okt 08 08:17:20 <hostname> systemd[2308]: Started dbus-:1.2-org.gnome.Shell.Extensions.GSConnect@0.service.
Okt 08 08:19:05 <hostname> gnome-shell[2660]: JS WARNING: [/home/<username>/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/shell/gmenu.js 606]: reference to undefined property "hidden_when"
Okt 08 08:31:30 <hostname> systemd[2308]: dbus-:1.2-org.gnome.Shell.Extensions.GSConnect@0.service: Succeeded.
Okt 08 08:31:43 <hostname> systemd[2308]: Created slice dbus\x2d:1.1\x2dorg.gnome.Shell.Extensions.GSConnect.slice.
Okt 08 08:31:43 <hostname> systemd[2308]: Started dbus-:1.1-org.gnome.Shell.Extensions.GSConnect@0.service.
Okt 08 08:31:50 <hostname> gnome-shell[6047]: JS WARNING: [/home/<username>/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/shell/gmenu.js 606]: reference to undefined property "hidden_when"
Okt 08 10:18:59 <hostname> gjs[6531]: JS WARNING: [/home/<username>/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/protocol/lan.js 684]: reference to undefined property "GSocketOutputStream"
Okt 08 12:02:57 <hostname> gjs[6531]: JS ERROR: Gio.IOErrorEnum: An object is already exported for the interface org.mpris.MediaPlayer2 at /org/mpris/MediaPlayer2
                                 _init@/home/<username>/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/components/dbus.js:196:13
                                 _onBusAcquired@/home/<username>/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/mpris.js:529:34
                                 @/home/<username>/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:1157:2
Okt 08 12:03:03 <hostname> gjs[6531]: JS ERROR: Gio.IOErrorEnum: An object is already exported for the interface org.mpris.MediaPlayer2 at /org/mpris/MediaPlayer2
                                 _init@/home/<username>/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/components/dbus.js:196:13
                                 _onBusAcquired@/home/<username>/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/mpris.js:529:34
                                 @/home/<username>/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:1157:2
Okt 08 12:03:03 <hostname> gjs[6531]: JS ERROR: Gio.IOErrorEnum: An object is already exported for the interface org.mpris.MediaPlayer2 at /org/mpris/MediaPlayer2
                                 _init@/home/<username>/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/components/dbus.js:196:13
                                 _onBusAcquired@/home/<username>/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/mpris.js:529:34
                                 @/home/<username>/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:1157:2
Okt 08 12:03:12 <hostname> gjs[6531]: JS ERROR: Gio.IOErrorEnum: An object is already exported for the interface org.mpris.MediaPlayer2 at /org/mpris/MediaPlayer2
                                 _init@/home/<username>/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/components/dbus.js:196:13
                                 _onBusAcquired@/home/<username>/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/mpris.js:529:34
                                 @/home/<username>/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:1157:2
Okt 08 12:03:13 <hostname> gjs[6531]: JS ERROR: Gio.IOErrorEnum: An object is already exported for the interface org.mpris.MediaPlayer2 at /org/mpris/MediaPlayer2
                                 _init@/home/<username>/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/components/dbus.js:196:13
                                 _onBusAcquired@/home/<username>/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/mpris.js:529:34
                                 @/home/<username>/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:1157:2
Okt 08 12:03:26 <hostname> gjs[6531]: JS ERROR: Gio.IOErrorEnum: An object is already exported for the interface org.mpris.MediaPlayer2 at /org/mpris/MediaPlayer2
                                 _init@/home/<username>/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/components/dbus.js:196:13
                                 _onBusAcquired@/home/<username>/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/mpris.js:529:34
                                 @/home/<username>/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:1157:2
Okt 08 12:07:20 <hostname> gjs[6531]: JS ERROR: Gio.IOErrorEnum: An object is already exported for the interface org.mpris.MediaPlayer2 at /org/mpris/MediaPlayer2
                                 _init@/home/<username>/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/components/dbus.js:196:13
                                 _onBusAcquired@/home/<username>/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/mpris.js:529:34
                                 @/home/<username>/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:1157:2
Okt 08 12:07:22 <hostname> gjs[6531]: JS ERROR: Gio.IOErrorEnum: An object is already exported for the interface org.mpris.MediaPlayer2 at /org/mpris/MediaPlayer2
                                 _init@/home/<username>/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/components/dbus.js:196:13
                                 _onBusAcquired@/home/<username>/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/mpris.js:529:34
                                 @/home/<username>/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:1157:2
Okt 08 13:50:58 <hostname> gjs[6531]: JS ERROR: Gio.IOErrorEnum: An object is already exported for the interface org.mpris.MediaPlayer2 at /org/mpris/MediaPlayer2
                                 _init@/home/<username>/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/components/dbus.js:196:13
                                 _onBusAcquired@/home/<username>/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/mpris.js:529:34
                                 @/home/<username>/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:1157:2
Okt 08 13:51:02 <hostname> gjs[6531]: JS ERROR: Gio.IOErrorEnum: An object is already exported for the interface org.mpris.MediaPlayer2 at /org/mpris/MediaPlayer2
                                 _init@/home/<username>/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/components/dbus.js:196:13
                                 _onBusAcquired@/home/<username>/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/mpris.js:529:34
                                 @/home/<username>/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:1157:2
Okt 08 14:12:56 <hostname> systemd[2308]: dbus-:1.1-org.gnome.Shell.Extensions.GSConnect@0.service: Succeeded.
Okt 08 14:12:56 <hostname> systemd[2308]: Removed slice dbus\x2d:1.1\x2dorg.gnome.Shell.Extensions.GSConnect.slice.
Okt 08 14:12:56 <hostname> systemd[2308]: Removed slice dbus\x2d:1.2\x2dorg.gnome.Shell.Extensions.GSConnect.slice.
-- Reboot --
</pre>
</details>

1. First `dbus-:1.1-org.gnome.Shell.Extensions.GSConnect@0.service` is started
2. Then almost immediately after, `dbus-:1.1-org.gnome.Shell.Extensions.GSConnect@0.service` is started
3. And it appears _both_ of them stay running all the way through shutdown:

```
Okt 08 14:12:56 <hostname> systemd[2308]: Removed slice dbus\x2d:1.1\x2dorg.gnome.Shell.Extensions.GSConnect.slice.
Okt 08 14:12:56 <hostname> systemd[2308]: Removed slice dbus\x2d:1.2\x2dorg.gnome.Shell.Extensions.GSConnect.slice.
-- Reboot --
```

So, it's no wonder the space in between is filled with these dbus interface conflict errors:

```
Okt 08 13:51:02 <hostname> gjs[6531]: JS ERROR: Gio.IOErrorEnum: An object is already exported for the interface org.mpris.MediaPlayer2 at /org/mpris/MediaPlayer2
                                 _init@/home/<username>/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/components/dbus.js:196:13
                                 _onBusAcquired@/home/<username>/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/mpris.js:529:34
                                 @/home/<username>/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:1157:2
```
GSConnect is tripping all over itself, fighting over the same bus address!

Have you ever seen anything like that, @andyholmes ?

**Comment by ferdnyc** [comment]
> 1. First `dbus-:1.1-org.gnome.Shell.Extensions.GSConnect@0.service` is started
> 2. Then almost immediately after, `dbus-:1.1-org.gnome.Shell.Extensions.GSConnect@0.service` is started

Copy-pasteo, that should've been `dbus-:1.2-org.gnome.Shell.Extensions.GSConnect@0.service` followed by `dbus-:1.1-org.gnome.Shell.Extensions.GSConnect@0.service`.

**Comment by Znert** [comment]
I have to admit, your response made me chuckle. Glad I somehow manifested the pure evil of gnome extensions onto my working laptop! Should I exorcise it immediately?

Jokes aside, is there anything else I can help you with?

**Comment by ferdnyc** [comment]
@Znert Bury it! Bury it in the woods with a shovel, _and then **bury the shovel!**_

Nah, I'm hoping @andyholmes will have some insights, because I'm just the comic relief.

**Comment by andyholmes** [comment]
Seems like it mostly cleared up after you upgraded (and that second daemon died). It might be there were leftover files from a previous version or something.

I guess just open a new issue if something else comes up :)
