### ISSUE TITLE
SMS gui - contact list sidebar minimum width

### ISSUE THREAD

**Issue by amivaleo** [andyholmes/gnome-shell-extension-gsconnect#648]
Hi!

I'm using gsconnect ver 26 right now, in gnome.

I noticed that the smallest size of the contact list sidebar in the sms dialog is... maybe too short?

![a](https://user-images.githubusercontent.com/24316547/65884115-8c4e8100-e398-11e9-9a1d-5077855c41cc.png)

As you can see from the picture, we can only see the profile pictures. The extra space on the right is filled with lots of dots (ellipsis) and only a couple of letters.

That extra space is useless.

I suggest to use a bigger minimum width, that allows to see more than just a couple of dots. Something like 200 px at least? Dunno, up to you.

The alternative is to use an even narrower minimum width:

![b](https://user-images.githubusercontent.com/24316547/65884400-17c81200-e399-11e9-8aaa-19e6c19de145.png)

I actually hope that, if you will ever make any change related to this issue, you actually go for the latter. Just a matter of preferences. :)

What do you thing about this "issue"?

**Comment by andyholmes** [comment]
Seems like a good idea :)

I just had a look, and it seems like we don't set a minimum width or position for the conversation list, so the minimum is probably set by the list row's minimum size (avatar + avatar margin + label margin). So we can't really squish to just the size of the avatar unfortunately.

It looks like the default window size is 300x300, so maybe a minimum width of 150px?

**Comment by amivaleo** [comment]
I've checked a bit with an image editor. It could be ok like that: 150 px [sidebar] + 300 px [conversation].
With a minimum width of 150px it becomes possible to discern the contacts. For what it worths, I think it's ok. 💪
