### ISSUE TITLE
Can I use this to control my Android TV?

### ISSUE THREAD

**Issue by stuaxo** [andyholmes/gnome-shell-extension-gsconnect#649]
Hi,
   My Android TV is usually on the same network as my laptop, can I use this to control apps, e.g. Spotify on it ?

Obviously other things, like the messaging controls make less sense.

Cheers
S

**Comment by andyholmes** [comment]
As long as you can install the KDE Connect Android app on your TV, you should be able to pair it with GSConnect. Controlling specific apps isn't really supported, but media player apps might be covered by the MPRIS plugin.

**Comment by stuaxo** [comment]
Cheers.
