### ISSUE TITLE
v26-27 broken on Ubuntu 18.04

### ISSUE THREAD

**Issue by jorgecodecom** [andyholmes/gnome-shell-extension-gsconnect#653]
**Describe the bug and Steps To Reproduce:**

When I go to https://extensions.gnome.org/local/ GSConnect always show me a red ERROR button over GSConnect row.
I can't see the phone menu on Ubuntu Menu although I can open the client by click over configure button(screwdriver and wrench blue icon) in the Installed Extensions page and the application communicate very well with the phone.

What's is wrong here?

Is there any way to open GSConnect by shell(by command prompt) ?
I don't want to load firefox and go to the installed extensions page everytime that I want to reach the GUI because this issue.

**Expected behavior**
I Expected to see my phone name in Ubuntu Menu to click over and load the GSConnect GUI

**Screenshots**

![Error](https://user-images.githubusercontent.com/50879027/66136302-873d3c00-e5fb-11e9-935e-47a74a4300f5.png)

**Support Log**

GSConnect Version: 26
GSConnect Install: user
GJS: 15205
XDG_SESSION_TYPE: x11
GDMSESSION: ubuntu
--------------------------------------------------------------------------------
-- Logs begin at Thu 2019-10-03 15:51:17 CEST, end at Thu 2019-10-03 16:35:05 CEST. --
oct 03 16:35:01 kernel: acpi INT3400:00: Unsupported event [0x86]
oct 03 16:35:01 gnome-shell-ext[7899]: JS ERROR: Could not load extension cast-to-tv@rafostar.github.com: Error: Missing metadata.json
                                       createExtensionObject@resource:///org/gnome/shell/misc/extensionUtils.js:110:15
                                       _loadExtension@resource:///org/gnome/shell/misc/extensionUtils.js:186:25
                                       wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
                                       scanExtensions/<@resource:///org/gnome/shell/misc/extensionUtils.js:197:13
                                       collectFromDatadirs@resource:///org/gnome/shell/misc/fileUtils.js:27:17
                                       scanExtensions@resource:///org/gnome/shell/misc/extensionUtils.js:196:9
                                       wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
                                       _scanExtensions@resource:///org/gnome/shell/extensionPrefs/main.js:197:9
                                       wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
                                       _onStartup@resource:///org/gnome/shell/extensionPrefs/main.js:227:9
                                       wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
                                       main@resource:///org/gnome/shell/extensionPrefs/main.js:397:5
                                       @<main>:1:43
oct 03 16:35:01 dbus-daemon[1936]: [session uid=1000 pid=1936] Reloaded configuration
oct 03 16:35:01 dbus-daemon[1936]: [session uid=1000 pid=1936] Reloaded configuration
oct 03 16:35:01 gnome-software[2677]: failed to rescan: Failed to parse /home/jj/.local/share/applications/org.gnome.Shell.Extensions.GSConnect.desktop file: cannot process file of type application/x-desktop
oct 03 16:35:01 gjs[7919]: Failed to set property AtkObject.accessible-role to title-bar: Could not parse integer 'title-bar'
oct 03 16:35:01 gjs[7919]: Failed to set property AtkObject.accessible-role to link: Could not parse integer 'link'
oct 03 16:35:01 gjs[7919]: Failed to set property AtkObject.accessible-role to link: Could not parse integer 'link'
oct 03 16:35:01 gjs[7919]: Failed to set property AtkObject.accessible-role to list: Could not parse integer 'list'
oct 03 16:35:01 gjs[7919]: Failed to set property AtkObject.accessible-role to link: Could not parse integer 'link'
oct 03 16:35:01 gjs[7919]: Failed to set property AtkObject.accessible-role to link: Could not parse integer 'link'
oct 03 16:35:01 gjs[7919]: Failed to set property AtkObject.accessible-role to link: Could not parse integer 'link'
oct 03 16:35:01 gjs[7919]: Failed to set property AtkObject.accessible-role to list: Could not parse integer 'list'
oct 03 16:35:01 gjs[7919]: Failed to set property AtkObject.accessible-role to layered-pane: Could not parse integer 'layered-pane'
oct 03 16:35:01 CRON[7943]: pam_unix(cron:session): session opened for user root by (uid=0)
oct 03 16:35:01 CRON[7944]: (root) CMD (command -v debian-sa1 > /dev/null && debian-sa1 1 1)
oct 03 16:35:01 CRON[7943]: pam_unix(cron:session): session closed for user root
oct 03 16:35:01 dbus-daemon[1033]: [system] Activating via systemd: service name='org.freedesktop.hostname1' unit='dbus-org.freedesktop.hostname1.service' requested by ':1.211' (uid=1000 pid=7919 comm="gjs /home/jorge/.local/share/gnome-shell/extension" label="unconfined")
oct 03 16:35:01 systemd[1]: Starting Hostname Service...
oct 03 16:35:02 kernel: acpi INT3400:00: Unsupported event [0x86]
oct 03 16:35:02 dbus-daemon[1033]: [system] Successfully activated service 'org.freedesktop.hostname1'
oct 03 16:35:02 systemd[1]: Started Hostname Service.

**System Details (please complete the following information):**

 - **GSConnect version:**
26
   - **Installed from:** 
GNOME Extensions Website
 - **GNOME/Shell version:**
3.28.2
 - **Distro/Release:** 
18.04

**GSConnect environment (if applicable):**
???
 - **Paired Device(s):**
Redmi Note 4 with MIUI Global 10.2.3.0 Stable

**Additional Notes:**

Thank you in advance

**Comment by andyholmes** [comment]
Sorry, there don't seem to be any errors related to GSConnect in the log you've posted and I can't reproduce this myself.

I would suggest you first remove the extension `cast-to-tv@rafostar.github.com` which seems to be causing problems, and try restarting GNOME Shell.

**Comment by jorgecodecom** [comment]
Hi andyholmes.
Thank you for check my previous log.
I removed cast-to-tv@rafostar.github.com as you suggest, thank you for that.
Next, you going to see a new GSConnect Support Log, in order to add more info about the issue. 

GSConnect Version: 27
GSConnect Install: user
GJS: 15205
XDG_SESSION_TYPE: x11
GDMSESSION: ubuntu
--------------------------------------------------------------------------------
-- Logs begin at Wed 2019-10-09 21:34:46 CEST, end at Tue 2019-10-22 16:36:29 CEST. --
oct 22 16:36:00 gjs[5039]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
oct 22 16:36:00 gjs[5039]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
oct 22 16:36:00 gjs[5039]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
oct 22 16:36:00 gjs[5039]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
oct 22 16:36:00 gjs[5039]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
oct 22 16:36:00 gjs[5039]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
oct 22 16:36:07 gnome-shell[2118]: Some code accessed the property 'WindowPreviewMenuItem' on the module 'windowPreview'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
oct 22 16:36:29 gjs[3657]: GtkDialog mapped without a transient parent. This is discouraged.

**Comment by andyholmes** [comment]
Sorry, there is still no information about GSConnect failing in your logs. Since the problem seems to be in the Shell extension you may have to go search in GNOME Logs (`journalctl`) for something like `gsconnect` or `gsconnect@andyholmes.github.io` to try and find an error.

There seem to be quite a few problems happening with GNOME 3.28, and sadly it may just be time to drop support for older versions. I don't have the hard drive space to keep VMs around for all these versions or the time to properly support them, and we've been holding back on newer language features and libraries going back over two years now.

So basically, unless someone volunteers to maintain support for older versions of GNOME, I think we'll drop support for them in v28.

**Comment by jorgecodecom** [comment]
> Sorry, there is still no information about GSConnect failing in your logs. Since the problem seems to be in the Shell extension you may have to go search in GNOME Logs (`journalctl`) for something like `gsconnect` or `gsconnect@andyholmes.github.io` to try and find an error.

This are the messages I found in journalctl:

oct 21 20:07:26 omen gnome-shell[2256]: Extension "gsconnect@andyholmes.github.io" had error: TypeError: imports.misc.extensionUtils.getCurrentExtension(...) is null
oct 21 20:27:21 omen gnome-shell[2109]: Extension "gsconnect@andyholmes.github.io" had error: TypeError: imports.misc.extensionUtils.getCurrentExtension(...) is null
oct 22 12:44:35 omen gnome-shell[2265]: Extension "gsconnect@andyholmes.github.io" had error: TypeError: imports.misc.extensionUtils.getCurrentExtension(...) is null
oct 22 16:08:36 omen org.gnome.Shell.desktop[2265]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x5800084 (gsconnect.)
oct 22 16:12:43 omen org.gnome.Shell.desktop[2265]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x5800084 (gsconnect.)
oct 22 16:12:57 omen org.gnome.Shell.desktop[2265]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x5800084 (gsconnect.)
oct 22 16:13:16 omen org.gnome.Shell.desktop[2265]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x5800084 (gsconnect.)
oct 22 16:13:30 omen org.gnome.Shell.desktop[2265]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x5800084 (gsconnect.)
oct 22 16:16:13 omen gnome-shell[2131]: Extension "gsconnect@andyholmes.github.io" had error: TypeError: imports.misc.extensionUtils.getCurrentExtension(...) is null
oct 22 16:24:45 omen gnome-shell[2118]: Extension "gsconnect@andyholmes.github.io" had error: TypeError: imports.misc.extensionUtils.getCurrentExtension(...) is null
oct 22 16:26:07 omen org.gnome.Shell.desktop[2118]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x4e00084 (*gsconnect)
oct 22 16:28:46 omen org.gnome.Shell.desktop[2118]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x4e00084 (gsconnect.)
oct 22 16:36:30 omen org.gnome.Shell.desktop[2118]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x5200084 (gsconnect.)
                                _init@/home/jorge/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/components/dbus.js:196:13
                                _onBusAcquired@/home/jorge/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/mpris.js:529:34
                                @/home/jorge/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:1149:2
oct 22 18:20:09 omen gnome-shell[2136]: Extension "gsconnect@andyholmes.github.io" had error: TypeError: imports.misc.extensionUtils.getCurrentExtension(...) is null
oct 23 09:34:17 omen gnome-shell[2052]: Extension "gsconnect@andyholmes.github.io" had error: TypeError: imports.misc.extensionUtils.getCurrentExtension(...) is null
oct 23 20:09:11 omen gnome-shell[2167]: Extension "gsconnect@andyholmes.github.io" had error: TypeError: imports.misc.extensionUtils.getCurrentExtension(...) is null
oct 24 02:15:24 omen gnome-shell[2229]: Extension "gsconnect@andyholmes.github.io" had error: TypeError: imports.misc.extensionUtils.getCurrentExtension(...) is null
oct 25 12:50:58 omen gnome-shell[2169]: Extension "gsconnect@andyholmes.github.io" had error: TypeError: imports.misc.extensionUtils.getCurrentExtension(...) is null
oct 25 14:25:45 omen gnome-shell[2851]: Extension "gsconnect@andyholmes.github.io" had error: TypeError: imports.misc.extensionUtils.getCurrentExtension(...) is null

**Comment by andyholmes** [comment]
Hi, it's unclear why these errors are happening, especially only for 3.28 users.

This error essentially shouldn't be possible since this function hasn't changed in many years (~8-ish). Our usage of it hasn't changed since mid-2018, but probably it's the root of the problem. However, this error is happening in the extension itself, not the preferences dialog.
```
oct 25 14:25:45 omen gnome-shell[2851]: Extension "gsconnect@andyholmes.github.io" had error: TypeError: imports.misc.extensionUtils.getCurrentExtension(...) is null
```

This error means the service is starting, since this error is happening in the MPRIS plugin. This code was added in v25/v26, so I'm surprised it didn't happen earlier. Unfortunately the error message itself is cut-off, so it only tells me where the error is happening but not what the error is:

```
_init@/home/jorge/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/components/dbus.js:196:13
_onBusAcquired@/home/jorge/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/mpris.js:529:34
@/home/jorge/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:1149:2
```

Unfortunately I'm just not sure what's causing this only for 3.28, since we don't use any code that should be incompatible with it :/

**Comment by jorgecodecom** [comment]
Hi andyholmes.
With the last update the issue was fixed.
Thank you and thanks to the community.

Versions:
GSConnect Version: 28
GSConnect Install: user
GJS: 15205
XDG_SESSION_TYPE: x11
GDMSESSION: ubuntu
GNOME/Shell version: 3.28.2
Distro/Release:  18.04
Paired Device(s): Redmi Note 4 with MIUI Global 10.2.3.0 Stable
