### ISSUE TITLE
User menu battery icon bug

### ISSUE THREAD

**Issue by 3ship** [andyholmes/gnome-shell-extension-gsconnect#659]
Not sure, if this is an issue with GSConnect or maybe the icon theme I'm using, but every once in a while the user menu entry uses a battery icon about four or five times the size of the regular one (see screenshot).

When I click on the menu entry, everything goes back to normal.

![gsconnect-icon-bug](https://user-images.githubusercontent.com/47889681/66272093-a6d79d00-e865-11e9-81f9-204e9bd1aab5.jpg)

**System Details:**

 - **GSConnect version:** 26
   - **Installed from:** Package Manager
 - **GNOME/Shell version:** 3.34
 - **Distro/Release:** Manjaro (testing branch)

**Additional Notes:**

Icon theme: Newaita (Inherits=breeze,gnome,hicolor)

**Comment by andyholmes** [comment]
Thanks for reporting. This is indeed a bug due to some CSS engine changes in GNOME Shell 3.34, I just haven't had time to track it down just yet.
