### ISSUE TITLE
cannot connect my mobiles

### ISSUE THREAD

**Issue by stephane-leg** [andyholmes/gnome-shell-extension-gsconnect#661]
Hello

Gsconnect worked till new update. On laptop, i can't see anymore my mobiles (sony xperia xa1, and huawei p8lite). On mobile, i can't see my laptop but i see my other mobile.
I've got no firewall.
I've uninstalled the extension, removed everything 
  gnome-shell-extension-tool -d gsconnect@andyholmes.github.io
  rm -rf ~/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io
  rm -rf ~/.cache/gsconnect
  rm -rf ~/.config/gsconnect
  dconf reset -f /org/gnome/shell/extensions/gsconnect/
reinstalled
Reboot

log:

GSConnect Version: 26
GSConnect Install: user
GJS: 15602
XDG_SESSION_TYPE: x11
GDMSESSION: gnome
--------------------------------------------------------------------------------
-- Logs begin at Sun 2019-08-04 21:27:26 CEST, end at Tue 2019-10-08 23:11:11 CEST. --
-- No entries --

I work on mageia 7 64bit, gnome Xorg session. I tried wayland, it doesn't work anyway.

Thanks

**Comment by andyholmes** [comment]
Hi, can you please follow the steps described in [Generate Support Log](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Help#generate-support-log) to get complete debug information for this problem?

**Comment by stephane-leg** [comment]
hello
log:

GSConnect Version: 26
GSConnect Install: user
GJS: 15602
XDG_SESSION_TYPE: x11
GDMSESSION: gnome-xorg
--------------------------------------------------------------------------------
-- Logs begin at Sun 2019-08-04 21:27:26 CEST, end at Thu 2019-10-10 13:20:59 CEST. --
-- No entries --

**Comment by stephane-leg** [comment]
![Capture d’écran de 2019-10-10 13-23-15](https://user-images.githubusercontent.com/56323032/66564808-367c9480-eb61-11e9-8f97-419883ba7057.png)

**Comment by ferdnyc** [comment]
@stephane-leg 

It appears you may have skipped part of [step 2](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Help#generate-support-log) (emphasis mine):
> 2. Take any steps necessary to reproduce the problem
>
>    This is the most important step. You must use the functionality which is not working. **For example, if you are having trouble connecting devices you must activate the _Refresh_ action for both devices or errors will not be logged.**

**Comment by stephane-leg** [comment]
GSConnect Version: 26
GSConnect Install: user
GJS: 15602
XDG_SESSION_TYPE: x11
GDMSESSION: gnome-xorg
--------------------------------------------------------------------------------
-- Logs begin at Sun 2019-08-04 21:27:26 CEST, end at Tue 2019-10-15 21:53:10 CEST. --
oct. 15 21:53:10 gnome-shell[2486]: g_environ_setenv: assertion 'value != NULL' failed

i've got nothing else

**Comment by andyholmes** [comment]
Like this:
![Peek 2019-10-15 15-11](https://user-images.githubusercontent.com/1265208/66873791-38c66080-ef5e-11e9-8eb6-d5767ad1569a.gif)

**Comment by stephane-leg** [comment]
Well , i've installed version 21. 
it works.
It doesn't work with latest version.

**Comment by stephane-leg** [comment]
And when i try to generate a log with version 26, i have nothing else that i ve copied.

**Comment by andyholmes** [comment]
Sorry, without error messages there's not much I can do. If you aren't getting lines like the ones above saying *"Broadcasting to LAN", then something has gone pretty wrong but it's hard to say what.

**Comment by stephane-leg** [comment]
thanks. I understand. I will use version 21 without updating
