### ISSUE TITLE
Device Id contains newline

### ISSUE THREAD

**Issue by R1tschY** [andyholmes/gnome-shell-extension-gsconnect#665]
**Describe the bug**

The device id send by GSConnect contains a trailing newline. So it is not possible the pair with [SailfishConnect](https://github.com/R1tschY/harbour-sailfishconnect/) (and possible KDEConnect, not tested). 

I will work around the problem in SailfishConnect, but maybe this is not intended behavior. See also https://github.com/R1tschY/harbour-sailfishconnect/issues/28.

**Steps To Reproduce:**

1. Click the refresh button in ui
2. GSConnect sends a UDP datagram something like `{"id":1570731176136,"type":"kdeconnect.identity","body":{"deviceId":"9179a699-99bb-4197-aaf9-0314d0d0046e\n","deviceName": ... `
3. Paring will fail with SailfishConnect (Pairing works with Android-App)

**Expected behavior**

GSConnect sends deviceId without newline at the end. The SSL certificate common name does also not contain the newline.

**Support Log**

```
GSConnect Version: 26
GSConnect Install: user
GJS: 15205
XDG_SESSION_TYPE: x11
GDMSESSION: ubuntu
```

**System Details (please complete the following information):**

 - **GSConnect version:** 26
   - **Installed from:** GNOME Extensions Website
 - **GNOME/Shell version:** 3.28.4
 - **Distro/Release:** Ubuntu 18.04.3 LTS

**Comment by andyholmes** [comment]
Thanks for reporting, this was a known mistake in the v25-v26 releases, but should be fixed in v27-rc1. Now would be a good time to download the rc and test it out. See [Install from Zip](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Installation#install-from-zip) for instructions.

**Comment by R1tschY** [comment]
Is fixed in v27-rc1 :+1:
