### ISSUE TITLE
Pause browser media playback on calls and browser media controls in general

### ISSUE THREAD

**Issue by christfried** [andyholmes/gnome-shell-extension-gsconnect#667]
### Firefox Add-on GSConnect version 6
I would like to be able to pause media playing in my browser from the phone and want it to be automatically muted when I start or get a call, just like with music players. (This is a useful feature of the "Plasma Integration" Add-on for Firefox).

**Comment by andyholmes** [comment]
Sorry, there are no plans to implement this in GSConnect. For Chromium-based browsers there should already be MPRIS support and there are other extensions including plasma-integration for Firefox.

Implementing a whole MPRIS interface adapter and DBus exporter for various web sites and browsers is just too far out of scope for a KDE Connect client.

**Comment by ferdnyc** [comment]
@christfried 
The thing is... this already works. GSConnect already has the necessary features to pause/mute MPRIS players, and it's possible to link browser media playback to MPRIS using external tools. As you say:

> (This is a useful feature of the "Plasma Integration" Add-on for Firefox).

...It definitely is, and for Chrome as well. And the thing is: `kde-plasma-integration` _already works_ with GSConnect. See https://github.com/andyholmes/gnome-shell-extension-gsconnect/issues/628#issuecomment-533783113 and the tail of #121 for info.

**Comment by christfried** [comment]
Oh, I'm sorry. I have not found the earlier comments about this topic. I never expected this to work just with `plasma-browser-integration` ... Thank you for clarification! Wouldn't it be practical to point this out on [extensions.gnome.org](https://extensions.gnome.org/extension/1319/gsconnect/) or somewhere here in the wiki?

**Comment by ferdnyc** [comment]
> I never expected this to work just with `plasma-browser-integration`

Yeah, I kind of blame the KDE team for _calling_ it that — really, it's "MPRIS browser integration". Turns out, **nothing** about it is plasma-specific at all. They're so on-brand sometimes, they can end up selling their own tools short as a result. :laughing: 

> Wouldn't it be practical to point this out on [extensions.gnome.org](https://extensions.gnome.org/extension/1319/gsconnect/) or somewhere here in the wiki?

Seems reasonable to me, sure! The wiki is... well, a wiki (IOW, community editable), feel free to add any info you feel is missing.

(If you can find a good spot to include it. I had a quick look just now, and I wasn't immediately sure where I'd even stick that info. I'll have to try again later.)

**Comment by christfried** [comment]
@andyholmes 
What do you think about adding a link inside the settings to the Plasma Integration Add-ons for [Firefox](https://addons.mozilla.org/en-US/firefox/addon/plasma-integration/) and [Chrome](https://chrome.google.com/webstore/detail/plasma-integration/cimiefiiaegbelhefglklhhakcgmhkai) in addition to the GSConnect Add-ons?
![grafik](https://user-images.githubusercontent.com/54483908/66767688-440f8280-eeb1-11e9-99b3-1e92506b8431.png)

**Comment by ferdnyc** [comment]
@christfried 

I would personally recommend against either of those approaches, because unlike GSConnect's WebExtension, the `plasma-browser-integration` WebExtension is useless without the corresponding native backend binary, `plasma-browser-integration-host`.

**Comment by christfried** [comment]
@ferdnyc 
I get that the 2nd question was a little bit of a long shot but what about adding links inside the settings?

**Comment by andyholmes** [comment]
`plasma-browser-integration` doesn't actually have anything to do with GSConnect, it just happens to provide a DBus interface (MPRISv2) that one of GSConnect's plugins consumes. If we added a link to it, there would be no reason not to link to MPRIS plugins for other media players or others that relate to other GSConnect device plugins.

**Comment by ferdnyc** [comment]
Plus, it isn't even necessary for Chrome anymore — it includes a native MPRIS exporter/connector now, so the functionality is there out-of-the-box. I wouldn't be surprised if Firefox follows suit.

**Comment by towo** [comment]
Just as an FYI since GitHub issues are inofficial documentation c/o Google: MPRIS integration landed in Firefox with version 75.
