### ISSUE TITLE
Answer calls from gnome BT

### ISSUE THREAD

**Issue by MoonDragon-MD** [andyholmes/gnome-shell-extension-gsconnect#668]
Hi, I wanted to know if you can integrate the answer for calls via BT, since you can connect it to hear android calls. Here is the link to my guide to Ubuntu: [http://moondragon.ilbello.com/ubuntu-telefonate-bluetooth-android-come-vivavoce/?lang=en](url)
At the moment I use Scrcpy via usb but it would be more comfortable all from BT
It would become like the bt-band speakerphone of cars.
Thank you for your project

**Comment by andyholmes** [comment]
Sorry, there is no support for this in the KDE Connect protocol. You should consider opening an upstream request at [bugs.kde.org](https://bugs.kde.org/buglist.cgi?component=android-application&list_id=1669730&product=kdeconnect).

**Comment by nazar2sfive** [comment]
@MoonDragon-MD https://bugs.kde.org/show_bug.cgi?id=436867
