### ISSUE TITLE
Nautilus integration not working

### ISSUE THREAD

**Issue by FMuro** [andyholmes/gnome-shell-extension-gsconnect#67]
Fedora 27, the indicated dependencies are installed, but nothing happens when "Share" is on, I don't see the "send to mobile device" option in the context menu.

**Comment by andyholmes** [comment]
Could you open a terminal and run:

    nautilus -q && nautilus

And tell me if there is any useful output when you open the context menu?

**Comment by FMuro** [comment]
The only line I think could be related to the extension is 

`Server response: STRING:SHARE_MENU_TITLE:Share...`

but it there from the very beginning, opening the context menu doesn't produce new output.

**Comment by andyholmes** [comment]
Hmm, this string doesn't seem to have anything to do with the GSConnect Nautilus extension.

You're sure that you have all dependencies installed, the device has the Share plugin enabled and Nautilus integration is enabled in Preferences? If so and there are no other messages, I'm not sure what the problem could be. What distribution are you using and do you have any other Nautilus extensions installed that *are* working?

**Comment by FMuro** [comment]
Oh, man, I feel stupid, it looks like if I forgot to enable Nautilus integration in preferences. Sorry.

**Comment by andyholmes** [comment]
No problem, I'm always happy to hear it's not my fault ;)

**Comment by basilrabi** [comment]
In fedora 28, `python2-gobject` must also be installed for the nautilus integration to work

**Comment by andyholmes** [comment]
Thanks, I don't use Fedora so didn't know that. I've added it to the Wiki->Dependencies.

**Comment by uwe-007** [comment]
If you are new to gsconnect, you should read Wiki->Dependencies. Then you will know, that you need "python-nautilus" to get nautilus integration working :-)

**Comment by ujwalnk** [comment]
Facing a similar issue here, the context menu appeared for a while and suddenly disappeared recently. I can share files using the icon at the top bar, but nothing in the Nautilus context menu.

I seem to have all the required dependencies, i.e. `nautilus-python`,  `python3-gobject` (Not able to install python2-gobject), `nautilus-extensions.x86_64` & `gnome-shell-extension-gsconnect.x86_64`

I am running Fedora 40 (Workstation Edition), Gnome 46 Wayland. 

Thanks in advance for the help.

PS. Another qa-form mentioned about the default file-browser app not being called Nautilus, but Files in Gnome 46. If that means anything...
