### ISSUE TITLE
connection is not automatic

### ISSUE THREAD

**Issue by mikelpr** [andyholmes/gnome-shell-extension-gsconnect#672]
**Describe the bug**
when I log in, I have to click the status icons, Mobile Devices, and then Turn On.

**Steps To Reproduce:**
1. Turn on computer
2. Log into my account
3. all logged in

**Expected behavior**
my notifications appearing whenever I get them
instead, I tend not to be aware it isn't connected until I get 2FA codes on my device and not on my computer

 - **GSConnect version:** 27
   - **Installed from:** GNOME Extensions Website
 - **GNOME/Shell version:** 3.34
 - **Distro/Release:** Fedora 31

**GSConnect environment (if applicable):**

 - **Paired Device(s):** OnePlus 6T
 - **KDE Connect app version:** 1.13.2

**Additional Notes:**
on KDE, KDE Connect connected automatically (it is not an issue with my device)

**Comment by ivandotv** [comment]
I have similar issue, started happening after the last update from the gnome site (v 27) 
The extension is not connecting to the phone automatically. I need to go to extension -> mobile settings -> refresh devices (click a couple of times) and then the phone appears.

 GSConnect version: 27
 Installed from: GNOME Extensions Website
 GNOME/Shell version: 3.34
 Distro/Release: Ubuntu 19.04


Paired Device: Nokia 7.1 - Android One
KDE Connect app version: 1.13.2

**Comment by Eonfge** [comment]
I have the same issue. With the same steps of reproduction using GSConnect 27, Fedora 30

I did notice something else. When I start playing music, there is no audio controls on my phone. Then, when I got 'mobile settings' it tells me it's waiting for the service. If I then refresh the overview (button top left) it does see my phone.

**Comment by dac73** [comment]
Also not connecting automatically, and after connecting icon for desktop sharing is activated.
![image](https://user-images.githubusercontent.com/20690019/67145317-dd0f1680-f280-11e9-9c79-f3227a4580d9.png)

![image](https://user-images.githubusercontent.com/20690019/67145313-d54f7200-f280-11e9-8eb8-5a89e0adf183.png)

**Comment by gautierlabarre** [comment]
Same issue here since last update.

**Comment by andyholmes** [comment]
Here's a tester (see the wiki for install instructions):

[gsconnect@andyholmes.github.io.zip](https://github.com/andyholmes/gnome-shell-extension-gsconnect/files/3759309/gsconnect%40andyholmes.github.io.zip)

**Comment by dac73** [comment]
@andyholmes I tried the zip, `screen sharing` problem is fixed, but the connection was still not automatic.

**Comment by andyholmes** [comment]
If the service has been stuck off, you will have to select *Turn On* in the *Mobile Devices* menu to enable it. After this the service should respect that settings, like Bluetooth and WiFi.

**Comment by ferdnyc** [comment]
I've updated this with the more-descriptive title from #682 and pinned it to the top of the issues list, for now. Hopefully that'll head off further duplicates until v28 is out the door.

**Comment by andyholmes** [comment]
Good idea. I've gotten tied up all over the place this week, but I think I'll just push it out later today when I get home (after I get through the other extensions in the review queue, because otherwise I feel like selfish jerk :wink:).

We don't really get good [stats](https://www.somsubhra.com/github-release-stats/?username=andyholmes&repository=gnome-shell-extension-gsconnect) for this, but no one's opened any new issues since the RC. I figured it was unlikely someone would want or be able to maintain older GNOME versions, but it was worth giving the opportunity.
