### ISSUE TITLE
"Screen is being shared" Notification

### ISSUE THREAD

**Issue by kcattakcaz** [andyholmes/gnome-shell-extension-gsconnect#673]
On Fedora 30 with all available updates installed, I installed an update to GSConnect to version 27.  I noticed an unfamiliar icon appear in the notification area, clicking it reveals it's a warning that the "Screen is Being Shared".  This was rather alarming, since I was not expecting my screen to be shared and didn't know who it was being shared with or why :scream:  .  After poking around the system and checking all the extensions, I realized that uninstalling GSConnect makes it go away, and reinstalling makes it appear.

![screen_is_being_shared](https://user-images.githubusercontent.com/11695767/66981351-5384fc00-f068-11e9-8e8b-620ce11a6e3c.png)

I imagine that this extension has several features that legitimately could be using a permission or feature that could trigger such a warning.  I had a hard time finding any documentation or anyone else mentioning it though...  could this be related to the new remote input feature that's in the release notes for v27?  That mentions Mutter RemoteDesktop, which seems like it could cause this?

You might want to put a warning or something in the documentation and extension description if this message is unavoidable.  I'm probably not the only one wondering why my screen is suddenly being "shared".  The notification itself doesn't tell you which application is causing it, which is probably the real bug here.

**Comment by andyholmes** [comment]
Duplicated of #671. Discussion will continue there.
