### ISSUE TITLE
Clipboard not working for Wayland when GSConnect enabled

### ISSUE THREAD

**Issue by mnoukhov** [andyholmes/gnome-shell-extension-gsconnect#677]
**Describe the bug**

When GSConnect is enabled but not connected, I can't copy from certain sources. So far, for certain, I can't copy from Firefox fields (e.g. address bar), Evince, Terminal

Strangely, copying seems to work from the Slack app so I suspect the issue is Wayland vs XWayland

**Steps To Reproduce:**

1. Enable GSConnect through panel but don't connect to a Phone
2. Try to copy the url in the Firefox address bar 
3. Try to paste that into the address bar or somewhere else

**Expected behavior**

We expect something to be pasted but instead nothing changes as though the clipboard is empty

**Support Log**
I find these two errors to maybe be correlated but I don't know if they're related

```
Oct 21 14:31:32 gnome-shell[3847]: #1   7ffc3592ca00 b   self-hosted:975 (7f7e1f02f160 @ 392)
Oct 21 14:31:32 gnome-shell[3847]: Object St.Button (0x559a46187e80), has been already deallocated — impossible to get any property from it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
Oct 21 14:31:32 gnome-shell[3847]: Object St.Button (0x559a45909440), has been already deallocated — impossible to get any property from it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
Oct 21 14:31:32 gnome-shell[3847]: Object St.Button (0x559a46187e80), has been already deallocated — impossible to get any property from it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
Oct 21 14:31:32 gnome-shell[3847]: == Stack trace for context 0x559a40c9f3d0 ==
Oct 21 14:31:32 gnome-shell[3847]: #0   559a46ec5eb0 i   resource:///org/gnome/shell/ui/workspace.js:695 (7f7e1f171160 @ 15)
Oct 21 14:31:32 gnome-shell[3847]: #1   7ffc3592ca00 b   self-hosted:975 (7f7e1f02f160 @ 392)
```

**System Details (please complete the following information):**

 - **GSConnect version:** 27
   - **Installed from:** GNOME Extensions through GNOME Software
 - **GNOME/Shell version:** 3.34.1
 - **Distro/Release:** Fedora 31

**Comment by andyholmes** [comment]
Thanks for reporting, I can reproduce in Wayland on 3.34.

**Comment by diegovasconcelos** [comment]
After 14fde91 content is only copied to clipboard when I run twice (ctrl + c).

When I copy a text (crtl + c) the clipboard contents are empty. I have to repeat the operation again (crtl + c) to be able to paste the text (crtl + v).

Fedora 31
Gsconnect v28

**Comment by diegovasconcelos** [comment]
After 14fde91 content is only copied to clipboard when I run twice (ctrl + c)

When I copy a text (crtl + c) the clipboard contents are empty (crtl + v). I have to repeat the operation again (crtl + c) to be able to paste the text.

Fedora 31
Gsconnect v28

**Comment by diegovasconcelos** [comment]
After 14fde91 content is only copied to clipboard when I run twice (ctrl + c).

When I copy a text (crtl + c) the clipboard contents are empty. I have to repeat the operation again (crtl + c) to be able to paste the text (crtl + v).

Fedora 31
Gsconnect v28

**Comment by andyholmes** [comment]
Okay, I'll have another look when I get the chance.

**Comment by teohhanhui** [comment]
Copying text from `gnome-terminal` using the "Copy" context menu item doesn't work properly (the copied text gets corrupted), but using "Copy as HTML" works. It's been baffling me for a while.

I suspect it's related to this extension, but I'll report back with the results when this extension is disabled...

**Comment by andyholmes** [comment]
Can definitely confirm, and it's super annoying :D The double-copy does seem to work as a workaround. I'll have to figure out what's going on here.
