### ISSUE TITLE
Will gsconnect support remote desktop?

### ISSUE THREAD

**Issue by fgheng** [andyholmes/gnome-shell-extension-gsconnect#678]
**Is your feature request related to a problem? Please describe.**
Hello, I often switch soft between my computer and my phone. would you like to support remote screen that i can use my phone by my computer?

**Describe the solution you'd like**
I can operate my phone on my computer by remote screen.

**Describe alternatives you've considered**
i am using scrcpy instead now, but it is limited to screen operations, and the operation of transferring files, copying, etc. is not user-friendly.

**System Details (please complete the following information):**
 - GSConnect version: 27
   - Installed from: release download

**Additional context**
Add any other context for your suggestion here, including screenshots if applicable.
Another, it's good if clipboard sync support copy image and file

**Comment by andyholmes** [comment]
Sorry, all of these features need to first be supported by the KDE Connect protocol.

You should open bugs for each of these separately at [bugs.kde.org](https://bugs.kde.org/buglist.cgi?component=android-application&list_id=1673343&product=kdeconnect).

**Comment by mavit** [comment]
For the benefit of anyone brought here by search engines, I hacked up a quick script to make running `scrcpy` slightly more convenient if you also already use KDEConnect or GSConnect: [`scrcpy-with-kdeconnect`](https://gitlab.com/mavit/scrcpy-with-kdeconnect/-/blob/master/scrcpy-with-kdeconnect).
