### ISSUE TITLE
[Feature Request] Picture and Message search support

### ISSUE THREAD

**Issue by CCF100** [andyholmes/gnome-shell-extension-gsconnect#679]
**Is your feature request related to a problem? Please describe.**
No
**Describe the solution you'd like**
I was wondering if it would be possible to implement photo and message/group search support...
**Describe alternatives you've considered**
Something similar to this: https://messages.google.com/web
**System Details (please complete the following information):**
   - Installed from: [extensions.gnome.org]

**Additional context**

**Comment by ferdnyc** [comment]
@CCF100 

This is one of those requests that would fall under this umbrella:

> GSConnect works in concert with the [KDE Connect][1] app on paired Android devices. Communication between GSConnect and the device is controlled by **KDE Connect**, _not_ GSConnect.
> 
> Any request that would require features not supported in KDE Connect, or would require GSConnect to deviate from the KDE Connect protocols, cannot be implemented. Any such requests should be made to the KDE Connect project. The requested functionality can only be implemented in GSConnect after support is added to KDE Connect.
> 
> [1]: (https://community.kde.org/KDEConnect)

Any such functionality would _**have**_ to already exist on the KDE Connect app end, before GSConnect could make use of it. The KDE Connect bugzilla is the place to make such a request. (Or find an existing request, if one's already been made.)
