### ISSUE TITLE
Implement new album art feature

### ISSUE THREAD

**Issue by TamasBarta** [andyholmes/gnome-shell-extension-gsconnect#68]
KDEConnect introduced a new feature, where it is capable of showing the album art on the mobile. Media controls are implemented, so the notification with the controls on the mobile works fine with the new mobile app, but album art is not shown. I guess it needs to be implemented in GSConnect as well.

See https://matthijstijink.nl/static/blog_entry_1.html

**Comment by andyholmes** [comment]
Here is a test build incorporating the new feature:

[gsconnect@andyholmes.github.io.zip](https://github.com/andyholmes/gnome-shell-extension-gsconnect/files/1831679/gsconnect.andyholmes.github.io.zip)

If you could test this and confirm that it works before I push the commit, I would appreciate it. Note that as per the linked blog post:

> Currently, only remote album art is supported (used in e.g. Spotify). Local album art and album art in the media notifications will come in a future release of KDE Connect.

**Comment by TamasBarta** [comment]
Hi!

After installing this version, and restarting (following [this guide](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Installation#installing-from-zip)), nothing really happened, so I went into the settings, and I got this message:

```
TypeError: metadata is undefined

Stack trace:
  Stack<._addDaemon@/home/tamas/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/widgets/device.js:296:13
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  Stack<._init@/home/tamas/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/widgets/device.js:262:9
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  PrefsWidget<._init@/home/tamas/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/prefs.js:102:29
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  buildPrefsWidget@/home/tamas/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/prefs.js:215:23
  Application<._selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:91:22
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  Application<._onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:246:17
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  main@resource:///org/gnome/shell/extensionPrefs/main.js:402:5
  @<main>:1:43
  ```

Not sure how to proceed.

**Comment by andyholmes** [comment]
Hmm, it's odd you are the second the report that problem after an update, although nothing has changed in regards to the preferences. Have you restarted Gnome Shell?

Perhaps try this one that hardcodes the icon:

[gsconnect@andyholmes.github.io.zip](https://github.com/andyholmes/gnome-shell-extension-gsconnect/files/1834450/gsconnect.andyholmes.github.io.zip)

**Comment by TamasBarta** [comment]
Settings now works, but I cannot connect at all (my device is remembered on both sides, but not available). Can I provide you with more details?

**Comment by andyholmes** [comment]
Ah, I'm really sorry about that and expecting to get lots of questions regarding this. The short story is you probably just have to unpair and repair your device.

The build I've posted includes all fixes in master since v10, including #26, which fixed a bug parsing `openssl` output. I really don't why `openssl` has such different terminal output for some people, but it caused all devices to be identified as "" (eg. empty `deviceId`). If you only have one device you probably didn't notice, but if you had two or more they would get mixed up and cause random disconnects due to incorrect TLS certificates.

Let me know if that doesn't solve your problem.

**Comment by TamasBarta** [comment]
I still cannot connect, as neither on the phone, nor on the PC the list of available devices has any elements. I also checked the latest zip from the issue where you mentioned this one, but that doesn't even show my settings (I guess it's the same as here the first one).

**Comment by TamasBarta** [comment]
I just installed the extension from Gnome extensions site, and I get:

```
TypeError: metadata is undefined

Stack trace:
  Stack<._addDaemon@/home/tamas/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/widgets/device.js:296:13
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  Stack<._init@/home/tamas/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/widgets/device.js:262:9
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  PrefsWidget<._init@/home/tamas/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/prefs.js:102:29
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  buildPrefsWidget@/home/tamas/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/prefs.js:215:23
  _selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:91:22
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  _onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:243:17
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  main@resource:///org/gnome/shell/extensionPrefs/main.js:397:5
  @<main>:1:43
```

**Comment by andyholmes** [comment]
Hi, there was an issue with KDE Connect Android 1.8.1, but Albert Vaka has just pushed a fix (as 1.8.2) to the Play Store. If you still have 1.8.1 it's unlikely you can connect any devices (regardless of GSConnect).

The error `TypeError: metadata is undefined`, seems to be a result of the preferences window opening faster than the daemon can start up to report it's type. I'll just push the hardcoded icon fix for that.

> I believe some of the zips messed up something with my settings, and I don't know how to reset it.

The updated Zip shouldn't have messed with any of your settings, more likely it's either the `openssl` issue from #26 (which *will* require you to repair *if* you were affected), or the TLS issue with KDE Connect Android 1.8.1. However, you want to do a clean sweep of GSettings, you can do that with:

    dconf reset -f /org/gnome/shell/extensions/gsconnect/

There really aren't that many settings anyways, so it's not that big of a deal, especially if you're going to unpair your devices anyways.

Sorry about the trouble, I do appreciate you sticking with it to help test this issue. Here's a Zip I just built from master that includes the metadata fix, and the MPRIS patch:

[gsconnect@andyholmes.github.io.zip](https://github.com/andyholmes/gnome-shell-extension-gsconnect/files/1854012/gsconnect.andyholmes.github.io.zip)

**Comment by stark-dev** [comment]
Hi, just built from master, seems that this new feature is working!

Thanks,

Mauro

**Comment by TamasBarta** [comment]
I updated everything, and now everything works perfectly, including the album art! Thank you for your help, and clarifications!
