### ISSUE TITLE
GSConnect; Authentication Failure after upgrade to ubuntu 19.10

### ISSUE THREAD

**Issue by Ruud68** [andyholmes/gnome-shell-extension-gsconnect#693]
**Describe the bug**

After upgrading to Ubuntu 19.10 my phone is not connecting with GSConnect anymore.
The phone is visible (status disconnected) in GSConnect

**Steps To Reproduce:**

1. on mobile click refresh in available devices screen
2. there is a short display of my desktop but is disappears again from the list
3. on desktop I get the GSConnect: Authentication Failure

I have already tried to remove and reinstall mobile app including clearing data on the app, I already removed and reinstalled gsconnect on Ubuntu desktop.

**Expected behavior**
Connection to mobile device should be made

**Support Log**

Please generate a support log ([Instructions](wiki/Help#generate-support-log)) and paste any messages related to this issue between the two ``` lines below.

```
nov 03 10:29:10 org.gnome.Shell.Extensions.GSConnect[4324]: [/service/protocol/lan.js:open:733]: "lan://192.168.2.196:1716 (0b1a05ca-12a4-4de1-9d8e-221c4ab961de)"
nov 03 10:29:10 gjs[4324]: JS ERROR: AuthenticationError
                           _authenticate@/home/ruud/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/protocol/lan.js:594:29
                           async*_serverEncryption@/home/ruud/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/protocol/lan.js:638:16
                           open@/home/ruud/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/protocol/lan.js:738:38
                           async*_onIdentity@/home/ruud/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/protocol/lan.js:349:19
                           async*_onIncomingIdentity@/home/ruud/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/protocol/lan.js:291:17
                           @/home/ruud/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:1149:2
nov 03 10:29:10 org.gnome.Shell.Extensions.GSConnect[4324]: [/service/protocol/lan.js:close:750]: "lan://192.168.2.196:1716 (0b1a05ca-12a4-4de1-9d8e-221c4ab961de)"
nov 03 10:29:10 gjs[4324]: JS ERROR: AuthenticationError
                           _authenticate@/home/ruud/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/protocol/lan.js:594:29
                           async*_serverEncryption@/home/ruud/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/protocol/lan.js:638:16
                           open@/home/ruud/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/protocol/lan.js:738:38
                           async*_onIdentity@/home/ruud/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/protocol/lan.js:349:19
                           async*_onIncomingIdentity@/home/ruud/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/protocol/lan.js:291:17
                           @/home/ruud/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:1149:2

```

**System Details (please complete the following information):**

 - **GSConnect version:** 28
   - **Installed from:** GNOME Extensions Website
 - **GNOME/Shell version:** [e.g. 3.30, 3.28, ...]
 - **Distro/Release:** Ubuntu 19.10
 - **GSConnect Install:** user
 - **GJS:** 15801
 - **XDG_SESSION_TYPE:** x11
 - **GDMSESSION:** ubuntu

**GSConnect environment (if applicable):**

 - **Paired Device(s):** OnePlus 6
 - **KDE Connect app version:** 1.13.2
 - **Plugin(s):** -

**Additional Notes:**

-

**Comment by genericusername3** [comment]
Try removing the extension as described [here](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Help#how-can-i-reset-the-settings) and reinstalling. That did it for me when I had the exact same issue.

**Comment by Ruud68** [comment]
Hi @genericusername3,

just gave that another go and got this to work: issue was before that I was executing the command as sudo / root and then ~ is not the correct home directory.

redid it without sudo / root and now it works again!
Great tip!

closing this one :)

**Comment by andyholmes** [comment]
Yay :) I think this was probably my fault because of b2ebb83, but it shouldn't be an issue again.
