### ISSUE TITLE
GUI: Download path - dropdown menu

### ISSUE THREAD

**Issue by amivaleo** [andyholmes/gnome-shell-extension-gsconnect#694]
Hi!

My eyes are bleeding because of that dropdown-menu that selects the download path:

![Schermata da 2019-11-04 08-39-23](https://user-images.githubusercontent.com/24316547/68105392-a4a54480-fede-11e9-90c5-2aef7aa8099c.png)

Can you please consider to make it look like this? 😶

![Schermata da 2019-11-04 08-40-32](https://user-images.githubusercontent.com/24316547/68105559-2b5a2180-fedf-11e9-99ad-502d80db81b6.png)

The label on the <strike>right</strike> left (it looks like I still have to think twice about left/right. That's weird, I haven't this issue when speaking my native language) could be "Save Folder" / "Download Path" or similar.

Thank you! 😄

**Comment by amivaleo** [comment]
Why my name is a label? o.O

Is my name a synonim of "boring stuff from that noisy guy"? 😄😄

**Comment by andyholmes** [comment]
Haha, it only seems fair now: JX = Jimmy Experience :D

**Comment by andyholmes** [comment]
Apparently there are no other core apps using a "Download *something*" string, so I followed Firefox and used "Save files to". If you have a better wording, you can change it in the github editor before the translations get regenerated.

**Comment by ferdnyc** [comment]
> Apparently there are no other core apps using a "Download _something_" string

GNOME core apps, allow the user to _control_ where things get saved? LOL. Maybe in 1998. :rofl:

**Comment by amivaleo** [comment]
> Apparently there are no other core apps using a "Download _something_" string, so I followed Firefox and used "Save files to". If you have a better wording, you can change it in the github editor before the translations get regenerated.

gnome-web/epiphany! Look at that, in Preferences.

> GNOME core apps, allow the user to control where things get saved? LOL. Maybe in 1998.

I *deplore* such an attitude! u.u

😃
