### ISSUE TITLE
Missing "Delete this device" option in Advanced settings

### ISSUE THREAD

**Issue by jgoulet1994** [andyholmes/gnome-shell-extension-gsconnect#705]
**Describe the bug**

In the advanced device settings, "Delete this device" is missing

**Screenshots**

![image](https://user-images.githubusercontent.com/4106435/68548493-9910bc80-03bb-11ea-9bb5-4da30d905597.png)

**System Details (please complete the following information):**

 - **GSConnect version: 28** 
   - **Installed from:** GNOME Extensions Website
 - **GNOME/Shell version:** 3.34.1
 - **Distro/Release:** Ubuntu 19.10

**Comment by andyholmes** [comment]
Not a bug :) This is done automatically when unpaired devices become disconnected.

**Comment by ferdnyc** [comment]
@andyholmes Ah... it seems the issue, then, is that we probably shouldn't be claiming that button _**is**_ there, [in the Wiki](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Help#how-can-i-reset-the-settings). :wink:

**Comment by ferdnyc** [comment]
[Fixed.](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Help/_compare/85ade28ec4838d904cedb722fa27a2bb64629662...22a1e547d7fed09f28f48746f925ee4499f162c0)
