### ISSUE TITLE
GSConnect can't see any device

### ISSUE THREAD

**Issue by vbelloir** [andyholmes/gnome-shell-extension-gsconnect#714]
I try to connect to two smartphone :
- Xperia XA2 with Sailfish OS 
- Samsung Galaxy S8

Each smartphone can't see the other one, but the computer can't see them.
Devices can't see the computer

**Steps To Reproduce:**

1. Go to GSconnect configuration page 
2. Click on "search devices " (my computer is in french, don't know the real sentence)
3. No device seen.

**Expected behavior**
GSconnect should see devices and devices should see the computer.

**Screenshots**

> ![image](https://user-images.githubusercontent.com/13942805/69521498-6d670800-0f5f-11ea-8eb2-0b3cc5312027.png)
> 
> **Support Log**
> 
> -- Logs begin at Wed 2019-03-27 19:06:23 CET, end at Mon 2019-11-25 08:43:00 CET. --
> nov. 25 08:42:00 gnome-shell[14043]: [AppIndicatorSupport-WARN] Attempting to re-register :1.63/org/ayatana/NotificationItem/multiload; resetting instead
> nov. 25 08:42:00 gnome-shell[14043]: [AppIndicatorSupport-WARN] Item :1.63/org/ayatana/NotificationItem/multiload is already registered
> nov. 25 08:42:00 gnome-shell[14043]: [AppIndicatorSupport-WARN] Attempting to re-register :1.63/org/ayatana/NotificationItem/multiload; resetting instead
> nov. 25 08:42:00 gnome-shell[14043]: [AppIndicatorSupport-WARN] Item :1.63/org/ayatana/NotificationItem/multiload is already registered
> nov. 25 08:42:00 gnome-shell[14043]: [AppIndicatorSupport-WARN] Attempting to re-register :1.63/org/ayatana/NotificationItem/multiload; resetting instead
> nov. 25 08:42:00 gnome-shell[14043]: [AppIndicatorSupport-WARN] Item :1.63/org/ayatana/NotificationItem/multiload is already registered
> nov. 25 08:42:00 gnome-shell[14043]: [AppIndicatorSupport-WARN] Attempting to re-register :1.63/org/ayatana/NotificationItem/multiload; resetting instead
> nov. 25 08:42:00 gnome-shell[14043]: [AppIndicatorSupport-WARN] Item :1.63/org/ayatana/NotificationItem/multiload is already registered
> nov. 25 08:42:01 gnome-shell[14043]: [AppIndicatorSupport-WARN] Attempting to re-register :1.63/org/ayatana/NotificationItem/multiload; resetting instead
> nov. 25 08:42:01 gnome-shell[14043]: [AppIndicatorSupport-WARN] Item :1.63/org/ayatana/NotificationItem/multiload is already registered
> nov. 25 08:42:01 gnome-shell[14043]: [AppIndicatorSupport-WARN] Attempting to re-register :1.63/org/ayatana/NotificationItem/multiload; resetting instead
> nov. 25 08:42:15 org.gnome.Shell.desktop[14043]: [Parent 15182, Gecko_IOThread] WARNING: pipe error (236): Connexion ré-initialisée par le correspondant: file /build/firefox-clezVp/firefox-70.0.1+build1/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 358
> nov. 25 08:42:48 gjs[25161]: GtkDialog mapped without a transient parent. This is discouraged.
> nov. 25 08:42:49 gnome-shell[14043]: [AppIndicatorSupport-WARN] Attempting to re-register :1.63/org/ayatana/NotificationItem/multiload; resetting instead
nov. 25 08:42:49 gnome-shell[14043]: [AppIndicatorSupport-WARN] Item :1.63/org/ayatana/NotificationItem/multiload is already registered
> nov. 25 08:42:49 gnome-shell[14043]: [AppIndicatorSupport-WARN] Attempting to re-register :1.63/org/ayatana/NotificationItem/multiload; resetting instead
> nov. 25 08:42:49 gnome-shell[14043]: [AppIndicatorSupport-WARN] Item :1.63/org/ayatana/NotificationItem/multiload is already registered
> nov. 25 08:42:49 gnome-shell[14043]: setup_framebuffers: assertion 'width > 0' failed
> nov. 25 08:42:49 gnome-shell[14043]: setup_framebuffers: assertion 'width > 0' failed
> nov. 25 08:42:49 gnome-shell[14043]: setup_framebuffers: assertion 'width > 0' failed
> nov. 25 08:42:51 org.gnome.Shell.Extensions.GSConnect[20658]: [/service/protocol/lan.js:broadcast:385]: "Broadcasting to LAN"

**System Details (please complete the following information):**

 - **GSConnect version:** 28
   - **Installed from:** GNOME Extensions Website
 - **GNOME/Shell version:** Gnome Wayland 3.28.2
 - **Distro/Release:** Ubuntu 18.04.3 LTS

**GSConnect environment (if applicable):** Firefox 70

 - **Paired Device(s):** 
Xperia XA2 with Sailfish OS 3.2.0.12  and Sailfish Connect app
Samsung Galaxy S8 Androïd 9
 - **KDE Connect app version:** [e.g. 1.12.7]
[Android KDE Connect](https://play.google.com/store/apps/details?id=org.kde.kdeconnect_tp&hl=en_US) 1.13.5
[Sailfish Connect](https://openrepos.net/content/r1tschy/sailfish-connect) 0.4.1.1

**Comment by andyholmes** [comment]
It seems like there are no errors coming from GSConnect, so this is most likely a problem with the local network. Can you confirm:

1. Your computer and phones are on the same subnet (eg. `192.168.X.X`)
2. Your computer has no firewall and/or ports 1716-1764 are open for TCP & UDP
3. Your network allows UDP broadcasts
4. You have tried connecting directly with the `Connect to...` dialog
5. You can ping your phones from the terminal with `ping`

**Comment by vbelloir** [comment]
OK, I found on a website the firewall needed to be configured, but with 1714 and 1764 ports.
With 1716 it's ok.
Sorry for that.
