### ISSUE TITLE
Gnome's contacts not shown when contact sync disabled

### ISSUE THREAD

**Issue by wargreen** [andyholmes/gnome-shell-extension-gsconnect#718]
**Describe the bug**

The contacts in gnome's contact are not shown in the message window when contact sync is disabled in gsconnect.

**Steps To Reproduce:**
1. Sync contacts via a GOA account (here : Nextcloud)
2. Disable the GsConnect's "contact" plugin for avoid duplicate contact's
2. Sync sms via GsConnect
3. Open message window

**Expected behavior**
Gnome's contacts are used even if there are not synced via GsConnect

**System Details (please complete the following information):**

 - **GSConnect version:** 28
 - **Installed from:** GNOME Extensions Website
 - **GNOME/Shell version:** 3.34.1-1
 - **Distro/Release:** debian sid

**GSConnect environment (if applicable):**

 - **KDE Connect app version:** 1.13.5

**Comment by andyholmes** [comment]
Can you confirm you have all the dependencies installed for libfolks? Can you post a support log for what happens when you press the `[+]` button in the messaging window?

**Comment by wargreen** [comment]
I have libfolks25 installed via apt, so with all the dependencies.
As log when i click on the [+], all my sms are synced :
`Dec  3 19:20:08 fetide org.gnome.Shell.Extensions.GSConnect[10530]: [/service/protocol/core.js:send:329]: Mercredi: {#012  "id": 1575397208684,#012  "type": "kdeconnect.sms.request_conversations",#012  "body": {}#012}`

**Comment by andyholmes** [comment]
So you have `libglib2.0-dev`, `gir1.2-folks-0.6` and `libfolks-eds25` installed, as [described in the Wiki](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Installation#optional-features)?

What happens when you run the script `~/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/components/folks.py`?

**Comment by wargreen** [comment]
gir1.2-folks-0.6 was not installed... But after install it, disable/re-enable the extension, i got the same issue.
folks.py return :
`❰wargreen❙~❱✔≻ python ~/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/components/folks.py
Traceback (most recent call last):
  File "/home/wargreen/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/components/folks.py", line 437, in <module>
    Aggregator(loop, action)
  File "/home/wargreen/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/components/folks.py", line 346, in __init__
    self._aggregator = Folks.IndividualAggregator.dup()
gi.repository.GLib.Error: g-invoke-error-quark: Could not locate folks_individual_aggregator_dup: 'folks_individual_aggregator_dup': python: undefined symbol: folks_individual_aggregator_dup (1)
`

**Comment by andyholmes** [comment]
Okay, I guess libfolks is just totally broken for introspection now. Hopefully the [`replace-folks-with-eds`](https://github.com/andyholmes/gnome-shell-extension-gsconnect/tree/replace-folks-with-eds) branch will be a usable alternative.

You can try that now if you want, but you'll need the GIRs for evolution-data-server which for Ubuntu is probably at least `gir1.2-ebook-1.2`, `gir1.2-ebookcontacts-1.2`, `gir1.2-ebookdataserver-1.2`.

**Comment by andyholmes** [comment]
Closed with the merge of #728, there will be a release candidate up shortly that includes this change.
