### ISSUE TITLE
gsconnect-28 fails to show WhatsApp notification since latest KDE Connect app update (1.13.5)

### ISSUE THREAD

**Issue by pacho2** [andyholmes/gnome-shell-extension-gsconnect#720]
**Describe the bug**

Since KDE Connect app got updated to 1.13.5 in Google App Store, GSConnect fails to show whatsapp notifications. I don't know if it's a bug in kde connect or is an incompatibility with the newer version :/

Thanks a lot

**Steps To Reproduce:**

1. Update android app to 1.13.5
2. Whatsapp messages are no longer reported in gnome-shell notifications.

**Support Log**

Please generate a support log ([Instructions](wiki/Help#generate-support-log)) and paste any messages related to this issue between the two ``` lines below.

```

```

**System Details (please complete the following information):**

 - **GSConnect version:** 28
   - **Installed from:** package manager (I package it for Gentoo)
 - **GNOME/Shell version:**3.32
 - **Distro/Release:** Gentoo

**GSConnect environment (if applicable):**

 - **Paired Device(s):** Galaxy S10 and S8
 - **KDE Connect app version:**1.13.5
 - **Plugin(s):**Notifications

[1.txt](https://github.com/andyholmes/gnome-shell-extension-gsconnect/files/3899115/1.txt)

**Comment by andyholmes** [comment]
Thanks for the report with log :)

```js
{
  "id": 1574896485055,
  "type": "kdeconnect.notification",
  "body": {
    "payloadHash": "cfc431aa650c64219613377dda033c16",
    "actions": [
      "Marcar como leído"
    ],
    "id": "0|com.whatsapp|1|gr4uqqvJ268tQ4mSMcmSmxoc5fK1sJTTlgp5QmBqnsM=\n|10221",
    "silent": true, <==== HERE
    "isClearable": true,
    "appName": "WhatsApp",
    "time": "1574896484924",
    "requestReplyId": "5b2eb611-a449-4dff-be9c-53897387c90c",
    "ticker": "****",
    "title": "****",
    "text": "****"
  },
  "payloadSize": 17108,
  "payloadTransferInfo": {
    "port": 1747
  }
}
```

The reason the notification is not being shown is because `kdeconnect-android` is marking the notification as `silent`. Looks like this happened in [this commit](https://invent.kde.org/kde/kdeconnect-android/commit/f2064aaef87000bd932f13b47091693ed78034af).

**Comment by pacho2** [comment]
Thanks a lot!

**Comment by san213** [comment]
I am facing the same issue in my galaxy phone paired with mac. Any idea on how to get this fixed?

**Comment by ferdnyc** [comment]
@san213 What are you running on the Mac end, to communicate with the phone? I can't imagine it could be GSConnect. (Does the KDEConnect desktop app have a Mac version? [...I guess so!](https://community.kde.org/KDEConnect/Build_MacOS))

If that's what you're using, I'd suggest reporting the issue in [the KDE bugzilla](https://bugs.kde.org/).
