### ISSUE TITLE
Fix themed icon fallbacks in GNOME Shell

### ISSUE THREAD

**Issue by jnsh** [andyholmes/gnome-shell-extension-gsconnect#726]
Gnome 3.34 added a new experimental option to mutter, that allows to "initialize Xwayland lazily if there are X11 clients", and can be enabled via the `org.gnome.mutter.experimental-features` dconf key.

GSConnect extension fails to start on Wayland if the aforementioned option is enabled, with the following error:
```
JS ERROR: Extension gsconnect@andyholmes.github.io: TypeError: get_gicon.theme is null
get_gicon@/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/extension.js:39:1
ServiceIndicator@/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/extension.js:108:33
enable@/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/extension.js:451:24
_callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:148:13
loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:280:21
_loadExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:490:13
collectFromDatadirs@resource:///org/gnome/shell/misc/fileUtils.js:27:17
_loadExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:469:9
_enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:499:13
_sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:530:13
init@resource:///org/gnome/shell/ui/extensionSystem.js:48:9
_initializeUI@resource:///org/gnome/shell/ui/main.js:242:5
start@resource:///org/gnome/shell/ui/main.js:138:5
@<main>:1:31
```

To my understanding, the plan is to make the "lazy Xwayland init" a permanent feature, so it's probably a good idea to have a look at it before that happens. I'm not sure whether this is something that should be fixed upstream in mutter, or worked around in the extension itself.

This seemed to be the cause for previously reported issue #684, which was closed due to lack of information provided.

Let me know if you need any additional details, or other help with testing.

**System Details:**

 - **GSConnect version:** 30
 - **Installed from:** GitHub
 - **GNOME/Shell version:** 3.34
 - **Distro/Release:** Arch

**Comment by andyholmes** [comment]
Thanks for the log. I'm guessing `GtkIconTheme` is unavailable in this circumstance, so we can avoid the `TypeError`. Unfortunately it will mean that we won't respect the desktop icon theme, since we can't check if the icon theme has an icon to decide whether to fallback to our included icons.

**Comment by andyholmes** [comment]
Feel free to give that a try.

**Comment by jnsh** [comment]
757949240c37ceab066941594fd32fe3ec269663 fixes the startup failure.

However, it does indeed break the icon theming for the panel/power-menu icon. Oddly, the battery indicator icon on the GSConnect power menu item still uses the correct icon from chosen icon theme.

Icons in the "GSConnect Preferences" application are also still themed correctly.

**Comment by andyholmes** [comment]
Hmm, our icons shouldn't affect gnome-shell. That might be [this](https://github.com/GNOME/gnome-shell/blob/master/js/ui/status/power.js#L120). Does this change if gsconnect is not enabled?

**Comment by jnsh** [comment]
Sorry, I meant that the fix breaks theming for the GSConnect panel/power menu icon, as you said it will on your first reply.

Other icons on panel and power menu are still themed correctly.

**Comment by andyholmes** [comment]
Ah I see, that is strange though.

**Comment by jnsh** [comment]
And just to clarify what I meant with "breaks icon theming", is that it uses the fallback gsconnect icon from the extension, instead of the one from the desktop icon theme. As you said would happen.

It's of course better than failing to start the extension altogether, but it would be nice if this could be fixed without breaking the icon theming.

Since other gnome-shell icons aren't effected by the `autostart-xwayland` mutter option, I'd imagine there would be some way the grab the correct icon from the theme. I had a quick look at gnome-shell code and it seems all icon theming in shell is handled via `St` functions. At a quick glance, I didn't find anything that could be used to simply replace the `Gtk.IconTheme.get_default();`, which is causing the startup issue, if I'm understanding correctly.

Since the extension startup was fixed, feel free to close this issue if the icon theme thing isn't bothering you :)

**Comment by andyholmes** [comment]
It would be nice to fix, there's just no way to tell if a theme has an icon that I know of. All other `GThemedIcon` instances in gnome-shell probably know for certain that those icons exist at least in adwaita.

In the case of our icons though, some themes ship alternatives but there are no fallbacks in adwaita.

**Comment by jnsh** [comment]
I think this should be considered an upstream issue in mutter anyway. I doubt they wanted to break the extension API with this feature.

I reported this upstream here: https://gitlab.gnome.org/GNOME/mutter/issues/960

**Comment by jnsh** [comment]
Mutter devs responded on the [upstream issue](https://gitlab.gnome.org/GNOME/mutter/issues/960). Apparently this is an unfortunate side effect of the lazy Xwayland startup, since `gtk_icon_theme_get_default()` relies on X11.

They also provided some suggestions for working around problems with extensions resulting from this, so have a look :)
