### ISSUE TITLE
PC does not see Android Phone but sees Android Tablet

### ISSUE THREAD

**Issue by armc** [andyholmes/gnome-shell-extension-gsconnect#727]
**Describe the bug**

I used to be able to use my Galaxy Note 9 with my computer.  I have never had this problem before, but since April, my phone appears for a brief second in the pair dialog and then disappears.

I am pared with my Tablet and Computer.  My Phone and Tablet see each other.  My Phone and Tablet can pair.  It is only my computers that cannot see my phone or pair.

**Steps To Reproduce:**

Try to Pair. Phone appears and disappears. I get messages on my one system still "paired" with authentication error.

**Expected behavior**

Phone appears on computer and can be paired.

**Screenshots**

None to report.

**Support Log**

Please generate a support log ([Instructions](wiki/Help#generate-support-log)) and paste any messages related to this issue between the two ``` lines below.

```
No messages appear in log except:
GSConnect Version: 30
GSConnect Install: user
```

**System Details (please complete the following information):**
GSConnect Version: 30
GSConnect Install: user
GJS: 15801
XDG_SESSION_TYPE: x11
GDMSESSION: ubuntu 19.10

**GSConnect environment (if applicable):**

 - **Paired Device(s):** Galaxy Note 10.4 2014 Edition Tablet; 
 - **KDE Connect app version:** Latest from Play Store (as of 2019-12-03)
 - **Plugin(s):**

**Additional Notes:**

Add any addtional information about the problem or your system.

**Comment by andyholmes** [comment]
It sounds like your certificate has changed on your devices so GSConnect is refusing to connect to them. You should probably unpair those devices and/or clear the certificate.

**Comment by armc** [comment]
I unpaired the device, but it still refuses to see the device.  I have also cleared the data and the cache on my phone and uninstalled and reinstalled the app on my phone.  Please advise what I should do next?  How do I clear the certificate (Phone ? Computer? )

**Comment by andyholmes** [comment]
Generally resetting your phone's settings or re-installing the app on your phone will cause this problem, as it changes the TLS certificate. This makes GSConnect think another device is trying to impersonate it.

You'll probably have to wipe the settings for your devices:

```sh
dconf reset -f /org/gnome/shell/extensions/gsconnect/device/
```

**Comment by armc** [comment]
That did work.  Perfect.  Thank you!
