### ISSUE TITLE
Dumb apps confuse share plugin

### ISSUE THREAD

**Issue by ferdnyc** [andyholmes/gnome-shell-extension-gsconnect#731]
**Is your feature request related to a problem? Please describe.**

Having upgraded to a new phone (Galaxy Note 8 running Android 9), with its requisite collection of new, tiresome ways to do stupid things that tick me off (so... many... spam... notifications), I've found that when _stupid_ apps share a link to another app, they don't **just** share the URL. They'll first add introductory/title text that confuses the share plugin.

E.g., a page shared from Google Chome on my phone produces this packet:
```
Dec 06 12:37:06 org.gnome.Shell.Extensions.GSConnect[8812]:
[/service/protocol/core.js:receive/<:283]: Galaxy Note8: {
"id": 1575653825731,
"type": "kdeconnect.share.request",
"body": {
  "url": "https://some.site/just_a_url_like_you_would_expect_in_a_sane_and_just_universe"
 }
}
```
But for a link shared from Samsung's stupid news app, the phone <strike>receives</strike> sends:
```
Dec 06 12:36:13 org.gnome.Shell.Extensions.GSConnect[8812]: 
[/service/protocol/core.js:receive/<:283]: Galaxy Note8: {
"id": 1575653773208,
"type": "kdeconnect.share.request",
"body": {
  "text": "The Title of the Page this URL Links to\n\nhttps://url.shortener/KILLMEBILLY"
 }
}
```

...As a result, GSConnect opens up a popup window containing the shared text, instead of forwarding the link to the browser, and I had to copy the URL and paste it into a browser to open it.

**Describe the solution you'd like / alternatives you've considered**

The way I see it, we've got two choices:

1. Search the shared text for a URL, and if we find one, treat it _as_ a shared URL and just ignore the surrounding text, even though it was sent through as a `"text"` share instead of a `"url"` share.

   That could potentially be problematic if someone shares text that _intentionally_ contains a URL, for purposes other than opening it in the browser, so maybe an additional check could be made on the position of the URL within the text: Only URLs that are either right at the beginning or right at the end of the text are auto-launched, while text with interior URLs is displayed as shared text.

1. Something we should do _anyway_ (even if we go with the restricted form of the previous option) is parse `"text"` shares for URLs and automatically hyperlink them, so that they can be launched with a click instead of requiring a manual copy-paste to the browser.

**System Details (please complete the following information):**
 - GSConnect version: v30
   - Installed from: e.g.o

**Comment by andyholmes** [comment]
Hmm, yeah 2. is probably a good idea. I've honestly forgot about that aspect of the Share plugin, since it seems largely useless. IIRC kdeconnect actually dumps the text in a `/tmp` file and opens it in an editor, but who knows what the use case for that originally was; might have pre-dated the clipboard plugin.

As for 1. that might be possible, I guess it just depends on whether anyone actually uses the "text" share feature. I guess it's hard to say without any analytics. I doubt we can expect the Android app to intercept these since I imagine it's passed directly from an "Intent".

**Comment by ferdnyc** [comment]
> Hmm, yeah 2. is probably a good idea. I've honestly forgot about that aspect of the Share plugin, since it seems largely useless.

Yeah, I really can't imagine why I'd ever want to send _text_ from my phone to my PC — **_maaaybe_** I could see it for a contact's address or something, but then that wouldn't contain a URL so it would be fine.

Or I suppose maybe something like a password or PIN code.

I definitely _love_ that when a website sends me a code for two-factor auth via SMS, a forwarded notification pops up on my desktop so I can read the code right from there without even picking up my phone. Along with media-player remote control from my phone, the notification forwarding is one of my favorite features of the GSConnect/KDE Connect combo. But a big part of the value there is that it's completely automated, so sharing text  _manually_... still meh.

**Comment by andyholmes** [comment]
Yeah, my guess is it was a "might as well" feature or predated the clipboard plugin :man_shrugging:

**Comment by ferdnyc** [comment]
Tested 576ccd1, works perfectly. Thanks! :+1:

**Comment by ferdnyc** [comment]
I'm going to close this as fixed. The low-hanging fruit is implemented, and represents a more than adequate "good enough", since the more ambitious solutions proposed are rife with acknowledged potential issues.
