### ISSUE TITLE
tray icon disappears and cannot turn this on

### ISSUE THREAD

**Issue by heartofstone** [andyholmes/gnome-shell-extension-gsconnect#733]
**Describe the bug**

after turning off on the extensions.gnome.org site I cannot now turn this back on and nothing appears in the tray icon

**Steps To Reproduce:**

1. Go to https://extensions.gnome.org/local/
2. Click on  turn the extension off

**Expected behavior**

I expected to be able to turn this back on. I cannot

**Screenshots**

If applicable, add screenshots to help explain your problem. You can drag-and-drop or cut-and-paste images directly into this edit window, to include them in your report.

**Support Log**

Please generate a support log ([Instructions](wiki/Help#generate-support-log)) and paste any messages related to this issue between the two ``` lines below.

```

GSConnect Version: 30
GSConnect Install: user
GJS: 15801
XDG_SESSION_TYPE: x11
GDMSESSION: ubuntu
--------------------------------------------------------------------------------
-- Logs begin at Thu 2019-10-03 13:49:19 BST, end at Wed 2019-12-11 16:09:38 GMT. --
Dec 11 16:09:02 gnome-software[11782]: Only 0 apps for recent list, hiding
Dec 11 16:09:03 gnome-software[11782]: g_path_get_basename: assertion 'file_name != NULL' failed
Dec 11 16:09:03 gnome-software[11782]: g_regex_match_full: assertion 'string != NULL' failed
Dec 11 16:09:03 gnome-software[11782]: g_path_get_basename: assertion 'file_name != NULL' failed
Dec 11 16:09:03 gnome-software[11782]: g_regex_match_full: assertion 'string != NULL' failed
Dec 11 16:09:03 gnome-software[11782]: not GsPlugin error g-io-error-quark:35: Invalid string value converting to GVariant
Dec 11 16:09:03 gnome-software[11782]: not GsPlugin error g-io-error-quark:35: Invalid string value converting to GVariant
Dec 11 16:09:03 PackageKit[10686]: resolve transaction /817_dbdaaadb from uid 1000 finished with success after 563ms
Dec 11 16:09:07 systemd[10828]: tracker-extract.service: Succeeded.
Dec 11 16:09:16 /usr/lib/gdm3/gdm-x-session[10865]: (II) modeset(0): EDID vendor "CMN", prod id 5250
Dec 11 16:09:16 /usr/lib/gdm3/gdm-x-session[10865]: (II) modeset(0): Printing DDC gathered Modelines:
Dec 11 16:09:16 /usr/lib/gdm3/gdm-x-session[10865]: (II) modeset(0): Modeline "1600x900"x0.0  107.80  1600 1648 1680 1940  900 903 908 926 -hsync -vsync (55.6 kHz eP)
Dec 11 16:09:17 gnome-control-c[12917]: No permissions store proxy yet, come back later
Dec 11 16:09:18 dbus-daemon[999]: [system] Activating via systemd: service name='net.reactivated.Fprint' unit='fprintd.service' requested by ':1.2032' (uid=1000 pid=12917 comm="gnome-control-center user-accounts " label="unconfined")
Dec 11 16:09:18 systemd[1]: Starting Fingerprint Authentication Daemon...
Dec 11 16:09:18 dbus-daemon[999]: [system] Successfully activated service 'net.reactivated.Fprint'
Dec 11 16:09:18 systemd[1]: Started Fingerprint Authentication Daemon.
Dec 11 16:09:27 tracker-store[12848]: OK
Dec 11 16:09:27 systemd[10828]: tracker-store.service: Succeeded.
Dec 11 16:09:31 dbus-daemon[10863]: [session uid=1000 pid=10863] Activating via systemd: service name='org.bluez.obex' unit='dbus-org.bluez.obex.service' requested by ':1.122' (uid=1000 pid=12917 comm="gnome-control-center user-accounts " label="unconfined")
Dec 11 16:09:31 systemd[10828]: Starting Bluetooth OBEX service...
Dec 11 16:09:31 obexd[12962]: OBEX daemon 5.50
Dec 11 16:09:31 dbus-daemon[10863]: [session uid=1000 pid=10863] Successfully activated service 'org.bluez.obex'
Dec 11 16:09:31 systemd[10828]: Started Bluetooth OBEX service.
Dec 11 16:09:38 xdg-desktop-por[11029]: Failed to get application states: GDBus.Error:org.freedesktop.portal.Error.Failed: Could not get window list: GDBus.Error:org.freedesktop.DBus.Error.AccessDenied: App introspection not allowed
Dec 11 16:09:38 dbus-daemon[999]: [system] Activating via systemd: service name='org.freedesktop.locale1' unit='dbus-org.freedesktop.locale1.service' requested by ':1.2032' (uid=1000 pid=12917 comm="gnome-control-center user-accounts " label="unconfined")
Dec 11 16:09:38 systemd[1]: Starting Locale Service...
Dec 11 16:09:38 dbus-daemon[999]: [system] Successfully activated service 'org.freedesktop.locale1'
Dec 11 16:09:38 systemd[1]: Started Locale Service.
```

**System Details (please complete the following information):**

 - **GSConnect version:** [e.g. 20, 24, ... (displayed in the GSConnect "About" window)]
   - **Installed from:** [e.g. GNOME Extensions Website, GitHub, Package Manager, ...]
 - **GNOME/Shell version:** [e.g. 3.30, 3.28, ...]
 - **Distro/Release:** [e.g. Ubuntu 18.04, Fedora 29, Arch, ...]

**GSConnect environment (if applicable):**

 - **Paired Device(s):** [e.g. Galaxy Note 8, Pixel 2, Honor 9, ...]
 - **KDE Connect app version:** [e.g. 1.12.7]
 - **Plugin(s):** [if the issue only occurs when using certain plugin(s)]

**Additional Notes:**

Add any addtional information about the problem or your system.

**Comment by ferdnyc** [comment]
@heartofstone 

None of the messages in your log capture are GSConnect-related at all, but if the extension is completely inactive that's to be expected since the reporting tool only shows _activity_ that occurs while it's capturing.

1. What GNOME release are you running, or what version of Ubuntu?
2. When you say you "can't turn this back on", do you mean that the On/Off switch on the extensions.gnome.org page isn't functioning? Or simply that it has no effect when it's switched to "On"?
3. GSConnect normally shows an icon in the top bar only when a device is connected, otherwise it's present only as a user menu item. Can you check whether your user menu contains a "Mobile Devices" item, and (if it does) whether there's a "Turn On" or "Turn Off" option in that item's submenu? If GSConnect is switched off, clicking "Turn On" in the user menu will reactivate it. Here's a screenshot of what you'd be looking for:

![GSConnect UserMenu TurnOn](https://user-images.githubusercontent.com/538020/70647502-13309d00-1c17-11ea-95ce-c830e5a1c430.png)

**Comment by heartofstone** [comment]
Thanks for your reply. Apologies for my late reply but my laptop charger broke and I had to wait for a new one.



I have resolved the issue myself. 


but to help identify what happened here

When you say you "can't turn this back on", do you mean that the On/Off switch on the extensions.gnome.org page isn't functioning? Or simply that it has no effect when it's switched to "On"?

I did not have a package installed called gnome-shell-extensions. I installed this and the gnome-tweak-tool.

I think the issue with this is one of interface rather than function.

I was able to turn off this extension using the webpage 

https://extensions.gnome.org/local/

this I think stopped the service. but, this did not restart or re enable the service once it was stopped.

i expected this to turn the plugin back on but this is not what happened.

Once I had the tweak tool and gnome-shell-extensions package installed I could see how to re-enable this and it continues to work as expected.

So not functional related at all. but maybe worthwhile mentioning in documentation as I did not know a command i could enter to restart the service. Could you possibly include this in documentation.

o
