### ISSUE TITLE
Fedora 31 and GSConnect 30 Gio.DBusError: The name is not activatable

### ISSUE THREAD

**Issue by blackjackshellac** [andyholmes/gnome-shell-extension-gsconnect#735]
**Describe the bug**

Installed the extension at extensions.gnome.org.  But it won't start the service.

**Steps To Reproduce:**

1. Installed at https://extensions.gnome.org/extension/1319/gsconnect/
2. Menu/Mobile Devices/Mobile Settings dialog shows "Waiting for service ..."
3. journalctl -r shows Gio.DBusError
4. See error: JS ERROR: GSConnect: Gio.DBusError: The name is not activatable

**Expected behavior**

Expect to see the app start

**Support Log**

```
Dec 12 11:44:35 doont gnome-shell[5753]: JS ERROR: GSConnect: Gio.DBusError: The name is not activatable
                                         start/</<@/home/steeve/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/shell/remote.js:470:45
Dec 12 11:44:35 doont gnome-shell[5753]:  extracting: /home/steeve/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/metadata.json
Dec 12 11:44:35 doont gnome-shell[5753]:   inflating: /home/steeve/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/nautilus-gsconnect.py
Dec 12 11:44:35 doont gnome-shell[5753]:   inflating: /home/steeve/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/gsconnect-preferences
Dec 12 11:44:35 doont gnome-shell[5753]:   inflating: /home/steeve/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/prefs.js
Dec 12 11:44:35 doont gnome-shell[5753]:   inflating: /home/steeve/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js
Dec 12 11:44:35 doont gnome-shell[5753]:   inflating: /home/steeve/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/ui/telephony.js
Dec 12 11:44:35 doont gnome-shell[5753]:   inflating: /home/steeve/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/ui/messaging.js

```

**System Details (please complete the following information):**

 - **GSConnect version:** 30
   - **Installed from:** GNOME Extensions Website
 - **GNOME/Shell version:** 3.34
 - **Distro/Release:** Fedora 31

**Additional Notes:**

If I start the daemon manually it works and I can pair my Nexus 5x with KDE connect running,

```
$ ./.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js 

(GSConnect:30866): GLib-CRITICAL **: 11:54:53.432: g_variant_new_string: assertion 'string != NULL' failed
Gjs-Message: 11:56:18.853: JS WARNING: [/home/steeve/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/protocol/lan.js 689]: reference to undefined property "GSocketOutputStream"
```

**Comment by andyholmes** [comment]
Can you confirm the `daemon.js` is executable?

```sh
$ ls -la ~/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js
-rwxr-xr-x. 1 andrew andrew 33572 Dec  6 12:01 /home/andrew/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js
```
And that the DBus service file installed properly?

```sh
$ cat ~/.local/share/dbus-1/services/org.gnome.Shell.Extensions.GSConnect.service
[D-BUS Service]
Name=org.gnome.Shell.Extensions.GSConnect
Exec=/home/andrew/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js
```

**Comment by blackjackshellac** [comment]
Definitely executable, 
```
$ ls -l ~/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js 
-rwxr-xr-x 1 steeve steeve 34018 Dec  1 19:26 /home/steeve/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js
steeve ~/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service 16:04 - 1011:
```
DBus service file looks okay to me,

```
$ cat ~/.local/share/dbus-1/services/org.gnome.Shell.Extensions.GSConnect.service
[D-BUS Service]
Name=org.gnome.Shell.Extensions.GSConnect
Exec=/home/steeve/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js
```
There's no dbus session running for this service though,

![gnome-shell-screenshot-S9D7C0](https://user-images.githubusercontent.com/825403/70749584-a8589200-1cfa-11ea-9c4f-c0055b4bd74c.png)

**Comment by andyholmes** [comment]
If the DBus service file is installed correctly, it should be visible in D-Feet whether it's currently running or not. It seems like DBus (probably `dbus-broker`) has not rescanned or picked up the service file for some reason. Is there anything peculiar about your setup: using experimental mutter features, etc?

**Comment by blackjackshellac** [comment]
If I start daemon.js manually I can see it in d-feet,

![gnome-shell-screenshot-1CATC0](https://user-images.githubusercontent.com/825403/70750866-43526b80-1cfd-11ea-9cd6-95d45c545a13.png)

**Comment by blackjackshellac** [comment]
> If the DBus service file is installed correctly, it should be visible in D-Feet whether it's currently running or not. It seems like DBus (probably `dbus-broker`) has not rescanned or picked up the service file for some reason. Is there anything peculiar about your setup: using experimental mutter features, etc?

Can't think of any reason why my setup would be unusual or experimental.

**Comment by andyholmes** [comment]
That makes sense. What doesn't make sense is`dbus-broker-launch` not noticing the file change. It should print a message like this:

```
Noticed file-system modification, trigger reload.
```

**Comment by blackjackshellac** [comment]
> If the DBus service file is installed correctly, it should be visible in D-Feet whether it's currently running or not. It seems like DBus (probably `dbus-broker`) has not rescanned or picked up the service file for some reason. Is there anything peculiar about your setup: using experimental mutter features, etc?

There's nothing particularly interesting about my setup.  It's just a devel desktop.

Okay, rebooting fixed the problem with the dbus-broker picking up the service in  ~/.local/share/dbus-1/services/  Not sure what the problem is, something doesn't seem to be right, but it's working now, and I can see the service in d-feet regardless if it's Turned on or off.

**Comment by blackjackshellac** [comment]
Strange indeed.  Given that it happens on (at least) two of my desktops both running fedora, it would seen to be an issue with how dbus-broker-launch is triggering reloads.  I think the only reload that happened today was after I rebooted,

```
$ journalctl -r | grep "Noticed file-system modification, trigger reload."
Dec 12 16:41:23 doont dbus-broker-launch[5507]: Noticed file-system modification, trigger reload.
Dec 06 09:47:26 doont dbus-broker-launch[12041]: Noticed file-system modification, trigger reload.
Dec 06 09:47:26 doont dbus-broker-launch[12041]: Noticed file-system modification, trigger reload.
Dec 06 09:47:26 doont dbus-broker-launch[12041]: Noticed file-system modification, trigger reload.
Dec 06 09:47:26 doont dbus-broker-launch[12041]: Noticed file-system modification, trigger reload.
Dec 06 09:47:16 doont dbus-broker-launch[12041]: Noticed file-system modification, trigger reload.
Dec 06 09:47:16 doont dbus-broker-launch[12041]: Noticed file-system modification, trigger reload.
Dec 06 09:47:14 doont dbus-broker-launch[12041]: Noticed file-system modification, trigger reload.
Dec 06 09:47:14 doont dbus-broker-launch[12041]: Noticed file-system modification, trigger reload.
Dec 06 09:47:13 doont dbus-broker-launch[12041]: Noticed file-system modification, trigger reload.
Dec 06 09:47:13 doont dbus-broker-launch[12041]: Noticed file-system modification, trigger reload.
Dec 06 09:47:12 doont dbus-broker-launch[12041]: Noticed file-system modification, trigger reload.
Dec 06 09:47:12 doont dbus-broker-launch[12041]: Noticed file-system modification, trigger reload.
Dec 06 09:47:11 doont dbus-broker-launch[12041]: Noticed file-system modification, trigger reload.
Dec 06 09:47:09 doont dbus-broker-launch[12041]: Noticed file-system modification, trigger reload.
Dec 06 09:46:50 doont dbus-broker-launch[5473]: Noticed file-system modification, trigger reload.
Dec 06 09:46:47 doont dbus-broker-launch[12041]: Noticed file-system modification, trigger reload.
Dec 06 09:46:47 doont dbus-broker-launch[12041]: Noticed file-system modification, trigger reload.
Dec 06 09:46:41 doont dbus-broker-launch[5473]: Noticed file-system modification, trigger reload.
Dec 06 09:46:41 doont dbus-broker-launch[5473]: Noticed file-system modification, trigger reload.
Dec 06 09:46:39 doont dbus-broker-launch[12041]: Noticed file-system modification, trigger reload.
```

**Comment by blackjackshellac** [comment]
Okay, well it seems to just be a periodic issue with dbus-broker-launch.  Since rebooting every test I've done has resulted in a trigger reload.  Thanks for your help.

**Comment by andyholmes** [comment]
Seems like this might be related to bus1/dbus-broker#202. There might be a regression there, although we definitely install a full file and not a symlink.

**Comment by ferdnyc** [comment]
When I upgraded from v29 to v30 on Fedora 31, ISTR GSConnect required a reboot before it worked again. It was a one-time thing so I didn't think to mention it. Upgrades are always a tiny bit chancy, and "when in doubt, reboot" is my mantra by now.

**Comment by brianjmurrell** [comment]
I'm also running into this on Fedora 31.  Is there anything short of a reboot that will resolve this?

I have too much work-in-progress to suffer a reboot and have to get it all back in progress again.

**Comment by brianjmurrell** [comment]
```bash
$ systemctl reload --user dbus-broker.service
```
