### ISSUE TITLE
Taskbar icon eventuualy appears even though I choose the user menu display mod.

### ISSUE THREAD

**Issue by Amathadius** [andyholmes/gnome-shell-extension-gsconnect#740]
I don't know why or how, but when I choose use menu in the display mod, taskbar icon eventually also appears. For instance, it happens when I unlock my computer, but not after alt-f2+r.

**Comment by Amathadius** [comment]
![image](https://user-images.githubusercontent.com/9408075/71453332-c2fa2480-2758-11ea-9d60-fb195ea51f36.png)

**Comment by andyholmes** [comment]
Are you using any other taskbar extensions? Are there any errors in the log?

**Comment by Amathadius** [comment]
I don't really know how, but after a while (deactivate/activate extension, changing mod) it doesn't do that anymore.

I use dash to panel and appindicator. Maybe it had something to do with a older dash-to-panel build.
