### ISSUE TITLE
Scroll ubuntu 18.04.3 

### ISSUE THREAD

**Issue by laurentiucalonfir** [andyholmes/gnome-shell-extension-gsconnect#749]
The scroll feature in ubuntu 18.04.3 doesn't work. Tested in ubuntu 19.10 and debian 10 - no issues 

smartphone -Xiaomi Redmi 7

**Comment by ferdnyc** [comment]
@laurentiucalonfir Ubuntu 18.04 is no longer supported in newer GSConnect versions, GNOME 3.34 (available in Ubuntu 19.10 and later) is the minimum supported version for the current releases.

You could try installing an older version compatible with your GNOME Shell release at extensions.gnome.org, to see if it fixes the issue. But if it doesn't I'm afraid development has ended for those older systems, so any remaining issues won't be fixed.

**Comment by laurentiucalonfir** [comment]
I understand. Thank you so much for reply.

În joi, 9 ian. 2020 la 14:10, Frank Dana <notifications@github.com> a scris:
