### ISSUE TITLE
Unable to start GSConnect on Pop_OS!

### ISSUE THREAD

**Issue by vaibhavkulkarni** [andyholmes/gnome-shell-extension-gsconnect#751]
Hello,

I am unable to start GSConnect on Pop_OS!. I am sure I am doing something wrong. Any help would be appreciated.

Here is what I did:
Inst
1. Installed GSConnect from GIT
2. GSConnect wasn't visible in settings menu. (I am not sure if I am looking at the correct place)
3. Manually started gsconnect-preferences and fetched support logs
3. Checked logs and I see the following:
`GSConnect Version: 30
GSConnect Install: user
GJS: 15801
XDG_SESSION_TYPE: x11
GDMSESSION: pop
Logs begin at Thu 2019-08-29 05:39:09 BST, end at Tue 2020-01-14 09:38:36 GMT. --
Jan 14 09:38:01 kubelet[6938]: E0114 09:38:01.208980    6938 kubelet.go:2183] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
Jan 14 09:38:04 kubelet[6938]: W0114 09:38:04.850286    6938 cni.go:237] Unable to update cni config: no networks found in /etc/cni/net.d
Jan 14 09:38:06 kubelet[6938]: E0114 09:38:06.231847    6938 kubelet.go:2183] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
Jan 14 09:38:09 kubelet[6938]: W0114 09:38:09.850689    6938 cni.go:237] Unable to update cni config: no networks found in /etc/cni/net.d
Jan 14 09:38:11 kubelet[6938]: E0114 09:38:11.273169    6938 kubelet.go:2183] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
Jan 14 09:38:14 kubelet[6938]: W0114 09:38:14.851029    6938 cni.go:237] Unable to update cni config: no networks found in /etc/cni/net.d
Jan 14 09:38:16 kubelet[6938]: E0114 09:38:16.284137    6938 kubelet.go:2183] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
Jan 14 09:38:19 kubelet[6938]: W0114 09:38:19.851481    6938 cni.go:237] Unable to update cni config: no networks found in /etc/cni/net.d
Jan 14 09:38:21 kubelet[6938]: E0114 09:38:21.325039    6938 kubelet.go:2183] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
Jan 14 09:38:24 kubelet[6938]: W0114 09:38:24.851802    6938 cni.go:237] Unable to update cni config: no networks found in /etc/cni/net.d
Jan 14 09:38:26 kubelet[6938]: E0114 09:38:26.348321    6938 kubelet.go:2183] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
Jan 14 09:38:29 kubelet[6938]: W0114 09:38:29.852126    6938 cni.go:237] Unable to update cni config: no networks found in /etc/cni/net.d
Jan 14 09:38:31 kubelet[6938]: E0114 09:38:31.389350    6938 kubelet.go:2183] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
Jan 14 09:38:34 kubelet[6938]: W0114 09:38:34.852422    6938 cni.go:237] Unable to update cni config: no networks found in /etc/cni/net.d
Jan 14 09:38:36 kubelet[6938]: E0114 09:38:36.411889    6938 kubelet.go:2183] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized`

**Comment by andyholmes** [comment]
There aren't any messages related to GSConnect here, but that makes sense since this log won't contain anything if it's not running :)

You'll want to check `journalctl` or GNOME Logs for an error when the extension is enabled or the shell starts. Since you're running Xorg, if you have the extension still enabled, you can just:

1. run `journalctl -f -o cat /usr/bin/gnome-shell` in a terminal
2. do a <kbd>Alt</kbd> + <kbd>F2</kbd> with `r` as the command.

Then you can just paste that output here.

**Comment by vaibhavkulkarni** [comment]
Thank you very much for your response Andy. Here is the ourput:
`journalctl -f -o cat /usr/bin/gnome-shell
[20901:1:0114/121321.381269:ERROR:child_process_sandbox_support_impl_linux.cc(79)] FontService unique font name matching request did not receive a response.
[21384:1:0114/121400.407009:ERROR:child_process_sandbox_support_impl_linux.cc(79)] FontService unique font name matching request did not receive a response.
[21384:1:0114/121400.407472:ERROR:child_process_sandbox_support_impl_linux.cc(79)] FontService unique font name matching request did not receive a response.
[22008:1:0114/121433.884754:ERROR:child_process_sandbox_support_impl_linux.cc(79)] FontService unique font name matching request did not receive a response.
[22008:1:0114/121433.886231:ERROR:child_process_sandbox_support_impl_linux.cc(79)] FontService unique font name matching request did not receive a response.
[4068:1:0114/121812.310697:ERROR:child_process_sandbox_support_impl_linux.cc(79)] FontService unique font name matching request did not receive a response.
[4068:1:0114/121812.311104:ERROR:child_process_sandbox_support_impl_linux.cc(79)] FontService unique font name matching request did not receive a response.
gnome-shell-extension-system76-power: power profile was set: 'Balanced'
Error setting metadata to desktop files , Gio.IOErrorEnum: Setting attribute metadata::nautilus-icon-position not supported
Error setting metadata to desktop files , Gio.IOErrorEnum: Setting attribute metadata::nautilus-icon-position not supported
Window manager warning: META_CURRENT_TIME used to choose focus window; focus window may not be correct.
Object Meta.BackgroundActor (0x557a271a8480), has been already deallocated — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
== Stack trace for context 0x557a2646e600 ==
#0   7fffc1bc6bf0 b   resource:///org/gnome/gjs/modules/overrides/GObject.js:508 (7f50a12ad790 @ 25)
#1   557a316d3320 i   /usr/share/gnome-shell/extensions/desktop-icons@csoriano/desktopGrid.js:210 (7f506c954d30 @ 75)
#2   557a316d32a8 i   /usr/share/gnome-shell/extensions/desktop-icons@csoriano/desktopGrid.js:115 (7f506c954940 @ 12)
#3   557a316d3230 i   resource:///org/gnome/shell/ui/main.js:224 (7f50a12cf820 @ 12)
JS ERROR: Error: Argument 'instance' (type interface) may not be null
_init/GObject.Object.prototype.disconnect@resource:///org/gnome/gjs/modules/overrides/GObject.js:508:16
_onDestroy@/usr/share/gnome-shell/extensions/desktop-icons@csoriano/desktopGrid.js:210:13
DesktopGrid</<@/usr/share/gnome-shell/extensions/desktop-icons@csoriano/desktopGrid.js:115:45
_initializeUI/<@resource:///org/gnome/shell/ui/main.js:224:9

Object Meta.BackgroundActor (0x557a271a8840), has been already deallocated — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
== Stack trace for context 0x557a2646e600 ==
#0   7fffc1bc6bf0 b   resource:///org/gnome/gjs/modules/overrides/GObject.js:508 (7f50a12ad790 @ 25)
#1   557a316d3320 i   /usr/share/gnome-shell/extensions/desktop-icons@csoriano/desktopGrid.js:210 (7f506c954d30 @ 75)
#2   557a316d32a8 i   /usr/share/gnome-shell/extensions/desktop-icons@csoriano/desktopGrid.js:115 (7f506c954940 @ 12)
#3   557a316d3230 i   resource:///org/gnome/shell/ui/main.js:224 (7f50a12cf820 @ 12)
JS ERROR: Error: Argument 'instance' (type interface) may not be null
_init/GObject.Object.prototype.disconnect@resource:///org/gnome/gjs/modules/overrides/GObject.js:508:16
_onDestroy@/usr/share/gnome-shell/extensions/desktop-icons@csoriano/desktopGrid.js:210:13
DesktopGrid</<@/usr/share/gnome-shell/extensions/desktop-icons@csoriano/desktopGrid.js:115:45
_initializeUI/<@resource:///org/gnome/shell/ui/main.js:224:9

JS ERROR: TypeError: actor.get_meta_window(...) is null
_destroyWindowDone@resource:///org/gnome/shell/ui/windowManager.js:1804:26
onStopped@resource:///org/gnome/shell/ui/windowManager.js:1774:34
_makeEaseCallback/<@resource:///org/gnome/shell/ui/environment.js:72:13
_easeActor/<@resource:///org/gnome/shell/ui/environment.js:128:56
_initializeUI/<@resource:///org/gnome/shell/ui/main.js:224:9

JS ERROR: TypeError: actor.get_meta_window(...) is null
_destroyWindowDone@resource:///org/gnome/shell/ui/windowManager.js:1804:26
onStopped@resource:///org/gnome/shell/ui/windowManager.js:1774:34
_makeEaseCallback/<@resource:///org/gnome/shell/ui/environment.js:72:13
_easeActor/<@resource:///org/gnome/shell/ui/environment.js:128:56
_initializeUI/<@resource:///org/gnome/shell/ui/main.js:224:9

JS ERROR: TypeError: actor.get_meta_window(...) is null
_destroyWindowDone@resource:///org/gnome/shell/ui/windowManager.js:1804:26
onStopped@resource:///org/gnome/shell/ui/windowManager.js:1794:34
_makeEaseCallback/<@resource:///org/gnome/shell/ui/environment.js:72:13
_easeActor/<@resource:///org/gnome/shell/ui/environment.js:128:56
_initializeUI/<@resource:///org/gnome/shell/ui/main.js:224:9

JS ERROR: TypeError: actor.get_meta_window(...) is null
_destroyWindowDone@resource:///org/gnome/shell/ui/windowManager.js:1804:26
onStopped@resource:///org/gnome/shell/ui/windowManager.js:1774:34
_makeEaseCallback/<@resource:///org/gnome/shell/ui/environment.js:72:13
_easeActor/<@resource:///org/gnome/shell/ui/environment.js:128:56
_initializeUI/<@resource:///org/gnome/shell/ui/main.js:224:9

JS ERROR: TypeError: actor.get_meta_window(...) is null
_destroyWindowDone@resource:///org/gnome/shell/ui/windowManager.js:1804:26
onStopped@resource:///org/gnome/shell/ui/windowManager.js:1774:34
_makeEaseCallback/<@resource:///org/gnome/shell/ui/environment.js:72:13
_easeActor/<@resource:///org/gnome/shell/ui/environment.js:128:56
_initializeUI/<@resource:///org/gnome/shell/ui/main.js:224:9

JS ERROR: TypeError: actor.get_meta_window(...) is null
_destroyWindowDone@resource:///org/gnome/shell/ui/windowManager.js:1804:26
onStopped@resource:///org/gnome/shell/ui/windowManager.js:1774:34
_makeEaseCallback/<@resource:///org/gnome/shell/ui/environment.js:72:13
_easeActor/<@resource:///org/gnome/shell/ui/environment.js:128:56
_initializeUI/<@resource:///org/gnome/shell/ui/main.js:224:9

JS ERROR: TypeError: actor.get_meta_window(...) is null
_destroyWindowDone@resource:///org/gnome/shell/ui/windowManager.js:1804:26
onStopped@resource:///org/gnome/shell/ui/windowManager.js:1774:34
_makeEaseCallback/<@resource:///org/gnome/shell/ui/environment.js:72:13
_easeActor/<@resource:///org/gnome/shell/ui/environment.js:128:56
_initializeUI/<@resource:///org/gnome/shell/ui/main.js:224:9

JS ERROR: TypeError: actor.get_meta_window(...) is null
_destroyWindowDone@resource:///org/gnome/shell/ui/windowManager.js:1804:26
onStopped@resource:///org/gnome/shell/ui/windowManager.js:1774:34
_makeEaseCallback/<@resource:///org/gnome/shell/ui/environment.js:72:13
_easeActor/<@resource:///org/gnome/shell/ui/environment.js:128:56
_initializeUI/<@resource:///org/gnome/shell/ui/main.js:224:9

JS ERROR: TypeError: actor.get_meta_window(...) is null
_destroyWindowDone@resource:///org/gnome/shell/ui/windowManager.js:1804:26
onStopped@resource:///org/gnome/shell/ui/windowManager.js:1774:34
_makeEaseCallback/<@resource:///org/gnome/shell/ui/environment.js:72:13
_easeActor/<@resource:///org/gnome/shell/ui/environment.js:128:56
_initializeUI/<@resource:///org/gnome/shell/ui/main.js:224:9

JS ERROR: TypeError: actor.get_meta_window(...) is null
_destroyWindowDone@resource:///org/gnome/shell/ui/windowManager.js:1804:26
onStopped@resource:///org/gnome/shell/ui/windowManager.js:1774:34
_makeEaseCallback/<@resource:///org/gnome/shell/ui/environment.js:72:13
_easeActor/<@resource:///org/gnome/shell/ui/environment.js:128:56
_initializeUI/<@resource:///org/gnome/shell/ui/main.js:224:9

JS ERROR: TypeError: actor.get_meta_window(...) is null
_destroyWindowDone@resource:///org/gnome/shell/ui/windowManager.js:1804:26
onStopped@resource:///org/gnome/shell/ui/windowManager.js:1774:34
_makeEaseCallback/<@resource:///org/gnome/shell/ui/environment.js:72:13
_easeActor/<@resource:///org/gnome/shell/ui/environment.js:128:56
_initializeUI/<@resource:///org/gnome/shell/ui/main.js:224:9

Failed to load module "appmenu-gtk-module"
Unset XDG_SESSION_ID, getCurrentSessionProxy() called outside a user session. Asking logind directly.
Will monitor session 2
current session already has an ibus-daemon.
Telepathy is not available, chat integration will be disabled.
Some code accessed the property 'Extension' on the module 'dndExtension'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
Some code accessed the property 'DoNotDisturb' on the module 'doNotDisturb'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
Some code accessed the property 'GnomePresence' on the module 'system'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
Some code accessed the property 'DoNotDisturbToggle' on the module 'widgets'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
Some code accessed the property 'DoNotDisturbIcon' on the module 'widgets'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
Some code accessed the property 'SettingsManager' on the module 'settings'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
Some code accessed the property 'NotificationManager' on the module 'system'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
Some code accessed the property 'RemoteAPI' on the module 'settings'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
Some code accessed the property 'AudioManager' on the module 'system'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
gnome-shell-extension-system76-power: power profile was set: 'Balanced'
ibus_bus_hello: assertion 'ibus_bus_is_connected (bus)' failed
Error while sending AddMatch() message: The connection is closed
ibus_bus_call_async: assertion 'ibus_bus_is_connected (bus)' failed
ibus_bus_call_async: assertion 'ibus_bus_is_connected (bus)' failed
Error looking up permission: GDBus.Error:org.freedesktop.portal.Error.NotFound: No entry for geolocation
JS ERROR: error initializing the NetworkManager Agent: NM.AgentManagerError: An agent with this ID is already registered for this user.
NetworkAgent</<@resource:///org/gnome/shell/ui/components/networkAgent.js:639:17

GNOME Shell started at Tue Jan 14 2020 13:16:27 GMT+0000 (GMT)
Registering session with GDM
Error setting metadata to desktop files , Gio.IOErrorEnum: Setting attribute metadata::nautilus-icon-position not supported
Error setting metadata to desktop files , Gio.IOErrorEnum: Setting attribute metadata::nautilus-icon-position not supported`

**Comment by andyholmes** [comment]
Hmm, there are still no message about GSConnect here, are you sure it is enabled?

Try: `gnome-extensions enable gsconnect@andyholmes.github.io`

**Comment by vaibhavkulkarni** [comment]
Hey,

Thanks for looking into this again.

I checked again and saw that extension was enabled indeed. But though both my phone and laptop were on same Wi-Fi network they were on different subnet and hence couldn't see each other. Once this issue was resolved I could use GSConnect and it works like a charm. Thanks again for all your work! 

I am closing the issue now.

Regards,
Vaibhav
