### ISSUE TITLE
Lack of Gsconnect notification icon in Gnome panel

### ISSUE THREAD

**Issue by maczet** [andyholmes/gnome-shell-extension-gsconnect#752]
I have Ubuntu 19.10 and Gsconnect v30. Some time ago notification icon on GNOME disappeared. When I turn on Gsconnect from Ubuntu Software its works, my phone is connected. 
![Screenshot from 2020-01-21 09-14-34](https://user-images.githubusercontent.com/28823676/72789976-f6837e00-3c34-11ea-9af1-0b95ddf8efce.png)
Any idea how to restore notification button? I tried change between Panel and User Menu.

My log
```

GSConnect Version: 30
GSConnect Install: user
GJS: 15801
XDG_SESSION_TYPE: wayland
GDMSESSION: ubuntu-wayland
--------------------------------------------------------------------------------
-- Logs begin at Tue 2020-01-21 09:23:44 CET, end at Tue 2020-01-21 09:43:40 CET. --
sty 21 09:43:32 dbus-daemon[10000]: [session uid=1000 pid=10000] Activating service name='org.gnome.gedit' requested by ':1.180' (uid=1000 pid=12021 comm="gjs /home/maczet/.local/share/gnome-shell/extensio" label="unconfined")
sty 21 09:43:32 dbus-daemon[10000]: [session uid=1000 pid=10000] Successfully activated service 'org.gnome.gedit'
sty 21 09:43:40 gnome-shell[10063]: libinput error: client bug: timer event4 debounce short: offset negative (-1ms)
```

**Comment by andyholmes** [comment]
Hmm, that almost looks like the Shell extension got disabled somehow, since there isn't even a menu item. If you run this does it fix it?

```
$ gnome-extensions enable gsconnect@andyholmes.github.io 
```

The service can be running without the Shell extension, so it's possible it became disabled somehow.

**Comment by maczet** [comment]
Extensions were turned off in GNOME Tweaks.

**Comment by andyholmes** [comment]
Ah, sometimes that happens if an extension crashes the Shell, to prevent it from breaking login.
