### ISSUE TITLE
Alarm volume on phone set to zero when app disconnects / computer shutdowns

### ISSUE THREAD

**Issue by ricardoV94** [andyholmes/gnome-shell-extension-gsconnect#753]
**Describe the bug**

Alarm volume on phone always goes to zero when app disconnects / computer shutdowns.

**Steps To Reproduce:**

0. Alarm volume above 0
1. Connect to PC
2. Shutdown PC
3. Alarm volume is now set to 0

**Expected behavior**

This is an issue, because I have to always check the alarm volume after shutting down the PC

**Comment by andyholmes** [comment]
Probably fixed upstream in [2f4dcd14](https://invent.kde.org/kde/kdeconnect-android/commit/10f94781c33825db2560e674190f79b0d093e74f), but it's hard to tell if you don't fill out the version info :)

**Comment by ricardoV94** [comment]
Will check version!

**Comment by ricardoV94** [comment]
I updated KDE connect on the mobile and the issue seems to be gone. Thank you
