### ISSUE TITLE
Files menu inconsistent with rest of shell

### ISSUE THREAD

**Issue by danielhuang** [andyholmes/gnome-shell-extension-gsconnect#754]
**Describe the bug**

The "Files" button behaves in an inconsistent manner.

**Steps To Reproduce:**

1. Click on device icon in panel
2. Click on Files icon

**Expected behavior**

The mount menu appears with an animation, and clicking an option (e.g. "primary" or "Unmount") will dismiss the menu, similar to other items located on the panel.

**Support Log**

```
GSConnect Version: 31
GSConnect Install: user
GJS: 15804
XDG_SESSION_TYPE: x11
GDMSESSION: gnome-xorg
```

**System Details (please complete the following information):**

 - **GSConnect version:** 31
   - **Installed from:** GNOME Extensions website
 - **GNOME/Shell version:** 3.34.3
 - **Distro/Release:** Arch

**Additional Notes:**
I am using the Panel display mode.

**Comment by andyholmes** [comment]
Thanks for reporting, I'll have a look when I get the chance.
