### ISSUE TITLE
Messages dialog list don't show name that contains sanitized string

### ISSUE THREAD

**Issue by xsgb** [andyholmes/gnome-shell-extension-gsconnect#760]
**Describe the bug**

In my phone's address book, a name is: `Tim <3`, which get transformed to `Tim &lt;3`. This seems to cause it disappear in the conversations list on the left.

**Steps To Reproduce:**

1. Name a contact with the special char `<` 
2. Sychronize contacts and messages with gsconnect
3. Display the messages conversation with gsconnect

**Expected behavior**

Replace special chars again so they can be shown correctly in the discussion title and in the discussions list.

**Screenshots**
![image](https://user-images.githubusercontent.com/1431656/73696256-39852d00-46dc-11ea-8682-ffe2612aa557.png)

**Support Log**

```

GSConnect Version: 31
GSConnect Install: user
GJS: 15801
XDG_SESSION_TYPE: x11
GDMSESSION: gnome-xorg
--------------------------------------------------------------------------------
-- Logs begin at Sat 2020-02-01 17:06:57 CET, end at Mon 2020-02-03 23:33:04 CET. --
Feb 03 23:33:01 syncthing[967456]: [O262T] INFO: Joined relay relay://141.14.27.100:443
Feb 03 23:33:02 syncthing[967456]: [O262T] INFO: Dialer for quic://82.64.51.58:22000: unknown address scheme "quic"
Feb 03 23:33:02 syncthing[967456]: [O262T] INFO: Dialer for quic://[2a01:e0a:eb:29d0:ba27:ebff:fe61:3d2f]:22000: unknown address scheme "quic"
Feb 03 23:33:03 syncthing[967456]: [O262T] INFO: Dialer for quic://192.168.1.64:22000: unknown address scheme "quic"
Feb 03 23:33:03 syncthing[967456]: [O262T] INFO: Dialer for quic://194.182.119.137:22000: unknown address scheme "quic"
Feb 03 23:33:03 syncthing[967456]: [O262T] INFO: Dialer for quic://[fe80::3e39:ab6a:4753:69b7%25wlp1s0]:22000: unknown address scheme "quic"
Feb 03 23:33:03 syncthing[967456]: [O262T] INFO: Established secure connection to OVHN65Q-6UNTLWT-YXQKFQU-7CTU5PV-4AAAGCG-RBWUJRM-FULYRK2-VFB6YAW at 192.168.1.58:55724-82.64.51.58:22000/tcp-client/TLS1.2-TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
Feb 03 23:33:03 syncthing[967456]: [O262T] INFO: Device OVHN65Q-6UNTLWT-YXQKFQU-7CTU5PV-4AAAGCG-RBWUJRM-FULYRK2-VFB6YAW client is "syncthing v1.3.2" named "" at 192.168.1.58:55724-82.64.51.58:22000/tcp-client/TLS1.2-TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
Feb 03 23:33:03 syncthing[967456]: [O262T] INFO: Connection to OVHN65Q-6UNTLWT-YXQKFQU-7CTU5PV-4AAAGCG-RBWUJRM-FULYRK2-VFB6YAW at 192.168.1.58:55724-82.64.51.58:22000/tcp-client/TLS1.2-TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305 closed: reading length: EOF
Feb 03 23:33:04 syncthing[967456]: [O262T] INFO: Established secure connection to V4NITAI-52OBBXP-2BXLNKA-6WC4KHI-F4KNZOU-FU4LO7Y-HSDLI3S-CHQ3XAU at 192.168.1.58:46200-192.168.1.64:22000/tcp-client/TLS1.2-TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
Feb 03 23:33:04 syncthing[967456]: [O262T] INFO: Replacing old connection 192.168.1.58:41222-51.158.96.181:22067/relay-client/TLS1.2-TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305 with 192.168.1.58:46200-192.168.1.64:22000/tcp-client/TLS1.2-TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305 for V4NITAI-52OBBXP-2BXLNKA-6WC4KHI-F4KNZOU-FU4LO7Y-HSDLI3S-CHQ3XAU
Feb 03 23:33:04 syncthing[967456]: [O262T] INFO: Connection to V4NITAI-52OBBXP-2BXLNKA-6WC4KHI-F4KNZOU-FU4LO7Y-HSDLI3S-CHQ3XAU at 192.168.1.58:41222-51.158.96.181:22067/relay-client/TLS1.2-TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305 closed: replacing connection
Feb 03 23:33:04 syncthing[967456]: [O262T] INFO: Device V4NITAI-52OBBXP-2BXLNKA-6WC4KHI-F4KNZOU-FU4LO7Y-HSDLI3S-CHQ3XAU client is "syncthing v1.3.0" named "Pixel 3a" at 192.168.1.58:46200-192.168.1.64:22000/tcp-client/TLS1.2-TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
```

**System Details (please complete the following information):**

 - **GSConnect version:** 31
   - **Installed from:** GNOME Extensions Website
 - **GNOME/Shell version:** 3.34
 - **Distro/Release:** Debian Unstable

**GSConnect environment (if applicable):**

 - **Paired Device(s):** Pixel 3a with Lineage OS 16
 - **KDE Connect app version:** 1.13.7

**Comment by ferdnyc** [comment]
Hmmm. Another form of #562 rears its head? (That bug mutates like hantavirus!)

**Comment by andyholmes** [comment]
Thanks for reporting. Looks like just a few more cases of contact names not being sanitized before being used in Gtk. Good thing we're not a SQL-backed web app or we'd be in the news today :wink: 

Here's an [installable ZIP](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Installation#install-from-zip) with the fixes included, let me know if the error still happens:
[gsconnect@andyholmes.github.io.zip](https://github.com/andyholmes/gnome-shell-extension-gsconnect/files/4155351/gsconnect%40andyholmes.github.io.zip)

**Comment by xsgb** [comment]
The title on top still show `&lt;` instead of `<`. But it works perfectly now for the contact list on the left and seem to solve the sanitizing problem.

> Good thing we're not a SQL-backed web app or we'd be in the news today wink
I hope someone would have reported just in time before bad guys notice it.

Thanks for what you're doing for the community. Me and... Tim already love your work, he got gsconnect installed as well :)
