### ISSUE TITLE
Android to android messages not showing up

### ISSUE THREAD

**Issue by trippingbillies41** [andyholmes/gnome-shell-extension-gsconnect#763]
Messages from a specific contact do not appear on my desktop. I'll get the notification but when I go to reply, there is nothing. It only seems to be from my significant other who also has a Galaxy S10.

**Comment by trippingbillies41** [comment]
Update, another person who I haven't talked to in months just messaged me. The first 10 messages worked then they stopped appearing on my desktop.

**Comment by andyholmes** [comment]
Are these SMS, MMS or RCS messages? As far as I know, only SMS messages are well supported in the Android app.

**Comment by trippingbillies41** [comment]
What is an RCS message? As far as I know they are all regular text messages. I'm using the stock messages app.

**Comment by andyholmes** [comment]
[RCS messaging](https://en.wikipedia.org/wiki/Rich_Communication_Services) is a new messaging standard planned to replace SMS/MMS, rolling out on some carriers now.

Can you please fill out the following fields from the bug report template:

> **System Details (please complete the following information):**
> 
>  - **GSConnect version:** [e.g. 20, 24, ... (displayed in the GSConnect "About" window)]
>    - **Installed from:** [e.g. GNOME Extensions Website, GitHub, Package Manager, ...]
>  - **GNOME/Shell version:** [e.g. 3.30, 3.28, ...]
>  - **Distro/Release:** [e.g. Ubuntu 18.04, Fedora 29, Arch, ...]
> 
> **GSConnect environment (if applicable):**
> 
>  - **Paired Device(s):** [e.g. Galaxy Note 8, Pixel 2, Honor 9, ...]
>  - **KDE Connect app version:** [e.g. 1.12.7]
>  - **Plugin(s):** [if the issue only occurs when using certain plugin(s)]

And also follow the steps from [Generate a Support Log](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Help#generate-support-log). You can use the <kbd>+</kbd> button in the messaging window to force a message re-sync, while the dialog is open.

**Comment by trippingbillies41** [comment]
GSConnect version: 31
Installed from: GNOME Extensions Website
GNOME/Shell version: 3.34.1
Distro/Release: Ubuntu 19.10
GSConnect environment (if applicable):

Paired Device(s): Galaxt S10
KDE Connect app version: 1.13.7

**Comment by andyholmes** [comment]
> Clicking the [+] doesn't populate any of the missed messages.

That's to be expected if it didn't work the first time :)

I'm more interested in the [log that's generated](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Help#generate-support-log) when you press that button and whether there are any errors when GSConnect receives the message list, or if the Android app is simply not forwarding these messages.

99% of the time bugs are reported about the SMS plugin, it's either a phone manufacturer using the Android SMS sqlite database incorrectly, or a message type not well supported by the Android app yet (eg. MMS/RCS). A debug log from GSConnect during the period when messages are requested and received will confirm whether or not this is the case.

**Comment by trippingbillies41** [comment]
[gsconnectG1KSF0.txt](https://github.com/andyholmes/gnome-shell-extension-gsconnect/files/4189408/gsconnectG1KSF0.txt)

**Comment by andyholmes** [comment]
Sorry, but there is no request or response for SMS messages in that log. The wiki documentation I will link again for [Generating a Support Log](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Help#generate-support-log) explains how to do this:

1. Click *Generate Support Log*
2. Leave the Support Log dialog open
3. Press the <kbd>+</kbd> button in the *Messaging* window
4. Wait a reasonable amount of time for the phone to respond (eg. a few seconds)
5. Close the Support Log dialog
6. Review the log and remove any sensitive information before submitting

**Comment by trippingbillies41** [comment]
Sorry for the late response, I haven't been home. That is what I sent originally. I just tried again and there all of my contact and messages appear in the support log. Is it still diagnostic if I remove that data?

**Comment by trippingbillies41** [comment]
[gsconnect9QFXF0.txt](https://github.com/andyholmes/gnome-shell-extension-gsconnect/files/4201694/gsconnect9QFXF0.txt)

**Comment by andyholmes** [comment]
It's not necessary to post all the content, but the response from the phone will indicate if GSConnect is receiving the messages at all.

If the packets received from the phone do not include the messages that you are missing, then the error is not in GSConnect and you should file a bug upstream at [bugs.kde.org](https://bugs.kde.org/buglist.cgi?component=android-application&product=kdeconnect).

If the packets do include the messages, then there should be error messages indicating what is going wrong and if the packets are malformed. If there are MMS or RCS messages included, they may be missing information necessary to display them properly.

**Comment by trippingbillies41** [comment]
[GSconnect21620.txt](https://github.com/andyholmes/gnome-shell-extension-gsconnect/files/4211286/GSconnect21620.txt)

**Comment by andyholmes** [comment]
The only errors I see here are these:

```
Feb 16 19:14:26 gjs[2120]: Failed to set text 'Contacts AT&T Service' from markup due to error parsing markup: Error on line 1: Entity did not end with a semicolon; most likely you used an ampersand character without intending to start an entity — escape ampersand as &amp;
Feb 16 19:14:26 gjs[2120]: Failed to set text 'Contacts AT&T Service' from markup due to error parsing markup: Error on line 1: Entity did not end with a semicolon; most likely you used an ampersand character without intending to start an entity — escape ampersand as &amp;
```
Which should be fixed in a47a040 and will be released with v32. Other than that I just don't have enough information to help here.

**Comment by trippingbillies41** [comment]
[gsconnectNED2F0.txt](https://github.com/andyholmes/gnome-shell-extension-gsconnect/files/4222723/gsconnectNED2F0.txt)

What about this one?

**Comment by andyholmes** [comment]
No, that only shows three instances of the same error, likely fixed in a47a040.

**Comment by andyholmes** [comment]
Is this issue still valid?

**Comment by trippingbillies41** [comment]
Yes, messages from other Galaxy phones do not show up under the messaging screen on my desktop. Is there plan to support the advanced messaging type? Is there a way in android to disable that type so that this will function correctly?

**Comment by andyholmes** [comment]
GSConnect doesn't control what message types are supported, we just receive whatever the Android app sends us. If they can't be retrieved in Android they just won't be sent to the desktop.

If this is only happening with Galaxy-to-Galaxy messages, you should open a bug on [bugs.kde.org](https://bugs.kde.org/buglist.cgi?component=android-application&product=kdeconnect). Samsung is particularly notorious for breaking the SMS/MMS provider though, so this will probably require someone with such a phone digging into the Android app to figure out what's not working and why.

**Comment by trippingbillies41** [comment]
I will do that, thanks for your help.

**Comment by andyholmes** [comment]
Closing as upstream, who in turn should probably blame Samsung :smiling_imp:
