### ISSUE TITLE
Cannot copy URL to clipboard of connected device from Chrome address bar

### ISSUE THREAD

**Issue by drishit96** [andyholmes/gnome-shell-extension-gsconnect#769]
User should be able to copy URLs from chrome's address bar.

**Steps To Reproduce:**

1. Open Chrome browser
2. Go to any website and copy the URL from the address bar
3. URL doesn't get copied to the clipboard of the connected device

**Expected behavior**
Only URLs don't get copied from the address bar. If you put any other text, it gets copied without any issues.

**Support Log**
```

GSConnect Version: 28
GSConnect Install: user
GJS: 15205
XDG_SESSION_TYPE: x11
GDMSESSION: ubuntu
--------------------------------------------------------------------------------
-- Logs begin at Fri 2019-12-27 21:42:54 IST, end at Sat 2020-02-22 20:48:37 IST. --
Feb 22 20:48:08 gjs[6223]: GtkDialog mapped without a transient parent. This is discouraged.
Feb 22 20:48:10 org.gnome.Shell.Extensions.GSConnect[2064]: [/service/protocol/core.js:send:321]: AndroidZ: {
                                                              "id": 1582384690630,
                                                              "type": "kdeconnect.clipboard",
                                                              "body": {
                                                                "content": "github.com"
                                                              }
                                                            }
Feb 22 20:48:13 org.gnome.Shell.desktop[6040]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x3400084 (gsconnect.)
Feb 22 20:48:17 docky.desktop[2011]: Cairo.Surface is leaking, programmer is missing a call to Dispose
Feb 22 20:48:17 docky.desktop[2011]: Set MONO_CAIRO_DEBUG_DISPOSE to track allocation traces
Feb 22 20:48:37 gjs[6223]: GtkDialog mapped without a transient parent. This is discouraged.

```

**System Details (please complete the following information):**

 - **GSConnect version:** 28
   - **Installed from:** GNOME Extensions Website
 - **GNOME/Shell version:** 3.28.4
 - **Distro/Release:** Ubuntu 18.04

**GSConnect environment (if applicable):**

 - **KDE Connect app version:** 1.13.7

**Comment by andyholmes** [comment]
Sorry, I can't reproduce this myself, and your logs indicate that GSConnect is properly sending the clipboard packet. Check the plugins on the Android app for correct permissions.

Also note, we don't support GSConnect on versions of GNOME other that the current stable verison (currently `3.34`).
