### ISSUE TITLE
Not working on dev version of Ubuntu 20.04 (Gnome 3.35.91)

### ISSUE THREAD

**Issue by stdevPavelmc** [andyholmes/gnome-shell-extension-gsconnect#772]
**Describe the bug**

The extension does not work on Ubuntu 20.04 devel as today, it crash with the error: 

```
ERROR: Extension gsconnect@andyholmes.github.io: Error: Tried to construct an object without a GType; are you using GObject.registerClass() when inheriting from a GObject type?#012ServiceIndicator@/home/pavel/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/extension.js:88:9#012enable@/home/pavel/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/extension.js:476:24#012_callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:161:13#012loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:312:21#012_loadExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:545:13#012collectFromDatadirs@resource:///org/gnome/shell/misc/fileUtils.js:27:17#012_loadExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:520:9#012_enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:554:13#012_sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:585:13#012init@resource:///org/gnome/shell/ui/extensionSystem.js:55:9#012_initializeUI@resource:///org/gnome/shell/ui/main.js:245:5#012start@resource:///org/gnome/shell/ui/main.js:141:5#012@<main>:1:31
```

**Steps To Reproduce:**

1. Install Ubuntu 20.04 from the nightly builds, update and upgrade it
2. Install the extrension via https://extensions.gnome.org/ or local as described in the github repo 
3. Extension does not came up after the Gnome Shell restart
4. Check the logs to see and an error like the described above

**Expected behavior**

Working extension

**Screenshots**

NA

**Support Log**

Please generate a support log ([Instructions](../wiki/Help#generate-support-log)) and paste any messages related to this issue between the two ``` lines below.

```
Non working, can't generate the log
```

**System Details (please complete the following information):**

 - **GSConnect version:** v32-rc1 from gittub
   - **Installed from:** GNOME Extensions Website and GitHub (logs are for the most up to date code from github)
 - **GNOME/Shell version:** 3.35.91
 - **Distro/Release:** Ubuntu 20.04-dev (updated daily...)

**GSConnect environment (if applicable):**

Can pair it, when worked paired to a Samsung Galaxy J2 & Motorola 5, E5, E4, E4+

**Additional Notes:**

Can help with debug info and test, I think that next release of Ubuntu must have gsconnect support out of the box, it's not working now.

**Comment by stdevPavelmc** [comment]
This can be related to this one #750

**Comment by andyholmes** [comment]
Yes, this is the same error. Currently we don't support 3.36. Support for that will probably be in v33 after the formal release of GNOME 3.36.

**Comment by stdevPavelmc** [comment]
Ok, I see, thanks for the answer
 
> Yes, this is the same error. Currently we don't support 3.36. Support for that will probably be in v33 after the formal release of GNOME 3.36.
