### ISSUE TITLE
Scrolling Isn't Working.

### ISSUE THREAD

**Issue by wildcard-f8** [andyholmes/gnome-shell-extension-gsconnect#773]
When I used KDE Connect browsing the phones files didn't work but the remote input working fine, including scrolling and reverse scrolling. On GSConnect everything works fine except two-finger scrolling doesn't work. When I try to scroll up sometimes it shoots to the top but that's it. Most of the time it does nothing.

GSConnect Version: 28
GSConnect Install: user
GJS: 15205
XDG_SESSION_TYPE: x11
GDMSESSION: ubuntu
--------------------------------------------------------------------------------
-- Logs begin at Fri 2019-10-25 13:37:39 PST, end at Thu 2020-03-05 23:31:44 PST. --
Mar 05 23:31:13 gjs[7514]: GtkDialog mapped without a transient parent. This is discouraged.
Mar 05 23:31:26 gjs[4416]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Mar 05 23:31:26 gjs[4416]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Mar 05 23:31:26 gjs[4416]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Mar 05 23:31:26 gjs[4416]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Mar 05 23:31:26 gjs[4416]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Mar 05 23:31:26 gjs[4416]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Mar 05 23:31:26 gjs[4416]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Mar 05 23:31:26 gjs[4416]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Mar 05 23:31:26 gjs[4416]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Mar 05 23:31:26 gjs[4416]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Mar 05 23:31:26 gjs[4416]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Mar 05 23:31:26 gjs[4416]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Mar 05 23:31:26 gjs[4416]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Mar 05 23:31:26 gjs[4416]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Mar 05 23:31:26 gjs[4416]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Mar 05 23:31:26 gjs[4416]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Mar 05 23:31:26 gjs[4416]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Mar 05 23:31:26 gjs[4416]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Mar 05 23:31:26 gjs[4416]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Mar 05 23:31:26 gjs[4416]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Mar 05 23:31:26 gjs[4416]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Mar 05 23:31:26 gjs[4416]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Mar 05 23:31:26 gjs[4416]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Mar 05 23:31:26 gjs[4416]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Mar 05 23:31:26 gjs[4416]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Mar 05 23:31:26 gjs[4416]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Mar 05 23:31:44 gjs[7514]: GtkDialog mapped without a transient parent. This is discouraged.

**Comment by andyholmes** [comment]
Looks like that was a bug fixed in v29. Unfortunately we no longer support Ubuntu 18.04 LTS, so you'll have to fix this yourself if you want it to work:

https://github.com/andyholmes/gnome-shell-extension-gsconnect/blob/3050a7878a1cf35a6cf9b648b9253b74c7cc1967/src/service/components/atspi.js#L129-L135

On line `#132` you should change `>` to `<`. You can find that in:

```
~/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/components/atspi.js
```

You can restart the service after with:

```
touch ~/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js
```

**Comment by wildcard-f8** [comment]
Thanks! It's working perfectly now.
