### ISSUE TITLE
Remove template literals from files with translations

### ISSUE THREAD

**Issue by andyholmes** [andyholmes/gnome-shell-extension-gsconnect#775]
Since it seems like parsing template literals in xgettext is not going to be fixed anytime soon, I'll have to follow gnome-shell and rip out all the template literals in files listed in `POTFILES` :disappointed: 

See: https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/1014

**Comment by ferdnyc** [comment]
_\_UGGH.\__

Time to switch to... 
* [QTranslator](https://doc.qt.io/qt-5/qtranslator.html)? (Not very JavaScript.)
* [Format.js](https://formatjs.io/)?
* [i18next](https://www.i18next.com/)?
* [banana-i18n](https://github.com/wikimedia/banana-i18n)? (the jQuery-free jQuery.i18n)

...Most of those look kind of _\_UGGGH.\__ in their own right, too. Like, from the banana-i18n docs:

> #### Placeholders
> Messages take parameters. They are represented by $1, $2, $3, … in the message texts, and replaced at run time. Typical parameter values are numbers (Example: "Delete 3 versions?"), or user names (Example: "Page last edited by $1"), page names, links, and so on, or sometimes other messages.
> ```js
> const message = "Welcome, $1";
> banana.i18n(message, 'Alice'); // This gives "Welcome, Alice"
> ```
> 
> #### Plurals
> To make the syntax of sentence correct, plural forms are required. jquery.i18n support plural forms in the message using the syntax `{{PLURAL:$1|pluralform1|pluralform2|...}}`
> 
> For example:
> 
> ```js
> const message = "Found $1 {{PLURAL:$1|result|results}}";
> banana.i18n(message, 1); // This gives "Found 1 result"
> banana.i18n(message, 4); // This gives "Found 4 results"
> ```
> Note that `{{PLURAL:...}}` is not case sensitive. It can be `{{plural:...}}` too.
> 
> In case of English, there are only 2 plural forms, but many languages use more than 2 plural forms. All the plural forms can be given in the above syntax, separated by pipe(|). The number of plural forms for each language is defined in CLDR. You need to provide all those plural forms for a language.

**Comment by andyholmes** [comment]
Yeah, I think it'll be even more work to migrate from gettext entirely. The `String.prototype.format()` route isn't so bad, it's just that template literals are so much easier.

There's actually been an upstream [fix for this](https://savannah.gnu.org/bugs/?50920) since [July 2019](https://git.savannah.gnu.org/gitweb/?p=gettext.git;a=commitdiff;h=4785289e45f4467bd484ae4249c58ad730966d1b), there just hasn't been a release of gettext since, afaik.

**Comment by andyholmes** [comment]
I'm going to close this one. Short of writing a xgettext replacement parser, I think it's easier to just manually add the strings to the POT file for now.
