### ISSUE TITLE
Wiko View 2: no sms history

### ISSUE THREAD

**Issue by legluondunet** [andyholmes/gnome-shell-extension-gsconnect#776]
Hello,
I can not read my SMS history on the computer (Ubuntu 19.10 with last gnome-shell-extension-gsconnect version from official extension site.

**Comment by andyholmes** [comment]
See [SMS Messages Don't Sync](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Help#sms-messages-dont-sync).

duplicate of #320
