### ISSUE TITLE
Can't install from Git

### ISSUE THREAD

**Issue by mavit** [andyholmes/gnome-shell-extension-gsconnect#78]
When I try to follow the [installation instructions for Git](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Installation#building-from-git), I get the following error:

```
JS ERROR: ImportError: No JS module 'METADATA' found in search path
Daemon<._getIdentityPacket@/home/mavit/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:354:1
wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
Daemon<.vfunc_startup@/home/mavit/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:808:25
wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
Daemon<._init@/home/mavit/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:213:9
wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
@/home/mavit/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:892:2
```

This is on Fedora 27.

**Comment by andyholmes** [comment]
Sorry, I can't seem to reproduce this. Can you confirm your `gnome-shell` and `gjs` versions?

**Comment by mavit** [comment]
I’ve tracked this down.  I’d accidentally run `meson gnome-shell-extension-gsconnect/ build` in the `src/service/plugins` directory, which had created two empty directories that I’d overlooked because `git status` doesn’t mention them.  For whatever reason, copying these empty directories over to the installation causes it to fail.

**Comment by andyholmes** [comment]
Okay, good because I was scratching my head pretty hard over this one :)
