### ISSUE TITLE
Url send with web extension only opens on phone when app is in foreground

### ISSUE THREAD

**Issue by bestrandomnameever** [andyholmes/gnome-shell-extension-gsconnect#790]
Using the GSConnect web extension (both Chrome and Firefox) to send a URL with the "Open in browser" method only opens the URL on the phone when the KDE Connect app is active in the foreground. When the app is not open, nothing happens.

**Support Log**

The log shows no consistent message when sending an URL, regardless of that the app is open or not (and thus regardless of success). The log is either empty or sometimes contains the following warning.

```
org.gnome.tweaks.desktop[11353]: Warning: 'sandbox' is not in the list of known options, but still passed to Electron/Chromium.
```

**System Details**

 - **GSConnect version:** 33
   - **Installed from:** GNOME Extensions Website
 - **GNOME/Shell version:** 3.34.4
 - **Distro/Release:** Manjaro 

**GSConnect environment (if applicable):**

 - **Paired Device(s):** Poco F1 (Pixel Experience Android 10 ROM)
 - **KDE Connect app version:** 1.13.7

**Comment by andyholmes** [comment]
You'll have to open a bug upstream in kdeconnect-android for this ([link](https://bugs.kde.org/buglist.cgi?component=android-application&product=kdeconnect)).

Once the URL is send to the remote device, it's up to that device to do something useful with it. This is probably another case of Android 10 restricting background apps.

**Comment by bestrandomnameever** [comment]
I have created a bug report there. Should I close this issue or wait till it is resolved there and update the resolution here?

**Comment by andyholmes** [comment]
We can leave it for now. It's an upstream bug but people can find it this way :)

**Comment by andyholmes** [comment]
Going to close this one; I don't know if we'll be able to fix this in the Android app, but it will still be searchable here anyways.
