### ISSUE TITLE
phone doesn't have media player notify anymore

### ISSUE THREAD

**Issue by Sherlock-Holo** [andyholmes/gnome-shell-extension-gsconnect#792]
**Describe the bug**

**Steps To Reproduce:**

1. Update gsconnect to 34 and gnome to 3.36.0
2. Use netease cloud music in linux
3. phone use kde connect(1.13.7) to connect to gsconnect
4. no notify about cloud music player, only can enter kde connect to pause music, but without any music info

**Expected behavior**

phone has a notify about cloud music player so I can switch music or pause it.

**Support Log**

log: https://fars.ee/mAkE/ I delete some log about my SMS

**System Details (please complete the following information):**

 - **GSConnect version: 34
   - **Installed from: arch [AUR](https://aur.archlinux.org/packages/gnome-shell-extension-gsconnect/)
 - **GNOME/Shell version: 3.36.0
 - **Distro/Release: Arch

**GSConnect environment (if applicable):**

 - **Paired Device(s): Pixel 2 XL android 10
 - **KDE Connect app version: 1.13.7
 - **Plugin(s): enable all defaut plugins

**Additional Notes:**

before update to gnome 3.36.0 and gsconnect 34, the music player notify works well

**Comment by andyholmes** [comment]
Sorry, this should be fixed in 696b83a, I just haven't done a release yet :)

**Comment by Sherlock-Holo** [comment]
great! I am looking forward for the next release

**Comment by andyholmes** [comment]
v35 is up now with the fix :)
