### ISSUE TITLE
Doesn't work on GNOME 3.36

### ISSUE THREAD

**Issue by AtakanErmis** [andyholmes/gnome-shell-extension-gsconnect#794]
**Doesn't work on GNOME 3.36**

on/off switch greyed out from GNOME Extensions app or GNOME Tweaks app. Can't turn it on in any way.

**Screenshots**

![image](https://user-images.githubusercontent.com/16894959/77428785-b7ff7080-6de9-11ea-8847-1349e2d86103.png)

**System Details (please complete the following information):**

 - **GSConnect version:** 35
   - **Installed from:** GNOME Extensions Website
 - **GNOME/Shell version:** 3.36
 - **Distro/Release:** Manjaro Linux

**Comment by jsonMartin** [comment]
@AtakanErmis I'm running into the same issue, did you fix this?

**Comment by AtakanErmis** [comment]
It solved when I reboot machine. You can try reinstalling if it's not working.
