### ISSUE TITLE
Error: Tried to construct an object without a GType; are you using GObject.registerClass() when inheriting from a GObject type?

### ISSUE THREAD

**Issue by ChronosX88** [andyholmes/gnome-shell-extension-gsconnect#795]
**Describe the bug**

Extension don't want to start due to unhandled exception

**Steps To Reproduce:**

1. Install extension of GNOME Shell Extensions Website
2. Try to enable extension.
3. Extension don't start because it have unhandled exception

**Expected behavior**

The extension starts normally.

**Screenshots**: no.

**Support Log**

```
gnome-shell[1576]: JS ERROR: Extension gsconnect@andyholmes.github.io: Error: Tried to construct an object without a GType; are you using GObject.registerClass() when inheriting from a GObject type?
                                                  ServiceIndicator@/home/chronosx/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/extension.js:88:9
                                                  enable@/home/chronosx/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/extension.js:476:24
                                                  _callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:160:32
                                                  loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:311:26
                                                  callback@resource:///org/gnome/shell/ui/extensionDownloader.js:204:39
                                                  gotExtensionZipFile/<@resource:///org/gnome/shell/ui/extensionDownloader.js:97:13
```

**System Details (please complete the following information):**

 - **GSConnect version:** 35
   - **Installed from:** GNOME Extensions Website
 - **GNOME/Shell version:** 3.36.0
 - **Distro/Release:** Manjaro Linux 19.0.2

**GSConnect environment (if applicable):**

 - **Paired Device(s):** LG M320
 - **KDE Connect app version:** 1.13.7
 - **Plugin(s):** no.

**Additional Notes:** no.

**Comment by ChronosX88** [comment]
By the way, interesting thing: line 88 is empty.

**Comment by andyholmes** [comment]
Seems like something must have gone wrong during install. That line is pointing here:

https://github.com/andyholmes/gnome-shell-extension-gsconnect/blob/ec38bf073f87aa345e04439240a381e9c7f3338f/src/extension.js#L85-L89

From <= v33. So either you have another, older version installed or something went really wrong during download.

**Comment by ChronosX88** [comment]
@andyholmes it's very interesting, but I saw local file and there is newer version of `extensions.js` file and line 88 is empty as well.

**Comment by andyholmes** [comment]
Probably you're running Wayland, or maybe the Shell didn't properly disable the extension before updating. You probably just need to reload the shell.

**Comment by andyholmes** [comment]
Is this issue still valid, or was it resolved?

**Comment by ChronosX88** [comment]
Yes, issue is resolved for me, we can close this.

**Comment by Konarkm68** [comment]
I am unavle to solve the same error on uvuntu 20.4. Can you please help me??

**Comment by ShahrukhUXfantasy** [comment]
I have the same issue   "Error: Tried to construct an object without a GType;"
How can I resolve it?
