### ISSUE TITLE
command not works

### ISSUE THREAD

**Issue by Sherlock-Holo** [andyholmes/gnome-shell-extension-gsconnect#796]
**Describe the bug**

kde connect app can see commands, when click them, nothing happened

**Steps To Reproduce:**

1. register command like `xdg-screensaver lock` in gsconnect
2. click a command in kde connect app

**Expected behavior**

gnome will be locked

**Support Log**

[log](https://fars.ee/F7-h/)

**System Details (please complete the following information):**

 - **GSConnect version:** 35
   - **Installed from:** arch AUR with custom modify: update version to 35
 - **GNOME/Shell version:** 3.36.0
 - **Distro/Release:** Arch

**GSConnect environment (if applicable):**

 - **Paired Device(s):** Pixel 2 XL
 - **KDE Connect app version:** 1.13.7
 - **Plugin(s):** no custom plugins

**Comment by andyholmes** [comment]
Thanks for reporting, should be fixed in 006e3a02.

[gsconnect@andyholmes.github.io.zip](https://github.com/andyholmes/gnome-shell-extension-gsconnect/files/4382847/gsconnect%40andyholmes.github.io.zip)
