### ISSUE TITLE
meson 0.49 required but meson 0.45 available

### ISSUE THREAD

**Issue by SmilyLynx** [andyholmes/gnome-shell-extension-gsconnect#798]
**Describe the bug**

I tried to install GSConnect but get the following warning about meson version :

`meson.build:1:0: ERROR: Meson version is 0.45.1 but project requires >= 0.49.0.`

**Steps To Reproduce:**

1. Followed installation process "Install from Git"
2. First 2 steps are OK
3. input `meson _build` in CLI and get the warning above
4. Cannot finish installation

**Expected behavior**

I expected no error to finish installation```

**System Details (please complete the following information):**
   - **Installed from: GitHub
 - **GNOME/Shell version:Version: 1:3.22+9
 - **Distro/Release: Mint 19.3

**Additional Notes:**

this is my first report so, sorry if there is important informations missing

**Comment by ferdnyc** [comment]
Like it says, your meson `0.45.1` is too old. You need to install a newer version of `meson`, at least `0.49`.

However, that's only if you actually need to install from source, and you probably don't want to do that. The source tree currently supports only GNOME 3.36 and up, so it wouldn't be compatible with your GNOME 3.22 system anyway. Most users can just install from the GNOME extensions site.

...Wait, GNOME 3.22!?! Is that correct? If it is, then your entire system is so old that it's completely unsupported anyway, the current GNOME release is 3.36 ­— 3.22 was released in 2016.

However, you should still be able to install a very old version of GSConnect that's compatible with your system from extensions.gnome.org.

See: https://extensions.gnome.org/extension/1319/gsconnect/

**Comment by SmilyLynx** [comment]
Ok, thanks for your quicky and useful answer
