### ISSUE TITLE
Help with installation - tried installing from zip

### ISSUE THREAD

**Issue by magick93** [andyholmes/gnome-shell-extension-gsconnect#802]
**Describe the bug**

After downloading the zip, and following the install from zip instructions, nothing happens.

**Steps To Reproduce:**

1. `mkdir -p ~/.local/share/gnome-shell/extensions`
1. `rm -rf ~/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io`
1. `unzip -o gsconnect@andyholmes.github.io.zip -d ~/.local/share/gnome-shell/extensions`/gsconnect@andyholmes.github.io`
1. log out and login
1. try restarting
1. Try installing `python-nautilus` and  `gir1.2-nautilus-3.0`. Restart again.

**Expected behavior**

Not entirely sure, but I expected to have some kind of UI, and/or nautilus integration. 

**System Details (please complete the following information):**

 - **GSConnect version:** unknown, cant get the UI to show
   - **Installed from:** github, downloaded zip
 - **GNOME/Shell version:** [e.g. 3.30, 3.28, ...]
 - **Distro/Release:** Ubuntu 18.04.4

**Comment by andyholmes** [comment]
If you're still running Ubuntu 18.04 then the latest version available is [v28](https://github.com/andyholmes/gnome-shell-extension-gsconnect/releases/tag/v28). Any newer version won't work for you, as GNOME 3.28 is no longer supported.

**Comment by magick93** [comment]
HI @andyholmes 

Thanks for the prompt response, its really appreciated.

I tried again with v28, and am getting the same results.

Would you recommend I wait until Ubuntu 20 is released?

**Comment by andyholmes** [comment]
It should still work (somewhat). You probably just need to restart gnome-shell or ensure the directory is deleted. You'll obviously have to enable the extension for it to work, also.

**Comment by magick93** [comment]
Thanks

> You probably just need to restart gnome-shell or ensure the directory is deleted. You'll obviously have to enable the extension for it to work, also.

Yes, I did delete the directory, and did a system restart.

**Comment by andyholmes** [comment]
And you enabled the extension? Because just installing the files won't do that.

The easiest way to do this is just to install it from extensions.gnome.org.

**Comment by magick93** [comment]
Im not sure what you mean by "enabled the extension". I'm following the instructions, eg, download, delete existing, extract into correct folder, log out/in, restart.

**Comment by magick93** [comment]
Using extensions.gnome.org was indeed the easier way.

I also needed to ` sudo apt install chrome-gnome-shell `, which was a bit confusing as I'm using firefox. 

Thanks for your help Andy.
