### ISSUE TITLE
Send sms feature not showing

### ISSUE THREAD

**Issue by Navidos1** [andyholmes/gnome-shell-extension-gsconnect#810]
Hi Andy

Thanks a lot for this contribution. I have ubuntu 18.04 LTS and gnome 3.28.4. I have installed the KDE Connect 1.3.3 from ubuntu software gui. Everything works fine with my Huawei P9 phone, except 2 things. I that i dont see the "Send sms" feature in the window, and i when clicking on "Browse device", then nothing happens. 

I do have given permission to my storage from the Kde Connect from google play. Also the plugin "Remote filesystem browser" is enabled. 

Here is 2 screenshots from imgbb
https://ibb.co/stLyr5n
https://ibb.co/M1FkDFJ

_I read the following from your site:

**"Latest News
REMINDER: GSConnect only supports the current stable version of GNOME. There will be no further releases supporting older versions and thus we will not be accepting bug reports for these versions.

2020-03-27 - v36 has been reviewed and is available on extensions.gnome.org_"**

So is this issue related to that i have older gnome?

Oh besides..i see notitifications with the sms when i receive sms in ubuntu...the messages appear for 5 seconds before they disappear though.

I use Arc menu by the way.

**Comment by andyholmes** [comment]
> GSConnect is a complete implementation of KDE Connect especially for GNOME Shell with Nautilus, Chrome and Firefox integration. **It does not rely on the KDE Connect desktop application and will not work with it installed.**

Your main issue is that you're trying to run two implementations of KDE Connect. Your screenshots are of KDE Connect not GSConnect, so I can't give you help with that at all.

GSConnect only supports the latest version of GNOME, which means there will be no further releases or bug fixes for older versions of GNOME.

**Comment by Navidos1** [comment]
Okey. So i have uninstalled those two KDE connect applications that i had. And will install GSConnect.
But on 18.04LTS it says i have the newest Gnome version which is 3.28.4. While yours is 3.34 (if i dont remember wrong). 

I have read that it is not recommended to update gnome on 18.04LTS ?
https://askubuntu.com/questions/1179421/why-can-i-not-update-gnome-to-version-3-34

What are my options? To update to ubuntu 20.04 beta ?

Or to install  gsconnect which supports an older version for gnome (i know there is no support for that if i do that) from here:

https://extensions.gnome.org/extension/1319/gsconnect/

If so i dont neither see 3.28.4. Only 3.28.12.

May be i need some commercial help for this.

**Comment by andyholmes** [comment]
> I have read that it is not recommended to update gnome on 18.04LTS ?

Updating GNOME on Ubuntu 18.04 is not an option. so your choices are to upgrade Ubuntu or just install the version of GSConnect that supports GNOME 3.28.

> Or to install gsconnect which supports an older version for gnome (i know there is no support for that if i do that) from here:

Yes, that's the recommended option. GSconnect never supported point releases, so the only option for GNOME 3.28 is **v28**.

**Comment by Navidos1** [comment]
Just wanted to say you can close this thead. I managed to install it from ubuntu software gui. Thanks for your help also.
