### ISSUE TITLE
Mount not working with galaxy note 9

### ISSUE THREAD

**Issue by sunilsunny087** [andyholmes/gnome-shell-extension-gsconnect#812]
Below is the log i get when trying to mount, i am not sure what the issue is:- 
GSConnect Version: 36
GSConnect Install: user
GJS: 16401
XDG_SESSION_TYPE: x11
GDMSESSION: gnome
--------------------------------------------------------------------------------
-- Logs begin at Tue 2020-04-07 16:36:20 EDT, end at Tue 2020-04-07 17:34:12 EDT. --
Apr 07 17:34:09 gnome-shell[1452]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x2e00010
Apr 07 17:34:12 systemd[1]: systemd-hostnamed.service: Succeeded.
Apr 07 17:34:12 audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj==unconfined msg='unit=systemd-hostnamed comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Apr 07 17:34:12 kernel: audit: type=1131 audit(1586295252.648:138): pid=1 uid=0 auid=4294967295 ses=4294967295 subj==unconfined msg='unit=systemd-hostnamed comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'

**Comment by andyholmes** [comment]
Sorry, there's nothing here indicating a mount was attempted or any error caused by it. You'll have to generate a log by following the [instructions in the Wiki](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Help#generate-support-log).

**Comment by sunilsunny087** [comment]
Sorry about that, here is the log:- 

GSConnect Version: 36
GSConnect Install: user
GJS: 16401
XDG_SESSION_TYPE: x11
GDMSESSION: gnome
--------------------------------------------------------------------------------
-- Logs begin at Tue 2020-04-07 16:36:20 EDT, end at Tue 2020-04-07 21:19:13 EDT. --
Apr 07 21:18:45 org.gnome.Shell.Extensions.GSConnect[4109]: [/service/protocol/core.js:send:344]: Galaxy Note9: {
                                                              "id": 1586308725698,
                                                              "type": "kdeconnect.sftp.request",
                                                              "body": {
                                                                "startBrowsing": true
                                                              }
                                                            }
Apr 07 21:18:45 org.gnome.Shell.Extensions.GSConnect[4109]: [/service/protocol/core.js:receive/<:298]: Galaxy Note9: {
                                                              "id": 1586308725944,
                                                              "type": "kdeconnect.sftp",
                                                              "body": {
                                                                "ip": "192.168.1.8",
                                                                "port": 1739,
                                                                "user": "kdeconnect",
                                                                "password": "ck8JxIgnR1DIKweikX3lEJiDUiOn",
                                                                "path": "/",
                                                                "multiPaths": [
                                                                  "/Note 9"
                                                                ],
                                                                "pathNames": [
                                                                  "Note 9"
                                                                ]
                                                              }
                                                            }
Apr 07 21:19:13 systemd[1]: flatpak-system-helper.service: Succeeded.
Apr 07 21:19:13 audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj==unconfined msg='unit=flatpak-system-helper comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Apr 07 21:19:13 kernel: audit: type=1131 audit(1586308753.924:184): pid=1 uid=0 auid=4294967295 ses=4294967295 subj==unconfined msg='unit=flatpak-system-helper comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'

**Comment by andyholmes** [comment]
Hmm, doesn't look like there are any errors here from GSConnect or GVfs. Do you happen to be using Arch or Manjaro? This sounds like a similar issue #801. 

If not, you may have to debug GVfs to get a better idea what's happening:

```sh
$ pkill gvfs; pkill nautilus
$ GVFS_DEBUG=1 $(find /usr/lib* -name gvfsd 2>/dev/null) --replace
```
Once that's running in a terminal, try to mount the device and you should see messages like this *or* some error indicating the problem:

```
sftp: Added new job source 0x560ae67a3080 (GVfsBackendSftp)
sftp: Queued new job 0x560ae6784730 (GVfsJobMount)
sftp: spawn_ssh: /usr/bin/ssh -oForwardX11 no -oForwardAgent no -oPermitLocalCommand no -oClearAllForwardings yes -oProtocol 2 -oNoHostAuthenticationForLocalhost yes -p 1755 -s 192.168.1.68 sftp 
sftp: handle_login #1 initial_connection = 1 - user: (null), host: 192.168.1.68, port: 1755
sftp: handle_login #1 - password_save: 0
sftp: handle_login #1 - ret_val: 1
sftp: spawn_ssh: /usr/bin/ssh -oForwardX11 no -oForwardAgent no -oPermitLocalCommand no -oClearAllForwardings yes -oProtocol 2 -oNoHostAuthenticationForLocalhost yes -p 1755 -s 192.168.1.68 sftp 
sftp: handle_login #2 initial_connection = 0 - user: (null), host: 192.168.1.68, port: 1755
sftp: handle_login #2 - ret_val: 1
sftp: send_reply(0x560ae6784730), failed=0 ()
```

**Comment by sunilsunny087** [comment]
yes, i am using Manjaro

**Comment by andyholmes** [comment]
It seems like this is a bug in Manjaro's gvfs packaging. I'd recommend you open a bug with Manjaro to see if they know anything about this.

**Comment by sunilsunny087** [comment]
Thanks will do that..
