### ISSUE TITLE
(gjs:8359): Gjs-CRITICAL 

### ISSUE THREAD

**Issue by vadakkodan** [andyholmes/gnome-shell-extension-gsconnect#815]
vadakkodan@VADAKKODANZ:~/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service$ ./daemon.js --help

(gjs:8359): Gjs-CRITICAL **: 14:19:19.894: JS ERROR: SyntaxError: JSON.parse: unexpected character at line 1 column 2 of the JSON data @ /home/vadakkodan/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/_gsconnect.js:34
Script ./daemon.js threw an exception

I don't know much.

**Comment by vadakkodan** [comment]
SyntaxError: JSON.parse: unexpected character at line 1 column 2 of the JSON data

Stack trace:
  gsconnect.metadata<@/home/vadakkodan/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/_gsconnect.js:34:12
  @/home/vadakkodan/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/_gsconnect.js:31:22
  @/home/vadakkodan/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/prefs.js:9:1
  _getExtensionPrefsModule@resource:///org/gnome/shell/extensionPrefs/main.js:75:13
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  _selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:90:31
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  _onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:243:17
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  main@resource:///org/gnome/shell/extensionPrefs/main.js:397:5
  @<main>:1:43

**Comment by andyholmes** [comment]
Sounds like you're trying to use a version of GSConect not supported by your desktop. You''ll have to fill out the issue information for me to say for certain.

---

**System Details (please complete the following information):**

 - **GSConnect version:** [e.g. 35, 36, ... (displayed in the GSConnect "About" window)]
   - **Installed from:** [e.g. GNOME Extensions Website, GitHub, Package Manager, ...]
 - **GNOME/Shell version:** [e.g. 3.36, ...]
 - **Distro/Release:** [e.g. Ubuntu 18.04, Fedora 29, Arch, ...]

**GSConnect environment (if applicable):**

 - **Paired Device(s):** [e.g. Galaxy Note 8, Pixel 2, Honor 9, ...]
 - **KDE Connect app version:** [e.g. 1.12.7]
 - **Plugin(s):** [if the issue only occurs when using certain plugin(s)]

**Additional Notes:**

Add any addtional information about the problem or your system.

**Comment by vadakkodan** [comment]
Hi Ansyholmes,

I'm sorry, I was desperate. So I tried to install the latest version of GSConnect in my incompatible GNOME 3.28.4 shell.
I'm not sure whether any support is available for **GNOME 3.28.4** or not, if yes please let me know.

This time I removed the whole GSConnect using the commands you've given in the page.
I reinstalled through **GNOME Extension**, now the problem is it is not showing my devices. 

Log Details:
 
**GSConnect Version:** 28
**GSConnect Install:** user
**GJS:** 15205
**XDG_SESSION_TYPE:** x11
**GDMSESSION:** ubuntu
--------------------------------------------------------------------------------
-- Logs begin at Sun 2020-03-08 22:00:31 IST, end at Tue 2020-04-14 14:17:02 IST. --
Apr 14 14:17:00 gjs[11807]: GtkDialog mapped without a transient parent. This is discouraged.
Apr 14 14:17:01 CRON[11949]: pam_unix(cron:session): session opened for user root by (uid=0)
Apr 14 14:17:01 CRON[11950]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Apr 14 14:17:02 CRON[11949]: pam_unix(cron:session): session closed for user root
Apr 14 14:17:02 org.gnome.Shell.Extensions.GSConnect[11621]: [/service/protocol/lan.js:broadcast:385]: "Broadcasting to LAN"
-------------------------------------------------------------------------------------------------------------------------------------
**GSConnect environment (if applicable):**

Tried to connect **Redmi Note 4:**  & **Samsung Galaxy Grand Duos** : KDE Connect v1.13.6.

I tried to ping those android devices through terminal. I'm able to ping. Firewall status is inactive. These two android devices are able to connect each other in the same network, same router.

**Comment by andyholmes** [comment]
It doesn't look like there are any errors in GSConnect. All I can recommend is that you re-check your firewall and router to see that they allow UDP broadcasts.

You can also try using the *Connect to...* dialog in GSConnect or *Add devices by IP* in the Android app.

**Comment by vadakkodan** [comment]
Upgraded to Ubuntu 20.04 LTS, GNOME 3.36.2. Able to connect to my android devices. Smooth and awesome! Thanks for the Support!
