### ISSUE TITLE
Error at extension loading

### ISSUE THREAD

**Issue by wargreen** [andyholmes/gnome-shell-extension-gsconnect#817]
**Describe the bug**
When install the last version from extensions.gnome.org, I got an Error button, and this in the logs :
```Apr 16 03:11:22 fetide gnome-shell[1762]: JS ERROR: Extension gsconnect@andyholmes.github.io: Error: Tried to construct an object without a GType; are you using GObject.registerClass() when inheriting from a GObject type?#012ServiceIndicator@/home/wargreen/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/extension.js:88:9#012enable@/home/wargreen/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/extension.js:476:24#012_callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:165:32#012loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:335:26#012callback@resource:///org/gnome/shell/ui/extensionDownloader.js:220:39#012gotExtensionZipFile/<@resource:///org/gnome/shell/ui/extensionDownloader.js:106:13```

**Steps To Reproduce:**

Go to the gnome extension webpage
Install the last version of GsConnect

**System Details (please complete the following information):**

 - **GSConnect version:** 36
   - **Installed from:** GNOME Extensions Website
 - **GNOME/Shell version:** 3.36.1-5
 - **Distro/Release:** Debian SID

**GSConnect environment (if applicable):**

 - **Paired Device(s):** Samsung GT-I9195
 - **KDE Connect app version:** 1.13.7

**Comment by andyholmes** [comment]
You'll have to restart gnome-shell for the extension to load.

For the full story, see upstream:

* [gnome-shell #2582](https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/2582)
* [chrome-gnome-shell #19](https://gitlab.gnome.org/GNOME/chrome-gnome-shell/-/issues/19)
* [extensions-web #109](https://gitlab.gnome.org/Infrastructure/extensions-web/-/issues/109)

**Comment by wargreen** [comment]
Ok, disconnect-reconnect work perfectly !
Thank you, sorry for the noise.

**Comment by andyholmes** [comment]
No problem, we just have to fix extensions.gnome.org so it stops confusing people :slightly_smiling_face:
