### ISSUE TITLE
[Solved] Mount not working: Gio.IOErrorEnum: Connection failed

### ISSUE THREAD

**Issue by mikail0** [andyholmes/gnome-shell-extension-gsconnect#818]
- **GSConnect version:** 37
   - **Installed from:** GNOME Extensions Website
- **GNOME/Shell version:** 3.36
 - **Distro/Release:** Arch

**GSConnect environment (if applicable):**

 - **Paired Device(s):** Galaxy S7 Edge
 - **KDE Connect app version:** 1.13.7

**Additional Notes:**

When I press "Mount" on my laptop, nothing happens.
I have set a location in the kde app.

Support log gives me this error:

`gjs[17503): JS ERROR: Galaxy S7 Edge: Gio.IOErrorEnum: Connection failed
_mount/</<@/home/user/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/sftp.js:185:38
@home/user/.local/share/gnome-shell/gnome-extensions/gsconnect@andyholmes.github.io/service/daemon.js:1125:17`

Thank you.

**Comment by andyholmes** [comment]
Probably the key exchange bug from #816, should be fixed when the Android app is updated.

**Comment by mikail0** [comment]
Yes, it works now with the App from the Google Playstore.
The App in the F-Droid Appstore is not up to date.

**Comment by Agarwal-Nikhil** [comment]
@andyholmes  Could you please update fdroid repository?

**Comment by andyholmes** [comment]
I'm not associated with F-Droid, so I don't control their repos:

https://gitlab.com/fdroid/fdroiddata/-/issues/2020
