### ISSUE TITLE
[idea]Share Phone Screen On Desktop

### ISSUE THREAD

**Issue by Mark24Code** [andyholmes/gnome-shell-extension-gsconnect#824]
Just like Huawei devices, then we can control phone on desktop just like use phone directly:

![share_screen](https://user-images.githubusercontent.com/7592004/79992677-69c3b700-84e6-11ea-92f6-20a3e8afd589.jpg)

**Comment by andyholmes** [comment]
There is an upstream request for this [here](https://bugs.kde.org/show_bug.cgi?id=413774) (and probably elsewhere.

This has to be implemented in the protocol before we can do anything in GSConnect:

> GSConnect works in concert with the [KDE Connect][1] app on paired Android devices. Communication between GSConnect and the device is controlled by **KDE Connect**, _not_ GSConnect.
> 
> Any request that would require features not supported in KDE Connect, or would require GSConnect to deviate from the KDE Connect protocols, cannot be implemented. Any such requests should be made to the KDE Connect project. The requested functionality can only be implemented in GSConnect after support is added to KDE Connect.
> 
> [1]: (https://community.kde.org/KDEConnect)
