### ISSUE TITLE
GLib.SpawnError Failed to execute child process Permission denied

### ISSUE THREAD

**Issue by fhteagle** [andyholmes/gnome-shell-extension-gsconnect#825]
New Arch install today, gnome shell 3.36.1 using wayland, extension version 37 downloaded from gnome extensions website. I had tried to install both versions from aur via yay, but both failed to build, but that is a different bug. 

Anyway, the extension shows up in the Installed Extensions web portal, and claims to be on after each logout / login. When I click on the settings icon on the web portal, I get this error in a dialog:

GLib.SpawnError: Failed to execute child process “/home/myuser/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/gsconnect-preferences” (Permission denied)

Stack trace:
  buildPrefsWidget@/home/mysuer/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/prefs.js:29:10
  _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:207:40
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:13
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:175:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
  run@resource:///org/gnome/gjs/modules/script/package.js:222:19
  start@resource:///org/gnome/gjs/modules/script/package.js:206:5
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17

Selecting Mobile Devices > "Mobile Settings" from the gnome shell menu does nothing. This arch install does not show up in the "Pair new devices" list, even after pulling down to refresh. Two other kdeconnect devices on my LAN do show up, however.

I did a pretty barebones arch / gnome install. Is there any chance there is a dependency that is not listed in the Install Instructions?

**Comment by andyholmes** [comment]
> GLib.SpawnError: Failed to execute child process “/home/myuser/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/gsconnect-preferences” (Permission denied)

This sounds like the permissions were messed up at somehow. You should check the executable bit is enabled.

> This arch install does not show up in the "Pair new devices" list, even after pulling down to refresh. Two other kdeconnect devices on my LAN do show up, however.

What does `lsof -i UDP:1716` say? If GSConnect is listening on this port, it's probably doing everything it can.

> I did a pretty barebones arch / gnome install. Is there any chance there is a dependency that is not listed in the Install Instructions?

Nope. The only dependencies are `gnome-shell` and `openssl`. Everything else should be pulled in by `gnome-shell`.

**Comment by fhteagle** [comment]
```
[myuser@mycomp gsconnect@andyholmes.github.io]$ ls -al
total 132
drwxr-xr-x  8 myuser users  4096 Apr 22 15:34 .
drwxr-xr-x  3 myuser users  4096 Apr 22 15:34  ..
-rw-r--r--  1 myuser users  9004 Mar  8 17:58 _gsconnect.js
-rw-r--r--  1 myuser users 15535 Mar  8 17:58 extension.js
-rwxr-xr-x  1 myuser users  3110 Mar  8 17:58 gsconnect-preferences
drwxr-xr-x 27 myuser users  4096 Apr 16 16:49 locale
-rw-r--r--  1 myuser users  1095 Apr 16 16:49 metadata.json
-rw-r--r--  1 myuser users  6252 Jan 21 20:01 nautilus-gsconnect.py
-rw-r--r--  1 myuser users 47200 Apr 14 20:30 org.gnome.Shell.Extensions.GSConnect.gresource
drwxr-xr-x  2 myuser users  4096 Apr 16 16:49 preferences
-rw-r--r--  1 myuser users   723 Mar  8 17:58 prefs.js
drwxr-xr-x  2 myuser users  4096 Apr 16 16:49 schemas
drwxr-xr-x  6 myuser users  4096 Apr 16 16:49 service
drwxr-xr-x  2 myuser users  4096 Apr 16 16:49 shell
-rw-r--r--  1 myuser users  2118 Mar  8 17:58 stylesheet.css
drwxr-xr-x  2 myuser users  4096 Apr 16 16:49 utils
```

`lsof -i UDP:1716` gives no output. Ill try it again after a fresh boot and edit if anything changes.

yay -S gnome-shell openssl gives...
...
warning: gnome-shell-1:3.36.1-1 is up to date -- reinstalling
warning: openssl-1.1.1.g-1 is up to date -- reinstalling

**Comment by andyholmes** [comment]
Seems like everything is in order, not sure why the preferences would fail to open. Maybe try running it manually?

`$ gjs ~/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/gsconnect-preferences`

If GSConnect is not showing up in `lsof -i UDP:1716` that probably means the service hasn't started and something else is going wrong. Otherwise there should have been a desktop notification indicating why.

**Comment by fhteagle** [comment]
Running it manually gives no errors or output to the terminal window, but the GSConnect Preferences gui window does open. Under Devices... the gui window shows "Waiting for service..."

I generated a support log, but there wasnt much in it:

```
GSConnect Version: 37
GSConnect Install: user
GJS: 16401
XDG_SESSION_TYPE: wayland
GDMSESSION: gnome
--------------------------------------------------------------------------------
-- Logs begin at Wed 2020-04-22 12:23:20 MDT, end at Wed 2020-04-22 17:34:52 MDT. --
-- No entries --
```

Any way to start the service manually to generate a more useful error output?

**Comment by andyholmes** [comment]
You can start the service from the Shell menu, by clicking the *Refresh* button in the top-left corner, or run it in a terminal with:

`$ gjs ~/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js`

**Comment by fhteagle** [comment]
So we're a little closer... starting the daemon from command line works, for the most part. KDEConnect app on device finds the mycomp laptop, and vice versa. Paired the devices, tested a few plugins, everything is as expected. However, selecting Mobile Devices -> Mobile Settings fails silently, no gui or error message. Manually launching gjs ... gsconnect-preferences gives a working gui window.

The terminal I started the daemon from has only this for output, repeated 3x:

```
(GSConnect:5167): GLib-CRITICAL **: 18:44:56.045: g_variant_new_string: assertion 'string != NULL' failed
Gjs-Message: 18:45:25.130: JS WARNING: [/home/dalis/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/protocol/lan.js 715]: reference to undefined property "GSocketOutputStream"
```

So next step is to figure out why gnome-shell can't start the daemon or the preferences , but I can, yesno? What else do you want me to test?

**Comment by andyholmes** [comment]
Does it not work to just enable the service with *Turn On* in *Mobile Settings*? I assume there are no left over files from installing from AUR?

There are no messages in `journalctl` or GNOME Logs for gnome-shell or GSConnect?

**Comment by fhteagle** [comment]
I did your completely remove gsconnect instructions, and yay -R 'ing both gsconnect AUR entries does not do anything. 

journalctl had these two relevant lines several times:

```
Apr 22 18:44:36 mycomp gnome-shell[843]: JS ERROR: GSConnect: Gio.DBusError: Failed to execute program org.gnome.Shell.Extensions.GSConnect: Permission denied
                                          start/</<@/home/myuser/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/utils/remote.js:473:51
Apr 22 18:46:03 mycomp gnome-shell[843]: JS ERROR: GLib.SpawnError: Failed to execute child process “/home/myuser/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/gsconnect-preferences” (Permission denied)
                                          _preferences@/home/myuser/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/extension.js:211:14
A```

So, I did a chmod -R +x *.js, and have not seen those two lines since. However, there's still these lines in journalctl every time I try Mobile Settings -> Turn On...

```
Apr 23 11:46:23 mycomp dbus-daemon[552]: [session uid=1000 pid=552] Activating service name='org.gnome.Shell.Extensions.GSConnect' requested by ':1.13' (uid=1000 pid=900 comm="/usr/bin/gnome-shell ")
Apr 23 11:46:23 mycomp dbus-daemon[552]: [session uid=1000 pid=552] Activated service 'org.gnome.Shell.Extensions.GSConnect' failed: Failed to execute program org.gnome.Shell.Extensions.GSConnect: Permission denied
```

Is it some sort of dbus permissions error?!?

**Comment by andyholmes** [comment]
This is starting to sound like your DBus instance is not set up correctly. I don't really know much about Arch or how they configure DBus, but I guess you could check `dbus-daemon-launch-helper` has the correct permissions and GID, etc.

Other than that, I don't really know how to help here as it seems GSConnect really isn't doing anything wrong.

**Comment by fhteagle** [comment]
Thanks for the suggestions. So I did a second complete arch install from the same media but on a different PC, installed gnome 3 and gnome-shell-extension-gsconnect-git. Everything was working as expected on the new instance. The only difference is I used a script to automate the arch install on the instance with the error, vs doing everything by hand on the instance where everything is working right. So it may not be a direct dependency of gsconnect that is missing, but something in dbus dependency tree. I'll keep trying to see if I find a difference in the installed package sets or user groups or something, as I really hate to close this bug without a real solution. Mind keeping it open for awhile?

**Comment by andyholmes** [comment]
Sure no problem

**Comment by fhteagle** [comment]
Wow, this was a doozy to solve, but I finally cracked it. My home partition was getting mounted noexec on this machine. Fixed that via editing fstab options, then this bug disappeared (as well as several other script issues that clued me in to the real problem). Thanks again for your tips and attempts to solve this ...

**Comment by E34rrsff** [comment]
fapolicyd may also be blocking scripts from being run. https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/security_hardening/assembly_blocking-and-allowing-applications-using-fapolicyd_security-hardening
