### ISSUE TITLE
Notifications from device don't work anymore

### ISSUE THREAD

**Issue by moulip** [andyholmes/gnome-shell-extension-gsconnect#826]
**Describe the bug**

Hi I'm using GsConnect on Debian Testing. Everything was working smoothly but since the last Debian upgrade (which led to a major Gnome update), I don't receive the device notifications any longer nor do I have the menu in the Network-Manager.
Actions from the device to the laptop are all working.
But I have to go through the gnome-shell extensions website to open the extension setting and connect the mobile device to the laptop.

**Expected behavior**

I wish to be able to recover the settings item in the network-manager and receives the notifications from my mobile on the laptop.

**Screenshots**

If applicable, add screenshots to help explain your problem. You can drag-and-drop or cut-and-paste images directly into this edit window, to include them in your report.
![image](https://user-images.githubusercontent.com/805421/80078425-323d2500-854f-11ea-8cb7-a3f609d08826.png)

![image](https://user-images.githubusercontent.com/805421/80080088-631e5980-8551-11ea-99a7-31c63c31fede.png)

**Support Log**

Please generate a support log ([Instructions](../wiki/Help#generate-support-log)) and paste any messages related to this issue between the two ``` lines below.

Nothing in the logs.
```

```

**System Details (please complete the following information):**

 - **GSConnect version: 37
   - **Installed from: GNOME Extensions Website
 - **GNOME/Shell version: 3.36
 - **Distro/Release: Debian Testing (Xorg)

**GSConnect environment (if applicable):**

 - **Paired Device(s): Galaxy S10+
 - **KDE Connect app version: 1.14.2

**Comment by andyholmes** [comment]
Is there really nothing in logs? If there's an error on the website there should be an error in the logs.

What happens if you open `journalctl -f -o cat /usr/bin/gnome-shell` in a terminal and restart `gnome-shell` ([<kbd>Alt</kbd>+<kbd>F2</kbd>, <kbd>r</kbd>)?

**Comment by ferdnyc** [comment]
You might also be able to find a bit more information about the extension error using looking glass.

1. Hit <kbd>Alt</kbd>+<kbd>F2</kbd>
1. Type `lg` (**L**ooking **G**lass) followed by <kbd>Enter</kbd>
1. In the panel that drops down, switch to the Extensions "tab" (upper right corner)
1. You'll see a list of the available extensions, and each will have a "Show Errors" link that very occasionally displays an error message when clicked.

(Or not. Sometimes even when there is a problem, looking glass will claim "foo<span>@</span>org.bar has not emitted any errors". Can't hurt to check, though.)

**Comment by moulip** [comment]
Hi,

It seems that everything has come back to normal.
Thanks anyway.
