### ISSUE TITLE
Panel menu not loading after upgrade to Ubuntu 20.04

### ISSUE THREAD

**Issue by itsmewallis** [andyholmes/gnome-shell-extension-gsconnect#827]
**Describe the bug**

This morning, prior to the 20.04 update I was able to see the menu in the panel and configure my cellphone to connect. After the update to 20.04 I do not see the applet and can't invoke features such as camera, SMS, file share, Etc. from the desktop. 

**Steps To Reproduce:**

1. [Uninstall] -> Install the extension.
2. "Error" will show up on Gnome Extensions website.
3. Open "Extensions" in the desktop applications menu, you should be able to search and launch the application to manage installed extensions. you should be able to see the "GSConnect" extension is forcibly disabled and can't be enabled.
4. However, If you open the settings for the extension by clicking on the left 'gear' icon you will see the extension still show's it's configuration screen, allows you to modify settings, and pair/unpair the cellphone. 
5. If you manually unpair your cellphone, you should should still be able to pair the it in the extension's settings window, but the applet will not appear. 

**Support Log**

```
JS ERROR: Extension gsconnect@andyholmes.github.io: Error: Tried to construct an object without a GType; are you using GObject.registerClass() when inheriting from a GObject type?
ServiceIndicator@/home/user/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/extension.js:88:9
enable@/home/user/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/extension.js:476:24
_callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:166:32
loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:336:26
callback@resource:///org/gnome/shell/ui/extensionDownloader.js:232:39
gotExtensionZipFile/<@resource:///org/gnome/shell/ui/extensionDownloader.js:115:13

Window manager warning: Invalid WM_TRANSIENT_FOR window 0x260000a specified for 0x2600033.
JS ERROR: Error: Source.notify() has been moved to Source.showNotification()this code will break in the future
notify@resource:///org/gnome/shell/ui/messageTray.js:868:23
addNotification@/home/user/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/shell/notification.js:241:18
AddNotificationAsync@resource:///org/gnome/shell/ui/notificationDaemon.js:815:16
_handleMethodCall@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:371:35
_wrapJSObject/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:404:34

JS ERROR: Error: No signal 'acknowledged-changed' on object 'Gjs_ui_notificationDaemon_GtkNotificationDaemonNotification'
pushNotification@/home/user/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/shell/notification.js:257:22
showNotification@resource:///org/gnome/shell/ui/messageTray.js:857:14
notify@resource:///org/gnome/shell/ui/messageTray.js:872:22
addNotification@/home/user/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/shell/notification.js:241:18
AddNotificationAsync@resource:///org/gnome/shell/ui/notificationDaemon.js:815:16
_handleMethodCall@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:371:35
_wrapJSObject/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:404:34
```

**System Details (please complete the following information):**
- GDM 3.34.1
- GSConnect Version: 37
- GSConnect Install: user
- GJS: 16401
- XDG_SESSION_TYPE: x11
- GDMSESSION: ubuntu

**Comment by andyholmes** [comment]
See #817. You'll just have to restart GNOME Shell or logout/login to make this upgrade.

**Comment by charitarthchugh** [comment]
I can confirm that this worked.

**Comment by charitarthchugh** [comment]
> See #817. You'll just have to restart GNOME Shell or logout/login to make this upgrade.

I can confirm that this worked

**Comment by itsmewallis** [comment]
Yeah, same here. Thanks guys!
