### ISSUE TITLE
Error in notification icon

### ISSUE THREAD

**Issue by Katsuki642** [andyholmes/gnome-shell-extension-gsconnect#829]
**Describe the bug**

No matter what the notification is, the icon is only an error-like icon.

**Expected behavior**

Notifications show the corresponding icon.

**Screenshots**
![icon-error](https://user-images.githubusercontent.com/54808964/80239752-f3ac8500-868a-11ea-9166-084450593ffc.png)

**System Details (please complete the following information):**

 - **GSConnect version:** 37
   - **Installed from:** GNOME Extensions Website
 - **GNOME/Shell version:** 3.36.1
 - **Distro/Release:** Arch

**GSConnect environment (if applicable):**

 - **Paired Device(s):** Galaxy A10, Android 10
 - **KDE Connect app version:** 1.14.2

**Comment by andyholmes** [comment]
Partially fixed in 7b48108, but more problems are being caused here by the sftp plugin hogging ports.

**Comment by andyholmes** [comment]
Closing, since fix is in v38.
