### ISSUE TITLE
Remote Keyboard does not support Chinese characters

### ISSUE THREAD

**Issue by nlpsuge** [andyholmes/gnome-shell-extension-gsconnect#836]
> ***ATTENTION**: GSConnect only supports the latest, stable version of GNOME. We are no longer accepting bug reports for previous versions.*

**Describe the bug**

When typing Chinese via  Remote Keyboard, Chinese characters can not be input into the text area on my phone.

**Steps To Reproduce:**

1. Open the Remote Keyboard function on PC
2. Click a text area, change to the KDE Connect Remote Keyboard on phone
3. Type any Chinese characters on PC via Remote Keyboard
4. Chinese characters do appear on the text area on PC, but not appear on the phone's

**Expected behavior**

Can input Chinese characters via Remote Keyboard

**Screenshots**

No need, I think...

**Support Log**

Please generate a support log ([Instructions](../wiki/Help#generate-support-log)) and paste any messages related to this issue between the two ``` lines below.

```
I see no releated logs when I type Chinese.
```

**System Details (please complete the following information):**

 - **GSConnect version:** [e.g. 35, 36, ... (displayed in the GSConnect "About" window)]
37
   - **Installed from:** [e.g. GNOME Extensions Website, GitHub, Package Manager, ...]
GNOME Extensions Website
 - **GNOME/Shell version:** [e.g. 3.36, ...]
3.36
 - **Distro/Release:** [e.g. Ubuntu 18.04, Fedora 29, Arch, ...]
Fedora 32
**GSConnect environment (if applicable):**

 - **Paired Device(s):** [e.g. Galaxy Note 8, Pixel 2, Honor 9, ...]
Redmi Note 5
 - **KDE Connect app version:** [e.g. 1.12.7]
1.14.2
 - **Plugin(s):** [if the issue only occurs when using certain plugin(s)]

**Additional Notes:**

Not any for now...

**Comment by andyholmes** [comment]
Looks like the input method is not triggering regular key press events. Do you use IBus?

**Comment by nlpsuge** [comment]
@andyholmes 
Yes, I use IBus. Precisely, I use ibus-rime.

**Comment by andyholmes** [comment]
@nlpsuge okay, this might tricky depending :)

We usually handle all key presses manually, but IBus seems to just insert text directly. Do you ever use modifiers like <kbd>Ctrl</kbd>, <kbd>Shift</kbd>, <kbd>Alt</kbd> or  <kbd>Super</kbd> with characters sent by IBus?

**Comment by nlpsuge** [comment]
> Do you ever use modifiers like Ctrl, Shift, Alt or Super with characters sent by IBus?

Maybe the answer is no. But, I'm very sorry, I can not fully understand what you mean. Can you exemplify  what you said?

P.S. I myself only use IBus to input Chinese characters.

**Comment by andyholmes** [comment]
Oh I mean, would you ever do something like <kbd>Ctrl</kbd>+<kbd>可</kbd>, like you would do <kbd>Ctrl</kbd>+<kbd>a</kbd>. If not, I think I can support IBus pretty easy.

**Comment by andyholmes** [comment]
Here's a test zip with the fix from above, testing would be appreciated ([instructions](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Installation#install-from-zip)):

[gsconnect@andyholmes.github.io.zip](https://github.com/andyholmes/gnome-shell-extension-gsconnect/files/4567030/gsconnect%40andyholmes.github.io.zip)

**Comment by nlpsuge** [comment]
> Oh I mean, would you ever do something like Ctrl+可, like you would do Ctrl+a.

No, never do that before, but that's very fantastic for me...

**Comment by nlpsuge** [comment]
> Here's a test zip with the fix from above, testing would be appreciated ([instructions](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Installation#install-from-zip)):
> 
> [gsconnect@andyholmes.github.io.zip](https://github.com/andyholmes/gnome-shell-extension-gsconnect/files/4567030/gsconnect%40andyholmes.github.io.zip)

I'll try it out. Reply you later.

**Comment by nlpsuge** [comment]
@andyholmes 

It works! Now I can type Chinese, thank your very much for your excellent work. ^_^

**Comment by rainbyte** [comment]
Is this also valid for writing in Chinese using Android GBoard? I would like to type in Chinese using my phone.

**Comment by andyholmes** [comment]
This issue doesn't have anything to do with Android -> Desktop input, so nope.

GSConnect should already be able to handle unicode characters from Android, although I wouldn't be surprised if this was broken on Debian/Ubuntu.

**Comment by rainbyte** [comment]
> This issue doesn't have anything to do with Android -> Desktop input, so nope.
> 
> GSConnect should already be able to handle unicode characters from Android, although I wouldn't be surprised if this was broken on Debian/Ubuntu.

It doesn't work from Android to Desktop, maybe it is a limitation of the Android app. Where should I report this issue? It doesn't seem to be problem of GSConnect, if it does support receiving the events.

**Comment by andyholmes** [comment]
Non-latin languages seem to work for me. You might want to generate a debug log to be sure, and if there's an error open a new issue, since this one is closed.

Otherwise you should open a bug on https://bugs.kde.org.
