### ISSUE TITLE
this._pulseaudio is undefined

### ISSUE THREAD

**Issue by mokilcde** [andyholmes/gnome-shell-extension-gsconnect#838]
> ***ATTENTION**: GSConnect only supports the latest, stable version of GNOME. We are no longer accepting bug reports for previous versions.*
On my box Gnome 3.36.2 is running (Debian SID)

See a popup when login. This have the following content:
header: 
this._pulseaudio is undefined
content:
_init@/srv/home/michael/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/systemvolume.js:35:13
_loadPlugin@/srv/home/michael/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/device.js:966:26
_loadPlugins@/srv/home/michael/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/device.js:989:28
async*_init@/srv/home/michael/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/device.js:149:14
vfunc_startup@/srv/home/michael/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:632:26
vfunc_handle_local_options@/srv/home/michael/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:1058:18
@/srv/home/michael/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:1125:17

**Steps To Reproduce:**

1. Start machine
2. Log in
3. See error

CU 
  Michael

**Comment by George1896** [comment]
same here... (Debian sid user 3.36.2 Gnome)

**Comment by andyholmes** [comment]
Are there any other errors in the log from GSConnect?

**Comment by andyholmes** [comment]
Can you test this zip to see if it fixes the problem ([instructions](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Installation#install-from-zip)):

[gsconnect@andyholmes.github.io.zip](https://github.com/andyholmes/gnome-shell-extension-gsconnect/files/4569336/gsconnect%40andyholmes.github.io.zip)

**Comment by lzuccolo** [comment]
> Can you test this zip to see if it fixes the problem ([instructions](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Installation#install-from-zip)):
> 
> [gsconnect@andyholmes.github.io.zip](https://github.com/andyholmes/gnome-shell-extension-gsconnect/files/4569336/gsconnect%40andyholmes.github.io.zip)

Thanks. 
The zip file fix the error.

Debian sid 3.36.2 Gnome

**Comment by guillaume-uH57J9** [comment]
Thanks for the fix. Consider uploading the latest to https://extensions.gnome.org/

**Comment by andyholmes** [comment]
Probably be about week or so until I have time, there's about 40 other extensions in the queue to go through first.

**Comment by premek** [comment]
The workaround is to turn it off and on again here https://extensions.gnome.org/local/
