### ISSUE TITLE
"browse file system" kept crashing and ubuntu internal error 

### ISSUE THREAD

**Issue by tuchang** [andyholmes/gnome-shell-extension-gsconnect#839]
**Describe the bug**
browse remote file system via Nautilus, then it crashed and Ubuntu internal error alerts.

**Steps To Reproduce:**

1. install GSConnect on ubuntu 18.04
2. open folders of remote file system in nautilus 
3. wait for minutes
4. See Ubuntu internal error and the file browser gets back to HOME directory.

**Support Log**

GSConnect Version: 28
GSConnect Install: user
GJS: 15205
XDG_SESSION_TYPE: x11
GDMSESSION: ubuntu
--------------------------------------------------------------------------------
-- Logs begin at Sun 2020-04-19 03:06:08 CDT, end at Sat 2020-05-02 03:22:56 CDT. --
May 02 03:22:04 gjs[11246]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
May 02 03:22:04 gjs[11246]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
May 02 03:22:04 gjs[11246]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
May 02 03:22:04 gjs[11246]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
May 02 03:22:04 gjs[11246]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
May 02 03:22:04 gjs[11246]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
May 02 03:22:56 gjs[14913]: GtkDialog mapped without a transient parent. This is discouraged.

```

```

**System Details (please complete the following information):**

 - **GSConnect version:28
   - **Installed from: GNOME Extensions Website
 - **GNOME/Shell version:3.28.4
 - **Distro/Release:Ubuntu 18.04

**GSConnect environment (if applicable):**

 - **Paired Device(s):Huawei Mate9
 - **KDE Connect app version:1.14.2
 - **Plugin(s): Filesystem expose

**Comment by andyholmes** [comment]
This probably a problem with the key exchange algorithm. You might want to try downgrading the Android app to `<= 1.13.7`.

Unfortunately we don't support older versions of GNOME, so I can't help much here.
