### ISSUE TITLE
Can't install python-nautilus to use Nautilus

### ISSUE THREAD

**Issue by tiennou44** [andyholmes/gnome-shell-extension-gsconnect#844]
I'm on Ubuntu 20.04.
There is conflict between python-nautilus and python3-nautilus to install them.
In fact, some of nautilus extensions I installed (nautilus-admin, nautilus-nextcloud, ...) depend on python3-nautilus.
So I can't use Nautilus to browse my phone files system.
What solution ?

**Comment by andyholmes** [comment]
Does the extension not work with python3-nautilus? Are there any errors in you logs? If you restart Nautilus in a terminal does it print any errors?

```sh
$ pkill nautilus; nautilus
```

**Comment by tiennou44** [comment]
In my Ubnutu 20.04 box, kdeconnect was running every startup.
I removed kdeconnect, and now all is ok.
