### ISSUE TITLE
the latest GSConect breaks in ubuntu 20.04 gnome-shell: 3.36.1

### ISSUE THREAD

**Issue by grizzlysmit** [andyholmes/gnome-shell-extension-gsconnect#846]
> ***ATTENTION**: GSConnect only supports the latest, stable version of GNOME. We are no longer accepting bug reports for previous versions.*

**Describe the bug**

**Steps To Reproduce:**

update in webpage https://extensions.gnome.org/local/ and it's broken and does not work, I rolled back by copying the files from a system I hadn't updated, note you can see it's broken the minute you upgrade as the on/off icon is replaced with error and KDEConnect on the phone no longer connects to it

```

**System Details (please complete the following information):**

 - **GSConnect version:** 37
   - **Installed from:** GNOME Extensions Website
 - **GNOME/Shell version:**  3.36.1
 - **Distro/Release:** Ubuntu 20.04

**GSConnect environment (if applicable):**

 - **Paired Device(s):** Pixel 4 XL
 - **KDE Connect app version:**  1.14.2
 - **Plugin(s):** who knows, run a few but I get the same problem on both boxes, the moment I update GSConncect
**Additional Notes:** nothing I caot get the logs with out breaking it again by updating it back

Add any addtional information about the problem or your system.

**Comment by andyholmes** [comment]
Did you restart GNOME Shell after updating?

**Comment by davidrhoderick** [comment]
I had an error before restarting GNOME, then it worked.

**Comment by andyholmes** [comment]
> I had an error before restarting GNOME, then it worked.

That's to be expected, the shell needs to be restarted before extension updates are applied.

**Comment by grizzlysmit** [comment]
sorry I tried the restart a it was all ok
