### ISSUE TITLE
Can't start extension "undefined" error

### ISSUE THREAD

**Issue by KishCom** [andyholmes/gnome-shell-extension-gsconnect#847]
Trying to install gsconnect both from the gnome extensions website and manually from git.

If I attempt to enable the service from within the extensions settings menu - it seems to work but nothing happens and I am unable to see my device for pairing in the Android app even though `kdeconnectd` appears to be running.

```
May  7 08:19:15 ubuntu dbus-daemon[1762]: [session uid=1000 pid=1762] Activating service name='org.gnome.Shell.Extensions.GSConnect' requested by ':1.137' (uid=1000 pid=6726 comm="gjs /home/kishcom/.local/share/gnome-shell/extensi" label="unconfined")
May  7 08:19:15 ubuntu dbus-daemon[1762]: [session uid=1000 pid=1762] Successfully activated service 'org.gnome.Shell.Extensions.GSConnect'
May  7 08:19:16 ubuntu gjs[7217]: JS ERROR: Gio.IOErrorEnum: Error binding to address 0.0.0.0:1716: Address already in use#012_initUdpListener@/home/kishcom/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/protocol/lan.js:242:24#012start@/home/kishcom/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/protocol/lan.js:414:18#012_initBackends@/home/kishcom/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:493:25#012vfunc_startup@/home/kishcom/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:631:14#012vfunc_handle_local_options@/home/kishcom/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:1061:18#012@/home/kishcom/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:1128:17
May  7 08:19:16 ubuntu gjs[7217]: g_variant_new_string: assertion 'string != NULL' failed
```

**System Details (please complete the following information):**

 - **GSConnect version**: 37
   - **Installed from**: git
 - **GNOME/Shell version:** 3.36
 - **Distro/Release:** Ubuntu 20.04

**Comment by KishCom** [comment]
I pasted the wrong log. The one above is me trying to restart the extension -- it's already running.
This is the error I'm seeing `GSettings schema undefined not found`
```
May  7 08:12:53 ubuntu gnome-shell[2310]: JS WARNING: [resource:///org/gnome/gjs/modules/core/overrides/Gio.js 552]: reference to undefined property "undefined"
May  7 08:12:53 ubuntu gnome-shell[2310]: JS ERROR: Extension gsconnect@andyholmes.github.io: Error: GSettings schema undefined not found#012_init@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:552:23#012@/home/kishcom/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/_gsconnect.js:118:22#012@/home/kishcom/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/extension.js:15:1#012_callExtensionInit@resource:///org/gnome/shell/ui/extensionSystem.js:403:13#012_callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:144:18#012_onEnabledExtensionsChanged/<@resource:///org/gnome/shell/ui/extensionSystem.js:475:18#012_onEnabledExtensionsChanged@resource:///org/gnome/shell/ui/extensionSystem.js:474:11#012_init/createCheckedMethod/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:529:46#012enableExtension@resource:///org/gnome/shell/ui/extensionSystem.js:193:29#012EnableExtension@resource:///org/gnome/shell/ui/shellDBus.js:307:38#012_handleMethodCall@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:327:38#012_wrapJSObject/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:404:34
```

**Comment by ferdnyc** [comment]
Oh, having `kdeconnectd` running will break GSConnect for sure — it's a replacement implementation for the desktop side of KDE Connect, so they'll conflict if used together. When using GSConnect, you should _uninstall_ kdeconnect completely from the system.

The GSConnect process will be a `gjs` instance executing the `daemon.js` file from the extension directory.

**Comment by ferdnyc** [comment]
(The relevant [bit of FAQ](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Help#network-error) — buried way down at the bottom, weirdly enough.)

And as it says there, a conflict with `kdeconnectd` should result in Network Errors being logged when GSConnect fails to bind to the already-in-use network ports. So if that's not happening, it could be there actually is some additional issue with GSConnect itself. But getting `kdeconnectd` out of the picture should definitely be the first step, before going down any other roads.)

**Comment by KishCom** [comment]
Oh wow, I feel dumb for this one! I for some reason assumed this used the kconnectd instead of it's own! I removed kconnectd, rebooted, and everything is happy and healthy again.

Thanks so much for taking the time to answer.
