### ISSUE TITLE
Manjaro issue..!

### ISSUE THREAD

**Issue by internauta2000** [andyholmes/gnome-shell-extension-gsconnect#850]
**Describe the bug**
The extension does not connect to the device automatically, it is not shown in the top bar or in the user menu, only when the icon for the device search is activated, but nothing in the menu and top bar ... Everything else works correctly.

**Screenshots**
![gnome-shell-screenshot-77U9J0](https://user-images.githubusercontent.com/12079105/81475179-80515a00-91d8-11ea-823f-d6e1bdf7f443.png)

![gnome-shell-screenshot-96ABK0](https://user-images.githubusercontent.com/12079105/81475439-4719e980-91da-11ea-9617-dfb9d3e09df6.png)

**Support Log**

GSConnect Version: 37
GSConnect Install: user
GJS: 16402
XDG_SESSION_TYPE: x11
GDMSESSION: gnome
--------------------------------------------------------------------------------
-- Logs begin at Wed 2019-06-26 13:43:26 -04, end at Sat 2020-05-09 09:37:17 -04. --
may 09 09:37:00 gnome-shell[5275]: GNOME Shell started at Sat May 09 2020 09:36:57 GMT-0400 (hora de Venezuela)
may 09 09:37:00 gnome-shell[5275]: Registering session with GDM
may 09 09:37:00 gnome-shell[5275]: meta_display_get_monitor_geometry: assertion 'META_IS_DISPLAY (display)' failed
may 09 09:37:00 gnome-shell[5275]: meta_display_get_monitor_geometry: assertion 'META_IS_DISPLAY (display)' failed
may 09 09:37:01 dbus-daemon[558]: [system] Activating via systemd: service name='org.freedesktop.Avahi' unit='dbus-org.freedesktop.Avahi.service' requested by ':1.1184' (uid=1000 pid=36878 comm="/usr/bin/lpstat -a ")
may 09 09:37:01 dbus-daemon[558]: [system] Activation via systemd failed for unit 'dbus-org.freedesktop.Avahi.service': Unit dbus-org.freedesktop.Avahi.service not found.
may 09 09:37:01 gnome-shell[5275]: Usage of object.actor is deprecated for PrintersManager
                                   get@resource:///org/gnome/shell/ui/environment.js:287:29
                                   refresh/</</</<@/home/orlando/.local/share/gnome-shell/extensions/printers@linux-man.org/extension.js:179:25
                                   spawn_async@/home/orlando/.local/share/gnome-shell/extensions/printers@linux-man.org/extension.js:36:5
                                   refresh/</</<@/home/orlando/.local/share/gnome-shell/extensions/printers@linux-man.org/extension.js:143:21
                                   spawn_async@/home/orlando/.local/share/gnome-shell/extensions/printers@linux-man.org/extension.js:36:5
                                   refresh/</<@/home/orlando/.local/share/gnome-shell/extensions/printers@linux-man.org/extension.js:133:17
                                   spawn_async@/home/orlando/.local/share/gnome-shell/extensions/printers@linux-man.org/extension.js:36:5
                                   refresh/<@/home/orlando/.local/share/gnome-shell/extensions/printers@linux-man.org/extension.js:113:13
                                   spawn_async@/home/orlando/.local/share/gnome-shell/extensions/printers@linux-man.org/extension.js:36:5
                                   refresh@/home/orlando/.local/share/gnome-shell/extensions/printers@linux-man.org/extension.js:111:9
                                   wrapper@resource:///org/gnome/gjs/modules/script/_legacy.js:82:27
                                   warningTimeout@/home/orlando/.local/share/gnome-shell/extensions/printers@linux-man.org/extension.js:203:14
                                   wrapper@resource:///org/gnome/gjs/modules/script/_legacy.js:82:27
may 09 09:37:01 gnome-shell[5275]: Usage of object.actor is deprecated for PrintersManager
                                   get@resource:///org/gnome/shell/ui/environment.js:287:29
                                   refresh/</</</<@/home/orlando/.local/share/gnome-shell/extensions/printers@linux-man.org/extension.js:181:30
                                   spawn_async@/home/orlando/.local/share/gnome-shell/extensions/printers@linux-man.org/extension.js:36:5
                                   refresh/</</<@/home/orlando/.local/share/gnome-shell/extensions/printers@linux-man.org/extension.js:143:21
                                   spawn_async@/home/orlando/.local/share/gnome-shell/extensions/printers@linux-man.org/extension.js:36:5
                                   refresh/</<@/home/orlando/.local/share/gnome-shell/extensions/printers@linux-man.org/extension.js:133:17
                                   spawn_async@/home/orlando/.local/share/gnome-shell/extensions/printers@linux-man.org/extension.js:36:5
                                   refresh/<@/home/orlando/.local/share/gnome-shell/extensions/printers@linux-man.org/extension.js:113:13
                                   spawn_async@/home/orlando/.local/share/gnome-shell/extensions/printers@linux-man.org/extension.js:36:5
                                   refresh@/home/orlando/.local/share/gnome-shell/extensions/printers@linux-man.org/extension.js:111:9
                                   wrapper@resource:///org/gnome/gjs/modules/script/_legacy.js:82:27
                                   warningTimeout@/home/orlando/.local/share/gnome-shell/extensions/printers@linux-man.org/extension.js:203:14
                                   wrapper@resource:///org/gnome/gjs/modules/script/_legacy.js:82:27
may 09 09:37:04 gnome-shell[5275]: meta_display_get_monitor_geometry: assertion 'META_IS_DISPLAY (display)' failed
may 09 09:37:04 gnome-shell[5275]: meta_display_get_monitor_geometry: assertion 'META_IS_DISPLAY (display)' failed
may 09 09:37:06 systemd[5214]: Started Application launched by gnome-shell.
may 09 09:37:06 gnome-shell[36906]: gnome-shell-extension-prefs is deprecated
may 09 09:37:06 gnome-shell[36906]: Install https://flathub.org/apps/details/org.gnome.Extensions for extension
may 09 09:37:06 gnome-shell[36906]: management, or use the gnome-extensions command line tool.
may 09 09:37:06 gnome-shell[36906]: Extensions can use the ExtensionUtils.openPrefs() method.
may 09 09:37:06 dbus-daemon[5235]: [session uid=1000 pid=5235] Activating service name='org.gnome.Extensions' requested by ':1.8355' (uid=1000 pid=36907 comm="gapplication launch org.gnome.Extensions ")
may 09 09:37:06 dbus-daemon[5235]: [session uid=1000 pid=5235] Successfully activated service 'org.gnome.Extensions'
may 09 09:37:06 dbus-daemon[5235]: [session uid=1000 pid=5235] Activating service name='org.gnome.Shell.Extensions' requested by ':1.8356' (uid=1000 pid=36912 comm="/usr/bin/gjs /usr/share/gnome-shell/org.gnome.Exte")
may 09 09:37:06 dbus-daemon[5235]: [session uid=1000 pid=5235] Successfully activated service 'org.gnome.Shell.Extensions'
may 09 09:37:06 systemd[5214]: gnome-launched-gnome-shell-extension-prefs-36905.scope: Succeeded.
may 09 09:37:06 gnome-shell[5275]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x3000007
may 09 09:37:10 gjs[36912]: g_task_return_error: assertion '!task->ever_returned' failed
may 09 09:37:10 dbus-daemon[5235]: [session uid=1000 pid=5235] Reloaded configuration
may 09 09:37:11 dbus-daemon[5235]: [session uid=1000 pid=5235] Activating via systemd: service name='org.freedesktop.Tracker1' unit='tracker-store.service' requested by ':1.59' (uid=1000 pid=5532 comm="/usr/lib/tracker-miner-fs ")
may 09 09:37:11 systemd[5214]: Starting Tracker metadata database store and lookup manager...
may 09 09:37:11 dbus-daemon[5235]: [session uid=1000 pid=5235] Successfully activated service 'org.freedesktop.Tracker1'
may 09 09:37:11 systemd[5214]: Started Tracker metadata database store and lookup manager.
may 09 09:37:11 gjs[36925]: JS WARNING: [resource:///org/gnome/Shell/Extensions/js/extensionsService.js 131]: reference to undefined property "GdkX11Window"
may 09 09:37:16 gnome-shell[5275]: JS WARNING: [resource:///org/gnome/shell/ui/search.js 496]: reference to undefined property "isRemoteProvider"
may 09 09:37:17 dbus-daemon[5235]: [session uid=1000 pid=5235] Activating via systemd: service name='org.freedesktop.Tracker1.Miner.Extract' unit='tracker-extract.service' requested by ':1.59' (uid=1000 pid=5532 comm="/usr/lib/tracker-miner-fs ")
may 09 09:37:17 systemd[5214]: Starting Tracker metadata extractor...
may 09 09:37:17 tracker-extract[37010]: Set scheduler policy to SCHED_IDLE
may 09 09:37:17 tracker-extract[37010]: Setting priority nice level to 19
may 09 09:37:17 dbus-daemon[5235]: [session uid=1000 pid=5235] Successfully activated service 'org.freedesktop.Tracker1.Miner.Extract'
may 09 09:37:17 systemd[5214]: Started Tracker metadata extractor.

**System Details:**

 - **GSConnect version:** GSConnect Version: 37
   - **Installed from:** GNOME Extensions Website
 - **GNOME/Shell version:** 3.36
 - **Distro/Release:** Manjaro Linux Lysia

**GSConnect environment:**

 - **Paired Device(s):** Xiaomi Redmi Note 6
 - **KDE Connect app version:** 1.14.2
 - **Plugin(s):** None

**Comment by andyholmes** [comment]
You have to restart GNOME Shell after updating via the website.

**Comment by andyholmes** [comment]
Closing, as this is an upstream issue withe extensions.gnome.org
