### ISSUE TITLE
Slideshow remote not working

### ISSUE THREAD

**Issue by Qooley** [andyholmes/gnome-shell-extension-gsconnect#851]
the slideshow remote feature not working on Ubuntu 20.04

**Comment by andyholmes** [comment]
It's helpful if you fill out the bug report template. I assume you're using Wayland?

**Comment by Qooley** [comment]
GSConnect Version: 37
GSConnect Install: user
GJS: 16401
XDG_SESSION_TYPE: wayland
GDMSESSION: ubuntu-wayland
--------------------------------------------------------------------------------
-- Logs begin at Mon 2020-04-13 10:39:20 EAT, end at Mon 2020-05-11 09:34:17 EAT. --
Cam 11 09:34:17 systemd[1]: systemd-hostnamed.service: Succeeded.
Cam 11 09:34:17 tracker-store[4790]: OK
Cam 11 09:34:17 systemd[1466]: tracker-store.service: Succeeded.

**Comment by Qooley** [comment]
GSConnect Version: 37
GSConnect Install: user
GJS: 16401
XDG_SESSION_TYPE: wayland
GDMSESSION: ubuntu-wayland
--------------------------------------------------------------------------------
-- Logs begin at Mon 2020-04-13 10:39:20 EAT, end at Mon 2020-05-11 09:55:55 EAT. --
Cam 11 09:55:42 org.gnome.Shell.Extensions.GSConnect[1811]: [/service/protocol/core.js:receive/<:298]: Marrion-Phone: {
                                                              "id": 1589180142577,
                                                              "type": "kdeconnect.mousepad.request",
                                                              "body": {
                                                                "specialKey": 8
                                                              }
                                                            }
Cam 11 09:55:42 org.gnome.Shell.Extensions.GSConnect[1811]: [/service/device.js:receivePacket:443]: Marrion-Phone: Unsupported packet type (kdeconnect.mousepad.request)
                                                            receivePacket@/home/marrion/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/device.js:443:27
                                                            receive/<@/home/marrion/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/protocol/core.js:299:32
                                                            @/home/marrion/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:1125:17
Cam 11 09:55:42 org.gnome.Shell.Extensions.GSConnect[1811]: [/service/protocol/core.js:receive/<:298]: Marrion-Phone: {
                                                              "id": 1589180142731,
                                                              "type": "kdeconnect.mousepad.request",
                                                              "body": {
                                                                "specialKey": 8
                                                              }
                                                            }
Cam 11 09:55:42 org.gnome.Shell.Extensions.GSConnect[1811]: [/service/device.js:receivePacket:443]: Marrion-Phone: Unsupported packet type (kdeconnect.mousepad.request)
                                                            receivePacket@/home/marrion/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/device.js                                                                "specialKey": 9
                                                              }
                                                            }
Cam 11 09:55:43 org.gnome.Shell.Extensions.GSConnect[1811]: [/service/device.js:receivePacket:443]: Marrion-Phone: Unsupported packet type (kdeconnect.mousepad.request)
                                                            receivePacket@/home/marrion/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/device.js:443:27
                                                            receive/<@/home/marrion/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/protocol/core.js:299:32
                                                            @/home/marrion/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:1125:17
Cam 11 09:55:43 org.gnome.Shell.Extensions.GSConnect[1811]: [/service/protocol/core.js:receive/<:298]: Marrion-Phone: {
                                                              "id": 1589180143160,
                                                              "type": "kdeconnect.mousepad.request",
                                                              "body": {
                                                                "specialKey": 9
                                                              }
                                                            }
Cam 11 09:55:43 org.gnome.Shell.Extensions.GSConnect[1811]: [/service/device.js:receivePacket:443]: Marrion-Phone: Unsupported packet type (kdeconnect.mousepad.request)
                                                            receivePacket@/home/marrion/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/device.js:443:27
                                                            receive/<@/home/marrion/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/protocol/core.js:299:32
                                                            @/home/marrion/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:1125:17
Cam 11 09:55:43 systemd[1]: Starting Refresh fwupd metadata and update motd...
Cam 11 09:55:43 fwupdmgr[5613]: Fetching metadata https://cdn.fwupd.org/downloads/firmware.xml.gz
Cam 11 09:55:43 org.gnome.Shell.Extensions.GSConnect[1811]: [/service/protocol/core.js:receive/<:298]: Marrion-Phone: {
                                                              "id": 1589180143402,
                                                              "type": "kdeconnect.presenter",
                                                              "body": {
                                                                "stop": true
                                                              }
                                                            }
Cam 11 09:55:43 org.gnome.Shell.Extensions.GSConnect[1811]: [/service/protocol/core.js:receive/<:298]: Marrion-Phone: {
                                                              "id": 1589180143573,
                                                              "type": "kdeconnect.presenter",
                                                              "body": {
                                                                "stop": true
                                                              }
                                                            }
Cam 11 09:55:43 org.gnome.Shell.Extensions.GSConnect[1811]: [/service/protocol/core.js:receive/<:298]: Marrion-Phone: {
                                                              "id": 1589180143709,
                                                              "type": "kdeconnect.presenter",
                                                              "body": {
                                                                "stop": true
                                                              }
                                                            }
Cam 11 09:55:44 org.gnome.Shell.Extensions.GSConnect[1811]: [/service/protocol/core.js:receive/<:298]: Marrion-Phone: {
                                                              "id": 1589180143875,
                                                              "type": "kdeconnect.presenter",
                                                              "body": {
                                                                "stop": true
                                                              }
                                                            }
Cam 11 09:55:44 org.gnome.Shell.Extensions.GSConnect[1811]: [/service/protocol/core.js:receive/<:298]: Marrion-Phone: {
                                                              "id": 1589180144045,
                                                              "type": "kdeconnect.presenter",
                                                              "body": {
                                                                "stop": true
                                                              }
                                                            }
Cam 11 09:55:44 org.gnome.Shell.Extensions.GSConnect[1811]: [/service/protocol/core.js:receive/<:298]: Marrion-Phone: {
                                                              "id": 1589180144647,
                                                              "type": "kdeconnect.presenter",
                                                              "body": {
                                                                "stop": true
                                                              }
                                                            }
Cam 11 09:55:44 org.gnome.Shell.Extensions.GSConnect[1811]: [/service/protocol/core.js:receive/<:298]: Marrion-Phone: {
                                                              "id": 1589180144856,
                                                              "type": "kdeconnect.presenter",
                                                              "body": {
                                                                "stop": true
                                                              }
                                                            }
Cam 11 09:55:45 fwupdmgr[5613]: Fetching signature https://cdn.fwupd.org/downloads/firmware.xml.gz.asc
Cam 11 09:55:46 org.gnome.Shell.Extensions.GSConnect[1811]: [/service/protocol/core.js:receive/<:298]: Marrion-Phone: {
                                                              "id": 1589180145924,
                                                              "type": "kdeconnect.mousepad.request",
                                                              "body": {
                                                                "specialKey": 8
                                                              }
                                                            }
Cam 11 09:55:46 org.gnome.Shell.Extensions.GSConnect[1811]: [/service/device.js:receivePacket:443]: Marrion-Phone: Unsupported packet type (kdeconnect.mousepad.request)
                                                            receivePacket@/home/marrion/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/device.js:443:27
                                                            receive/<@/home/marrion/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/protocol/core.js:299:32
                                                            @/home/marrion/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:1125:17
Cam 11 09:55:46 fwupdmgr[5613]: Successfully downloaded new metadata: 0 local devices supported
Cam 11 09:55:46 systemd[1]: fwupd-refresh.service: Succeeded.
Cam 11 09:55:46 systemd[1]: Finished Refresh fwupd metadata and update motd.
Cam 11 09:55:47 org.gnome.Shell.Extensions.GSConnect[1811]: [/service/protocol/core.js:receive/<:298]: Marrion-Phone: {
                                                              "id": 1589180147066,
                                                              "type": "kdeconnect.mousepad.request",
                                                              "body": {
                                                                "specialKey": 8
                                                              }
                                                            }
Cam 11 09:55:47 org.gnome.Shell.Extensions.GSConnect[1811]: [/service/device.js:receivePacket:443]: Marrion-Phone: Unsupported packet type (kdeconnect.mousepad.request)
                                                            receivePacket@/home/marrion/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/device.js:443:27
                                                            receive/<@/home/marrion/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/protocol/core.js:299:32
                                                            @/home/marrion/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:1125:17
Cam 11 09:55:47 org.gnome.Shell.Extensions.GSConnect[1811]: [/service/protocol/core.js:receive/<:298]: Marrion-Phone: {
                                                              "id": 1589180147318,
                                                              "type": "kdeconnect.mousepad.request",
                                                              "body": {
                                                                "specialKey": 8
                                                              }
                                                            }
Cam 11 09:55:47 org.gnome.Shell.Extensions.GSConnect[1811]: [/service/device.js:receivePacket:443]: Marrion-Phone: Unsupported packet type (kdeconnect.mousepad.request)
                                                            receivePacket@/home/marrion/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/device.js:443:27
                                                            receive/<@/home/marrion/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/protocol/core.js:299:32
                                                            @/home/marrion/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:1125:17
Cam 11 09:55:47 org.gnome.Shell.Extensions.GSConnect[1811]: [/service/protocol/core.js:receive/<:298]: Marrion-Phone: {
                                                              "id": 1589180147517,
                                                              "type": "kdeconnect.mousepad.request",
                                                              "body": {
                                                                "specialKey": 8
                                                              }
                                                            }
Cam 11 09:55:47 org.gnome.Shell.Extensions.GSConnect[1811]: [/service/device.js:receivePacket:443]: Marrion-Phone: Unsupported packet type (kdeconnect.mousepad.request)
                                                            receivePacket@/home/marrion/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/device.js:443:27
                                                            receive/<@/home/marrion/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/protocol/core.js:299:32
                                                            @/home/marrion/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:1125:17
Cam 11 09:55:47 org.gnome.Shell.Extensions.GSConnect[1811]: [/service/protocol/core.js:receive/<:298]: Marrion-Phone: {
                                                              "id": 1589180147726,
                                                              "type": "kdeconnect.mousepad.request",
                                                              "body": {
                                                                "specialKey": 8
                                                              }
                                                            }
Cam 11 09:55:47 org.gnome.Shell.Extensions.GSConnect[1811]: [/service/device.js:receivePacket:443]: Marrion-Phone: Unsupported packet type (kdeconnect.mousepad.request)
                                                            receivePacket@/home/marrion/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/device.js:443:27
                                                            receive/<@/home/marrion/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/protocol/core.js:299:32
                                                            @/home/marrion/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:1125:17
Cam 11 09:55:48 org.gnome.Shell.Extensions.GSConnect[1811]: [/service/protocol/core.js:receive/<:298]: Marrion-Phone: {
                                                              "id": 1589180147959,
                                                              "type": "kdeconnect.mousepad.request",
                                                              "body": {
                                                                "specialKey": 9
                                                              }
                                                            }
Cam 11 09:55:48 org.gnome.Shell.Extensions.GSConnect[1811]: [/service/device.js:receivePacket:443]: Marrion-Phone: Unsupported packet type (kdeconnect.mousepad.request)
                                                            receivePacket@/home/marrion/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/device.js:443:27
                                                            receive/<@/home/marrion/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/protocol/core.js:299:32
                                                            @/home/marrion/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:1125:17
Cam 11 09:55:48 org.gnome.Shell.Extensions.GSConnect[1811]: [/service/protocol/core.js:receive/<:298]: Marrion-Phone: {
                                                              "id": 1589180148410,
                                                              "type": "kdeconnect.mousepad.request",
                                                              "body": {
                                                                "specialKey": 9
                                                              }
                                                            }
Cam 11 09:55:48 org.gnome.Shell.Extensions.GSConnect[1811]: [/service/device.js:receivePacket:443]: Marrion-Phone: Unsupported packet type (kdeconnect.mousepad.request)
                                                            receivePacket@/home/marrion/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/device.js:443:27
                                                            receive/<@/home/marrion/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/protocol/core.js:299:32
                                                            @/home/marrion/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:1125:17
Cam 11 09:55:49 org.gnome.Shell.Extensions.GSConnect[1811]: [/service/protocol/core.js:receive/<:298]: Marrion-Phone: {
                                                              "id": 1589180149122,
                                                              "type": "kdeconnect.presenter",
                                                              "body": {
                                                                "stop": true
                                                              }
                                                            }
Cam 11 09:55:49 org.gnome.Shell.Extensions.GSConnect[1811]: [/service/protocol/core.js:receive/<:298]: Marrion-Phone: {
                                                              "id": 1589180149314,
                                                              "type": "kdeconnect.presenter",
                                                              "body": {
                                                                "stop": true
                                                              }
                                                            }
Cam 11 09:55:49 org.gnome.Shell.Extensions.GSConnect[1811]: [/service/protocol/core.js:receive/<:298]: Marrion-Phone: {
                                                              "id": 1589180149575,
                                                              "type": "kdeconnect.mousepad.request",
                                                              "body": {
                                                                "specialKey": 8
                                                              }
                                                            }
Cam 11 09:55:49 org.gnome.Shell.Extensions.GSConnect[1811]: [/service/device.js:receivePacket:443]: Marrion-Phone: Unsupported packet type (kdeconnect.mousepad.request)
                                                            receivePacket@/home/marrion/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/device.js:443:27
                                                            receive/<@/home/marrion/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/protocol/core.js:299:32
                                                            @/home/marrion/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:1125:17
Cam 11 09:55:49 org.gnome.Shell.Extensions.GSConnect[1811]: [/service/protocol/core.js:receive/<:298]: Marrion-Phone: {
                                                              "id": 1589180149774,
                                                              "type": "kdeconnect.mousepad.request",
                                                              "body": {
                                                                "specialKey": 8
                                                              }
                                                            }
Cam 11 09:55:49 org.gnome.Shell.Extensions.GSConnect[1811]: [/service/device.js:receivePacket:443]: Marrion-Phone: Unsupported packet type (kdeconnect.mousepad.request)
                                                            receivePacket@/home/marrion/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/device.js:443:27
                                                            receive/<@/home/marrion/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/protocol/core.js:299:32
                                                            @/home/marrion/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:1125:17
Cam 11 09:55:53 org.gnome.Shell.Extensions.GSConnect[1811]: [/service/protocol/core.js:receive/<:298]: Marrion-Phone: {
                                                              "id": 1589180153261,
                                                              "type": "kdeconnect.mousepad.request",
                                                              "body": {
                                                                "specialKey": 9
                                                              }
                                                            }
Cam 11 09:55:53 org.gnome.Shell.Extensions.GSConnect[1811]: [/service/device.js:receivePacket:443]: Marrion-Phone: Unsupported packet type (kdeconnect.mousepad.request)
                                                            receivePacket@/home/marrion/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/device.js:443:27
                                                            receive/<@/home/marrion/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/protocol/core.js:299:32
                                                            @/home/marrion/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:1125:17
Cam 11 09:55:53 org.gnome.Shell.Extensions.GSConnect[1811]: [/service/protocol/core.js:receive/<:298]: Marrion-Phone: {
                                                              "id": 1589180153487,
                                                              "type": "kdeconnect.mousepad.request",
                                                              "body": {
                                                                "specialKey": 9
                                                              }
                                                            }
Cam 11 09:55:53 org.gnome.Shell.Extensions.GSConnect[1811]: [/service/device.js:receivePacket:443]: Marrion-Phone: Unsupported packet type (kdeconnect.mousepad.request)
                                                            receivePacket@/home/marrion/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/device.js:443:27
                                                            receive/<@/home/marrion/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/protocol/core.js:299:32
                                                            @/home/marrion/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:1125:17
Cam 11 09:55:53 org.gnome.Shell.Extensions.GSConnect[1811]: [/service/protocol/core.js:receive/<:298]: Marrion-Phone: {
                                                              "id": 1589180153743,
                                                              "type": "kdeconnect.mousepad.request",
                                                              "body": {
                                                                "specialKey": 8
                                                              }
                                                            }
Cam 11 09:55:53 org.gnome.Shell.Extensions.GSConnect[1811]: [/service/device.js:receivePacket:443]: Marrion-Phone: Unsupported packet type (kdeconnect.mousepad.request)
                                                            receivePacket@/home/marrion/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/device.js:443:27
                                                            receive/<@/home/marrion/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/protocol/core.js:299:32
                                                            @/home/marrion/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:1125:17
Cam 11 09:55:54 org.gnome.Shell.Extensions.GSConnect[1811]: [/service/protocol/core.js:receive/<:298]: Marrion-Phone: {
                                                              "id": 1589180153915,
                                                              "type": "kdeconnect.mousepad.request",
                                                              "body": {
                                                                "specialKey": 8
                                                              }
                                                            }
Cam 11 09:55:54 org.gnome.Shell.Extensions.GSConnect[1811]: [/service/device.js:receivePacket:443]: Marrion-Phone: Unsupported packet type (kdeconnect.mousepad.request)
                                                            receivePacket@/home/marrion/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/device.js:443:27
                                                            receive/<@/home/marrion/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/protocol/core.js:299:32
                                                            @/home/marrion/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:1125:17
Cam 11 09:55:54 org.gnome.Shell.Extensions.GSConnect[1811]: [/service/protocol/core.js:receive/<:298]: Marrion-Phone: {
                                                              "id": 1589180154232,
                                                              "type": "kdeconnect.presenter",
                                                              "body": {
                                                                "stop": true
                                                              }
                                                            }
Cam 11 09:55:54 org.gnome.Shell.Extensions.GSConnect[1811]: [/service/protocol/core.js:receive/<:298]: Marrion-Phone: {
                                                              "id": 1589180154428,
                                                              "type": "kdeconnect.presenter",
                                                              "body": {
                                                                "stop": true
                                                              }
                                                            }
Cam 11 09:55:54 org.gnome.Shell.Extensions.GSConnect[1811]: [/service/protocol/core.js:receive/<:298]: Marrion-Phone: {
                                                              "id": 1589180154646,
                                                              "type": "kdeconnect.presenter",
                                                              "body": {
                                                                "stop": true
                                                              }
                                                            }
Cam 11 09:55:54 org.gnome.Shell.Extensions.GSConnect[1811]: [/service/protocol/core.js:receive/<:298]: Marrion-Phone: {
                                                              "id": 1589180154834,
                                                              "type": "kdeconnect.presenter",
                                                              "body": {
                                                                "stop": true
                                                              }
                                                            }
Cam 11 09:55:55 org.gnome.Shell.Extensions.GSConnect[1811]: [/service/protocol/core.js:receive/<:298]: Marrion-Phone: {
                                                              "id": 1589180155044,
                                                              "type": "kdeconnect.presenter",
                                                              "body": {
                                                                "stop": true
                                                              }
                                                            }
Cam 11 09:55:55 org.gnome.Shell.Extensions.GSConnect[1811]: [/service/protocol/core.js:receive/<:298]: Marrion-Phone: {
                                                              "id": 1589180155268,
                                                              "type": "kdeconnect.presenter",
                                                              "body": {
                                                                "stop": true
                                                              }
                                                            }:443:27
                                                            receive/<@/home/marrion/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/protocol/core.js:299:32
                                                            @/home/marrion/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:1125:17
Cam 11 09:55:43 org.gnome.Shell.Extensions.GSConnect[1811]: [/service/protocol/core.js:receive/<:298]: Marrion-Phone: {
                                                              "id": 1589180142988,
                                                              "type": "kdeconnect.mousepad.request",
                                                              "body": {

**Comment by andyholmes** [comment]
Yep, remote input won't work on Ubuntu with Wayland, since they don't build with pipewire.

Sorry, you'll either have to use X11/Xorg or wait until Ubuntu builds GNOME Shell with PipeWire.

**Comment by Qooley** [comment]
thank you..i have switched to Ubuntu on X11
