### ISSUE TITLE
Screen Copy & Calling Feature

### ISSUE THREAD

**Issue by krishnaparit** [andyholmes/gnome-shell-extension-gsconnect#853]
> **BIG FAN !!**
> I like the idea of being able to seamlessly connect & communicate with the mobile device, and GSCONNECT has done great! Thank you for this.

**Feature request**
Requesting for a **ScreenCast** & **Calling** option.

**Screencast 💡**
I'm an android developer so I usually connect my device via USB or Wireless using ADB, and use **[SCRCPY](https://github.com/Genymobile/scrcpy)** to mirror & control the Android device, it would be great if the **[SCRCPY](https://github.com/Genymobile/scrcpy)/similar** feature was included in this project as well.

**Calling 💡**
I often switch to Windows 10 for designing work, the newest feature that I'm a big fan of is the calling feature provided by **Your Phone** application with a companion app installed in android similar to **KDE Connect**, it uses Bluetooth for transferring call just how an Android device connects to a car (here _car_ would be the system), it has the ability to receive and make a call. 

I believe these features would be a great addon to this already fantastic project.
Thank you!

**Comment by andyholmes** [comment]
Sorry, these features require changes to the KDE Connect protocol, so they must be discussed upstream with the KDE Connect team.

See https://bugs.kde.org for requesting features or https://invent.kde.org/kde/kdeconnect-android to get involved with contributing to the main project.
