### ISSUE TITLE
$GSCONNECT doesn't really set on user's shell

### ISSUE THREAD

**Issue by xcffl** [andyholmes/gnome-shell-extension-gsconnect#854]
> ***ATTENTION**: GSConnect only supports the latest, stable version of GNOME. We are no longer accepting bug reports for previous versions.*

**Describe the bug**

It is said in the documentation that the cli interface can be used like this
````
#!/bin/bash

echo $GSCONNECT;             # Path to the application (`daemon.js`)
echo $GSCONNECT_DEVICE_DBUS; # DBus object path, useful for Python, GJS or other script
echo $GSCONNECT_DEVICE_ID;
echo $GSCONNECT_DEVICE_NAME;
echo $GSCONNECT_DEVICE_ICON;

${GSCONNECT} --device ${GSCONNECT_DEVICE_ID} --file ${HOME}/test.jpg \
                                             --file ${HOME}/test.gif
````

But in user's shell where we actually can execute this command, `$GSCONNECT` is empty.

From the code, https://github.com/andyholmes/gnome-shell-extension-gsconnect/blob/6aee354c55671c3824ba6d2f02a859e6ad164587/src/service/device.js#L402

However, in [gio's documentation](https://lazka.github.io/pgi-docs/Gio-2.0/classes/SubprocessLauncher.html#Gio.SubprocessLauncher.setenv), it says
> Sets the environment variable variable in the environment of processes launched from this launcher. 

which in other words is that it only sets the env where gsconnect runs. And that shell IMO is the login shell rather than the shell in Gnome Terminal.

**Steps To Reproduce:**

1. Make sure a device is connected
2. Open Gnome Terminal
3. Execute `echo $GSCONNECT`

**Expected behavior**

````
~/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js
````

**Screenshots**

![image](https://user-images.githubusercontent.com/2216902/81630664-ca387b00-9438-11ea-83df-b1b99023354d.png)

**System Details (please complete the following information):**

 - **GSConnect version:** 37
   - **Installed from:** GitHub
 - **GNOME/Shell version:** 3.36
 - **Distro/Release:** Arch

**Comment by andyholmes** [comment]
This is the correct behaviour. As described in the wiki `$GSCONNECT` and other variable are only set in processes executed by the *Commands* plugin.

If you want to use these as general variables in user shells, you'll have to set them yourself in your `.bashrc` or elsewhere.

**Comment by xcffl** [comment]
Thanks, that makes sense.
