### ISSUE TITLE
Is there GSConnect API for sending custom notification to phone?

### ISSUE THREAD

**Issue by fsevenm** [andyholmes/gnome-shell-extension-gsconnect#855]
I am a big fan of this project. It's really helpful. Sometimes, I think why not create an API to give the ability to the user for sending a custom notification to Android devices. For example, I created a simple timer app, when the timer state is "break", I go walk around my house. And when the timer's state back to "focus" or a minute before it, a notification is sent to my android to notify me to get back to work. Instead, I make a special app for it, I think it's nice if GSConnect has the API to send push notification which perhaps can be triggered via shell. It may be helpful for others too.

**Comment by andyholmes** [comment]
You can either use `notify-send` which will be forwarded to devices, use the [CLI Interface](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/CLI-Scripting) or use the GActions exported over DBus which could be explored with [d-feet](https://flathub.org/apps/details/org.gnome.dfeet).

**Comment by fsevenm** [comment]
Great. I am sorry for my bad exploration of this extension so far. [CLI Interface](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/CLI-Scripting) gives me the idea to solve my problem. Run `./daemon.js --device <device_id> --ping` just works on my devices. However, running `./daemon.js --device <device_id> --notification=Notification test` gave me an error:
```
(GSConnect:22897): Gjs-WARNING **: 15:01:17.777: JS ERROR: Gio.IOErrorEnum: Error serializing GVariant with type string “mv” to the D-Bus wire format
_cliAction@./daemon.js:956:9
_cliNotify@./daemon.js:1044:9
vfunc_handle_local_options@./daemon.js:1118:17
@./daemon.js:1149:2
```
But for my case right now, **--ring** or **--ping** is enough to give me a notification to get back to work which is triggered automatically by my timer app. Really helpful, thanks.

**Comment by andyholmes** [comment]
Thanks, I added a fix for the notification bug you found, so that should work now too.
