### ISSUE TITLE
Extension not starting - GSettings schema undefined not found

### ISSUE THREAD

**Issue by ni-ka** [andyholmes/gnome-shell-extension-gsconnect#856]
> ***ATTENTION**: GSConnect only supports the latest, stable version of GNOME. We are no longer accepting bug reports for previous versions.*

**Describe the bug**

Extension does not start, shows error on extensions page.

**Steps To Reproduce:**

1. Install GSConnect
2. Go to https://extensions.gnome.org/extension/1319/gsconnect/

**Expected behavior**

Extension should start. In settings I can see service & device is found

**Support Log**

Please generate a support log ([Instructions](../wiki/Help#generate-support-log)) and paste any messages related to this issue between the two ``` lines below.

```
May 14 10:20:44 nk-zbook gnome-shell[1579825]: JS WARNING: [resource:///org/gnome/gjs/modules/core/overrides/Gio.js 552]: reference to undefined property "undefined"
May 14 10:20:44 nk-zbook gnome-shell[1579825]: JS ERROR: Extension gsconnect@andyholmes.github.io: Error: GSettings schema undefined not found
                                               _init@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:552:23
                                               @/home/nils/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/_gsconnect.js:120:22
                                               @/home/nils/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/extension.js:15:1
                                               _callExtensionInit@resource:///org/gnome/shell/ui/extensionSystem.js:398:13
                                               loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:332:27
                                               callback@resource:///org/gnome/shell/ui/extensionDownloader.js:220:39
                                               gotExtensionZipFile/<@resource:///org/gnome/shell/ui/extensionDownloader.js:106:13
```

**System Details (please complete the following information):**

 - **GSConnect version:** 37
   - **Installed from:** GNOME Extensions Website, tried aur install too
 - **GNOME/Shell version:** 3.36.2
 - **Distro/Release:** Manjaro

**GSConnect environment (if applicable):**

 - **Paired Device(s):** Huawei mate 20 pro
 - **KDE Connect app version:** 1.14.2
 - **Plugin(s):** [if the issue only occurs when using certain plugin(s)]

**Additional Notes:**

running on x11 currently

**Comment by andyholmes** [comment]
Sorry, I can't reproduce. Are you sure you didn't upgrade GSConnect without restarting GNOME SHell?

**Comment by l3chtan** [comment]
I get the same error:

```
Mai 15 07:43:36 gnome-shell[1152]: JS WARNING: [resource:///org/gnome/gjs/modules/core/overrides/Gio.js 552]: reference to undefined property "undefined"
Mai 15 07:43:36 gnome-shell[1152]: JS ERROR: Extension gsconnect@andyholmes.github.io: Error: GSettings schema undefined not found
                                   _init@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:552:23
                                   @/home/tibor/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/_gsconnect.js:118:22
                                   @/home/tibor/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/extension.js:15:1
                                   _callExtensionInit@resource:///org/gnome/shell/ui/extensionSystem.js:398:13
                                   loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:332:27
                                   callback@resource:///org/gnome/shell/ui/extensionDownloader.js:220:39
                                   gotExtensionZipFile/<@resource:///org/gnome/shell/ui/extensionDownloader.js:106:13
``` 

My System Details are:

- **GSConnect version** (as of today): 38
  - **Installed from**: GNOME Extensions Website
- **GNOME/Shell version**: 3.36.2
- **Distro/Release**: Arch Linux 

also running on X11. Additionally I have a second computer that I freshly set up in March which had the same issue from the beginning, it features the same system details. 

This has been going on for a while (maybe end of February or beginning of March). I didn't notice it at first, so it might be even longer. The menu vanished and I can only access the settings from the extension page. When opening the settings it says "Waiting for service", but finds my phone after a refresh. So basically the extension does work, it's just cumbersome not to have the user menu available and have to refresh the connection manually (possibly a different issue?).

I tried to restart GNOME Shell after first installing the extension on the new computer, and also after upgrading it. I also tried to completely remove the extension and reinstalling it.

Maybe there is some dependency missing or available in a wrong version in our Arch Linux (I don't know how much Manjaro adds to Arch Linux though) installations.

**Comment by Salohcins** [comment]
Also seeing this.  Wasn't specific to GSConnect version (I also am not sure when it started, but noticed it on both v37 and v38).

Distinctly noticed it when updating Ubuntu from 19.10 to 20.04, which meant going to Gnome Shell version 3.36.1.  Install was from Gnome Extensions Website.

Confusingly, error log appears to reference another extension in it (see below).

**Error messages from syslog are:**
`
gnome-shell[3522]: JS ERROR: Extension gsconnect@andyholmes.github.io: GLib.FileError: Failed to open file “/home/user/.local/share/gnome-shell/extensions/wintile@nowsci.com/org.gnome.Shell.Extensions.GSConnect.gresource”: open() failed: No such file or directory#012@/home/user/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/_gsconnect.js:126:14#012@/home/user/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/extension.js:15:1#012_callExtensionInit@resource:///org/gnome/shell/ui/extensionSystem.js:403:13#012loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:333:27#012callback@resource:///org/gnome/shell/ui/extensionDownloader.js:232:39#012gotExtensionZipFile/<@resource:///org/gnome/shell/ui/extensionDownloader.js:115:13
`

**Comment by andyholmes** [comment]
This sounds like there is a system version of GSConnect installed somewhere that wasn't configured properly. What does `locate gsconnect@andyholmes.github.io` show?

**Comment by andyholmes** [comment]
Actually, at second glance this seems i might be a duplicate of #820. Do you have wintile installed?

**Comment by ni-ka** [comment]
Yes, I do use wintile.

**Comment by l3chtan** [comment]
> Actually, at second glance this seems i might be a duplicate of #820. Do you have wintile installed?

Yes, disabling wintile made it work again. Thanks!

**Comment by ni-ka** [comment]
Thanks! I've commented on the issue over at wintile's repo
