### ISSUE TITLE
Add an option to change default file manager

### ISSUE THREAD

**Issue by LaurentOngaro** [andyholmes/gnome-shell-extension-gsconnect#857]
I'm using the extension  with Gnome 3.36.2 on Arch linux.
I've changed the default file manager application from nautilus to nemo.

There is a (Ubuntu) confirmed bug in the nemo file manager that makes file browsing impossible, because accessing to any folder or file of the connected device will crash nemo, so accessing files through the icon popup menu will fail.
A solution is to browse the phone content using another file manager. For me, Nautilus is working well

A good idea could be to add an option in the extension settings to change the application used to browse the phone content, instead of using the system default.

[The nemo bug report](https://bugs.launchpad.net/ubuntu/+source/nemo/+bug/1847888)

**Comment by andyholmes** [comment]
Hmm, this isn't exactly a trivial thing to do. It would make a lot more sense to get this fixed upstream in nemo.

You might want to open a bug with the actual project (https://github.com/linuxmint/nemo/issues), rather than hoping someone from Ubuntu will fix it downstream.

**Comment by LaurentOngaro** [comment]
Thanks for your answer, I've reported the bug on the nemo github, but I'm not sure it will be fixed quickly

**Comment by andyholmes** [comment]
Going to close this one, since the default browser isn't controlled by GSConnect and this is ultimately a bug in Nemo.
