### ISSUE TITLE
Can't send link to browser using the Firefox addon

### ISSUE THREAD

**Issue by atleta** [andyholmes/gnome-shell-extension-gsconnect#861]
> ***ATTENTION**: GSConnect only supports the latest, stable version of GNOME. We are no longer accepting bug reports for previous versions.*

I've just installed the Firefox addon and can't see a way to send the link directly to the browser. (After looking into the repo, I think I'd have to see a separate icon for this when I click the gsconnect icon on the browser toolbar, but I'm only seeing the SMS icon there. Opening the messaging app does work, though.) See screenshot below.

**Steps To Reproduce:**

1. Install the FF addon
2. Click the GSConnect button on the toolbar

**Expected behavior**

Send the link to the device. I guess I should see another icon in the drop down menu allowing to do thos.

**Screenshots**

![Selection_999(296)](https://user-images.githubusercontent.com/6267837/82112148-9c11ae80-974a-11ea-9aaa-f33c8f92407d.png)

**Support Log**

N/A

**Comment by andyholmes** [comment]
Is the *Share* plugin disabled? That's the only reason I can think the icon would be missing.

**Comment by atleta** [comment]
No, it seems it wasn't Thanks! (I've installed it yesterday and can't remember turning off any plugins, though. I enabled everything using the mobile app and that's it. Though, at first, I didn't enable 'send files', so I got a warning that I wouldn't be able to do so. Not sure if this could have caused turning off that plugin.)
