### ISSUE TITLE
Multiple media player notifications

### ISSUE THREAD

**Issue by jeetsrs** [andyholmes/gnome-shell-extension-gsconnect#867]
I have been noticing a persistant bug where in GSConnect shows multiple media player controls (while no music is playing currently). These don't go away even if I reboot the Android Phone (Pixel 3XL - fully updated). That said, they clear away when I reboot my PC (running Manjaro - fully updated).   

**Screenshots**
![image](https://user-images.githubusercontent.com/28262744/82820395-b133bf00-9e67-11ea-98d1-5881beeeb54b.png)

![image](https://user-images.githubusercontent.com/28262744/82820502-ec35f280-9e67-11ea-9291-1ed3b0818227.png)

**Support Log**
```
GSConnect Version: 38
GSConnect Install: user
GJS: 16402
XDG_SESSION_TYPE: x11
GDMSESSION: gnome
--------------------------------------------------------------------------------
-- Logs begin at Sun 2020-05-03 08:27:17 -05, end at Mon 2020-05-25 09:13:31 -05. --
May 25 09:13:16 tracker-store[96471]: OK
May 25 09:13:16 systemd[1699]: tracker-store.service: Succeeded.
May 25 09:13:21 gnome-shell[1771]: ../mutter/clutter/clutter/clutter-actor.c:10548: The clutter_actor_set_allocation() function can only be called from within the implementation of the ClutterActor::allocate() virtual function.
May 25 09:13:22 gnome-shell[1771]: ../mutter/clutter/clutter/clutter-actor.c:10548: The clutter_actor_set_allocation() function can only be called from within the implementation of the ClutterActor::allocate() virtual function.
May 25 09:13:22 gnome-shell[1771]: ../mutter/clutter/clutter/clutter-actor.c:10548: The clutter_actor_set_allocation() function can only be called from within the implementation of the ClutterActor::allocate() virtual function.
May 25 09:13:22 gnome-shell[1771]: ../mutter/clutter/clutter/clutter-actor.c:10548: The clutter_actor_set_allocation() function can only be called from within the implementation of the ClutterActor::allocate() virtual function.
May 25 09:13:22 gnome-shell[1771]: ../mutter/clutter/clutter/clutter-actor.c:10548: The clutter_actor_set_allocation() function can only be called from within the implementation of the ClutterActor::allocate() virtual function.
May 25 09:13:22 gnome-shell[1771]: ../mutter/clutter/clutter/clutter-actor.c:10548: The clutter_actor_set_allocation() function can only be called from within the implementation of the ClutterActor::allocate() virtual function.
May 25 09:13:27 dbus-daemon[786]: [system] Activating via systemd: service name='org.freedesktop.hostname1' unit='dbus-org.freedesktop.hostname1.service' requested by ':1.10256' (uid=1000 pid=96546 comm="gjs /home/ranjeets/.local/share/gnome-shell/extens" label="unconfined")
May 25 09:13:27 systemd[1]: Condition check resulted in First Boot Wizard being skipped.
May 25 09:13:27 systemd[1]: Condition check resulted in File System Check on Root Device being skipped.
May 25 09:13:27 systemd[1]: Condition check resulted in Store a System Token in an EFI Variable being skipped.
May 25 09:13:27 systemd[1]: Condition check resulted in Rebuild Hardware Database being skipped.
May 25 09:13:27 systemd[1]: Condition check resulted in Commit a transient machine-id on disk being skipped.
May 25 09:13:27 audit: AUDIT1334 prog-id=63 op=LOAD
May 25 09:13:27 audit: AUDIT1334 prog-id=64 op=LOAD
May 25 09:13:27 systemd[1]: Starting Hostname Service...
May 25 09:13:27 kernel: audit: type=1334 audit(1590416007.486:443): prog-id=63 op=LOAD
May 25 09:13:27 kernel: audit: type=1334 audit(1590416007.486:444): prog-id=64 op=LOAD
May 25 09:13:27 dbus-daemon[786]: [system] Successfully activated service 'org.freedesktop.hostname1'
May 25 09:13:27 systemd[1]: Started Hostname Service.
May 25 09:13:27 audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj==unconfined msg='unit=systemd-hostnamed comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
May 25 09:13:27 kernel: audit: type=1130 audit(1590416007.706:445): pid=1 uid=0 auid=4294967295 ses=4294967295 subj==unconfined msg='unit=systemd-hostnamed comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
May 25 09:13:30 systemd[1699]: Started flatpak-com.meetfranz.Franz-96581.scope.
May 25 09:13:31 appindicatorsupport@rgcjonas.gmail.com[1771]: Franz1, Impossible to lookup icon for 'Franz1_279-panel'
May 25 09:13:31 gnome-shell[1771]: JS ERROR: Exception in callback for signal: icon: Error: Argument 'filename' (type filename) may not be null
                                   _createIconByName@/home/ranjeets/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:406:26
                                   _cacheOrCreateIconByName@/home/ranjeets/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:368:14
                                   _updateIconByType@/home/ranjeets/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:574:18
                                   _updateIcon@/home/ranjeets/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:601:14
                                   _emit@resource:///org/gnome/gjs/modules/core/_signals.js:133:47
                                   _onPropertiesChanged/<@/home/ranjeets/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:220:22
                                   _onPropertiesChanged@/home/ranjeets/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:214:15
                                   refreshPropertyOnProxy/<@/home/ranjeets/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/util.js:51:19
May 25 09:13:31 pipewire[3763]: [W][000117187.955315][bluez5-dbus.c:2121 filter_cb()] Properties changed in unknown transport /org/bluez/hci0/dev_B8_D5_0B_67_99_93/sep1/fd1
```

**System Details (please complete the following information):**

 - **GSConnect version:** [38]
   - **Installed from:** [Package Manager]
 - **GNOME/Shell version:** [3.36.2]
 - **Distro/Release:** [Manjaro]

**GSConnect environment (if applicable):**

 - **Paired Device(s):** [Pixel 3XL] 
 - **KDE Connect app version:** [1.14.2]

**Comment by ferdnyc** [comment]
@jeetsrs 

What player(s) do those respond to, i.e. where did you actually play ARIZONA and Katy Perry?

If it was on a desktop (Linux-side) browser, and you have the Media Controls plugin enabled, what you're seeing are spurious re-re-mirrorings of the media control notification that KDE Connect generates for your browser media players. You can prevent those from circling back to the PC by disabling KDE Connect (ironically) in the  KDE Connect app "Notification sync" plugin settings.

If it was on your phone, those are probably synced Android playback notifications. So one option would be to turn off notification sync for that app, instead.

**Comment by jeetsrs** [comment]
I forgot to mention that both these were streamed to my Google home speakers (initiated by my phone). 

1. I was using my Plex server to stream Arizona (using the Plex app on the phone). 
2. And later my girlfriend was streaming Katy Perry from Spotify on the Google home speakers (again using my phone).
3. The third stream was actually just some random news site that had a video clip (I was reading this on my phone). 
4. There is a fourth BLANK media player control/notification on my Manjaro machine - which I have no idea about. It doesn't even show what was playing (as you see in the screen snapshot)

--
@ferdnyc  - I will try disabling the notifications for media players on my phone KDE Connect app, and report back.

**Comment by jeetsrs** [comment]
Update - changed the notification settings on the KDE Connect app on my phone to ignore the Plex app and Spotify app. This sort of fixed the issue - i no longer have any media player notifications (or controls) at all on my Manjaro PC :(.

Ideal situation would be that I get one (1) media player control notification (not multiple duplicate notifications) on my PC and be able to control the music (pause, play, previous/next tracks etc from my PC notification panel). 

Any recommendations on how I do that without having phantom media player notifications which don't disappear despite the music being stopped and the apps on the phone being closed?

**Comment by jeetsrs** [comment]
Update - disabling the notifications for the Plex app and the Spotify app on my phone (inside KDE Connect) seems to have resolved this issue. 

@ferdnyc  - thank you for the recommendation!

**Comment by ferdnyc** [comment]
> I forgot to mention that both these were streamed to my Google home speakers (initiated by my phone). 
> 
> 1. I was using my Plex server to stream Arizona (using the Plex app on the phone). 
> 2. And later my girlfriend was streaming Katy Perry from Spotify on the Google home speakers (again using my phone).
> 3. The third stream was actually just some random news site that had a video clip (I was reading this on my phone). 
> 4. There is a fourth BLANK media player control/notification on my Manjaro machine - which I have no idea about. It doesn't even show what was playing (as you see in the screen snapshot)

Ok, yeah, that's kind of what I was getting at, especially the fourth item.

You see how the divider between the fourth media player entry and the notification that follows it is thicker than normal? That's because all four of the items above are _not_ notifications at all. They're GNOME Shell media controls, a standard feature since I believe 3.32 that incorporates player controls for any available MPRIS player into the notification area. If you have MPRIS enabled in VLC, for instance, you'll also see transport controls there for whatever it's playing, while it's playing.

In recent versions of Chrome and I believe Firefox, HTML5 media players will also have MPRIS controls exported by the browser.

But if the playback in question was on your phone, the culprit is still most likely KDE Connect creating playback notifications that end up syncing back to the desktop via GSConnect.
