### ISSUE TITLE
pycompile error, ubuntu 20.04, Plasma Desktop

### ISSUE THREAD

**Issue by abu2020** [andyholmes/gnome-shell-extension-gsconnect#870]
> ***ATTENTION**: GSConnect only supports the latest, stable version of GNOME. We are no longer accepting bug reports for previous versions.*

**Describe the bug**
during installation I fund this error:
```
Setting up python-gi (3.36.0-1) ...
/var/lib/dpkg/info/python-gi.postinst: /usr/bin/pycompile: /usr/bin/python2: bad interpreter: Permission denied
dpkg: error processing package python-gi (--configure):
 installed python-gi package post-installation script subprocess returned error exit status 126
```

I think the bug is, correcting the above path as this I did:

**Steps To Reproduce:**

1. Go to ```/var/lib/dpkg/info/python-gi.postinst```
this is its original script:
```
#!/bin/sh
set -e
#Automatically added by dh_python2:
if which pycompile >/dev/null 2>&1; then
        pycompile -p python-gi
fi
#End automatically added section
```
2. Error is 'python2 should be changed to python3'
3. Change I made is 'pycompile  >>  py3compile'
```
#!/bin/sh
set -e
#Automatically added by dh_python2:
if which py3compile >/dev/null 2>&1; then
        py3compile -p python-gi
fi
#End automatically added section
```
4. and it will be run without error.

**Comment by andyholmes** [comment]
Sorry, how does this relate to GSConnect?

**Comment by abu2020** [comment]
because, this error occurred while I installed gsconnect.

**Comment by abu2020** [comment]
as error shows:
```/usr/bin/python2: bad interpreter```
so since the pycompile is in python2 version, I changed it to py3compile and it worked.

**Comment by andyholmes** [comment]
Where did you install GSConnect from? This sounds like a bug in an upstream Ubuntu package. Ubuntu 20.04 still ships GSConnect v20 which is very, very old.

I'd recommend you open a bug in [Luanchpad](https://launchpad.net/ubuntu/+source/gnome-shell-extension-gsconnect) for this.

**Comment by ferdnyc** [comment]
More importantly, isn't "Plasma Desktop" KDE? How are you even going to use a Gnome Shell extension with that? Surely the _actual_ KDE Connect (for which GSConnect is a compatible implementation in the Gnome Shell environment) would be a better choice.

**Comment by abu2020** [comment]
> More importantly, isn't "Plasma Desktop" KDE? How are you even going to use a Gnome Shell extension with that? Surely the _actual_ KDE Connect (for which GSConnect is a compatible implementation in the Gnome Shell environment) would be a better choice.

unfortunately, I could not connect via my KDE connect, so I installed GSConnect and I encountered the above issue and then solve it as mentioned. But as you know it does not perform in KDE.
