### ISSUE TITLE
gsconnect prevents lock screen

### ISSUE THREAD

**Issue by veipone** [andyholmes/gnome-shell-extension-gsconnect#871]
When using gsconnect, my Ubuntu 20.04 system can't lock the screen. It seems to try, but the screen flickers, and then the system returns to an "unlocked" status.

I'm using the GSConnect provided by extensions.gnome.org:
https://extensions.gnome.org/extension/1319/gsconnect/

**Comment by andyholmes** [comment]
Are there any errors in your logs indicating why this happens or how it relates to GSConnect?

**Comment by veipone** [comment]
Please find attached the gsconnect log.
I pressed the lock screen button on the gnome-panel around 08:39:20. The system returned to an unlocked status within 08:39:26. 
I don't know why the error occurs, maybe a segmentation fault in libst-1.0.so (at 08:39:21)? 


[gsconnect-log.txt](https://github.com/andyholmes/gnome-shell-extension-gsconnect/files/4750359/gsconnect-log.txt)

**Comment by andyholmes** [comment]
And this only happens if GSConnect is enabled? If so, you will have to inspect or find somewhere to upload the core dump to know why the segfault is happening.

**Comment by andyholmes** [comment]
Going to close this one since we haven't heard anything in sometime and there's no definite evidence this is caused by GSConnect and not another extension.
