### ISSUE TITLE
Message history messed up since 3392fbd

### ISSUE THREAD

**Issue by terencode** [andyholmes/gnome-shell-extension-gsconnect#877]
Since 3392fbd3360cdf34ba79ceeed6c747759fa0d366, the SMS history as well as message scrolling is broken and displays what looks like unsorted messages.

What I saw in the log:
```
JS WARNING: [/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/ui/messaging.js 712]: reference to undefined property "date"
```
Also this while scrolling:
```
Drawing a gadget with negative dimensions. Did you forget to allocate a size? (node row owner GtkListBoxRow)
```

**Comment by andyholmes** [comment]
I think this was because of #875 moving all message properties from the rows to the `message` property *of* the row. Should be a a relatively simple fix of finding those accesses and maybe adding a dummy message to the "pending" row.

cc @dmeltzer
