### ISSUE TITLE
Mount mobile device and sending files from mobile device no longer working.

### ISSUE THREAD

**Issue by wildcard-f8** [andyholmes/gnome-shell-extension-gsconnect#880]
I can no longer mount my mobile phone and I can't send files from my phone to my laptop but I can still send files from my laptop to my phone.

**Support Log**

Please generate a support log ([Instructions](../wiki/Help#generate-support-log)) and paste any messages related to this issue between the two ``` lines below.

```

GSConnect Version: 38
GSConnect Install: user
GJS: 16402
XDG_SESSION_TYPE: x11
GDMSESSION: ubuntu
--------------------------------------------------------------------------------
-- Logs begin at Thu 2020-06-18 06:30:32 PST, end at Thu 2020-06-18 09:06:08 PST. --
Jun 18 09:06:03 dbus-daemon[2200]: [session uid=1000 pid=2200] Activating service name='org.gnome.Nautilus' requested by ':1.195' (uid=1000 pid=2528 comm="/usr/bin/gnome-shell " label="unconfined")
Jun 18 09:06:03 dbus-daemon[2200]: [session uid=1000 pid=2200] Successfully activated service 'org.gnome.Nautilus'
Jun 18 09:06:04 nautilus[15962]: Called "net usershare info" but it failed: Failed to execute child process “net” (No such file or directory)
Jun 18 09:06:08 gnome-shell[2528]: ../clutter/clutter/clutter-actor.c:10548: The clutter_actor_set_allocation() function can only be called from within the implementation of the ClutterActor::allocate() virtual function.

```

 - **GSConnect version: 38
 - **GNOME/Shell version: 3.36.2
 - **Distro/Release: Ubuntu 20.04

 - **Paired Device: Galaxy S9+
 - **KDE Connect app version: 1.14.2

Both functions used to work even after upgrading from Ubuntu 18.04 to 20.04. I don't know when it stopped working until I needed to use them today.

**Comment by Mannshoch** [comment]
I have the problem that I have first klick on mount and after that klick again to solect the mountpath I setup in kdeconnect.
Also interesting, mounting only donot work, I have to choos the name in gsconnect and open the path that way. The problem is, that the mounted device is empty and gsconnet have to open the sub-directory.

**Comment by andyholmes** [comment]
Have you tried restarting the Android app? This sounds related to #478.

**Comment by wildcard-f8** [comment]
Restarting the Android app worked! I can't believe it was that simple. Thanks!

**Comment by ferdnyc** [comment]
Must... resist.. temptation.. to create... "HaveUTriedTurningItOffAndOnAgain?"... tag. 😉
