### ISSUE TITLE
entry in usermenu with active "show indicator" not hidden

### ISSUE THREAD

**Issue by jens-t** [andyholmes/gnome-shell-extension-gsconnect#89]
the entry in the usermenu with active "show indicator" is not hidden. so if i activate this setting i have basically both: an almost empty usermenu section / additional gsconnect icon and the indicator ...

see screenshot:
![bildschirmfoto von 2018-05-03 21-45-51](https://user-images.githubusercontent.com/9143480/39599274-98973f0a-4f1b-11e8-8303-947803c39bfe.png)

seems like a bug, or is this intentional? i would like to hide the user menu customizations ...

**Comment by andyholmes** [comment]
This is intentional. The GSConnect system indicator is for indicating the service status (which is different from the shell extension), and the User Menu entry *Mobile Settings* is for opening the extension settings, while the indicators can only open the device settings. The User Menu is also likely be expanded in future releases to include other extension/service wide options

**Comment by jens-t** [comment]
Ah, thanks for the Info, makes sense now! But i would still like an option to hide this, since i can also get to the extension settings over gnome software center and gnome tweak tools. And an indicator for the status of the service isn't as important for me as a clean usermenu. what do you think, would you add such a feature as opt-in or accept a PR for this?

**Comment by andyholmes** [comment]
In the future the service icon and user menu entry will be required for more facilities that won't be accessible elsewhere, so an option to hide them would have to be reverted eventually anyways. If it's essential to hide them now, you can always just remove the code that adds them in your local copy, but I won't be changing that in upstream for that reason.

**Comment by jens-t** [comment]
Then the additional facilities will be hidden in the future too. i see no problem with that, as it would be an opt-in option. It's essential now and in the future. But yeah, doesn't sound like you will change your mind about not adding this.

If i remove that code in my local copy, i have to remove it, after every update. And the next user, that wants to hide this, would also need to remove this by hand. So i would have to maintain a fork, just for that. But i dont think there is another way.

Closing here.
