### ISSUE TITLE
I would like to right click on a link and instead of Open in Browser, I would like my Android Phone handle the link and open it with the respective app

### ISSUE THREAD

**Issue by bitcoinuser** [andyholmes/gnome-shell-extension-gsconnect#890]
Hi,

Great extension but I have an issue:

I would like to right click on a link and instead of Open in Browser, I would like my Android Phone handle the link and open it with the respective app.
For example: I would like to right click on this kind of link (lightning:lnbc1100n1p0spszep..) This is a Bitcoin Lightning Invoice (Example how to generate this invoice: https://strike.me/strike). 
So when I go to Open in Browser, appear a https link and open in Browser instead open my Bitcoin wallet:

![photo_2020-07-04_14-48-28](https://user-images.githubusercontent.com/1178856/86518169-a32d7280-be05-11ea-8a5e-da50f79ce4a0.jpg)

**Comment by andyholmes** [comment]
This would have to be fixed in `kdeconnect-android`, since we don't control what Android does with links once it receives them. You can open a new bug at https://bugs.kde.org/enter_bug.cgi

**Comment by bitcoinuser** [comment]
Hi @andyholmes on Kde Connect I opened the issue: https://bugs.kde.org/show_bug.cgi?id=423859
And someone commented with:

I don't see kdeconnect-android doing anything wrong, so it's either:
1) The desktop side prepends https:// to the URL before sending
2) The receiving Android app is not set up properly

**Comment by andyholmes** [comment]
It looks like we do amend links after all, I will have a look into whether this is for good reason.

**Comment by andyholmes** [comment]
Thanks for reporting, should be fixed in cf58879

**Comment by bitcoinuser** [comment]
Hi, thanks. When the extension will be updated for Chrome?

**Comment by andyholmes** [comment]
The web extension gets updated very rarely, as it doesn't really contain any functionality. The GNOME extension is updated when there's been a reasonable amount of progress or a critical fix pushed.

It's pretty straighforward to [build from git](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Installation#install-from-git) though:

[gsconnect@andyholmes.github.io.zip](https://github.com/andyholmes/gnome-shell-extension-gsconnect/files/4874188/gsconnect%40andyholmes.github.io.zip)
