### ISSUE TITLE
can't connect Samsung Note 2 with pc

### ISSUE THREAD

**Issue by abuakram** [andyholmes/gnome-shell-extension-gsconnect#894]
I am running Ubuntu 20.02 using gsconnect extension... all my devices connect flawlessly, except:
Samsung Note 2...

What approach should I take to find out the issue???

Thanks in advance

**Comment by andyholmes** [comment]
1. Fill out the information in the issue template:
   
   **System Details (please complete the following information):**
  
   - **GSConnect version:** [e.g. 35, 36, ... (displayed in the GSConnect "About" window)]
     - **Installed from:** [e.g. GNOME Extensions Website, GitHub, Package Manager, ...]
   - **GNOME/Shell version:** [e.g. 3.36, ...]
   - **Distro/Release:** [e.g. Ubuntu 18.04, Fedora 29, Arch, ...]

   **GSConnect environment (if applicable):**

   - **Paired Device(s):** [e.g. Galaxy Note 8, Pixel 2, Honor 9, ...]
   - **KDE Connect app version:** [e.g. 1.12.7]
   - **Plugin(s):** [if the issue only occurs when using certain plugin(s)]

2. Generate a support log, as [described in the Wiki](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Help#generate-support-log)

**Comment by abuakram** [comment]
* GSConnect version: 39
* gnome extensions website
* gnome-shell version: 3.36.3
* Ubuntu 20.04
* Galaxy Note 2
*KDE Connect version: 1.14.2

The issue is: The devices can't see each other... neither Note 2 shows up in GSConnect nor the other way around... 
While I have atleast 4 devices connected to the pc (galaxy note 5, huawei, htc ... ). 
I tried adding devices with IP... But failed too.

**Comment by abuakram** [comment]
[gsconnect.txt](https://github.com/andyholmes/gnome-shell-extension-gsconnect/files/4940665/gsconnect.txt)

**Comment by andyholmes** [comment]
> Jul 18 00:58:27 gjs[3870]: JS ERROR: Gio.TlsError: Error performing TLS handshake: A packet with illegal or unsupported version was received.

This looks like your Note 2 is using a version of TLS encryption (or a cipher) that is no longer supported in GLib. Basically the version of Android your tablet is running is too old for us to support. Sorry about that :frowning_face: 

If you can find an Android ROM from LineageOS or something and upgrade your tablet that should fix this, but otherwise there's not much we can do.

**Comment by abuakram** [comment]
Indeed... Note 2 runs with android version 4.4 ... Surprisingly, it worked before... since version 37 it stopped...
Guess have to take a look on LineageOS...

THANKS ALOT

**Comment by andyholmes** [comment]
No, problem. I think this change happened recently in GLib as everyone is moving to TLS 1.3 and deprecating all the older versions.
