### ISSUE TITLE
can't get the browse files feature to work

### ISSUE THREAD

**Issue by jens-t** [andyholmes/gnome-shell-extension-gsconnect#90]
can't get the "browse files" feature to work/show:
- the icon in the indicator menu isn't showing
- the nautilus extension doesn't add a context menu entry
... as if the feature or the extension isn't even activated

additional infos:
- the nautilus extension symlink is in the right place
- had a look into the debug log output, but found no hint at what is going wrong ...
- i'm running ubuntu 18.04 and checked that all dependencies are installed.
- sending files directly with the "share" feature works fine in both directions

are there other things i can check?

**Comment by andyholmes** [comment]
The *Browse Files* and *Share* plugins are two different plugins, and the Nautilus extension only applies to the *Share* plugin.

Once *Share* is enabled in the device's plugins and *Nautilus Integration* is enabled in *Preferences* Nautilus will have to be restarted  (eg, by clicking *Restart* in the notification popup, or running `nautilus -q` in a terminal). Then it should show connected and paired devices in the context menu in the context menu for files (not directories), but only allows sending files directly, not browsing.

The *Browse Files* plugin requires `sshfs` to be installed and should be enabled separately in the local device's plugin list, as well as the remote device's *Filesystem expose* plugin in the Android App. Can you confirm this has been done?

**Comment by jens-t** [comment]
> The Browse Files and Share plugins are two different plugins, and the Nautilus extension only applies to the Share plugin.

Ah ok, my mistake, thought the browse plugin is coupled with the nautilus extension. so nautilus plugin is working fine with activated share plugin.

> The Browse Files plugin requires sshfs to be installed and should be enabled separately in the local device's plugin list, as well as the remote device's Filesystem expose plugin in the Android App. Can you confirm this has been done?

Yeah, had checked all this. after some more testing, reinstalling some things and restarting it now works, can't really say what the actual problem was, but thanks for your help!

Closing the issue here.
