### ISSUE TITLE
Device connected via USB tethering is not found by GSConnect

### ISSUE THREAD

**Issue by axelsimon** [andyholmes/gnome-shell-extension-gsconnect#900]
This is small thing, but thought i'd report anyway.

When a phone and laptop are on the same network, no problems, they find each other. However, when the phone is connected to the laptop via USB and providing networking via Ethernet-over-USB (ie: USB tethering), then GSconnect can't find the phone and says the device is disconnected.

Not sure if this is easy to fix, but thought it was worth mentioning :slightly_smiling_face: 

**System Details (please complete the following information):**
 - GSConnect version: 39
   - Installed from: extensions.gnome.org

**Comment by ferdnyc** [comment]
Hmm. I guess the question becomes, what does the network link "look like" to GSConnect, with that setup? Can you ping the phone from the linux system? Reach linux from the phone via SSH? What's the firewall configuration look like on the linux side? (You may need to open ports  1716 and 1739-1764 in the ether-over-USB-facing side of your system firewall, explicitly.)

As far as I know GSConnect isn't doing anything that would interfere with that sort of connection, but it also isn't doing anything special to _enable_ it, and there may be some prep needed.

**Comment by andyholmes** [comment]
Going to close this one since it's been almost a month with no reply.

**Comment by colorizer** [comment]
Hi,
I am facing the similar issue (Right now on Fedora 33). What kind of info is required by the team to solve this one? I might be able to provide.

**Comment by colorizer** [comment]
I'm able to ping my phone. No problem in that direction.

**Comment by colorizer** [comment]
Hi,
I just found out that installing gsconnect through extensions.gnome.org causes this problem. Installing directly from the repository ( sudo dnf install gnome-shell-extension-gsconnect.x86_64 ) solved it.
