### ISSUE TITLE
Can't connect to my phone, not even with IP address and firewall is supposed to be disabled

### ISSUE THREAD

**Issue by doronbehar** [andyholmes/gnome-shell-extension-gsconnect#901]
**Describe the bug**

I can't find out / debug why gsconnect won't connect to my phone. I have firewall disabled ~~(pretty sure)~~ I am sure, because kdeconnectd works fine.

**Steps To Reproduce:**

1. Install gsconnect.
2. Install kdeconnect on Android
3. Make sure kdeconnectd doesn't work.
4. Try to find phone in list of devices (and fail).
5. Try to find computer via kdeconnect's app (and fail).
6. Try to connect via IP address with both devices (and fail).

**Expected behavior + Screenshots**

In this screen:

![Screenshot from 2020-07-30 19-21-41](https://user-images.githubusercontent.com/10998835/88947942-cc181a80-d280-11ea-8857-37845d35c75e.png)

I expect to see my phone.

**Support Log**

[gsconnet-log1.txt](https://github.com/andyholmes/gnome-shell-extension-gsconnect/files/5003126/gsconnet-log1.txt)

Didn't notice something interesting... :/

**System Details (please complete the following information):**

 - **GSConnect version:** 38
   - **Installed from:** NixOS' package manager.
 - **GNOME/Shell version:** 3.36.4
 - **Distro/Release:** [e.g. Ubuntu 18.04, Fedora 29, Arch, ...]

**GSConnect environment (if applicable):**

 - **Paired Device(s):** None.
 - **KDE Connect app version:** 1.14.2 From F-Droid
 - **Plugin(s):** None

**Additional Notes:**

NixOS is weird beast, it may very well be that my setup is what's wrong - it was [reported in 2019](https://github.com/NixOS/nixpkgs/issues/40474#issuecomment-480249045) that gsconnect works on our distro, but I don't have yet other proofs.

**Comment by andyholmes** [comment]
Can you ping the phone from your desktop?

Can you [Generate a Support Log](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Help#generate-support-log) as described in the Wiki? If you are doing so, there should either be messages like below or an error message:

```
[/service/protocol/lan.js:broadcast:385]: "Broadcasting to LAN"
```

What is the output of `lsof`? It should be as below:

```
$ lsof -i UDP:1716
COMMAND    PID   USER   FD   TYPE  DEVICE SIZE/OFF NODE NAME
gjs     217460 andrew   15u  IPv6 3940137      0t0  UDP *:xmsg

$ lsof -i TCP:1716
COMMAND    PID   USER   FD   TYPE  DEVICE SIZE/OFF NODE NAME
gjs     217460 andrew   21u  IPv6 3940138      0t0  TCP *:xmsg (LISTEN)
```

If so, then there is a problem with your firewall, iptables or local network.

**Comment by doronbehar** [comment]
OK the problem was indeed the fact I had kdeconnect still installed. From some reason, it was running on startup, although I remember and I double checked that it was not listed in the "startup applications" of Gnome Tweaks. Even after I killed `kdeconnecd` with `htop`, GSConnect wasn't able to find any devices which is peculiar. I pressed the refresh button a few times and still I didn't find in the logs the message: `Broadcasting to LAN`.

Thanks for your quick reply and above all for creating this superb application (I can't tell you how happy I am to have this program :grinning:). You are the best!

Perhaps to help others in the future, I took the liberty to edit the [Help wiki page](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Help). I felt it would be proper to put the `lsof` debugging instructions at the "Connecting an Android Device" section, which makes the ["Network Error" section](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Help#LanError) a bit redundant. You wrote right above it:

> These problems are automatically detected. Do not edit this section.

So I didn't delete it, though I feel there's no point to it now.

Additionally, It might be nice to emphasize the fact that GSConnect is a complete _replacement_ for KDE connect on the desktop. It took me some time to realize that, and even yesterday I wasn't sure of this. Hence my README PR.

**Comment by andyholmes** [comment]
> These problems are automatically detected. Do not edit this section.

This message is in the Wiki because if you run GSConnect with KDE Connect installed you will get an urgent, blocking notification. If you click that notification it will open a link directly there. Did you not get that notification?

**Comment by doronbehar** [comment]
> KDE Connect installed you will get an urgent, blocking notification. If you click that notification it will open a link directly there. Did you not get that notification?

Not at all. I suspect it's because NixOS wraps some binaries so they will run in their proper environment, and due to this, in the process viewer, it was not the executable `kdeconnectd` which was running but `.kdeconnectd-wrapped`.

**Comment by andyholmes** [comment]
GSConnect doesn't check for `kdeconnectd`, only if it can bind to port 1716. GSConnect and KDE Connect are really the only applications that use that port, so unless there's some other port binding behaviour that NixOS changes it should still show.

In any case, the Wiki note will have to stay otherwise it will become a broken link for other users. For the README PR, I have left a note.

**Comment by doronbehar** [comment]
> unless there's some other port binding behaviour that NixOS changes it should still show.

Peculiar - I have triple checked with `lsof` that 1716 wasn't used. Is there a range of ports possibly used by GSConnect/KDEConnect? It is suggested by `1716-1764` used in the [detected problems help page section](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Help#LanError).

**Comment by andyholmes** [comment]
> Peculiar - I have triple checked with lsof that 1716 wasn't used. Is there a range of ports possibly used by GSConnect/KDEConnect? It is suggested by 1716-1764 used in the detected problems help page section.

Port 1716 is used to broadcast UDP packets, listen for incoming TCP connections and transmit packets, so failing to bind to that port is a critical failure for the LAN backend. Ports 1739-1764 are used for file transfers (including notification icons, MPRIS album art, etc) and SFTP connections, but aren't checked since they're used dynamically.

I haven't looked at the GSConnect package for NixOs in awhile, but I guess it's possible that NixOS is describing what ports it's allowed to use and that conflicts with the KDE Connect package. A NixOs developer would probably know more about that.

**Comment by tad-lispy** [comment]
I'd also like to thank you for this wonderful extension. I had similar problems on NixOS and was able to fix them by configuring firewall. This issue pointed me in right direction. For others who may struggle:

```sh
sudo iptables -I INPUT -i wlp1s0 -p udp --dport 1714:1764 -m state --state NEW,ESTABLISHED -j ACCEPT
sudo iptables -I INPUT -i wlp1s0 -p tcp --dport 1714:1764 -m state --state NEW,ESTABLISHED -j ACCEPT
sudo iptables -A OUTPUT -o wlp1s0 -p tcp --sport 1714:1764 -m state --state NEW,ESTABLISHED -j ACCEPT
sudo iptables -A OUTPUT -o wlp1s0 -p udp --sport 1714:1764 -m state --state NEW,ESTABLISHED -j ACCEPT 
```

You may need to change `wlp1s0` to the name of an appropriate network interface.
