### ISSUE TITLE
Support for latest Gnome

### ISSUE THREAD

**Issue by voxik** [andyholmes/gnome-shell-extension-gsconnect#904]
**Is your feature request related to a problem? Please describe.**
Would it be possible to be more relaxed about Gnome versions? I am Fedora Rawhide user and that means this extension is not usable for me just because (as far as I can tell) the extension is paranoid about Gnome version support. I'd rather have half broken gsconnect with ability to test and report he issue then don't have the extension at all. Would it be possible to reconsider this?

**Describe the solution you'd like**
Restrict the gnome version only when it is know to cause severe issues.

**Describe alternatives you've considered**
Currently, I am "using" the Fedora packaged version, but I'll have to reconsider to be able to manually tweak the restriction.

**System Details (please complete the following information):**
 Fedora Rawhide

**Comment by andyholmes** [comment]
I'm not sure what you mean by "restriction" exactly. As far as I know, no distributions are respecting the `shell-version` key in `metadata.json`. You can double-check the `/org/gnome/shell/org.gnome.shell disable-extension-version-validation` dconf key to be sure though.

I don't have any contact with the maintainer of the Fedora package, but I also don't see anything in the [package spec](https://src.fedoraproject.org/rpms/gnome-shell-extension-gsconnect/blob/master/f/gnome-shell-extension-gsconnect.spec) indicating they've made any changes from our upstream sources.

**Comment by voxik** [comment]
This is the [restriction](https://github.com/andyholmes/gnome-shell-extension-gsconnect/blob/96bcf1e7c3883dc5f3743a8023e246df93fc2932/data/metadata.json.in#L7). This specifies the (highest?) gnome shell version supported and it says 3.36, while in Fedora Rawhide, there is already Gnome Shell 3.37.3. I have tried to change this field to `3.38` and it indeed enabled the extension on my Rawhide.

**Comment by andyholmes** [comment]
Can you confirm the `/org/gnome/shell/disable-extension-version-validation` dconf key is set to `false`? If not I'd like to find out where this is being imposed, since the `shell-version` key is generally only used by extensions.gnome.org these days

**Comment by voxik** [comment]
So this is the settings:

~~~
$ gsettings get org.gnome.shell disable-extension-version-validation
true
~~~

It is in default value. What I don't understand is why it should be `false`? `true` appears to do what I would expect, but maybe it doesn't ...

**Comment by ferdnyc** [comment]
@voxik 
It should not be `false`, though if it WAS that could've explained your issue.

Given that it's _not_ set to `false`, you shouldn't have been having any issues using the extension in GNOME 3.37 — the old restriction (when that key didn't exist, so it was `false` _implicitly_ by not being a thing) was lifted ages and ages ago, like around Fedora 21. Merely adding `3.38` to the extension's versions list _should_, as far as any of us are aware, both (a) have been completely unnecessary, and (b) have had no effect on the extension's compatibility with Rawhide GNOME Shell. The extension certainly doesn't check that value, or do anything differently based on what's listed there. It's purely housekeeping metadata for SweetTooth, AKA extensions,gnome.org.

**Comment by ferdnyc** [comment]
Now, given that the bug you're reporting, if there is a bug, is not the one you initially believed it was, let's start over at the beginning.

You were trying to do: _________
Because you wanted to: __________
And you expected this to happen: ___________
But instead, this happened: ____________

So you changed this: ____________
And the result was this: _______________

**Comment by ferdnyc** [comment]
_Extra credit — Standard boilerplate addendum for open-source project feedback:_

And if we don't fix it immediately, you will:
- [ ] Campaign to have the extension deleted from the distro package repository
- [ ] Post a disparaging YouTube video
- [ ] Tell Reddit and/or blog about how much better `${similar_software_alternative}` is
- [ ] Threaten to sic your lawyers on the developers
- [ ] Demand a full refund

(Just kidding! ...Mostly.)

**Comment by voxik** [comment]
You were trying to do: 
I have installed gnome-shell-extension-gsconnect-39-3.fc33.x86_64 on Fedora Rawhide

Because you wanted to:
To be able to control my phone from computer, but mainly to be able to easily share pictures.

And you expected this to happen:
I expected gsconnect to work.

But instead, this happened:
It was mostly not loaded at all.

So you changed this: 
So I changed `"shell-version"` in `/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/metadata.json` from `[ "3.36" ],` to `[ "3.38" ],`

And the result was this:
And the extension is now loaded just fine and mostly works.

And if we don't fix it immediately, you will:
I will consider to uninstall the extension, because there is no point to have extension which works just in narrow period of time, when the major version of gnome-shell is in Fedora Rawhide and it is supported by gsconnect. And as a bonus, I'll stop bothering you with requests like this (seriously, I won't report issues I don't encounter :grin:)

**Comment by voxik** [comment]
> The extension certainly doesn't check that value, or do anything differently based on what's listed there.
It would be surprising if the extension checked the value somehow. But g-s might care. So there are two possible action items IMO:

1. You will bump the version, because it does not mean anything to gsconnect and it should be fine even if it is `3.99`
2. I'll open Gnome ticket asking about the purpose and if it is wrongly checked somewhere.

**Comment by voxik** [comment]
>     2. I'll open Gnome ticket asking about the purpose and if it is wrongly checked somewhere.

https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/3050

**Comment by voxik** [comment]
So I did a few more experiments, reinstalled the extension and what not and applying just the Tweener patch (#905), the extension loads. I am not sure anymore, what I did last time, because I reported the Tweener issue one day later. Going to close this now until I have more evidence what was wrong. Sorry and thank you for you support.
