### ISSUE TITLE
Tweener was removed from Gnome 3.37+

### ISSUE THREAD

**Issue by voxik** [andyholmes/gnome-shell-extension-gsconnect#905]
**Describe the bug**

Tweener was removed from Gnome 3.37+:

https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/1200

and the replacement should be clutter animations.

As a workaround, removing `const Tweener = imports.tweener.tweener;` seems to be good start to make the gsconnect work, but there are still some errors reported, which requires fixing.

**Comment by andyholmes** [comment]
Thanks for reporting, should be fixed in acf0aa3

**Comment by voxik** [comment]
Thx, but there are still two places remaining:

~~~
$ grep -R Tweener
src/service/ui/messaging.js:const Tweener = imports.tweener.tweener;
src/service/ui/messaging.js:            Tweener.addTween(this._vadj, {
src/service/components/pulseaudio.js:const Tweener = imports.tweener.tweener;
src/service/components/pulseaudio.js:        Tweener.removeTweens(this);
src/service/components/pulseaudio.js:            Tweener.addTween(this, {
src/service/components/pulseaudio.js:            Tweener.addTween(this, {
~~~

**Comment by andyholmes** [comment]
These are [shipped with GJS](https://gitlab.gnome.org/GNOME/gjs/-/tree/master/modules/script/tweener), so won't be affected by gnome-shell removing them.
