### ISSUE TITLE
Mount does not  longer work after upgrade to version 40

### ISSUE THREAD

**Issue by didierga** [andyholmes/gnome-shell-extension-gsconnect#916]
Mount does not  longer work after upgrade to version 40

Mount previously worked fine with version 39 and works fine after downgrade to version 39

**Support Log**

GSConnect Version: 40
GSConnect Install: user
GJS: 16404
XDG_SESSION_TYPE: x11
GDMSESSION: gnome-xorg
--------------------------------------------------------------------------------
-- Logs begin at Sat 2020-07-11 02:05:43 CEST, end at Sat 2020-08-15 12:56:18 CEST. --
août 15 12:56:02 systemd[1774]: dbus-:1.2-org.gnome.gedit@3.service: Succeeded.
août 15 12:56:09 systemd[1774]: Started dbus-:1.2-org.gnome.gedit@4.service.
août 15 12:56:09 gnome-shell[2014]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x38000f8
août 15 12:56:12 systemd[1774]: dbus-:1.2-org.gnome.gedit@4.service: Succeeded.
août 15 12:56:17 gnome-shell[2014]: ../clutter/clutter/clutter-actor.c:10556: The clutter_actor_set_allocation() function can only be called from within the implementation of the ClutterActor::allocate() virtual function.
août 15 12:56:18 gnome-shell[2014]: JS ERROR: TypeError: this.box.get_children is not iterable
                                     _onMapped@/home/didier/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/shell/gmenu.js:563:32
                                     onComplete@resource:///org/gnome/shell/ui/boxpointer.js:153:22
                                     _makeEaseCallback/<@resource:///org/gnome/shell/ui/environment.js:75:13
                                     _easeActor@resource:///org/gnome/shell/ui/environment.js:151:9
                                     init/Clutter.Actor.prototype.ease@resource:///org/gnome/shell/ui/environment.js:269:9
                                     close@resource:///org/gnome/shell/ui/boxpointer.js:146:14
                                     close@resource:///org/gnome/shell/ui/popupMenu.js:945:30
                                     vfunc_clicked@/home/didier/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/shell/gmenu.js:444:40
août 15 12:56:18 org.gnome.Shell.Extensions.GSConnect[2378]: [/service/device.js:sendPacket:478]: Moto G (5S): {
                                                                "id": 1234567890123,
                                                                "type": "kdeconnect.sftp.request",
                                                                "body": {
                                                                  "startBrowsing": true
                                                                }
                                                              }

**System Details (please complete the following information):**

GSConnect version 40
Upgraded from 39 to 40 from https://extensions.gnome.org/
gnome-shell-3.36.5-1.fc32.x86_64
Fedora 32

Lenovo Moto 5S
KDE Connect 1.14.2

**Comment by andyholmes** [comment]
Thanks for reporting, looking into this now.

**Comment by andyholmes** [comment]
Not sure I understand why this happened, or why it changed between v39 and v40, but I think I've fixed it. Could you please test this ZIP to confirm for me ([Instructions](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Installation#install-from-zip))?

[gsconnect@andyholmes.github.io.zip](https://github.com/andyholmes/gnome-shell-extension-gsconnect/files/5079282/gsconnect%40andyholmes.github.io.zip)

**Comment by didierga** [comment]
Good job Andy !

I just tested the zip above and it woorks !

**Comment by andyholmes** [comment]
Great, thanks for the report and testing! I'll see if any other bugs show up today and upload a new version later :+1:

**Comment by didierga** [comment]
I installed 41 this morning.

It works fine.
