### ISSUE TITLE
Installing gsconnect on ubuntu 18.04 makes top bar icons to disappear (skype, dropbox, etc)

### ISSUE THREAD

**Issue by djvergad** [andyholmes/gnome-shell-extension-gsconnect#92]
After installing gsconnect shell extension on a recently upgraded Ubuntu 18.04 system, the top bar indicators from other applications disappeared (skype and dropbox in my case). Recovering the icons is possible by executing

```bash
sudo apt remove indicator-application
```
And restarting gnome with `Alt-F2` and then typing `r` in the textfield.  
(credit to this answer on askubuntu: https://askubuntu.com/a/968305)

Not sure what that package does, or if removing it breaks stuff, but I feel that the installer should either block if the packet is present, or warn the user to remove it if they want icons for other programs.

**Comment by andyholmes** [comment]
Not sure what causes that problem. GSConnect itself doesn't install any icons, they're made available as fallbacks to the active icon theme via the GResource.

Strictly speaking there is no installer for GSConnect; it's just a Zip package that's uncompressed into the user's home directory. Additionally, there's no way to tell if GSConnect is about to be installed, whether the system is Ubuntu, or to query installed applications. I'd recommend you file an upstream bug with Ubuntu on Launchpad.

**Comment by djvergad** [comment]
Ok, that makes sense, thank you for the suggestion.
