### ISSUE TITLE
'New Issue' Links On Help Page Link To NixOS

### ISSUE THREAD

**Issue by poita66** [andyholmes/gnome-shell-extension-gsconnect#921]
**Describe the bug**

All of the New Issue links on https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Help go to the NixOS nixpkgs repo (https://github.com/NixOS/nixpkgs/issues/new?assignees=&labels=0.kind%3A+bug&template=bug_report.md)

**Steps To Reproduce:**

1. Go to https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Help
2. Click on 'New Issue'
4. See wrong repo

**Expected behavior**

New Issue links should take the user to https://github.com/andyholmes/gnome-shell-extension-gsconnect/issues/new/choose

**Comment by andyholmes** [comment]
Thanks for spotting that, I hadn't noticed that change.

@doronbehar, was there a reason you did that?

**Comment by andyholmes** [comment]
Closing this one up, since the wiki has been amended. Thanks again for the report.

**Comment by doronbehar** [comment]
Sorry, my bad.

**Comment by andyholmes** [comment]
No worries, just wondering if there was reason.
