### ISSUE TITLE
Name mount points after the device

### ISSUE THREAD

**Issue by alexanderadam** [andyholmes/gnome-shell-extension-gsconnect#925]
**Is your feature request related to a problem? Please describe.**

I'm using two devices with KDE connect and the visible mount point in [GNOME Files 3.36.3-stable](https://wiki.gnome.org/action/show/Apps/Files) just shows their IP.

**Describe the solution you'd like**

A human memorable mount point (i.e. the configured device name)

**Describe alternatives you've considered**

Not having a human memorable name.

**System Details (please complete the following information):**
 - GSConnect version: `41`
   - Installed from: extensions.gnome.org

**Additional context**

![Screenshot from 2020-08-19 09-42-28](https://user-images.githubusercontent.com/372620/90606912-c919a580-e200-11ea-8ad0-9977ce1ccdb0.png)

**PS:** Thank you so much for your work! GSConnect is wonderful to use! :pray:

**Comment by andyholmes** [comment]
Thanks for the kind words!

Unfortunately there's no way to rename these mounts in Nautilus, as Gvfs does naming of these. Another use contributed a patch that make symbolic links in a predictable place:

```sh
# $UID is your user id, you can get it with `echo $UID`
/run/user/$UID/gsconnect/by-name/DeviceName
```

You can probably make a bookmark in Nautilus with these.
