### ISSUE TITLE
Improve texting line-break user experience

### ISSUE THREAD

**Issue by klausenbusk** [andyholmes/gnome-shell-extension-gsconnect#932]
**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/1080056/91343303-9feaad80-e7dc-11ea-833c-e2fdcbca2e88.png)
It isn't very easy to write a long text when you only have a one line input.

**Describe alternatives you've considered**
Write the text in another program and cope-paste it.

**System Details (please complete the following information):**
 - GSConnect version: 41
   - Installed from: extensions.gnome.org

**Additional context**

~~I'm not sure if this is supported by KDEConnect and I'm not sure how to check?~~

**Comment by andyholmes** [comment]
You can add line breaks with <kbd>Shift</kbd>+<kbd>Enter</kbd>, is that what you mean?

**Comment by klausenbusk** [comment]
> You can add line breaks with Shift+Enter, is that what you mean?

Oh, I can. The user experience could be improved though: 
![image](https://user-images.githubusercontent.com/1080056/91343196-70d43c00-e7dc-11ea-9fa9-a14c6ab51287.png)

**Comment by andyholmes** [comment]
If you mean a multi-line text entry there is an issue open as #771?

**Comment by klausenbusk** [comment]
> If you mean a multi-line text entry there is an issue open as #771?

I'm not sure how I missed that issue. Sorry for the noise :)

**Comment by andyholmes** [comment]
no problem :)
