### ISSUE TITLE
GsConnect GUI not accessible

### ISSUE THREAD

**Issue by rkochar** [andyholmes/gnome-shell-extension-gsconnect#933]
**Describe the bug**
After downloading from the Ubuntu Software Manager as suggested [here](https://www.omgubuntu.co.uk/2018/11/connect-android-ubuntu-gsconnect), I do not see the ["launch" option](https://imgur.com/a/mG9RSIu). Searching for GsConnect after pressing the `Windows` key, gives me two files with the path `.local/share/applications` but no GUI.

At [top right](https://imgur.com/a/GhUXmON) corner of my laptop, I can see my phone (previously connected via BlueTooth), I don't recognize the icon, don't know why its there or what exactly it means, but it disappears when I turn BT off, re-appears when BT is enabled. Choosing the "Connect to Internet" option, gives `Activation of network failed` error. 

I can also see GsConnect here, it tells me to download the browser extension. Looks like [this](https://imgur.com/a/o17ijay). I do not have the option to pair my device here. Tried pairing my laptop from phone through hostname and IP address, neither worked.

Incase something is unclear, I also made a [reddit post](https://www.reddit.com/r/linux4noobs/comments/iinxhq/setup_kdeconnect_on_gnome_ubuntu/g388d5a?utm_source=share&utm_medium=web2x&context=3) asking for help that clearly describes the sequence of actions and responses to some suggestions by others.

**Steps To Reproduce:**
Download GsConnect from the Ubuntu Software Manager.

**Expected behavior**

There should be a "launch" option. I should also be able to search for the GUI after pressing the `Windows` key.

**Support Log**

The log doesn't have any entries which is weird but should probably lead to the solution.
```
Logs begin at Fri 2020-08-21 16:56:34 IST, end at Sat 2020-08-29 17:22:33 IST. --
-- No entries --
```

**System Details (please complete the following information):**

 - **GSConnect version:** 41
   - **Installed from:** Ubuntu Package Manager - search for "gnome-shell-extension-gsconnect" or use link from [here](https://www.omgubuntu.co.uk/2018/11/connect-android-ubuntu-gsconnect)
 - **GNOME/Shell version:** 3.36.4
 - **Distro/Release:** Ubuntu 20.04.1 LTS

**GSConnect environment (if applicable):**

 - **Paired Device(s):** OnePlus Nord (Shouldn't matter)
 - **KDE Connect app version:** 1.14.2

**Additional Notes**
I tried the browser extension option but it never worked because there was an error at the top of the page, `Although GNOME Shell integration extension is running, native host connector is not detected`. [This](https://askubuntu.com/questions/1034688/url-extensions-gnome-org-for-managing-gnome-extensions-not-working-in-any-browse) did not solve it.

I also tried KdeConnect, but it too doesn't have a GUI. They are different issues but might be worth mentioning.

On the app on my phone, I can see my other laptop that runs KDE with Manjaro. There is no issue on that end. It certainly is on this laptop running Ubuntu/Gnome.

Looking at some other issues, the `nativeMessgingHost.js` is executable and has permissions `rwxr-xr-x`.

```
ps aux | grep gsconnect
rkochar     3690  0.0  0.3 3305532 55416 ?       Sl   16:50   0:02 gjs /home/rkochar/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js
rkochar     7658  1.5  0.4 3465592 68680 ?       Sl   17:16   0:24 gjs /home/rkochar/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/gsconnect-preferences
rkochar     9039  0.0  0.0   9040  2484 pts/1    S+   17:42   0:00 grep --color=auto gsconnect
```

Please ask any questions that you may have. Thank you!

**Comment by andyholmes** [comment]
Thanks for reporting, I see you tried a lot of things :) 

> After downloading from the Ubuntu Software Manager as suggested here, I do not see the "launch" option. Searching for GsConnect after pressing the Windows key, gives me two files with the path .local/share/applications but no GUI.

There is no "launch" option, because GSConnect is a service so it runs in the background automatically. More importantly, Ubuntu only ships version 20, which is far too old to work on Ubuntu 20.04 LTS.

> At top right corner of my laptop, I can see my phone (previously connected via BlueTooth), I don't recognize the icon, don't know why its there or what exactly it means, but it disappears when I turn BT off, re-appears when BT is enabled. Choosing the "Connect to Internet" option, gives Activation of network failed error.

This icon doesn't have anything to do with GSConnect, the only menu related here is "Mobile Devices".

> I tried the browser extension option but it never worked because there was an error at the top of the page, Although GNOME Shell integration extension is running, native host connector is not detected. This did not solve it.

The error on https://extensions.gnome.org/ almost definitely means you are running a web browser in a Snap. There's really nothing I can do about that but recommend you don't use those for installing GNOME Shell extensions.

> Looking at some other issues, the nativeMessgingHost.js is executable and has permissions rwxr-xr-x.

This is not the browser extension for installing GNOME Shell extensions. This is the GSConnect browser extension for sharing links from the browser to your phone.


My recommendation is to install GSConnect from ZIP:
  1. Download [v41](https://github.com/andyholmes/gnome-shell-extension-gsconnect/releases/download/v41/gsconnect@andyholmes.github.io.zip)
  2. Open a terminal and run  `cd ~/Downloads`
  2. Run `gnome-extensions install --force gsconnect@andyholmes.github.io.zip`
  3. Restart GNOME Shell or log-out and log-in

After this you should open the "Mobile Settings" window and follow the steps for [Connecting an Android Device](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Help#connecting-an-android-device).

**Comment by rkochar** [comment]
> My recommendation is to install GSConnect from ZIP:

`gnome-extensions install --force gsconnect@andyholmes.github.io.zip` executed suspiciously quickly (nothing was outputted on terminal) and Mobile Devices is now gone from the top right. `gnome-extensions enable gsconnect@andyholmes.github.io` brought it back, but I can't see GSConnect on the phone as suggested in the last link

> The error on https://extensions.gnome.org/ almost definitely means you are running a web browser in a Snap. There's really nothing I can do about that but recommend you don't use those for installing GNOME Shell extensions.

Yes, that fixed it, since the error is gone I assume it means the requisite packages are correctly setup.

Clicking on Mobile Devices | Device Settings, I see [this](https://imgur.com/a/T4BK5lG)

The error log this time isn't empty which is very good.

```
GSConnect Version: 41
GSConnect Install: user
GJS: 16403
XDG_SESSION_TYPE: x11
GDMSESSION: ubuntu
--------------------------------------------------------------------------------
-- Logs begin at Fri 2020-08-21 16:56:34 IST, end at Sun 2020-08-30 10:40:25 IST. --
Aug 30 10:40:09 dbus-daemon[2722]: [session uid=1000 pid=2722] Activating service name='org.gnome.gedit' requested by ':1.200' (uid=1000 pid=10267 comm="gjs /home/rkochar/.local/share/gnome-shell/extensi" label="unconfined")
Aug 30 10:40:09 dbus-daemon[2722]: [session uid=1000 pid=2722] Successfully activated service 'org.gnome.gedit'
Aug 30 10:40:10 gnome-shell[3051]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x3400101
Aug 30 10:40:25 gnome-shell[3051]: ../../../gobject/gsignal.c:2735: instance '0x563a87ecab00' has no handler with id '82711'
```

Refreshed and checked the logs again (the previous lines were deleted instead of appending and I removed part at the top).

```
-- Logs begin at Fri 2020-08-21 16:56:34 IST, end at Sun 2020-08-30 10:41:13 IST. --
Aug 30 10:41:11 rtkit-daemon[1696]: Supervising 6 threads of 2 processes of 2 users.
Aug 30 10:41:11 rtkit-daemon[1696]: Supervising 6 threads of 2 processes of 2 users.
Aug 30 10:41:11 rtkit-daemon[1696]: Supervising 6 threads of 2 processes of 2 users.
Aug 30 10:41:11 rtkit-daemon[1696]: Supervising 6 threads of 2 processes of 2 users.
Aug 30 10:41:11 rtkit-daemon[1696]: Successfully made thread 10550 of process 10471 owned by '1000' RT at priority 10.
Aug 30 10:41:11 rtkit-daemon[1696]: Supervising 7 threads of 3 processes of 2 users.
Aug 30 10:41:11 rtkit-daemon[1696]: Supervising 7 threads of 3 processes of 2 users.
Aug 30 10:41:11 rtkit-daemon[1696]: Supervising 7 threads of 3 processes of 2 users.
Aug 30 10:41:12 rtkit-daemon[1696]: Supervising 7 threads of 3 processes of 2 users.
Aug 30 10:41:12 rtkit-daemon[1696]: Supervising 7 threads of 3 processes of 2 users.
Aug 30 10:41:12 rtkit-daemon[1696]: Supervising 7 threads of 3 processes of 2 users.
Aug 30 10:41:12 rtkit-daemon[1696]: Supervising 7 threads of 3 processes of 2 users.
Aug 30 10:41:13 rtkit-daemon[1696]: Supervising 7 threads of 3 processes of 2 users.
Aug 30 10:41:13 rtkit-daemon[1696]: Supervising 7 threads of 3 processes of 2 users.
```

Phone and laptop still can't detect each other. They are on the same wifi network.

**Comment by andyholmes** [comment]
You must leave the dialog open when refreshing for the messages to be logged.

Can you confirm:

* You can ping your phone from the terminal
* You have followed the [steps in the Wiki](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Help#connecting-an-android-device) for connecting a device
* If you have firewall it is configured (see [KDE Connect Wiki](https://userbase.kde.org/KDEConnect#Troubleshooting))

**Comment by rkochar** [comment]
Yes, it was the firewall. Thank you for your time!
