### ISSUE TITLE
Unable to uninstall gsconnect

### ISSUE THREAD

**Issue by Gs-001** [andyholmes/gnome-shell-extension-gsconnect#939]
I installed gsconnect firefox extension from  https://extensions.gnome.org/extension/1319/gsconnect/
I installed some of it's plugins for notifications and file transfer but there was no interface for accessing gsconnect in panel indicator area

So I tried installed 
```
gnome-shell-extension-gsconnect
gnome-shell-extension-gsconnect-browsers
```
using apt package manager.
After that I got to know about the need to restart gnome-shell and everything worked fine.

Now I need to work with on some plugins on KDE connect. I installed KDE connect using apt package manager.
Both KDE connect and gsconnect are working in my system right now even after i uninstalled both the gnome-shell-extensions using apt and also uninstalled the gsconnect extension from firefox.
I can still see the gsconnect options in the panel indicator area.

GNOME Shell version: 3.36.4
Ubuntu version: 20.04

**Comment by andyholmes** [comment]
It sounds like you have effectively three clients installed, so you will have to uninstall GSConnect from the Extensions application/website and `apt`. When uninstalled the GSConnect service will automatically stop.

The version of GSConnect in Ubuntu is years old, so it's possible that caused some problems.

**Comment by ferdnyc** [comment]
You could also use `gnome-extensions uninstall "gsconnect@andyholmes.github.io"` from a terminal, as an alternative. (Which is exactly equivalent to uninstalling via the extensions.gnome.org website.)

**Comment by andyholmes** [comment]
Closing this one, since it seems like a package manager bug not related to GSConnect.
