### ISSUE TITLE
Local MPRIS album art upload not supported

### ISSUE THREAD

**Issue by kogli** [andyholmes/gnome-shell-extension-gsconnect#94]
The original KDE Connect implementation sends the currently playing song's album art to the mobile device. The notification on the mobile device then shows the image. GSConnect should do the same, but in practice I get just an orange notification without the album art on my phone.

**Comment by kogli** [comment]
Nevermind, it's actually available in v11. Sorry.

**Comment by andyholmes** [comment]
I'm going to re-open this actually. v11 supports remote album art via URLs (eg. Spotify), but doesn't yet support local file art (eg. album.jpg), which was released just a few days after I added the original support. I only realized that after seeing your issue, though :)

**Comment by andyholmes** [comment]
Implemented in the rewrite now.
