### ISSUE TITLE
Error calling StartServiceByName for org.freedesktop.UPower: Failed to activate service 'org.freedesktop.UPower': timed out (service_start_timeout=25000ms)

### ISSUE THREAD

**Issue by mercertom** [andyholmes/gnome-shell-extension-gsconnect#948]
```
GSConnect Version: 41
GSConnect Install: user
GJS: 16404
XDG_SESSION_TYPE: x11

_init@/home/tom/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/components/upower.js:18:14
_initComponents@/home/tom/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:436:37
vfunc_startup@/home/tom/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:592:14
vfunc_handle_local_options@/home/tom/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:1011:18
@/home/tom/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:1074:17
```

**Comment by andyholmes** [comment]
Interesting, what distribution is this?

**Comment by mercertom** [comment]
Manjaro

**Comment by ferdnyc** [comment]
And there's really no `upower` package installed? No `/usr/share/dbus-1/system-services/org.freedesktop.UPower.service` file? How strange, normally both `gnome-settings-daemon` and `gnome-control-center` would require it.

**Comment by mercertom** [comment]
IDK, I thought the recent versions of linux kernel (or GNOME, I can't
remember which) moved beyond upower recently.

**Comment by andyholmes** [comment]
I don't think there's any plans to replace UPower, but that's okay. I can remove it as a requirement.

**Comment by andyholmes** [comment]
Should be fixed now, here's a Zip if you don't want to wait for the next release ([Instructions](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Installation#install-from-zip)):

[gsconnect@andyholmes.github.io.zip](https://github.com/andyholmes/gnome-shell-extension-gsconnect/files/5216090/gsconnect%40andyholmes.github.io.zip)

**Comment by mercertom** [comment]
Thanks! I don't think anyone replaced upower, but somehow just don't need
it at all after some change. I'm probably mis-remembering some crucial part
of this. I don't remember if it was for Manjaro, one of the newer kernels
like 5.8/5.9, GNOME, or for a specific laptop/hardware component, but I
remember reading recently that for some reason, I wouldn't be
running/needing upower anymore.

**Comment by ferdnyc** [comment]
I can certainly see how it makes sense for it to at least be _optional_, on desktop machines especially. So, good to know, thanks!
