### ISSUE TITLE
Remote control Ubuntu 18.04

### ISSUE THREAD

**Issue by vjm7494** [andyholmes/gnome-shell-extension-gsconnect#95]
Remote control on Ubuntu 18.04 does not work on Xiaomi mi6. Exactly on debug mode it receives correct signals, but it has no effect on screen.

```
JS LOG: [gsconnect@andyholmes.github.io]: LanChannel.receive(2005f5f559ee8c19)
JS LOG: [gsconnect@andyholmes.github.io]: Device received: {"id":1525903209020,"type":"kdeconnect.mousepad.request","body":{"dx":43.076904296875,"dy":-34.35223388671875}}
JS LOG: Received from 'Xiaomi Mi6'
JS LOG: [gsconnect@andyholmes.github.io]: Mousepad: handlePacket()
JS LOG: [gsconnect@andyholmes.github.io]: Mousepad: movePointer(43.076904296875, -34.35223388671875)
JS LOG: [gsconnect@andyholmes.github.io]: LanChannel.receive(2005f5f559ee8c19)
JS LOG: [gsconnect@andyholmes.github.io]: Device received: {"id":1525903209031,"type":"kdeconnect.mousepad.request","body":{"dx":9.01251220703125,"dy":-7.0101318359375}}
JS LOG: Received from 'Xiaomi Mi6'
JS LOG: [gsconnect@andyholmes.github.io]: Mousepad: handlePacket()
JS LOG: [gsconnect@andyholmes.github.io]: Mousepad: movePointer(9.01251220703125, -7.0101318359375)
```

and keyboard signals 

```
JS LOG: Received from 'Xiaomi Mi6'
JS LOG: [gsconnect@andyholmes.github.io]: Mousepad: handlePacket()
JS LOG: [gsconnect@andyholmes.github.io]: Mousepad: pressKey(f)
JS LOG: [gsconnect@andyholmes.github.io]: LanChannel.receive(2005f5f559ee8c19)
JS LOG: [gsconnect@andyholmes.github.io]: Device received: {"id":1525903270560,"type":"kdeconnect.mousepad.request","body":{"key":"h"}}
JS LOG: Received from 'Xiaomi Mi6'
JS LOG: [gsconnect@andyholmes.github.io]: Mousepad: handlePacket()
JS LOG: [gsconnect@andyholmes.github.io]: Mousepad: pressKey(h)
JS LOG: [gsconnect@andyholmes.github.io]: LanChannel.receive(2005f5f559ee8c19)
JS LOG: [gsconnect@andyholmes.github.io]: Device received: {"id":1525903270743,"type":"kdeconnect.mousepad.request","body":{"key":"g"}}
JS LOG: Received from 'Xiaomi Mi6'
JS LOG: [gsconnect@andyholmes.github.io]: Mousepad: handlePacket()
JS LOG: [gsconnect@andyholmes.github.io]: Mousepad: pressKey(g)
```

**Comment by andyholmes** [comment]
That's strange because if anything fails an error should be printed. Are there any errors in the general system log, especially related to AT-SPI? Are you running a display server other than Xorg?

**Comment by vjm7494** [comment]
In fact it is clear Ubuntu 18.04 out of box, because i run it from Live Session. Here is LOG
[Сообщения журнала.txt](https://github.com/andyholmes/gnome-shell-extension-gsconnect/files/1989710/default.txt)

**Comment by andyholmes** [comment]
> 01:24:52 gjs: JS LOG: [gsconnect@andyholmes.github.io]: Mousepad: pressKey(м)01:24:52

Unicode characters like these require Caribou. This was the on-screen keyboard (and libraries) for Gnome so used to to be installed by default, but I *think* might be replaced with something else now. Maybe trying to use these characters without Caribou causes AT-SPI to break?

Not sure if this will fix all the problems, but install the package `gir1.2-caribou-1.0` then disable/enable the plugin. This should fix unicode characters like `м` and see if it also fixes the other problems too.

**Comment by vjm7494** [comment]
Thanks. I will try it tomorrow. I was going to test Ubuntu for migrate from Kde. And kde connect is one of important feature for me.

Do you think it will fix mouse signals too?

**Comment by andyholmes** [comment]
It might fix the mouse problems. Normally it should throw errors if it doesn't work so I believe the problem is not specifically is GSConnect, but maybe a missing library or something that changed in 3.26->3.28.

If you are sending from your phone using a non-english language it might send all characters as unicode. Maybe once it sees a certain number of those errors AT-SPI gives up. In any case, I would try that and if the mouse still doesn't work, then we'll go from there.

**Comment by vjm7494** [comment]
Hello.
I have installed all by "Caribou" as there was. No result.
[Сообщения журнала.txt](https://github.com/andyholmes/gnome-shell-extension-gsconnect/files/1992993/default.txt)

**Comment by andyholmes** [comment]
It seems from your logs that Caribou is still not being used, so you may have to install the `caribou` package in addition to `gir1.2-caribou-1.0`. As far as the mouse movements, I'm just not sure since no errors are being thrown at all to indicate why it's not working. I'll keep looking though.

**Comment by frohro** [comment]
Hi Andy,
This also affects me.  I'm using wayland if that matters.  I did install the gir1.2-caribou-1.0 as well, and I still get these messages:
JS LOG: [gsconnect@andyholmes.github.io]: LanChannel.receive(1975064744217f3e)
JS LOG: [gsconnect@andyholmes.github.io]: Device received: {"id":1526191175747,"type":"kdeconnect.mousepad.request","body":{"dx":1.04534912109375,"dy":0}}
JS LOG: Received from 'Rob's G5'
JS LOG: Received unsupported packet type: {"id":1526191175747,"type":"kdeconnect.mousepad.request","body":{"dx":1.04534912109375,"dy":0}}
JS LOG: [gsconnect@andyholmes.github.io]: LanChannel.receive(1975064744217f3e)
JS LOG: [gsconnect@andyholmes.github.io]: Device received: {"id":1526191175764,"type":"kdeconnect.mousepad.request","body":{"dx":-0.30731201171875,"dy":0}}
JS LOG: Received from 'Rob's G5'
JS LOG: Received unsupported packet type: {"id":1526191175764,"type":"kdeconnect.mousepad.request","body":{"dx":-0.30731201171875,"dy":0}}
JS LOG: [gsconnect@andyholmes.github.io]: LanChannel.receive(1975064744217f3e)
JS LOG: [gsconnect@andyholmes.github.io]: Device received: {"id":1526191175781,"type":"kdeconnect.mousepad.request","body":{"dx":1.3013916015625,"dy":0}}
JS LOG: Received from 'Rob's G5'
JS LOG: Received unsupported packet type: {"id":1526191175781,"type":"kdeconnect.mousepad.request","body":{"dx":1.3013916015625,"dy":0}}
Let me know if I can help.  I'm glad to test things.
Thanks for your good work!
Rob

**Comment by andyholmes** [comment]
> This also affects me. I'm using wayland if that matters.

Yes, if you're using Wayland mouse and keyboard synthesis are not yet possible (see: [Accessibility + Wayland](https://wiki.gnome.org/Accessibility/Wayland)). Usually the plugin should fail to load in GSConnect if Wayland is running, but only if the `XDG_SESSION_TYPE` env variable is set.

**Comment by vjm7494** [comment]
> It seems from your logs that Caribou is still not being used, so you may have to install the caribou package in addition to gir1.2-caribou-1.0. As far as the mouse movements, I'm just not sure since no errors are being thrown at all to indicate why it's not working. I'll keep looking though.
I have installed these package then.  No result.

**Comment by andyholmes** [comment]
I'm kind of stumped on this problem. For the keyboard input Caribou still doesn't seem to be active, which it should be. For mouse input, no errors are being printed to either log, so I just don't know where to look for the problem. The only hint is this line:

    19:26:32 gnome-shell-ext: Couldn't register with accessibility bus: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.

which implies AT-SPI is not working for some reason, but the extension should detect that when the plugin is loaded. If you're running this on a Live CD that may be the problem, but I just don't know.

**Comment by vjm7494** [comment]
I think no. On another PC it was ok in live session.
Please, dont close. If there are any details, I'll let you know.

**Comment by mpolidori** [comment]
Not entirely sure if I should post here or open a new one. I'm running Arch with GNOME 3.28.2 (not using Wayland) and I'm seeing the same issue with input. The log shows correct touch input (with no errors), but the pointer doesn't actually move.

I was having the same issue with the keyboard. Installing caribou fixed that, but I couldn't find gir1.2-caribou-1.0 for Arch anywhere.

**Comment by mpolidori** [comment]
I built from git with the same results. Not sure what else to try.

**Comment by andyholmes** [comment]
It seems that the Atspi call is succeeding so I'm not sure where the problem is with this, especially if you have the HiDPI fix from master. On rare occasions, some errors don't get to `journalctl` for `gjs`, so one idea is to check Gnome Logs for "All Applications" or "Important" to see if there are errors been thrown outside of GJS.

I believe Atspi is actually a pure DBus service with convenience bindings for Gnome, so the errors may be showing up elsewhere.

**Comment by bornolbers** [comment]
I have the same problem (as described above): gsconnect is unusable in ubuntu 18.04 4k monitor. But the issue is about hidpi.. If I configure the monitor at 100% scale everything is fine. The problem exists only at 200% scale configuration. I hope it helps

Also (because I'm a newbie trying to help) gsconnect has also something unexpected. When I installed on a laptop, it finds and can "connect" with itself (!) : Except from the phone device and the pc, it has on the list the laptop itself as a new device.. I don't know where to inform you about it also, so please as you are the experts forward it the right people or tell me how I can do it myself. Thank's

**Comment by andyholmes** [comment]
It sounds like you are running KDE Connect at the same time, that will break lots of things.

**Comment by andyholmes** [comment]
Can anyone confirm this issue still exists in v13?

**Comment by andyholmes** [comment]
This bug is quite old now, and hasn't seen new activity or confirmation on a current release. Can you please re-open if still affects v15?

**Comment by bornolbers** [comment]
on ubuntu 18.10 and current version of gsconnect (19) the problem is no more. Thank you very much! I loved this!

ps. I haven't tested the in between versions because I have just uninstalled the extension till now.
