### ISSUE TITLE
Remote input & Debian testing

### ISSUE THREAD

**Issue by Elvith** [andyholmes/gnome-shell-extension-gsconnect#952]
Today's upgrade in Debian testing introduces pipewire 0.3. 
https://packages.debian.org/bullseye/pipewire
However it seems that remote input (mouse+keyboard) with GSconnect still does not work. Is there something still missing in Debian, or is it on GSconnect side? And if it is GSconnect-related, would it be possible to fix this in the next version?

Thanks a lot for your attention.

**Comment by andyholmes** [comment]
As far as I can see, they still don't compile gnome-shell or mutter with pipewire support. Until they do that, the remote desktop interface we use will not be available.

**Comment by Elvith** [comment]
Will it work out of the box once they properly compile gnome-shell and mutter with pipewire support, or do you need to change something in GSConnect for it to work? (In other words, is it useful for you that I report here the evolution on the Debian side?)

**Comment by andyholmes** [comment]
Yes, it should work automatically.

**Comment by andyholmes** [comment]
Going to close this once, since there's nothing to do for GSConnect. I'll keep an eye on debian though, thanks for pointing that out.

**Comment by Elvith** [comment]
FYI, remote input (mouse & keyboard) is now working. Finally. Awesome! :+1: 

(Let me point out that this is about Debian testing, not Debian stable).
