### ISSUE TITLE
Please warn that upgrading the extension requires logging out to make it work

### ISSUE THREAD

**Issue by rrthomas** [andyholmes/gnome-shell-extension-gsconnect#964]
**Describe the bug**

After upgrading the extension, logout/login is required to make it work. It would be nice to fix this, but in the mean time, good to have a warning; however, the only warning is in the error logs, which of course are only visible when it is too late (i.e. you have already upgraded).

**Steps To Reproduce:**

1. Upgrade GSConnect

**Expected behavior**

It would be good to have a warning (e.g. a prominent notice in the extension's description on extensions.gnome.org) that it is necessary to log out and back in to make the extension work again.

**System Details (please complete the following information):**

 - **GSConnect version:** 42
   - **Installed from:** GNOME Extensions Website
 - **GNOME/Shell version:** 3.36
 - **Distro/Release:** Ubuntu 20.04

**Comment by andyholmes** [comment]
Sure, I'll add a note to the description, but this is really not a problem with GSConnect.

Please follow the [upstream issue](https://gitlab.gnome.org/Infrastructure/extensions-web/-/issues/109) for updates about this problem.

**Comment by rrthomas** [comment]
Thanks, and thanks for the link!
