### ISSUE TITLE
GS Not working after update

### ISSUE THREAD

**Issue by shehan0** [andyholmes/gnome-shell-extension-gsconnect#968]
Hi,

There was an update for GSConect. But after it, the extension gives an error. It is not connecting. 

![image](https://user-images.githubusercontent.com/45060844/93719067-e9d97000-fb9d-11ea-906e-4ef4120c7b63.png)

**Comment by andyholmes** [comment]
Thanks for reporting, but this is not a bug in GSConnect.

This is a known bug in the Extensions website, [documented in the wiki](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Help#update-error).
