### ISSUE TITLE
Unable to send files from computer to mobile . Everything else is working.

### ISSUE THREAD

**Issue by hari64** [andyholmes/gnome-shell-extension-gsconnect#977]
GSConnect: 43 (user)
GJS:       16403
Session:   x11
OS:        Ubuntu 20.04.1 LTS
--------------------------------------------------------------------------------
-- Logs begin at Mon 2020-08-31 08:20:27 +0545, end at Wed 2020-09-23 17:21:07 +0545. --
सितम्बर 23 17:20:07 systemd[1]: systemd-hostnamed.service: Succeeded.
सितम्बर 23 17:20:23 kernel: [UFW BLOCK] IN=enp4s0 OUT= MAC=01:00:5e:00:00:01:04:5e:a4:1f:94:a0:08:00 SRC=192.168.1.254 DST=224.0.0.1 LEN=32 TOS=0x00 PREC=0x00 TTL=1 ID=57423 DF PROTO=2 
सितम्बर 23 17:20:23 kernel: [UFW BLOCK] IN=enp4s0 OUT= MAC=01:00:5e:00:00:fb:c0:65:99:33:94:e9:08:00 SRC=192.168.1.102 DST=224.0.0.251 LEN=32 TOS=0x00 PREC=0xC0 TTL=1 ID=0 DF PROTO=2 
सितम्बर 23 17:20:53 kernel: [UFW BLOCK] IN=enp4s0 OUT= MAC=01:00:5e:00:00:fb:2a:95:75:e9:6f:b5:08:00 SRC=192.168.1.101 DST=224.0.0.251 LEN=32 TOS=0x00 PREC=0xC0 TTL=1 ID=0 DF PROTO=2 
सितम्बर 23 17:20:55 org.gnome.Shell.Extensions.GSConnect[9853]: [/service/device.js:sendPacket:446]: Nokia 5.1 Plus: {
                                                                                "id": 1600860955287,
                                                                                "type": "kdeconnect.systemvolume",
                                                                                "body": {
                                                                                  "sinkList": [
                                                                                    {
                                                                                      "name": "alsa_output.pci-0000_00_1b.0.analog-stereo",
                                                                                      "description": "Speakers (Built-in Audio Analog Stereo)",
                                                                                      "muted": false,
                                                                                      "volume": 47185,
                                                                                      "maxVolume": 65536
                                                                                    }
                                                                                  ]
                                                                                }
                                                                              }
सितम्बर 23 17:21:00 dbus-daemon[1100]: [system] Activating via systemd: service name='org.freedesktop.hostname1' unit='dbus-org.freedesktop.hostname1.service' requested by ':1.153' (uid=1000 pid=9853 comm="gjs /home/hari/.local/share/gnome-shell/extensions" label="unconfined")
सितम्बर 23 17:21:00 org.gnome.Shell.Extensions.GSConnect[9853]: [/service/device.js:sendPacket:446]: Nokia 5.1 Plus: {
                                                                                "id": 1600860960382,
                                                                                "type": "kdeconnect.systemvolume",
                                                                                "body": {
                                                                                  "sinkList": [
                                                                                    {
                                                                                      "name": "alsa_output.pci-0000_00_1b.0.analog-stereo",
                                                                                      "description": "Speakers (Built-in Audio Analog Stereo)",
                                                                                      "muted": false,
                                                                                      "volume": 47185,
                                                                                      "maxVolume": 65536
                                                                                    }
                                                                                  ]
                                                                                }
                                                                              }
सितम्बर 23 17:21:00 systemd[1]: Starting Hostname Service...
सितम्बर 23 17:21:00 dbus-daemon[1100]: [system] Successfully activated service 'org.freedesktop.hostname1'
सितम्बर 23 17:21:00 systemd[1]: Started Hostname Service.
सितम्बर 23 17:21:07 org.gnome.Shell.Extensions.GSConnect[9853]: [/service/backends/lan.js:_transfer/</<:935]: Nokia 5.1 Plus: Error sending data: Connection reset by peer
                                                                              _transfer/</<@/home/hari/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/backends/lan.js:935:40
                                                                              @/home/hari/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:729:17
सितम्बर 23 17:21:07 kernel: [UFW BLOCK] IN=enp4s0 OUT= MAC=5c:f9:dd:4a:6c:4a:2a:95:75:e9:6f:b5:08:00 SRC=192.168.1.101 DST=192.168.1.106 LEN=40 TOS=0x00 PREC=0x00 TTL=64 ID=0 DF PROTO=TCP SPT=40222 DPT=1739 WINDOW=0 RES=0x00 RST URGP=0

**Comment by andyholmes** [comment]
Please ensure you have configured a download directory in Android.

**Comment by hari64** [comment]
i have already configured a download director. its not working

**Comment by andyholmes** [comment]
> सितम्बर 23 17:21:07 kernel: [UFW BLOCK] IN=enp4s0 OUT= MAC=5c:f9:dd:4a:6c:4a:2a:95:75:e9:6f:b5:08:00 SRC=192.168.1.101 DST=192.168.1.106 LEN=40 TOS=0x00 PREC=0x00 TTL=64 ID=0 DF PROTO=TCP SPT=40222 DPT=1739 WINDOW=0 RES=0x00 RST URGP=0

Sorry, I didn't see this at first. Your firewall is blocking transfers. You should configure it to open ports 1716-1764 for TCP.

**Comment by hari64** [comment]
> > सितम्बर 23 17:21:07 kernel: [UFW BLOCK] IN=enp4s0 OUT= MAC=5c:f9:dd:4a:6c:4a:2a:95:75:e9:6f:b5:08:00 SRC=192.168.1.101 DST=192.168.1.106 LEN=40 TOS=0x00 PREC=0x00 TTL=64 ID=0 DF PROTO=TCP SPT=40222 DPT=1739 WINDOW=0 RES=0x00 RST URGP=0
> 
> Sorry, I didn't see this at first. Your firewall is blocking transfers. You should configure it to open ports 1716-1764 for TCP.

i did configure to open ports 1716-1764 but it is not working.
i also tried to open port 1739 but no positive result

**Comment by hari64** [comment]
Thank you for your help. I disabled an external firewall installed in my pc and now its working.
