### ISSUE TITLE
Waiting for service....

### ISSUE THREAD

**Issue by frohro** [andyholmes/gnome-shell-extension-gsconnect#979]
I got a message there was a new GSConnect available, so I went to try and update, clicked the update icon and got a red ERROR message.  Now if I select the settings it says "Waiting to connect".

Any suggestions?

Thanks,

Rob

**Comment by andyholmes** [comment]
You must restart GNOME Shell after updating an extension. See [Update Error](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Help#update-error) and [Waiting for service...](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Help#waiting-for-service) in the Wiki.

**Comment by frohro** [comment]
Restarting gnome shell solved the issue.  Thanks for the tip!
