### ISSUE TITLE
Does it support xfce?

### ISSUE THREAD

**Issue by netjune** [andyholmes/gnome-shell-extension-gsconnect#984]
If yes, how to install? If not, is there a plan to support xfce?

**Comment by ferdnyc** [comment]
@netjune Sorry, GSConnect is a Gnome Shell extension, there's no way to use it with other desktop environments.

It may be possible to use the original KDE Connect desktop daemon with XFCE, I'm not sure. There should be more information at [the KDE Connect website](https://kdeconnect.kde.org/).

**Comment by ferdnyc** [comment]
(KDE Connect even works on _Windows_, so I'd say it's more than likely. GSConnect was created as an alternative desktop-side monitoring/configuration interface, to provide better integration with the Gnome Shell environment.)
