### ISSUE TITLE
KDECONNECT CRASH. Ubuntu 20.04

### ISSUE THREAD

**Issue by samuk190** [andyholmes/gnome-shell-extension-gsconnect#990]
> ***ATTENTION**: GSConnect only supports the latest, stable version of GNOME. We are no longer accepting bug reports for previous versions.*

**Describe the bug**
When go to kde slideshow remote and click at pointer button it slightly open something and crashes.
**Steps To Reproduce:**

Go to kde connect app (android)
Slideshow remote
click pointer.

**Expected behavior**
Nothing.

**Screenshots**

If applicable, add screenshots to help explain your problem. You can drag-and-drop or cut-and-paste images directly into this edit window, to include them in your report.

**Support Log**

Please generate a support log ([Instructions](../wiki/Help#generate-support-log)) and paste any messages related to this issue between the two ``` lines below.

```

```

**System Details (please complete the following information):**

 - **GSConnect version:** [e.g. 35, 36, ... (displayed in the GSConnect "About" window)]
   - **Installed from:** [e.g. GNOME Extensions Website, GitHub, Package Manager, ...]
 - **GNOME/Shell version:** [e.g. 3.36, ...]
 - **Distro/Release:** [e.g. Ubuntu 18.04, Fedora 29, Arch, ...]

**GSConnect environment (if applicable):**

 - **Paired Device(s):** [e.g. Galaxy Note 8, Pixel 2, Honor 9, ...]
 - **KDE Connect app version:** [e.g. 1.12.7]
 - **Plugin(s):** [if the issue only occurs when using certain plugin(s)]

**Additional Notes:**

Add any addtional information about the problem or your system.

**Comment by samuk190** [comment]
using gsconnect is a good workaround

**Comment by andyholmes** [comment]
Is this a bug in GSConnect or KDE Connect? If this is bug in KDE Connect please open an issue at https://bugs.kde.org.

**Comment by samuk190** [comment]
> Is this a bug in GSConnect or KDE Connect? If this is bug in KDE Connect please open an issue at https://bugs.kde.org.

Thanks, its KDE.
