### ISSUE TITLE
100% CPU spikes cause freezes for a few seconds

### ISSUE THREAD

**Issue by saligari** [andyholmes/gnome-shell-extension-gsconnect#992]
I noticed a few weeks ago freezes which were caused by 100% cpu usage seen in gnome-monitor. I think this was after some gnome update but it could be after updating the extension (?).

Fedora 32 (Workstation Edition)
GNOME 3.36.6
under Wayland
on an intel i5 and using intel graphics.

I hope a new maintainer steps up! This extension has made my transition from Plasma (KDE) easier, and is so very useful! Thanks!!

**Comment by andyholmes** [comment]
Sorry, I'll need some more information here. What process was showing 100% CPU usage? What was happening when the CPU spiked?

**Comment by saligari** [comment]
I can't replicate the issue now after an update. Perhaps it was a gnome issue and I had misunderstood. Sorry!
