### ISSUE TITLE
Please add option to notify when phone battery is 80% (or some x%)

### ISSUE THREAD

**Issue by hrishie01** [andyholmes/gnome-shell-extension-gsconnect#996]
Nowadays, we all are well aware that charging the phone upto 100% reduces the number of life cycles of the battery. So, like many I like to charge my phone upto 80%. It would be very helpful if we get a notification in our PC that the battery is charged upto that %.

**Comment by andyholmes** [comment]
Seems like a duplicate of #872. Patches are welcome.
